### ISSUE TITLE
Godmode not starting

### ISSUE THREAD

**Issue by ThaManWithTheHat** [d0k3/GodMode9#10]
Whatever way I try to boot GodMode9 it won't work. I've tried booting with luma, the homebrew launcher and also changing the boot in sd card to GodMode9, but nither version makes it boot, I can only see some red in the top left for a split second, and then my 3ds boots normaly/goes back to homebrew.
I'm running A9LH Sys 11.0.-33E on an o3ds.

**Comment by d0k3** [comment]
Have you already solved this issue? If so, how? If not, can you give me more information?

**Comment by MrDarius125** [comment]
could you tell me how to fix if you know how to fix it
im running old3ds xl 9.2 and 11.0 as emunand

**Comment by MrDarius125** [comment]
i have 2 3ds xl and normal i havent tryed the small one becuse im trying to downgrade it

**Comment by d0k3** [comment]
Well, it works for me and for everyone else. There is no reason why it should not work on A9LH.

**Comment by d0k3** [comment]
Also, did you guys use the release? Maybe tried to repalce the arm9loaderhax.bin on the SD card with it?

**Comment by d0k3** [comment]
And, one more hint. Try arm9loaderhax_si.bin as filename instead of arm9loaderhax.bin.

**Comment by MrDarius125** [comment]
I last time tryed getting arm9haxloader but i failed so i have to downgrade my old 3ds to try again and i did use the latest release

**Comment by MrDarius125** [comment]
how can i get the Brahma payload?

**Comment by d0k3** [comment]
Try renaming the GodMode9.bin to "arm9loaderhax_si.bin". Put it in root. Also, make sure there is no "arm9loaderhax.bin" in root. Then tyr again and tell me if it worked.

**Comment by d0k3** [comment]
Try renaming the GodMode9.bin to "arm9loaderhax_si.bin". Put it in root. Also, make sure there is no "arm9loaderhax.bin" in root. Then tyr again and tell me if it worked.

**Comment by d0k3** [comment]
Try renaming the GodMode9.bin to "arm9loaderhax_si.bin". Put it in root. Also, make sure there is no "arm9loaderhax.bin" in root. Then tyr again and tell me if it worked.

**Comment by d0k3** [comment]
Try renaming the GodMode9.bin to "arm9loaderhax_si.bin". Put it in root. Also, make sure there is no "arm9loaderhax.bin" in root. Then tyr again and tell me if it worked.

**Comment by d0k3** [comment]
Try renaming the GodMode9.bin to "arm9loaderhax_si.bin". Put it in root. Also, make sure there is no "arm9loaderhax.bin" in root. Then tyr again and tell me if it worked.

**Comment by d0k3** [comment]
Try renaming the GodMode9.bin to "arm9loaderhax_si.bin". Put it in root. Also, make sure there is no "arm9loaderhax.bin" in root. Then tyr again and tell me if it worked.

**Comment by d0k3** [comment]
Try renaming the GodMode9.bin to "arm9loaderhax_si.bin". Put it in root. Also, make sure there is no "arm9loaderhax.bin" in root. Then tyr again and tell me if it worked.

**Comment by MrDarius125** [comment]
i used the latest version of FBI it works great

**Comment by MrDarius125** [comment]
I tryed it it dosent work

**Comment by MrDarius125** [comment]
Maybe i need arm9loaderhax

**Comment by MrDarius125** [comment]
But i need to wait 6 days so i can transfer it again

**Comment by MrDarius125** [comment]
is there 3ds system transfer cooldown hack so i can disable it or hack the cool down?

**Comment by ihaveamac** [comment]
the cooldown is server-sided, so you can't "hack" it. also I don't think this is the right place to discuss that.

**Comment by MrDarius125** [comment]
So now do i hack the server side and where should i look for it?

**Comment by ihaveamac** [comment]
you just don't. you need to wait. no exceptions.

**Comment by MrDarius125** [comment]
Ok then

**Comment by MrDarius125** [comment]
Its not working becuse you dont have a9lh use fbi

**Comment by d0k3** [comment]
Oh, well, this is devolving into a support thread fast. HBL boots of ARM9 payloads have become problematic (even more so than they always were) during the last few months. In fact, we'd need a complete update / rewrite of Brahma. Nothing that I can do from my side.

Closing this now.
