### ISSUE TITLE
Error: The payload is too large or corrupted

### ISSUE THREAD

**Issue by vprw** [d0k3/GodMode9#101]
I'm on luma v8.0 and b9s v1.2 with n3ds 11.4. There's only godmode9.firm in my `sd:\luma\payloads`. When I boot up while holding start, it just shows this error and I can't get godmode9 to work. I've tried the newest release and old releases, all same result. Is there anything I could do now?

**Comment by d0k3** [comment]
What is the file size of godmode9.firm? Also, any chance this SD is corrupted? Try with a different SD, for testing purposes.

**Comment by vprw** [comment]
so i dont know whats going on. i saw your reply, and i tried a different sd card, and it just worked. then i switched back to the original card, and do the same thing ive done many times before i open this issue, and now it just works... maybe its because i deleted the '.Trash-999' folder in the original sd card(?)

**Comment by d0k3** [comment]
Most likely a SD card corruption issue. Be careful with this SD card. Closing this now...
