### ISSUE TITLE
support for other VC saves?

### ISSUE THREAD

**Issue by gingerbeardman** [d0k3/GodMode9#106]
would be much appreciated.

I need to transfer a Game Gear save.

**Comment by d0k3** [comment]
Well, not really possible, cause GBA saves have their own partition in NAND, while other VCs don't. I suggest you try with something like JKSM. Save handling in general is near impossible in ARM9 cause we need system OS functions normally, GBA is the exception.

**Comment by gingerbeardman** [comment]
Thanks for the explanation!

**Comment by gingerbeardman** [comment]
I just did it using JKSM (and also FBI just for kicks)
