### ISSUE TITLE
Feature Request - image .bmp viewer

### ISSUE THREAD

**Issue by RS55** [d0k3/GodMode9#107]
I apologize for the suggestion, but it is possible that you can see images .bmp (luma/ntr screenshot)?. It would be nice not to be checking on the PC always, but I imagine it would be a feature for CTRX

**Comment by d0k3** [comment]
As much as I'd like this, implementing an image viewer would mean implementing a proper scaler, too, which can get very complciated. Add on top of that that this would only be for the rarely used BMP format, and doing actual JPEG and PNG codecs in GM9 is out of question. Won't be coming to GM9, sorry.
