### ISSUE TITLE
DSi-Enhanced dumping not proper dumps

### ISSUE THREAD

**Issue by Shadow322** [d0k3/GodMode9#108]
OK so I used the latest nightly as instructed to dump System FLAW DSi White retail Cart full rom not trim then place the dumped rom on my iEVO and i get this error

"ERROR: This DSi-enhanced game cannot be played while operating in DSi mode, because the DSi specific sections are missing from the ROM file. Please load iEVO in DSL mode to play this file."

**Comment by d0k3** [comment]
Can you check the CRC32 or MD5 for your dump?
http://datomatic.no-intro.org/index.php?page=show_record&s=54&n=0004

If it matches, the problem is not in GM9, but rather in the iEVO.

**Comment by Shadow322** [comment]
Ok yep the crc/md5 match :(

**Comment by Shadow322** [comment]
that means the iEVO can never run it because games like Tron work fine in DSi mode as it can use the QR Code option as i just tested and used the camera

**Comment by d0k3** [comment]
Well.... that at least means GM9 does a good job here. You may need to search around, maybe there is a solution. Sounds like an iEVO compatibility issue to me, though.

**Comment by RocketRobz** [comment]
Can this be re-opened?
Reportedly, the DSi areas aren't being dumped properly on the latest GM9i version, as a recent Pokemon Black dump via GM9, causes TWiLight Menu++ to report that the DSi binaries are missing.

**Comment by d0k3** [comment]
This depends. Do dumps made with older GM9 builds work? Are other games also affected? Does the CRC match the Datomatic one?

I think that's rather a new issue. If it is one, we will need someone to do a bit bisect. Can you help? First open a new issue, though.

**Comment by Wolfvak** [comment]
@RocketRobz if you want to, open a new issue and include any relevant info on it.
