### ISSUE TITLE
GODMODE9 is not booting

### ISSUE THREAD

**Issue by h4rv1n** [d0k3/GodMode9#109]
This morning, I tried to update my Luma 7.1 to 8.1 through Luma star updater. It didn't update at all, so I tried to update it manually through 3ds.guide website on updating the B9S. However, Godmode9 cannot be booted by holding start button anymore. Any advices?
Thanks in advance

**Comment by fr3quency** [comment]
This is not a help forum... What's wrong with you guys wanting to make GitHub into GBAtemp and wasting our times in both sites?

**Comment by d0k3** [comment]
You didn't update properly. Update them all, boot9strap, Luma 3DS and GM9, @h4rv1n. And @fr3quency is right, you should search for support elsewhere (GBAtemp or Reddit maybe?). Github issues really is only for bug reporting and feature requests.
