### ISSUE TITLE
Inconsistent text when enabling write permissions with R+Y

### ISSUE THREAD

**Issue by flarn2006** [d0k3/GodMode9#11]
When you press R+Y to unlock write permissions, it says "You want to enable ALL writing permissions. This enabled you to do some really dangerous stuff!" However, even after entering the confirmation sequence, FIRM ("A9LH") writing is still disabled. Which means not "ALL writing permissions" were enabled.

Clearly either the text is wrong, or R+Y is supposed to enable FIRM writing as well but it doesn't. If you go the route of making R+Y truly enable all permissions, you should probably add a warning to that effect, to make it clear that you can brick that way even with A9LH installed. (Is there anything you can do with A9LH installed that will cause a brick _without_ enabling FIRM writing, other than editing RAM in a way that happens to cause GodMode9 to write to FIRM?)

**Comment by fox8091** [comment]
To answer the bricking question, yes, it is possible. "Accidentally" delete the titles folder on NAND with no backup.

**Comment by flarn2006** [comment]
@fox8091 Oh yeah, I meant if you have a full NAND backup. Sorry.

**Comment by d0k3** [comment]
Good find actually, but, tbh, this behaviour is fully intended. And you are still right about this, of course.

The logic behind this: You are a informed user, but not everyone is. Uninformed users may just "enable all writing permissions" (cause why bother with entering the sequences every time?) and not think about their A9LH. Thus, for those users, I need to make it extra clear when it gets really, really dangerous. And I rather accept inconsistent text then to make this dangerous.

I will think about changing the text, though.

@fox8091 - there actually is no way for a permanent, non-software-fixable brick without the A9LH write permission (if you have A9LH installed, that is), even without a NAND backup of your own. There is the CTR transfer in D9 that will help you fix a borked CTRNAND even without a NAND backup. TWLN is interchangeable between consoles (as long as on the same FW version, afaik). Losing your movable.sed / LocalFriendCodeSeed / SecureInfo_A is no laughing matter, ofc, but not irreplacable (as long as you can go without online play, ofc.

**Comment by d0k3** [comment]
Okay, I considered this, and I'll leave it as is. The reasoning is found in what I wrote above.
