### ISSUE TITLE
Feature Request - NCSD image options with scripting

### ISSUE THREAD

**Issue by joo456** [d0k3/GodMode9#111]
Decrypt file, Encrypt file, Build CIA from file, etc.

**Comment by Jan200101** [comment]
Possibly options like `Show title info` to get the user to confirm if that was the object they selected

**Comment by d0k3** [comment]
Okay, added here:
https://github.com/d0k3/GodMode9/commit/e4a0d62d169c70a168b03aee74955752147c1fd1

Please test (refer to HelloScript.gm9 for how stuff works)
https://transfer.sh/10ywpL/GodMode9-20170727-123014.zip
