### ISSUE TITLE
Feature Request - Environment Variables and user input

### ISSUE THREAD

**Issue by Jan200101** [d0k3/GodMode9#112]
User input should be pretty self explaining.

With Environment Variables I mean the same way Linux Windows have Variables for the current Directory the user is in or where the Home Folder is located.

**Comment by ZetaDesigns** [comment]
That's a great idea.

**Comment by d0k3** [comment]
The home folder is the `0:/gm9/out` folder, right? Use rinput has been requested several times, and will be coming. Now, you want an environment var for the directory your script runs from, right? I can do this.

**Comment by d0k3** [comment]
'CURRDIR' env var and 'input' command added. Check `HelloScript.gm9` to see how it works.
