### ISSUE TITLE
Bug Report: 'allow' command with SD fails to work.

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#114]
I wrote a script where I used 2 separate 'allow' commands to allow writes to the SD card and to the CTRNAND. It appears as follows:

set ERRORMSG "msg0"
allow -a 0:/
set ERRORMSG "msg1"
allow -a 1:/
set ERRORMSG "msg2"

When running the script, it **first** asks for the key input for unlocking the SysNAND, not the SD.
If I say yes to this, I can make changes to the CTRNAND without issue. If I say no, I get msg1 and a script abort, as expected.

However, if I say yes to the SysNAND permissions, do something with CTRNAND, then try to modify the SD, it asks for the key input for unlocking the SD **at this point**. If I say yes, it's fine, but if I say no, I get msg2.

The bug is that "allow -a 0:/" does not work as expected, but other mounts do work.

**Comment by Anggeloko** [comment]
Do not need permission in the SD

**Comment by CecilFF4** [comment]
You do if you need to modify the ID0 folder or its contents.

**Comment by d0k3** [comment]
@Anggeloko and @CecilFF4 are both right. However, the handling may seem illogical. Need to think about this for a bit. You're only asked for permissions if you try to modify something in `Nintendo 3DS`, which you should actually be using the A:/B: drives for.

**Comment by CecilFF4** [comment]
Ideally, yes, if I was modifying something inside the ID0 folder, I would use the dedicated mount you designated. However, I'm actually modifying the name of the ID0 folder itself.

By modifying the ID0 folder on the SD (and the data/dbs folders on the CTRNAND), I can effectively create multiple 3DS profiles (they use the same movable.sed, which is why a rename of the folder names is required).

I use other profiles for my kids and eshop access (so illegitimate DLC is not deleted... and also because I got a clean ticket.db on that profile, which may hypothetically decrease my chance of getting banned).

**Comment by d0k3** [comment]
Oh, okay. In that case the command to allow would be: `allow "0:/Nintendo 3DS"` (or `allow -a "0:/Nintendo 3DS"`, doesn't matter). Given the special nature of this folder, and people being likely to mess up here, I'll leave the handling as is, even if it may seem a bit illogical.

@CecilFF4 - can you confirm this works for you?

**Comment by CecilFF4** [comment]
@d0k3 That worked perfectly. I see no reason for you to change the handling as I'm sure most people aren't doing what I'm doing. Maybe a little note about this in the wiki is all it'll take. Thanks for the help!
