### ISSUE TITLE
Bug Report: Text Viewer numbers

### ISSUE THREAD

**Issue by AidenTheCuber** [d0k3/GodMode9#115]
If i scroll up and down with the R button pressed, sometimes the number "**0000**" will appear above the number "**0001**".  If i then scroll up and down **without the R** button pressed the number "**4294967295**" will appear. Please fix it.

**Comment by d0k3** [comment]
@AidenTheCuber - okay, that doesn't happen for me at all. Can you provide me with a text file for which it happens and/or provide more instructions to make it happen?

**Comment by AidenTheCuber** [comment]
[Text Viewer Bug.zip](https://github.com/d0k3/GodMode9/files/1174953/Text.Viewer.Bug.zip)

What I did in this video: **Hold the R button the whole time, then press 2 times down, press 2 times up,  press 2 times down and then press 2 times up.**

And i'm using "Decrypt9.log"

**Comment by james-d-elliott** [comment]
You might want to upload "Decrypt9.log" as well to make it easier to reproduce and find a fix for.

**Comment by AidenTheCuber** [comment]
@james-d-elliott 
[Decrypt9.zip](https://github.com/d0k3/GodMode9/files/1176279/Decrypt9.zip)
Here it is.

**Comment by d0k3** [comment]
Okay, that was actually pretty easy to reproduce. I'm at it.

**Comment by d0k3** [comment]
@AidenTheCuber can you try this and tell me if it is fixed?
https://transfer.sh/14Ylb4/GodMode9-20170726-203902.zip

**Comment by AidenTheCuber** [comment]
@d0k3 
It's fixed. Thanks!
