### ISSUE TITLE
Feature Request - Texteditor edit .txt and .cfg files

### ISSUE THREAD

**Issue by Lordkurzschluss** [d0k3/GodMode9#117]
It would be nice to edit .txt and .cfg files with the new text editor

**Comment by AidenTheCuber** [comment]
that's a cool idea

**Comment by joo456** [comment]
try making a good 3ds keyboard :V

**Comment by Lordkurzschluss** [comment]
@joo456 I guess it would be a bit hard, because in ARM9 Payload mode, there is no Touch in the Screen hehe 👍

**Comment by SvenDaHacker64** [comment]
@Lordkurzschluss Strangely enough [Linux for 3DS](https://gbatemp.net/threads/release-linux-for-the-3ds.407187/) has touchscreen support for keyboard while running ARM9 :/

**Comment by d0k3** [comment]
This may be coming at a later point, however, for now, I have to decline this request. If you just check the source, a limited text viewer is already a massive pita, and a text editor would complicates stuff to a point where it is no more feasible. Also, no keyboard as you guys have already pointed out.
