### ISSUE TITLE
Feature Request - New and Old3ds flag

### ISSUE THREAD

**Issue by Jan200101** [d0k3/GodMode9#118]
two (or maybe one) flags that are set based if its a old 3ds or not.

**Comment by d0k3** [comment]
Can you be more specific? Flags? Do you mean environment vars? And can you also give me an usage example?

**Comment by d0k3** [comment]
@Jan200101 - I need more info, otherwise I'll have to close this.

**Comment by Jan200101** [comment]
Sadly I have no current example on how this could be used effectifly.
Closing issue for having no use
