### ISSUE TITLE
devkitARM r47 compatibility

### ISSUE THREAD

**Issue by NWPlayer123** [d0k3/GodMode9#119]
r47 seems to break compilation, when building the elf at the end:
linking GodMode9.elf
C:\Users\NWPLAY~1\AppData\Local\Temp\cc7M9X1g.ltrans1.ltrans.o: In function 'run_line':
C:/Hacks/3DS/git/GodMode9/source/filesys/fsscript.c:399: undefined reference to 'strntohex'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/c/devkitPro/devkitARM/ds_rules:54: /c/Hacks/3DS/git/GodMode9/output/GodMode9.elf] Error 1
make: *** [Makefile:134: binary] Error 2

**Comment by TuxSH** [comment]
That's because strntohex shouldn't be inline to begin with. Issue solved.
