### ISSUE TITLE
GodMode9 always say "Failed initializing SD card"...

### ISSUE THREAD

**Issue by mariogamer2** [d0k3/GodMode9#12]
With an a9lh 3ds, I cannot run GodMode9 as a luma payload or arm9loaderhax_si.bin,this simply give me "Failed to init....".

**Comment by manc192** [comment]
This is also occuring with me as well

**Comment by d0k3** [comment]
Can you two try with another SD card? Also, do you have the same problems with D9?

**Comment by manc192** [comment]
Decrypt9 and Hourglass9 work just fine. Just the last 2 releases of GM9 don't work. I'll try swapping cards and seeing if that works

**Comment by d0k3** [comment]
You mean the release before worked?

**Comment by manc192** [comment]
v0.6.6 and  v0.7.3 dont work, but v0.5.1 does. Im o3ds xl btw

**Comment by mariogamer2** [comment]
@d0k3 I do not have the same problem with D9,it work just fine. I'll try another SD.

(Also I'm using latest commit of GM9 and D9)

**Comment by mariogamer2** [comment]
With another sd card: luma work,but GM9 black screen...

**Comment by urherenow** [comment]
@mariogamer2, so what's different between the two? Size, cluster size, emunand or some other differences in partitions, etc...

**Comment by d0k3** [comment]
@mariogamer2: I assume you have the noscreeninit version of A9LH installed? In that case, running GM9 will not show anything on screen. Also, try to find out what's different between the two SDs. What have they been formatted with? I assume it is either cluster size or a bad formatter.

**Comment by mariogamer2** [comment]
At least,they have the same size. Need to verify for other.

Also I mean the CFW work but I didn't used it as a payload.

I'll try with arm9loaderhax_si.bin.

**Comment by mariogamer2** [comment]
arm9loaderhax_si : initializing sd card fail

I'll rename the issues.

**Comment by mariogamer2** [comment]
Just formated with emunand9 it work.... Maybe it was a cluster thing? (I think it was under 64k)

@manc192 Try with creating a new partition table with 64k when prompted,or simply format with E9

**Comment by manc192** [comment]
@mariogamer2 I ended up copying all my files onto another sd and using godmode9 from there

**Comment by KallDrexx** [comment]
Just thought I'd pipe in and add that like manc192 I had to switch SD cards for some reason.  No idea the difference between the two.
