### ISSUE TITLE
[Suggestion] Install CIAs to console

### ISSUE THREAD

**Issue by Dimensional** [d0k3/GodMode9#120]
Would it be possible to use GM9 to install CIAs to the 3DS, as like an alternate method to FBI? The files would obviously have to be downloaded and copied to the SD card, but given the program can extract CIAs, couldn't it also be used to install? This isn't the same as suggesting injecting like others have.

**Comment by james-d-elliott** [comment]
I don't think that GM9 would have access to do this. I'm pretty sure there are services required to do installs as well as ARM11 access (maybe).

**Comment by Lordkurzschluss** [comment]
@james-d-elliott You are totally right, i guess that this wouldnt work the only thing i could imagine is #90 but @d0k3 already said, that this wont work. 

Probaly wont work

**Comment by Dimensional** [comment]
That has more to do with injections than installations. And if to install the game you need ARM11 access, couldn't GM9 be programmed with the necessary services and access code? This is running very early in the boot cycle, so couldn't it potentially call up some of the opcodes and syscalls, if not have it built right into the program itself?

**Comment by deadair3210** [comment]
The problem isn't that it couldn't be programmed to use the services, its that those services don't exist this early in the process. Not only would you have to worry about decrypting the CIA and reencrypting/placing the files in the right spot, you would also have to worry about adding the correct information into the relevant files. It's not worth it when its just as easy to just install it using FBI

**Comment by Lordkurzschluss** [comment]
@deadair3210 or NASA

**Comment by d0k3** [comment]
@deadair3210 is completely right. Injection is not installation, @Lordkurzschluss and @Dimensional, and it comes with it's own limititations (needs to replace an already installed title, has a small size limitation).

Not possible!
