### ISSUE TITLE
How Can I get the romfs and exefs?

### ISSUE THREAD

**Issue by Dudamax** [d0k3/GodMode9#123]
I know that there is braindump but homebrew launcher 2.0.0 dosent launch it anymore. Hopefully i could get these files with godmode9 or another app?

**Comment by d0k3** [comment]
Oh well, here's to something that really doesn't belong in here. Your question could have been answered via the readme or via one of the usual places (Google, GBAtemp, Reddit). Just mount the game file and copy the ExeFS / RomFS / whatever you need from the mounted drive.
