### ISSUE TITLE
Dump of Aging Card NTR is bad?

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#124]
GameHeader and Crappy Tiny Reader seem to think it isn't decrypted (or maybe bad in some other way).

Is this an oddity with the cart or a problem with GodMode9? The version used was v1.2.1

The ROM details can be found in the No-Intro dat.

**Comment by fox8091** [comment]
Remove the ROM link please. That's copyright content and has no place here.

**Comment by d0k3** [comment]
What cart is this about? A flashcart? If so, flashcarts are special and not a real priority in the GM9 cart dumper. If it is a flashcart, and if you know it works elsewhere, I may still be able to look into it.

**Comment by mariomadproductions** [comment]
It is a testing cart made by Nintendo, not a flash cart.

**Comment by fox8091** [comment]
@d0k3 NTR Aging is a DS cart that does system testing and likely burns the final firmware, similar to CTRAging.

**Comment by d0k3** [comment]
As far as I know, there is no good dump of NTRAGING available. @mariomadproductions - can you send me a pm (GBAtemp maybe) or contact me on IRC (freenode, Cakey)?

**Comment by mariomadproductions** [comment]
Its a recent dump. I've PM'd you.

**Comment by d0k3** [comment]
Okay, I've checked it, it's a good dump, and the secure area is not decrypted for some reason. The latter puzzles me. We may keep that as is, but I'll first have to look into this some more.

**Comment by d0k3** [comment]
Alright, here's some more info. There are titles with known bad secure areas. Dragon Quest 5 is a known commercial one, and NTR AGING also has a bad secure area (the one other known good dump has, too). If the secure area is bad, well... it may not be possible to be decrypted either.

As the dump is still good, I'm somewhat tempted to handle this as a non-issue. @mariomadproductions - does the cart itself still work?

**Comment by mariomadproductions** [comment]
Yes, the cart and both dumps work. I didn't make the dump and I don't own the cart, btw.

The old DS homebrew "NDS Backup Tool Wi-Fi v0.31f" produces a decrypted dump of Aging Card NTR. You may want to look into that.

**Comment by mariomadproductions** [comment]
The old DS homebrew "NDS Backup Tool Wi-Fi v0.31f" produces a decrypted dump of Aging Card NTR. You may want to look into that.

The cart and both dumps work. I didn't make the dump and I don't own the cart, btw.

**Comment by d0k3** [comment]
Okay, that tool is closed source, we can't learn anything from it. I have a suspicion it just detects the secure are as invalid and inserts a placeholder (maybe?).

**Comment by fox8091** [comment]
Perhaps we can test by dumping another known problem cart and comparing it?

**Comment by d0k3** [comment]
So... is anyone in possesion of Dragon Quest 5?

**Comment by d0k3** [comment]
Okay, @mariomadproductions - I think I know have a clue what happend. That secure area may have been decrypted from the start, we tried to decrypt again, and the end result is what you got.

Try this GM9 build:
https://transfer.sh/13Z6GD/GodMode9-20170729-121300.zip

Does it dump that cart the same as "NDS Backup Tool Wi-Fi v0.31f"?

**Comment by mariomadproductions** [comment]
I've asked the owner of the cart to dump it again with that.

**Comment by d0k3** [comment]
@mariomadproductions - got any news for me?

**Comment by mariomadproductions** [comment]
The owner is busy for about a week, sorry.

**Comment by mariomadproductions** [comment]
He said
> GodMode9-20170729-121300 crashes on my system, giving me this ARM9 dump: https://transfer.sh/QUUYU/crash_dump_00000000.dmp

**Comment by d0k3** [comment]
Can you tell me what entrypoint he uses?

**Comment by mariomadproductions** [comment]
With that last link he still got a crc32 of 3703322e.

**Comment by d0k3** [comment]
Okay, we'll try this differently then.

Can you try this build:
https://transfer.sh/LJ21L/GodMode9-20170805-160149.zip

... then send me a dump (it will be different now) via pm.

**Comment by Localhorst86** [comment]
got a CRC32 of D912301A now. PM sent

**Comment by Localhorst86** [comment]
![img_20170805_153027](https://user-images.githubusercontent.com/30772376/29003181-33210680-7ab2-11e7-86c7-16483a321fcf.jpg)
If it is at all relevant, this is what the 3DS shows me when inserting the cartridge. The title seems to be blank. My entrypoint is B9S 1.2

**Comment by d0k3** [comment]
@Localhorst86 - you're the owner of the cart? And the same cart has a different CRC when dumped via that other tool, right?

Did you try running the new dump via a flashcart, and does it work?

**Comment by Localhorst86** [comment]
Yes, I am the owner of the cartridge. I have dumped it using various tools and versions, both wooddumper and Godmode9 gave me the same CRC32 of 3703322e, whereas "NDS Backup Tool Wi-Fi v0.31f" results in a different CRC. 

It never occured to me to run the dumped ROM on a flashcard, though. I am going to give this a try later tonight and report back.

**Comment by Localhorst86** [comment]
Actually, none of the dumps work on my R4i-sdhc flashcard. Neither the one using NDS Backup Tool Wi-Fi v0.31f (b7f1a15e), nor the ones using Godmode9 1.2.9 (3703322e) or the last one from GodMode9-20170805-160149 (d912301a)

**Comment by mariomadproductions** [comment]
The old one worked on my Acekard 2i. I'll test the new one.

**Comment by mariomadproductions** [comment]
3703322e and d912301a work too.

**Comment by d0k3** [comment]
I've had some unexpected help from resident genius @Normmatt. This one should generate a correct result:
https://transfer.sh/FMEqY/GodMode9-20170809-233638.zip

Secure area will appear as encrypted, but only cause it isn't actually used. Secure area CRC should match. You can use Crappy Tiny Reader to check. Could you also check with one regular gamecart, to see if my fix broke anything?

**Comment by Localhorst86** [comment]
GodMode9-20170809-235158 gave me a CRC of d912301a again for the Aging Cartridge.

I also dumped a retail cartridge of "Guitar Hero on Tour Decades" (http://datomatic.no-intro.org/?page=show_record&s=28&n=2897) and for this i got the proper CRC of c9dd37c5

**Comment by d0k3** [comment]
d912301a is the correct CRC for that cart. Both earlier options (Woodumper and NTR Backup Tool Wifi) were wrong. 

See here:
http://problemkaputt.de/gbatek.htm#dscartridgesecurearea

"1) Set NDS9 ROM offset to 4000h, and leave the first 800h bytes of the Secure Area 00h-filled, which can be (and will be) safely destroyed during loading; due to the missing "encryObj" ID; that method is used by Nintendo's devkit."

Meaning: What you got there is the first ever good dump of this cart (check in Crappy Tiny Reader for the Secure Area CRC if you want). Can you, maybe, also update the entry on NoIntro? Also, thanks a lof, both of you.

**Comment by mariomadproductions** [comment]
Of course. Thank you for adding support for it.

**Comment by d0k3** [comment]
GM9 dumps what it can and doesn't blank the Secure Area out. It just dumps what it can find. As you see, the Secure Area is supposed to be all zeroes, at least the first 0x800 byte even have to be.

**Comment by mariomadproductions** [comment]
I see, thanks for the explanation.
