### ISSUE TITLE
"Gamecart writing is locked"?

### ISSUE THREAD

**Issue by ToxiKutie** [d0k3/GodMode9#128]
When there is a gamecart inserted and you attempt to use the "good name" on the ROM inside the gamecart, it allows you to unlock the write permission, then throws the error. I'm really just wondering why unlocking it allowed if it doesn't work.

An unrelated question; What is the Bonus Drive used for?

**Comment by RubberBrony** [comment]
Bonus drive uses the extra space (up to a gigabyte depending on your console) on NAND as exactly what it sounds like, a bonus storage. You can copy files there and keep them locally on the system.

**Comment by d0k3** [comment]
The exact error message is: "Unlock write permission for game carts is not allowed.", and, yes, that doesn't work. I'll need to think about this for a bit.
