### ISSUE TITLE
Feature Request - Control Flow in GM9 Scripts

### ISSUE THREAD

**Issue by ValliantStorme** [d0k3/GodMode9#129]
Control flow commands would be nice (if-else, loops, and maybe jumps to marked locations in a script). 
I've been playing with the scripting feature all night, and so far I'm impressed with the amount of control this early iteration gives the user. I hope to see it expanded upon massively!

EDIT: Additionally, allowing a script to call another script would be nice too, but would probably be overkill or unnecessary.

EDIT 2: Didn't know GM9 supported file structures within /gm9/scripts. Good to know that it does, solved my problem with selection menus (for my use-case at least).

**Comment by d0k3** [comment]
I'm actually thinking about adding a `goto` command, however this is prone to error and not a priority right now. Btw, I'm glad to see people putting scripting to use, and I hope to see some interesting scripts pop up soon :).

**Comment by d0k3** [comment]
Arithmetic may be a good addition to this, too.

**Comment by annson24** [comment]
Control Flow feature will be great, user input will be a good idea too rather than only having to choose from Yes/No(sorta).

Anyway, I'm up for testing.

**Comment by jason0597** [comment]
Maybe just implement lua?

**Comment by d0k3** [comment]
I guess you didn't think this day would come... thanks to the tireless work of @windows-server-2003 and in no small part thanks to [Kazuma77](http://gbatemp.net/threads/release-godmode9-all-access-file-browser-for-the-3ds.420027/page-43#post-7743068)'s testing, we now have `if`-`else`-`goto` in GodMode9 scripts. As a cherry on the Cake, I also added an `elif` command.

Thanks everyone involved, closing this now!
