### ISSUE TITLE
Home Button For Home Menu

### ISSUE THREAD

**Issue by emre009** [d0k3/GodMode9#131]
I can not enter other menus because my home key is defective on my device. I am happy if my software buddies do something for this. Instead of the Home key, you can enter another key.

**Comment by mariogamer2** [comment]
@d0k3 don't know if a script would be useful for noob to build custom button build?

**Comment by d0k3** [comment]
And here's to another "broken console" special build request. Do it yourself:
https://github.com/d0k3/GodMode9/blob/master/source/common/hid.h#L12-L23

Swap the definition of your broken button with one that works, one that you don't need otherwise. Compile and run from your console. If you can't do this, ask someone mrope knowledgeable.

**Comment by CuriousTommy** [comment]
> And here's to another "broken console" special build request. Do it yourself:
https://github.com/d0k3/GodMode9/blob/master/source/common/hid.h#L12-L23

@d0k3 Why not make these values as variables that can be changed instead? That way, you can have a text file on the root of the SD card, such as `accessibility.txt` that states which button you want to replace.

**Comment by emre009** [comment]
Only the home key is not working on my New 3ds XL. I was doing the 11.2 version breaking of my device. I came to that section. 

Section VI - CTRNAND Luma3DS
Launch GodMode9 by holding (Start) during boot
If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has completed
Press (Home) to bring up the action menu
Select “More…”
Select “Scripts…”
Select “setup_ctrnand_luma3ds”
When prompted, press (A) to proceed
Press (A) to unlock SysNAND (lvl1) writing, then input the key combo given
Press (A) to continue
Press (A) to relock write permissions

I can only do GodMode9 permissions. It's easy to make changes with Notepad but it's hard to build. I could not find any videos on these topics. I downloaded DevKitpro. But I did not do it either. Sd card i will try it if i let them do what you say. Programming is really hard work. God give you easiness.

**Comment by dark-samus** [comment]
compiling is a lot easier than a lot of people make it out to be. First, make sure that when you clone the repo (assuming you're using a command line) specify the "--recursive" option. Next, follow the instructions from here: https://www.3dbrew.org/wiki/Setting_up_Development_Environment#Windows (assuming you're on windows) from there, it should be as easy as typing "make" and pressing enter while in the proper directory from a command line.

**Comment by d0k3** [comment]
Oh well, @emre009 - I'm having mercy, for once. Be aware that normally it is fix your console or learn to compile, and that I won't do other special builds anymore.

This allows you to use the SELECT button as HOME button replacement:
https://transfer.sh/6QjNR/GodMode9-20170731-230358.zip

**Comment by FlashlightET** [comment]
kinda sucks that since its transfer.sh the link is broken, but ill try to compile it myself since theres a guide to set it up

**Comment by swartgaming** [comment]
> hey for anyone stumbling on this with godmode 9.2.1+ and you get to the "Press (Home) to bring up the action menu", you can just hit the Power button and it'll bring up a menu where you can select "Scripts..."

Thank you so much!
