### ISSUE TITLE
Feature Request: List current title being dumped in a bulk dump

### ISSUE THREAD

**Issue by AnalogMan151** [d0k3/GodMode9#136]
When using the title search feature on a directory, you can select multiple title names and choose to dump those titles to CIA or other options. While the dump is progressing, it's hard to tell which title it's on or how far through the list it is. 

Displaying a simple (X/Y) marker or even the name of the current TMD being processed would be nice.

**Comment by d0k3** [comment]
I'll look into it.

**Comment by d0k3** [comment]
https://github.com/d0k3/GodMode9/commit/f09aa9bf09a7e911e70be85210b44c451edaeae4
This ^ should serve well as an indicator on where in the filelist the current batch operation is.
