### ISSUE TITLE
Sleep mode switch causes home button to not work

### ISSUE THREAD

**Issue by Dysproh** [d0k3/GodMode9#139]
I was using gm9 on my 2ds and I noticed that the home button does nothing if the sleep switch is set to on. It is not a huge issue, but it is present. Is this a problem with gm9 or just nintendo nintending?

**Comment by al3x10m** [comment]
that's a nintendo thing....if you press HOME while in gm9...with sleep mode on...it doesn't work...but it'll register the press. when you release sleep button....the menu will appear out of nowhere...just like you pressed home in that moment.

**Comment by d0k3** [comment]
Yup, correct. Closing this now, @Dysproh, that's just the 3DS working as it should.
