### ISSUE TITLE
TWL NAND/Photo drives do not show up using boot9strap 1.0

### ISSUE THREAD

**Issue by enderghast13** [d0k3/GodMode9#140]
On GodMode9 v1.2.8 (official) and v1.2.7 (tested using CrimsonMaple's fork) on my Old 3DS, the TWLN and TWLP drives do not show up on the GodMode9 home screen. There partitions also do not show up in the SysNAND Virtual drive, though twlmbr.bin does show up. This has not been tested using boot9strap 1.1 or on a New 3DS running B9S 1.0/1.1. Also, on an unrelated note, the essential backup nag screen does no show up despite me not having made one.

**Comment by ValliantStorme** [comment]
Have you tried updating to B9S 1.2? You can find instructions for doing so [here](https://3ds.guide/updating-b9s). As far as I'm aware, B9S 1.0 was rushed to launch, and didn't support all of the planned/necessary features.

**Comment by enderghast13** [comment]
I do know how to install B9S 1.2 and have done so on my N3DS, but I chose not to on my O3DS as Luma3DS 8.0+ no longer supports *hax 2.0+ payloads and Rosalina's way of booting the homebrew launcher does not allow homebrew apps to take over other titles, which is needed for things like sploit installers and RomFS Extractor to work, so even if I never need to use those apps again, it would be nice knowing I still have the option to in some form. Anyways, this issue was mainly created just in case d0k3 hadn't known about it and may have either wanted to fix it or not do anything about it and just recommend people upgrade to B9S 1.2 and mark this bug as wontfix or closed.

**Comment by fox8091** [comment]
For one, it is a known issue. For two, those apps you mentioned can still be used. Just run Rosalina under the selected title by changing the hb title.

**Comment by enderghast13** [comment]
Thank you for telling me that second part, but how do you know that this is a known issue exactly. I haven't seen any closed issues about this nor any statement by d0k3 about this, and I'm also convinced it is a real bug as it did not happen with previous versions of GodMode9 on B9S v1.0. I understand it is not a major issue by any means, but I thought it would just be good to raise attention to it anyways just in case.

**Comment by fox8091** [comment]
My contributions are minimal at best. :P Anyways, I forget _where_ I saw it, but I remember TWL key init being an issue in earlier builds of boot9strap.

**Comment by enderghast13** [comment]
Okay, I understand now. Thanks for the reply as I was just confused as to why my issue was happening in the first place.

**Comment by fox8091** [comment]
No problem. Happy to help.

**Comment by d0k3** [comment]
You could have also solved that issue by simple getting the aeskeydb.bin file mentioned in the readme, just saying. Guess I should have made that clearer, though.

**Comment by enderghast13** [comment]
Ok then. Thanks.
