### ISSUE TITLE
GM9 1.3.0 displays at max brightness

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#141]
Regardless of Luma settings, the brightness is at max now on gm9, where 1.2.8 did not have that issue.

**Comment by d0k3** [comment]
That's because GodMode9 now does it's own screen init. I can look into providing ways to change it. Maybe I'll even lower the default a bit.

**Comment by CecilFF4** [comment]
Being able to change it would be a blessing. It does hurt my eyes to view it at night.

**Comment by d0k3** [comment]
Brightness is now changeable via the volume slider, courtesy of @Wolfvak. Release coming up...

**Comment by CecilFF4** [comment]
Can we not go back to letting Luma determine the brightness? Turning the volume down every time I want to use gm9 sounds irritating. I'm very appreciative of the work you are doing, btw; sorry if it sounds like I'm nitpicking.

**Comment by d0k3** [comment]
It's not as bad as you may think now, and it's definitely a lot better than having fixed brightness. Problem is, GM9 now does it's own screeninit, so we have to handle brightness, too.

**Comment by SvenDaHacker64** [comment]
Wouldn't that be better to use 3D slider for brightness?

**Comment by Wolfvak** [comment]
3D slider is unavailable in 2DS and new 2DS XL consoles.

 Sven Cuaresma <notifications@github.com> wrote:



Wouldn't that be better to use 3D slider for brightness?
