### ISSUE TITLE
GM9 1.3.0 brakes FAT Image Mount at DSiware sav file

### ISSUE THREAD

**Issue by knight-ryu12** [d0k3/GodMode9#142]
Yep, pretty much.
UPDATE: Old GM9 works fine

**Comment by d0k3** [comment]
By old GM9 you mean GM9 v1.2.8? That's almost impossible, cause I changed nothing in the relevant routines. Can you give me the file that doesn't mount and a more detailed description (I'd need to know at least the path you tried to mount from).

**Comment by knight-ryu12** [comment]
MountPath is CTRNAND TWLN->/title/00030004/<any8digit>/data/public.sav

[public.sav.zip](https://github.com/d0k3/GodMode9/files/1205131/public.sav.zip)

**Comment by d0k3** [comment]
Also, sorry @saibotu for not seeing your pull request earlier. Is the solution you came up with the same as mine?

**Comment by saibotu** [comment]
No problem. Mine, as mentioned in #144, didn't fully work anyway.

**Comment by d0k3** [comment]
Still, thank you! Know that these contributions are appreciated.

**Comment by knight-ryu12** [comment]
Yeah, Thanks. I'll go ahead using nightly for now
