### ISSUE TITLE
Feature Change: RTC time set to ISO YYYY-MM-DD format

### ISSUE THREAD

**Issue by AnalogMan151** [d0k3/GodMode9#143]
When setting my RTC time with the new GodMode9, I didn't realize it went YYYY-DD-MM and got my clock messed up a bit. Would it be possible to re-aarange it or provide a label above them or at least a note about the order?

**Comment by d0k3** [comment]
Okay, I'll look into that.

**Comment by Uumas** [comment]
Yeah DDMMYYYY would seem like a better idea to me

**Comment by ihaveamac** [comment]
[YYYY-MM-DD would be the least confusing format.](https://xkcd.com/1179/) nobody should be confused about the order. it also makes it easier to sort.

**Comment by Edualvs** [comment]
Objection!

**Comment by d0k3** [comment]
Eh, you dig out a one and a half year buried issue, one that has also reached a conlcusion, and you object?

**Comment by james-d-elliott** [comment]
Overruled, this issued was closed over a year ago. Don't make me hold you in contempt of the repository. (Couldn't help myself, I'm sorry)
