### ISSUE TITLE
Cannot mount public.sav as FAT

### ISSUE THREAD

**Issue by zanetheinsane** [d0k3/GodMode9#145]
When following 3ds.guide for installing B9S using the DSIware injection, on GodMode9-20170807-002353 when attempting to "Mount as FAT image" on the file public.sav I receive the error "Mounting Image: Failed".

When rolling back to a previous version, GodMode9-20170531-232521, public.sav mounts without issue.

**Comment by knight-ryu12** [comment]
#142 already reported. please try newest nightly.
