### ISSUE TITLE
Unable to Mount as FAT on public.sav

### ISSUE THREAD

**Issue by m0nm0npalam0n** [d0k3/GodMode9#150]
I am following the DSiWare Game Injection Guide but it says Mounting image: Failed... I'm using 1.3.0..

**Comment by d0k3** [comment]
Guys, give me a break. You're the 5th person to open an issue for that, and it's already fixed. It is in the nightly, now give me five minutes for a release, will ya?

**Comment by m0nm0npalam0n** [comment]
Tried running 1.2.8 and it just worked fine... i have no idea what went wrong

**Comment by m0nm0npalam0n** [comment]
oh sorry... thank you very much
