### ISSUE TITLE
Latest release may have broken GM9Link compatibility

### ISSUE THREAD

**Issue by LinkSoraZelda** [d0k3/GodMode9#151]
At least, my console isn't booting via GM9Link anymore. Using GM9 as y_GodMode9.firm in Luma payloads. My previous version was the very release before scripting compatibility. Boots fine while loading GM9 through Luma chainloader.

**Comment by d0k3** [comment]
Okay, by latest release you mean v1.3.1? If that does not work for you, try this:
https://transfer.sh/Frxs5/GodMode9-20170808-184732.zip

**Comment by LinkSoraZelda** [comment]
Hm, still hangs on a black screen actually.

**Comment by d0k3** [comment]
Both?

**Comment by LinkSoraZelda** [comment]
Correct, neither the official release nor the above one.

**Comment by d0k3** [comment]
I'll look into it, alright? In the meantime, you say the last working release was v1.2.8, and the current release still works for you when booted via Luma?

**Comment by LinkSoraZelda** [comment]
Lol, got it.

1.2.8 does indeed boot.

**Comment by d0k3** [comment]
Okay, alright. Can you maybe tell me what kind of console that is?

**Comment by LinkSoraZelda** [comment]
It doesn't boot as its own boot.firm, nope.

**Comment by LinkSoraZelda** [comment]
In addition, n3DS (XL, JPN sysNAND)

**Comment by d0k3** [comment]
Okay, let's try this in a different way. Can you maybe get that aeskeydb.bin file (A5B28945A7C051D7A0CD18AF0E580D1B, search for it), and put it into sd:/gm9/support, then retry?

**Comment by d0k3** [comment]
Also, can you maybe try this test build?
https://transfer.sh/VxNhj/GodMode9-20170811-204650.zip

**Comment by LinkSoraZelda** [comment]
Sorry to report that it still hangs on a black screen.
I checked the support files, and they are indeed valid. I may look into it eventually.
So it seems that it can load and jump into GM9 instruction as moving the volume slider actually changes the brightness of the screen. The screen, however, when loaded as boot.firm or bootonce.firm (GM9Link) just presents a blank screen.

**Comment by d0k3** [comment]
Okay, this one has high chances of success:
https://transfer.sh/vb2iw/GodMode9-20170819-132628.zip

Can you try?

**Comment by LinkSoraZelda** [comment]
http://imgur.com/FPk9OQo
Seems to have the same problem. Does boot when chainloaded (GodMode9 v1.3.3.7, gg) but otherwise this scanlined image appears when booting through GM9Link or as a boot.firm.

**Comment by AnalogMan151** [comment]
Sounds like a screeninit issue. If it chain loads fine (when screeninit is already started) but won't when booted on it's own (so it needs to screeninit itself) that's the best diagnosis I have.

**Comment by d0k3** [comment]
Okay, possible fix:
https://transfer.sh/d1ias/GodMode9-20170820-182524.zip

**Comment by AnalogMan151** [comment]
While I'm not having this exact issue, I think I may still have info that can help. 

On my o2DS XL, if I boot GodMode9 version > 1.2.8 from NTRBootHax, I have faint scan lines on the bottom screen only. These lines are not present when chain loaded through Luma3DS. The latest fix posted above does not change this. 

Direct booting through NTRBootHax on my n3DS and n2DS XL on the other hand works flawlessly, no graphical issues or scan lines at all.

I do not have a 2DS, o3DS, or n3DS XL model to test on.

**Comment by d0k3** [comment]
Okay, @LinkSoraZelda - we need your assistance once more. Please try this test build:
 https://usercontent.irccloud-cdn.com/file/DFjvSy1Q/GodMode9-20170822-100607.zip

I'm pretty sure this will fix it for you.

**Comment by LinkSoraZelda** [comment]
Hey, there we go! Everything seems to be in working order through all three entrypoints.

**Comment by d0k3** [comment]
Thanks a ton! Also tested by yours truly, @al3x10m. Closing this now...
