### ISSUE TITLE
Cannot create bonus drive

### ISSUE THREAD

**Issue by IngeniousDefault** [d0k3/GodMode9#152]
Hi there,

I have a few hacked 3DS systems but I noticed something strange with my Japanese New 3DS system. I don't have the option to create a bonus drive. I actually don't know why I need a bonus drive, however it's strange that the option does not appear in GM9. I'm using the latest version by the way.

**Comment by ihaveamac** [comment]
if your NAND size is too small, you can't create one. check S:/nand.bin, if it's 1.2gb you can't do it.

bonus drive is available if the NAND is larger than 1.2gb, to make the extra space useful.

**Comment by IngeniousDefault** [comment]
Yeah it's 1.2 GB. Well, that sucks. What exactly can I do with a bonus drive?

**Comment by d0k3** [comment]
Exactly, what @ihaveamac said. Don't worry, though it's onyl additional space, which you could, f.e. use for backups and stuff. You can do without that.
