### ISSUE TITLE
Wanted: ntrboot devkit tester

### ISSUE THREAD

**Issue by d0k3** [d0k3/GodMode9#157]
There are still some smaller issues in GodMode9 if it is ran via ntrboot -> b9s. As we want to iron these out, we will need help from a tester. You need a devkit plus an Ak2i (to run ntrboot). Also, don't worry, this is not a fulltime job, we will need your assistance only a few times.

So, anyone interested?

**Comment by fox8091** [comment]
I'm in. You know my Telegram, just contact me there. Idk why you didn't ping me first. xD

**Comment by d0k3** [comment]
Alright, thank you! Closing this now.
