### ISSUE TITLE
Errors in Releases page

### ISSUE THREAD

**Issue by WubTheGame** [d0k3/GodMode9#158]
i have found 2 errors in the releases page.

1: In the 1.2.7 notes, there is a broken link to .gm9 scripts. upon clicking it will present you with the simple error: Not Found

2: There's a typo in the notes for the latest release: "This wouldn't be GodMode9 if I wouldn't at least give you a new goody that makes the update ->*worthwile*<- for you.

Sorry if these can't really be fixed, i just found them and thought i would share them. I'm still new to github altogether (hence me previously not knowing not to comment on every post).

**Comment by d0k3** [comment]
Alright, thank you (2) is fixed, (1), well, can't be really fixed. These scripts are by now outdated, and there are improved versions of it.

**Comment by WubTheGame** [comment]
Your welcome. Happy to help. =)

**Comment by WubTheGame** [comment]
And, if you can't fix the link, is it possible to remove it?
