### ISSUE TITLE
Unable to delete all *.bin files in /luma/payloads

### ISSUE THREAD

**Issue by kekmaster97** [d0k3/GodMode9#159]
So I am working on a script, and I want it to delete all .bin payloads in /luma/payloads.

`rm 0:/luma/payloads/*.bin` is the line that gets the error, `line 6: remove fail`
The same thing happens if I remove the `/` before `luma`, if that would make a difference.

Am I just being an idiot or is it supposed to work and is just broken?

**Comment by d0k3** [comment]
Wildcards don't work with the rm command. I'd suggest you delete the whole dir instead and just mkdir it again.

**Comment by ValliantStorme** [comment]
The way I did it in my scripts is to move all of the .firm payloads out of the folder, remove and recreate, then move them back in. You'd have to hardcode the payloads, but if you're doing something like a B9S Guide cleanup program it's not hard to choose which ones to move.

**Comment by d0k3** [comment]
As an additional note... wildcard support everywhere is hard. I am working on if and goto support, though, so recreating wildcard support with two or three additional lines won't be too hard later on.
