### ISSUE TITLE
GodMode9 Brightness Bug

### ISSUE THREAD

**Issue by CCF100** [d0k3/GodMode9#160]
GodMode9 does not change brightness while converting app to cia.
N3DS XL USA
Luma3ds 8.1.1 + boot9strap 1.2
Sys 11.5.0-38 U (I think)
(Sorry if this isn't enough information, I'm new to GitHub)

**Comment by d0k3** [comment]
Yup, that's correct. Can't change brightness while GM9 is busy. I might change that later.

**Comment by CCF100** [comment]
Also, random question: Would it be possible in the future to install or uninstall a cia via GodMode9? Or does that require it to be running as a cia for example?

**Comment by Derek1199** [comment]
You probably could technically uninstall a cia with godmode9 by deleting the files from the Nintendo3DS and deleting the ticket file from the nand. However, you would need to know the TID of that application so you could delete the correct ticket and as for the nintendo3DS folder on your SD card, you probably have a ton of things installed there you would need to know exactly what folder it is in. So yeah, too risky. You would likely end up deleting another application. Anyway's as for it installing cias like FBI does it is not possible. GodMode9 is an arm9 payload, which means it launches before most of the actual system loads. It's way earlier than home menu pretty much. So yeah. Being that it is an arm9 payload, it is not meant to do that and never will have a feature like that for installing cias. You can inject cias into the health and safety app though, provided they're smaller than health and safety itself. Also, injection is not the same as installation. Anyway, that's everything.

**Comment by CCF100** [comment]
@Derek1199 Thank you.

**Comment by Derek1199** [comment]
You welcome.
