### ISSUE TITLE
Feature Request: Allow mounting boot9 and boot11

### ISSUE THREAD

**Issue by Derek1199** [d0k3/GodMode9#161]
Hi, It would be nice if we could mount boot9, and boot11. As they have pretty much all keys. So if we could mount them as images it would be interesting to see what is inside of them.

**Comment by fox8091** [comment]
Those are code. Nothing to mount.

**Comment by d0k3** [comment]
That's correct. You can parse that code, but other than NCSD / NCCH / CIA / FIRM / NDS ... files, there is no container structure in there, thus mounting makes no sense.

**Comment by Derek1199** [comment]
Ah. How could we parse this code though? I'd like to parse it.

**Comment by fox8091** [comment]
That requires reverse engineering. If you don't know how, no amount of explaining will help. This uses some "advanced techniques".

**Comment by Derek1199** [comment]
Yeah. Never done any RE. I don't even know a coding language at all. Only thing I can do is compile stuff. So yeah, I probably wouldn't be able to do it.
