### ISSUE TITLE
Issue with RTC clock support 

### ISSUE THREAD

**Issue by RS55** [d0k3/GodMode9#162]
I put for example: 2017 in 3DS NAND but in Godmode 1.3.1 it puts 2015. With the time and the rest of the date, there is no problem.

PD: Also happens the other way around.

**Comment by d0k3** [comment]
Keep an eye on this issue and tell me if you can reproduce it.

**Comment by RS55** [comment]
Okay, it seems or "I think" that it is a bug, I noticed that it happens when one enters directly to Godmode9 leaving of the configuration of the console, that is when it makes a restart
