### ISSUE TITLE
Feature Request: Search Function

### ISSUE THREAD

**Issue by CCF100** [d0k3/GodMode9#164]
Would it be possible to implement a file search function?

**Comment by james-d-elliott** [comment]
Likely possible on SD at least, how useful it'd be I'm not sure. Since you'd have no touch keyboard.

**Comment by d0k3** [comment]
R+A on folders, works from anywhere. At least CTRL-F the readme before you open an issue :/.

**Comment by d0k3** [comment]
R+A on folders, works from anywhere. At least CTRL-F the readme before you open an issue :/.

**Comment by CCF100** [comment]
Sorry. Didn't realize... This program is amazing! Thank you for making it! :)
