### ISSUE TITLE
Feature Request: Gamecart writing

### ISSUE THREAD

**Issue by AidenTheCuber** [d0k3/GodMode9#165]
It would be nice if you could add a feature to edit the gamecartridge

**Comment by AnalogMan151** [comment]
Need more clarification on what you want. The only part of a game cart that can be edited is the save file.

**Comment by AidenTheCuber** [comment]
![img_0408](https://user-images.githubusercontent.com/30151221/29379640-652f8ba6-82c3-11e7-8d6b-10afdb5e7dab.JPG)
If you can edit this.

**Comment by ihaveamac** [comment]
game cards are read-only. only the save area is writable.

**Comment by AidenTheCuber** [comment]
Okay
