### ISSUE TITLE
gm9 1.3.1 doesn't show the twln nand

### ISSUE THREAD

**Issue by sercho80** [d0k3/GodMode9#167]
I tried to do dsiwarehax with gm9 1.3.1 and it did not show the twln nand, and then when I tried to restore a backup it told me it was corrupt (mbr).

These errors do not happen to me with gm9 1.2.8 (Fbi and freeshop detect twln nand too) :S

(Sorry for my bad english, sorry for the quality too xD)
![1](https://user-images.githubusercontent.com/28808032/29379317-594b5c8a-82c2-11e7-95f0-a3b09cdb8abc.jpg)
![2](https://user-images.githubusercontent.com/28808032/29379318-594bcd46-82c2-11e7-8c90-cd6f4c187b76.jpg)
![3](https://user-images.githubusercontent.com/28808032/29379319-59518222-82c2-11e7-8c18-cc3db3d3f177.jpg)
![4](https://user-images.githubusercontent.com/28808032/29379320-5954579a-82c2-11e7-938e-952648afa27e.jpg)

**Comment by d0k3** [comment]
@MegaPramuk - this does look a lot like your issue (this one: https://github.com/d0k3/GodMode9/issues/155). Can you two try to find out what you got in common?

@sercho80 - this is an O3DS, running on B9S 1.2, correct?

First, try this new testbuild, also remove any aeskeydb.bin you may have on the SD card.
https://transfer.sh/b812z/GodMode9-20170816-191704.zip

Does that help?

**Comment by sercho80** [comment]
@d0k3 Yes, old and B9S 1.2. 
Gm9 1.3.1 and the testbuild works perfectly without aeskeydb.bin (I don't understand why, I've used it from menuhax to b9s without any problem) thank you ^^

**Comment by d0k3** [comment]
So, problem was, you had a bad aeskeydb.bin, if I got that correct, right? Leaving this open so @MegaPramuk can answer.

**Comment by d0k3** [comment]
Okay, just to be safe, here's another test build. @sercho80 - could you give this a try, too? There's only a small change in it, and I need to make sure this doesn't break anything.
https://transfer.sh/B8XZh/GodMode9-20170817-114745.zip

**Comment by TuxSH** [comment]
> Gm9 1.3.1 and the testbuild works perfectly without aeskeydb.bin (I don't understand why, I've used it from menuhax to b9s without any problem) thank you ^^

Because b9s initializes TWL keys correctly.

Which means, as d0k3 said, that your aeskeydb is incorrect (or at the very least that the issue is solely linked to aeskeydb).

**Comment by d0k3** [comment]
Okay, after having a through look - your old aeskeydb.bin had some issues, so thsi can be closed. Take note that GM9, starting from 1.3.0, now does a full (b9s-like) key setup, which may be the reason why that old aeskeydb.bin worked earlier.
