### ISSUE TITLE
Add Nintendo Zone to the injection list

### ISSUE THREAD

**Issue by shoguna** [d0k3/GodMode9#169]
Since Nintendo Zone app is inoperable even after launching it through FBI, can you add it to the list of injectable Nintendo apps?

**Comment by ihaveamac** [comment]
HOME Menu will still attempt to block launching it, so injecting is just one part of it. Luma3DS/some cfw will have to patch out the check.

also with Rosalina, injection is pretty much outdated. and it was only ever meant to be temporary.

**Comment by d0k3** [comment]
@ihaveamac is completely right. This has been asked several times, and it simply doesn't make sense. If you don't want to install homebrew apps in your homemenu, use 3DSX. Closing this now.
