### ISSUE TITLE
[Tiny feature request] Insert/remove char for hex editor

### ISSUE THREAD

**Issue by NinjaBoyLao** [d0k3/GodMode9#17]
the functionality just isn't there.

**Comment by d0k3** [comment]
Not possible, sorry. Even small deletions / insertions mean rewriting the whole file, which just is out of question here. Think about what would happen for large files.

The hex editor in CTRXplorer has that feature, if you want to see for yourself. Try an insertion or deletion on a large file. Closing this for now.

**Comment by NinjaBoyLao** [comment]
Thanks, sorry about that.
