### ISSUE TITLE
NDS ROM Image File Extraction Infinite Loop

### ISSUE THREAD

**Issue by NWPlayer123** [d0k3/GodMode9#170]
compiled from source (https://github.com/d0k3/GodMode9/commit/cfa26c2a2da3f672cada8b533ffefa6cb516266e)

- mounted Ace Attorney: Justice For All (A2GE08)
- selected all the base files (arm7.bin, arm9.bin, banner.bin, header.bin, /data) with L
- tried to copy to a folder on my SD with Y

for some reason it got stuck infinitely looping through the base files in /data (data.bin, mes_all.bin, sound_dat.sdat)
EDIT: looks like it happens on a totally unrelated rom, it copies all of /data and then loops around and copies it again in an infinite loop, never gets to arm7.bin, must be some way the raw data is being attached

**Comment by d0k3** [comment]
Thanks a lot! It's always appreciated when bugs are found that early. You may want to compile and try again now.

**Comment by NWPlayer123** [comment]
works like a charm 👌
