### ISSUE TITLE
Feature Request: Access a flashcard's MicroSD card

### ISSUE THREAD

**Issue by HamBone41801** [d0k3/GodMode9#171]
With this, gm9 scripts could then easily be used to switch the contents of the MicroSD without the need for a computer. It would be useful for people who have large MicroSD's in their 3DS's but much smaller cards in their flashcards.

**Comment by fox8091** [comment]
Not likely. A similar request using Gateway was declined, and this requires a lot of cartridge-specific stuff anyways. You would have to dump and parse the DLDI of every cart you support. Tl;dr, likely not happening.

**Comment by HamBone41801** [comment]
If I managed to dump and parse the dldi, what else would be needed to implement it for the ak2i?

**Comment by fox8091** [comment]
Hooking up the fatfs driver to the appropriate NTR commands, somehow managing to swap out an existing drive on the fly (an issue I ran into, and why I'm not too keen on finishing GatewayFS), and generally the fact that that's only one flashcart, and it'd end up being requested to be expanded to every DS flashcart.

**Comment by d0k3** [comment]
I'm not against including this, however, this would be a lot of work just to provide support for a specific card (and not all cards). I won't do it, however if someone else wants to try their hands at it, I'd take a pull request (once it's complete / fully working, ofc). Closing this now....

**Comment by mariomadproductions** [comment]
[TWiLightMenu](https://github.com/Robz8/TWiLightMenu) recently added support for reading flashcart microsd cards. I guess this code could help with implementing this feature into GodMode9.

**Comment by Wolfvak** [comment]
But that runs on DS mode and I think it relies on the DLDI drivers... Unless you want to rewrite all the drivers to run on the 3DS memory map (especially IO), it's useless

**Comment by d0k3** [comment]
Doubtful. TWiLightMenu (why the name change, again -_-?) is TWL mode software, it uses DLDI. Adapting DLDI for GM9 has been discussed in the past, see what @Wolfvak wrote.
