### ISSUE TITLE
boot.firm godmode from NTRhack not working

### ISSUE THREAD

**Issue by JaySea77** [d0k3/GodMode9#172]
when placing godmode as boot.firm on the root of the sd when performing the NTRhack on a 2ds versions > 1.2.8 do not boot. They result in a power down.

**Comment by urherenow** [comment]
Install b9s 1.2 first, then chailnload Godmode9 from luma. It still does the trick with a bricked nand.

**Comment by JaySea77** [comment]
Chainloading from luma works indeed, but I wanted it for primary boot for ntrhack and chainload b9s safe installer.
I thought godmode should be able to boot as primary hence why I reported it as a bug

**Comment by TuxSH** [comment]
FIRMs need to be specifically built for ntrboothax.

As @urherenow says just install b9s, then install b9s on your flashcard as well.

**Comment by JaySea77** [comment]
update: ntrboot.firm version of the ntrhack let's you install b9s 1.2 with ntrboot.firm, then reboot godmode 1.3.1 from boot.firm.

As stated before 1.2.8 does not need to be chainloaded with something like b9s installer or luma. As of 1.3.0 is does. Imo this is a bug unless d0k3 says it is intentional.

**Comment by d0k3** [comment]
Okay, as of now, ntrboot -> gm9 works (need to build from nightly), and ntrboot -> b9s -> luma -> gm9 works, but there's trouble with ntrboot -> b9s -> gm9 on the most recent release.

Can you try this testbuild?
https://transfer.sh/ThzpE/GodMode9-20170818-114431.zip

**Comment by JaySea77** [comment]
Ntrboot-> b9s safe installer as ntrboot.firm -> gm9 as boot.firm works though.

Will try the test build as soon as I get home. Does this support chainloading as well?
Meaning:
Ntrboot -> gm9 -> b9s?

**Comment by JaySea77** [comment]
ntrboot -> gm9 doesn't work with GodMode9-20170818-114431.zip

**Comment by d0k3** [comment]
Can you get that aeskeydb.bin I mention in the readme (md5 A5B28945A7C051D7A0CD18AF0E580D1B), put it into` 0:/gm9/support`, then try these tests again (the ones that didn't work earlier)?

Also, here's a slightly updated testbuild. And, thanks for bringing this up!
https://transfer.sh/6szKx/GodMode9-20170818-130845.zip

**Comment by JaySea77** [comment]
sure np.
I hope the one in the 3ds guide for updating al9h to b9s is the same aeskeydb.bin. I do not know how to see what md5 the file I have has.

Using the new build ntrboot -> b9s as ntrboot.firm then reboot gm9 as boot.firm doesn't work anymore.
With and without the aeskeydb.bin in /gm9/support.

Using the new build ntrboot -> gm9 doesn't work with or without the aeskeydb.bin

**Comment by d0k3** [comment]
Hint: you can also just search for the MD5 via Google ;). If your aeskeydb.bin is 1024 byte, you most likely have the correct one, though.

**Comment by JaySea77** [comment]
can I use that one for al9h to b9s aswell? I mean to put it in the boot9strap folder to revert al9h to stock.

**Comment by d0k3** [comment]
Hmm... as far as I know nothing but GM9 (and D9 / HG9) actually uses that `aeskeydb.bin`. I may have understood the question wrong, though.

**Comment by JaySea77** [comment]
can't seem to find any active link with the file. All links I have found are broken. Also I bet I have to clean up my pc after this due to torrent site browsing.

**Comment by d0k3** [comment]
I found it via Google :). Anyways, you can also contact me via pm on IRC (freenode Cakey) or on temp.

**Comment by JaySea77** [comment]
It seems that ntrboot -> b9s -> gm9 works when b9s is installed with and without the aeskeydb.bin and boots straight into home menu when b9s is not installed.
ntrboot -> gm9 immediate shutdown with or without the aeskeydb.bin

**Comment by d0k3** [comment]
Okay, here's a new one... shouldn't require any aeskeydb.bin (and on top, even boot a little faster):
https://transfer.sh/GTv1R/GodMode9-20170818-153619.zip

**Comment by JaySea77** [comment]
Same as before, though I have to say this one is really fast indeed.
If b9s is not installed. A reboot will not run boot.firm I guess. That is why it does this.

**Comment by d0k3** [comment]
And, another one, this time with high chances of success. I think we found the bug.
https://transfer.sh/IpDWM/GodMode9-20170818-165547.zip

**Comment by JaySea77** [comment]
Will try when I get home. Is this bug only for 2ds or should I test others as well?

**Comment by d0k3** [comment]
That bug should actually be everywhere, but only test elsewhere once it's fixed on the 2DS. Also, thanks for helping us with this!

**Comment by JaySea77** [comment]
Would love to help out more, but I don't know any of the 3ds coding

**Comment by JaySea77** [comment]
Btw on temp some have an ntrhack pack where they boot.firm gm9. How could they be succesful?

**Comment by JaySea77** [comment]
Still the same.
Just to make sure we are on the same page:
I use an acekard2i hw81 with the sleep mode switched on then I use X+start+select+Power to boot it into ntrboot.firm. After installing B9S it boots boot.firm which is godmode9. This flow works.
When I try to load gm9 as the ntrboot.firm, the power shuts down almost imediately.
Also when B9S is already installed and you power on the device without ntrboot, it loads boot.firm and this also doesn't work.
This has been happening on all versions I have tried so far except for 1.2.8. This one did work als ntrboot right of the bat.

**Comment by AnalogMan151** [comment]
Hey @d0k3, I'm able to boot the current release GodMode9 straight from NTRBootHax just fine as are others who are making all-in-one packs. Considering @JaySea77's 2DS doesn't even boot it from boot.firm with B9S installed I think this is an isolated case.

**Comment by JaySea77** [comment]
Could be related to issue 151, but surely is not isolated to my 2ds. I tested it on 2ds 11.2 and another 2ds on 11.5 and a N3DS 11.5. 2ds don't work at all, but 3ds just gives distorted screen. 
The aio package where you install b9s as ntrboot.firm then reboot gm9 as boot.firm works on all, but of the 3 devices but that is not what we are testing here. We are testing gm9 as first to be boot after ntrhack.

**Comment by JaySea77** [comment]
Could be related to issue 151, but surely is not isolated to my 2ds. I tested it on 2ds 11.2 and another 2ds on 11.5 and a N3DS 11.5. 2ds don't work at all, but 3ds just gives distorted screen. 
The aio package where you install b9s as ntrboot.firm then reboot gm9 as boot.firm works on all, but of the 3 devices but that is not what we are testing here. We are testing gm9 as first to be boot after ntrhack.

Could be isolated to my acekard2i though.

**Comment by d0k3** [comment]
Here's a possible fix:
https://transfer.sh/d1ias/GodMode9-20170820-182524.zip

Not committed yet. This improves the checks for already initialized screens.

**Comment by urherenow** [comment]
Wait... a .firm built to load with NTRBoot is NOT the same as a .firm built to load from b9s, is it? Sounds like @JaySea77 is trying to do both without swapping the boot.firm.

**Comment by d0k3** [comment]
I think @JaySea77 has the correct FIRM, I've been testing it with him for a while. It is correct, however, that an ntrboot FIRM can't be loaded via a conventional chainloader (B9S, Luma, GM9).

**Comment by JaySea77** [comment]
I think i only have 1 ntrboot firm which is the boot9strap firm which is flashed to my acekard2i.
The others are all normal firms right? Meaning luma, safeb9sinstaller, gm9

**Comment by AnalogMan151** [comment]
While I'm not having this exact issue, I think I may still have info that can help.

On my o2DS XL, if I boot GodMode9 version > 1.2.8 from NTRBootHax, I have faint scan lines on the bottom screen only. These lines are not present when chain loaded through Luma3DS. The latest fix posted above does not change this.

Direct booting through NTRBootHax on my n3DS and n2DS XL on the other hand works flawlessly, no graphical issues or scan lines at all.

I do not have a 2DS, o3DS, or n3DS XL model to test on.

**Comment by JaySea77** [comment]
I only have 3 different 2ds-es (old one, don't think there was an XL version) and a n3ds XL. My o3ds is bricked. I think the flat cable to to top screen is broken.

**Comment by d0k3** [comment]
Fixed in the most recent testbuild, commit coming soon. Thanks a ton @JaySea77 and @al3x10m!

**Comment by annson24** [comment]
Booting straight to gm9 via ntrboot is broken on the latest commit. Also if this is of any help, the screen brightness is also really low on the latest commit.
