### ISSUE TITLE
[Request] Add hash to NAND backup scripts in release

### ISSUE THREAD

**Issue by sora10pls** [d0k3/GodMode9#174]
Just in case something goes wrong with the backup, users have this to work with.

Would simply change the following line:
`cp X:/nand_minsize.bin $[OUTPATH]`
To:
`cp -h X:/nand_minsize.bin $[OUTPATH]`

`X` would obviously be replaced with `S` or `E`, for SysNAND and EmuNAND (respectively).

**Comment by d0k3** [comment]
Talk about lazy, you could just have done a pull request :P.

**Comment by sora10pls** [comment]
I'll be honest I didn't even notice where the scripts were in the repo hahaha. PR incoming.
