### ISSUE TITLE
"SysNAND backup failed"

### ISSUE THREAD

**Issue by T0m0ko** [d0k3/GodMode9#176]
There is no error code. I have 5.4 gb of free space.

**Comment by T0m0ko** [comment]
Also the modification date is set to the year 2002.

**Comment by urherenow** [comment]
Did you make a post on gbatemp? Github is not a support forum.

**Comment by d0k3** [comment]
You didn't set your RTC clock (look at the top right, so the modification date can't be correct, right?

Also, I'll need more info. There has to be some error message.

**Comment by T0m0ko** [comment]
I managed to setup the RTC clock and there still hasn't been any change. Where does the error message usually appear because i don't see any?

**Comment by d0k3** [comment]
Well, what is displayed on screen during and after the failed SysNAND backup? Also, of course just setting the RTC will only change modification date done from that point on.

**Comment by d0k3** [comment]
Better, try this script instead.
https://transfer.sh/H7JKY/Backup%20SysNAND%20test.gm9

Run it via the A button menu tell me what's displayed on screen.

**Comment by T0m0ko** [comment]
"0:/gm9/scrip... SysNAND test.gm9
line 10: copy fail
cp S:/nand_minsize.bin $[OUTP..."

Proof: http://imgur.com/a/OKxqv

**Comment by d0k3** [comment]
Hmm... wasn't there some output before this?

**Comment by AnalogMan151** [comment]
What version of GodMode?

**Comment by AnalogMan151** [comment]
Right before that screen it should have showed where on the SD card it was going to copy your backup to. Can you show us that screen?

**Comment by T0m0ko** [comment]
Sure.
http://imgur.com/a/fBGM4 (Hard to see text so look at bottom)
"Create a SysNAND backup in 0:/gm9/out"

**Comment by AnalogMan151** [comment]
Interesting, there should be one last screen after this one but before your line 10 error. It should be something like:

`0:/gm9/out/20170821_##########_sysnand_000.bin`

and then ask you to press A afterwards to continue.

**Comment by T0m0ko** [comment]
http://imgur.com/a/BPdjn
"0:/gm9/out/170822_SW40625615_sysnand_002.bin"
That is all it says there.

**Comment by AnalogMan151** [comment]
I see it ends in 002, implying there's a 000 and 001. If you run the script again does it say 003 the next time?

**Comment by d0k3** [comment]
I see strange SD card issues not too rarely... So, @T0m0ko, can you try a manual copy of S:/nand_min.bin to somewhere on your SD card? Maybe even chkdsk that SD card? Or try another one?

**Comment by T0m0ko** [comment]
It does say a 003 on there.

**Comment by T0m0ko** [comment]
How do i make a manual copy of S:/nand_min.bin to somewhere in my SD card? @d0k3

**Comment by ToxiKutie** [comment]
@T0m0ko Go to your S:\ directory and scroll to nand.bin. Press Y on it and then B to return to the top menu. Move to your SD Card and press A, then Y again to copy it to the nand.bin to the root of your SD Card

_Sent from my ZTE Z799VL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by urherenow** [comment]
Follow the instructions on the bottom screen? Hilight, press Y, navigate to 0: and optionally pick a folder, and hit Y again to paste.

**Comment by T0m0ko** [comment]
Couldn't copy it for some reason @Toxikute @d0k3

**Comment by T0m0ko** [comment]
It also told me "invalid directory object" @d0k3 @Toxikutie

**Comment by d0k3** [comment]
There's something wrong with your SD card or SD card slot. You can try formatting your SD card (make a backup of your important data first and copy it back afterwards). You can also try cleaning the SD card slot of your 3DS console. I think it would be best to try a different SD card, though.

Stuff like what you're experiencing can mean your SD card is failing, and data loss is imminent.

**Comment by d0k3** [comment]
Obviously a hardware / SD card issue, thus closing this now. @T0m0ko - try what I suggested to fix this issue for you.
