### ISSUE TITLE
Feature Request - Create blank files & inject beyond end of file (scripts)

### ISSUE THREAD

**Issue by 16BitWonder** [d0k3/GodMode9#177]
Really amazed at just how much you can do with this tool so far, especially with scripting!
Just thought I might suggest this:

Being able to create blank files through scripting and fill them with info/data through injecting would be pretty handy in certain circumstances. Though even if blank files could be made, the inject command would need to be able to inject/add data beyond the end of a file.

Would either of these things be doable or worth the trouble?

**Comment by d0k3** [comment]
Well, tell me a use case, and I'll look into it. We can allow the inject command to be more versatile, of course.

**Comment by 16BitWonder** [comment]
In my particular case I'm trying to set up a script that dumps a Citra ready config file from 1:/data/$[SYSID0]/sysdata/00010017/00000000.
However I would need a pre-existing file of the correct size to inject the block that I need from 00000000. Rather than copying 00000000 to gm9/out and trimming it on my computer.

Being able to create a blank file (possibly of specified length) from gm9 and then inject past the end of the file would allow for outputting specific blocks or info of interest, rather than copying entire file(s) and then needing to trim or extract what you were looking for on a computer.

Or in another scenario, one might create a blank log file and then (with the inject command) append certain info like SYSID0, EMUID0 (if present), or all installed title info. Things that generally vary in quantity from system to system and can't always be provided with a file of proper size before hand, hence the ability to inject past the end of a file should there be more info than can be stored in it.

**Comment by d0k3** [comment]
Okay, these are plausible use cases. I can make the inject command work in a away that it also can create / expand a file that does not exist - that would do it, right?.

**Comment by 16BitWonder** [comment]
Yes, that would do perfectly!

**Comment by d0k3** [comment]
If anything comes up, or stuff not working as intended, feel free to continue writing here or reopen.
