### ISSUE TITLE
Feature Request - Support for splitted NCSD image

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#179]
Gateway uses splitted image for 3DS files larger than 2GiB.The extension of the files are .3D0,.3D1 etc.You should support mounting of such images.
Example:When you open a .3D0 file,the system should find .3D1,.3D2...3D9 files with the same base name.The resulting .3DS is just those files concatenated in sequence.
(sorry for my poor English)

**Comment by d0k3** [comment]
This has been asked earlier, and it will not be supported in GodMode9. The effort required for this would be far too big.

As a workaround - combine these files on your computer. There is a maximum of 2 parts, .3d0 and .3d1. Remove the last byte from the .3d1 image (don't worry, nothing important in there), and concatenate the two files (from the command line: copy /b game.3d0 + game.3d1 game.3ds).
