### ISSUE TITLE
Cannot launch GM9, need help

### ISSUE THREAD

**Issue by tczorro** [d0k3/GodMode9#180]
The situation is I was in B9 before, and according to 3ds.guide, I was updating to the new b9 version. Before, I have gm9 in the CTR NAND/rw/luma/payload. Then in order to have the new firm in my sd card work, I delete the gm9.firm one in my ctrnand. (I think this is the step screwed up)
Then I cannot get into gm9 too. So is there any method I could let luma load the payload on sd first. Thanks

**Comment by urherenow** [comment]
Github isn't a support forum. If luma is loaded from nand, it checks for payloads in nand. If it's on your SD, it'll check for payloads on SD. Simple as that. Place Godmode9.firm in luma/payloads/ , place Luma's boot.firm in the root of your SD, then hold start while powering on.

**Comment by tczorro** [comment]
@urherenow sorry for this improper issue. If the luma is loaded from nand, is there a way I can change it load the payloads from sd or Is there a way I can for the luma loaded from sd first?

**Comment by urherenow** [comment]
What? I just TOLD you how!
