### ISSUE TITLE
Feature request: Built-in FTP server

### ISSUE THREAD

**Issue by Freshpep** [d0k3/GodMode9#181]
Don't know if this is possible due to wireless functionality without fully booting the 3DS OS, but I know little to nothing about this stuff, so..

Basically just a built-in FTP server so that you don't have to use FTPDB from a cia or anything like that.

I know that Godmode9 has an SD ejection system, but having FTP makes it all that easier for users doing their best to not move their SD card out of its' sweet spot on harshly-handled systems. Therefore, isn't really _that_ necessary..

**Comment by T3CHNOLOG1C** [comment]
afaik nobody has made wifi access possible from arm9 software

**Comment by d0k3** [comment]
One can dream :). Yes, I'd like to have that, too, but it's very unlikely anyone will ever manage to access Wifi on ARM9. For that reason, closing this now.

**Comment by fox8091** [comment]
@d0k3 If someone reimplements the software on ARM11, you can interface with it over PXI.
