### ISSUE TITLE
Feature Request: show B9S version

### ISSUE THREAD

**Issue by gingerbeardman** [d0k3/GodMode9#182]
is it possible that GM9 can display the version of boot9strap that was used to launch it?

i asked at B9S but they said, in a roundabout way, that this is better done by something else:
https://github.com/SciresM/boot9strap/issues/19

...currently version is `0x2BEEF`

https://github.com/SciresM/boot9strap/blob/a873f95e08bc9564a33e1b2af90e964ff24b61b8/stage2/arm9/itcm_stub/source/start.s#L56

this would help when people need to figure out if they need to update their B9S or not.

thanks!

**Comment by d0k3** [comment]
When in doubt, just update. This has seriously gotten as easy and safe as it can. I'll keep that request in mind if we ever go around to do some sysinfo thing, but for now this won't be added, as I feel it would also force us to detect other system installed stuff.

**Comment by gingerbeardman** [comment]
OK thanks
