### ISSUE TITLE
Cannot Execute GM9 script/Show in Textviewer

### ISSUE THREAD

**Issue by windows-server-2003** [d0k3/GodMode9#183]
I made my gm9 script and placed it to "/gm9/script/0 -A.gm9" (there is a whitespace in the file name)
But there aren't "Execute GM9 script" and "Show in Textviewer" in the menu.And I can run the script via the homemenu>more...>scripts...>.
If I rename it to "0-A.gm9",  they works correctly.
"0 -9.gm9" (one whitespace)>>> doesn't work
"0 A.gm9" (one whitespace)>>> works correctly
"0 -AA.gm9" (one white space)>>>works correctly
"0  -A.gm9" (two white space)>>>works correctly

**Comment by d0k3** [comment]
Fixed. Sometimes I seriously wonder how you guys manage to find stuff like that.
