### ISSUE TITLE
Feature request: Allow us to change the EULA Version.

### ISSUE THREAD

**Issue by Derek1199** [d0k3/GodMode9#184]
Currently the only ways to change the EULA version is with the config SDK app or by using SciresM's EULA version changer. However a lot of newbies do not know anything about this. This would be useful for newbies wanting to region change as they could change the EULA version to avoid the accept EULA version nag while going online with a region changed device.

**Comment by AuroraWright** [comment]
This requires editing savedata archives (it's a nand savegame) which GM9 is currently unable to do

**Comment by d0k3** [comment]
What @AuroraWright does. We can only edit save files using system OS functionality, cause we don't really know how these work yet.
