### ISSUE TITLE
Feature Request: Allowing F0/F1 Injects via scripting

### ISSUE THREAD

**Issue by ZetaDesigns** [d0k3/GodMode9#185]
Again, a very self explanatory title. 

~~could be useful to ditch safeb9sinstaller~~

**Comment by ihaveamac** [comment]
firm installing is coming. and I'm pretty sure you could already do that by just injecting into S:/firm#.bin

**Comment by d0k3** [comment]
As @ihaveamac said. Just cp or inject stuff to FIRM0 / FIRM1. Don't neglect safety, at least verify the FIRM before injecting in a script. Also, take note that SafeB9SInstaller may not be the absolute fastest option (when compared to scripting), but it contains stuff to make it the absolutely safest. Installing per scripts is not for noobs.

**Comment by annson24** [comment]
Tried copying to firm0/1, gm9 doesn't allow me to. Since the latest commit has install *.firm capability, maybe this could be a thing now?

**Comment by d0k3** [comment]
It works for others... Have a look at Kazuma77's work (official GBAtemp thread) and at the [Lazarus3DS](https://github.com/AnalogMan151/Lazarus3DS )script.

**Comment by annson24** [comment]
Thanks, forgot about the force overwrite switch
