### ISSUE TITLE
Some NDS roms don't load properly

### ISSUE THREAD

**Issue by NWPlayer123** [d0k3/GodMode9#186]
Just tried mounting Kirby Mass Attack, it loaded all the base files (arm7, arm9, overlay), and /data/data but that folder is empty with nothing else

**Comment by d0k3** [comment]
Another case of @d0k3's infamous "too-much-safety" :). Should be fixed now, can you try with others (that didn't work earlier), too?

**Comment by NWPlayer123** [comment]
seems good now 👍 @d0k3
