### ISSUE TITLE
Gba VC injection Failed Copying Path for gbavc.sav

### ISSUE THREAD

**Issue by AlexS2412** [d0k3/GodMode9#187]
It seems to fail every time when injecting from either godmode9 or decrypt9 on the latest version. If needbe i can post the cia and the save.

**Comment by d0k3** [comment]
No copyrighted material here pls. I have strong doubts this is really about the latest version but rather you doing something wrong. If not, name a version where it works and one where it doesn't.

**Comment by AlexS2412** [comment]
Ive only tried it with the newest gm9. I know better than to use a dated version of your software.

**Comment by AlexS2412** [comment]
I followed this page to the letter  : https://3ds.guide/godmode9-usage.html and it always fails when injecting.

**Comment by d0k3** [comment]
Umm... If you are really convinced this is an issue with a new version, you need to name an old version that works, no way around.

Granted GBA VC save injection can be wonky at times (it always was). So, recheck the steps maybe?

**Comment by AlexS2412** [comment]
In not sure but it may be due to save size from what im assuming. The save im injecting is 64kb and it seems the save when dumped was 32kb. But the 64kb save is legitimate as well so im not sure why it isntantly fails every time.

**Comment by d0k3** [comment]
Okay, well, the issue here is that some emulators and even flashcards pad the save. Use a hex editor or some tool to trim the save to the correct size (just discard everything beyound 32kB), then it should work. Also, better to ask on some support forum (GBAtemp, f.e.) if you need more help with that. Closing this now...
