### ISSUE TITLE
Feature Request - Script support for mounting/unmounting SD

### ISSUE THREAD

**Issue by AnalogMan151** [d0k3/GodMode9#190]
With NTRBoothax's release, many people are trying to make installation packs for use with NTRBoothax. These packs usually include some pre-downloaded files like boot9strap, Luma3DS, FBI, etc and the whole process is executed in a set of scripts. One key part is the copying of setup files from the installation SD card to the RAMDISK, then back again to the target SD card after unmounting and swapping the SD cards. Since unmounting cannot currently be done by script, this means either breaking it up into two scripts or removing the SD card unsafely. 

Since scripts run in memory, I would like to ask if scripting commands for `InitSDCardFS()` and `DeinitSDCardFS()` could be added so we could move files between SD cards using the RAMDISK without the need of multiple scripts.

**Comment by d0k3** [comment]
Can you go into detail a little more? Why is it required to unmount the SD card in the process?

**Comment by AnalogMan151** [comment]
>One key part is the copying of setup files from the installation SD card to the RAMDISK, then back again to the target SD card after unmounting and swapping the SD cards.

Basically these scripts are setup to move files from one SD card (a pre-made setup card containing a pack of files useful in installing CFW on 3DS) to another SD card (the SD card to be used in the 3DS long-term). I've already incorporated zetaPRIME's pull request into my own package. Example script can be found here: [NTRBootHax Setup Script](https://github.com/AnalogMan151/NTRBootHax-Pack/blob/master/gm9/scripts/Setup.gm9)

**Comment by d0k3** [comment]
Okay, so this is for PC less setup, correct? I may add this as a function that unounts, waits for card eject, then card reinsert.

Btw, GM9 release coming soon, so you'll have all that new scripting stuff officially released soon.

**Comment by AnalogMan151** [comment]
Correct, PC-less setup. Since we don't have DLDI access to the flash cart SD, this is the next best thing we can come up with for mobile and quick CFW installs.
