### ISSUE TITLE
What's happening with the release tags?

### ISSUE THREAD

**Issue by Valeri0p** [d0k3/GodMode9#195]
Hello, since I've a little bot that checks the github release pages of several 3ds projects, I've noticed something strange on this repo: starting from one month ago, every week a new release tag with an higher number is published, but there isn't any binary and the only description is the one of the latest commit.

Do you know what's happening with the release tags?

**Comment by d0k3** [comment]
These are lightweight tags. They only specifiy a certain commit, have no description, and are used by me to mark certain milestones (= more complete / more tested than your reguar run of the mill nightly). The next proper release will be v1.4.0, which will contain a binary and a proper description.

**Comment by Valeri0p** [comment]
OK,thanks for the explanation :)
