### ISSUE TITLE
Script command boot 'unknown cmd'

### ISSUE THREAD

**Issue by BradleyDS2** [d0k3/GodMode9#196]
Hello, I'm trying to write a gm9 script that will let me boot Luma, the script is the following

```
set SUCCESSMSG "Luma Booting"
set ERRORMSG "Luma failed to boot"
 
ask "This will boot Luma.\n\nContinue?"

# Boot Luma
boot 0:/Luma.firm
```

The script is stored as \gm9\scripts\boot_luma.gm9
and Luma.firm is on the root of the SD.

When I run the script, it says "This will boot Luma. Continue?" but then aborts with

```
0:/gm9/scripts/boot_luma.gm9
line 10: unknown cmd
boot 0:/Luma.firm
(<A> to continue)
```

Line 171 of the hello script describes the boot command, and I don't think I'm misusing it, but if I am, please correct me.

Also, would it be possible to add a dir command to GodMode9 in a future release? That would be great for checking what files are left in a directory after running my custom cleanup script. I see that there's a find command, but it states 

> If wildcards are used, 'find' will return the last alphanumerical match

so I believe it would return a single result, rather than a list of files in a directory, please correct me if I'm wrong.

Thanks for your time, and making such a wonderful tool with so many uses!

**Comment by BradleyDS2** [comment]
Nevermind, the hello script I was viewing was the new one, and the functionality has yet to be added to the newest release of GM9. Is there any way for me to build a copy of GM9 using the source files, and if not, is there any ETA on the next release?

Also, a dir command would still be really useful, if you wouldn't mind adding it :)

**Comment by windows-server-2003** [comment]
The next release will be v1.4.0 and v1.3.8 is already released(source only), but I don't known when.
