### ISSUE TITLE
Feature Request - Select file from directory

### ISSUE THREAD

**Issue by BradleyDS2** [d0k3/GodMode9#197]
Would it be possible to add a dir command to GodMode9 in a future release? That would be great for checking what files are in a directory, I believe find works similarly, but only returns a single result, based on 

> If wildcards are used, 'find' will return the last alphanumerical match

but please correct me if I'm wrong.

This would be amazingly useful for a standalone script runner.

Thank you for your time.

**Comment by d0k3** [comment]
You know about the `echo` command? Doesn't that do exactly what you want by `pause`?

Also, what you want is not only listing files, you want a way of selecting.

**Comment by BradleyDS2** [comment]
I realised my mistake about pause and edited it out shortly after posting, sorry about that, I wasn't thinking with a clear head. 


Just listing the files would be useful for me, as I work with about a console a week, so confirming the contents of the root of the SD and folders during a script would be useful, and I feel that it would be useful to others as well.

Selecting a file/files from a directory would be amazingly useful, and I can see it really enhancing the power of the scripts, especially if the name/path of the file can be stored to be called upon later in the script, like can be done with other values already,  but I'm not sure how difficult it would be to implement.
