### ISSUE TITLE
[Bug?] Godmode9 1.2.1 Can't run .gm9 scripts or see Script option in menu.

### ISSUE THREAD

**Issue by DNA64** [d0k3/GodMode9#198]
Every now and then I encounter this strange issue with **GodMode9 1.2.1** and was hoping someone could shed some light on the issue. I've attached an image below as proof.

1. The Script option is missing from the menu sometimes even though 0:/gm9/scripts is present and contains the .gm9 scripts.

> Run .gm9 scripts via a neat menu: Press the HOME button, select More... -> Scripts.... Any script you put into 0:/gm9/scripts (subdirs included) will be found here.

2. Scripts do not run anywhere on the SD Card. When I press the A button it opens a menu with only 3 options.

- Show in Hexeditor
- Calculate SHA-256
- Copy to 0:/gm9out

> Run .gm9 scripts from anywhere on your SD card: You can run scripts in .gm9 format via the A button menu. 

![20170911_234615](https://user-images.githubusercontent.com/4770097/30311921-4dfb77cc-974c-11e7-8da5-6b3c787f46fb.jpg)

**Comment by fox8091** [comment]
Scripting was added with 1.2.7? Try the latest release.

**Comment by DNA64** [comment]
*facepalm*
lol, I just realized I was somehow using 1.2.1 vs 1.2.7 the current build (I just did this system a few days ago), I shouldn't keep old files around >.< 

I knew it was something stupidly simple, thanks for the kind reply. I've already updated and it's working now. :+1:

**Comment by fox8091** [comment]
1.2.7 isn't the current build. 1.3.1 is.

**Comment by DNA64** [comment]
You caught me before I could update my mistake. I'm running 1.3.1 :)

**Comment by NaturalHarmonia** [comment]
I'm using the latest version now and can't find the script option after pressing home. Was it moved somewhere else?
