### ISSUE TITLE
Feature Request - Removing all traces of / resetting GM9

### ISSUE THREAD

**Issue by Noeliel** [d0k3/GodMode9#199]
This would remove things like the bonus drive for example if one has been set up, or any embedded essentials backups.  
I'd like to revert my 3DS to factory condition, and I believe this feature might come in handy here and there.
Not something you'd use every day, but still, might be worth considering.

**Comment by d0k3** [comment]
There is only one way to revert your 3DS to factory condition, and that is via a NAND backup. Writing this will also remove the bonus drive and essentual backup. There are also uninstaller scripts for b9s, if you only have a backup with b9s installed.
