### ISSUE TITLE
Script Live Preview

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#202]
I spoke with you a little bit about the live preview of scripts slowing down their execution, especially when there are a lot of comments. I'd like to formally request an option to live preview or not, please.

**Comment by fox8091** [comment]
That was fixed with commit [59928d7](https://github.com/d0k3/GodMode9/commit/59928d7573ad37fba846d8679bc33752a0943f2d), and also seems to be a duplicate of #201. Close please?

**Comment by CecilFF4** [comment]
You're absolutely right. I'm sorry I missed that. I'll close this. Thank you, btw.
