### ISSUE TITLE
Fauture Request - Add battery charging state

### ISSUE THREAD

**Issue by windows-server-2003** [d0k3/GodMode9#204]
Would you make the string of battery percentage orange/green to notice battery is charging/full on the top bar.
Godmode9 has the MCU access and can read battery charging/full state.
https://3dbrew.org/wiki/MCU_Services
0x002C0000
0x002B0000

On my console, mcu register 0x0F will be
10100010 (A2, not charging)
10101010 (AA, full)
10111010 (BA, charging)

**Comment by windows-server-2003** [comment]
Sorry, orange and green is sometimes same as top bar.Instead of changing string color, please add '+' at the end of percentage like below.
100%+    This means the battery is full.
47%+      This means the battery is 47% and charging.

**Comment by d0k3** [comment]
The latest commit improves the battery indicator visually. It is also obvious wether it is is charging or not.

**Comment by windows-server-2003** [comment]
Thank you very much.
