### ISSUE TITLE
SysNAND Virtual: ByteSwap EEPROM type agb saves

### ISSUE THREAD

**Issue by cheatfreak47** [d0k3/GodMode9#205]
For some reason EEPROM8K (512b) and EEPROM64K (8kb) saves are byte swapped in hardware, so byteswap them back in input and output for gbavc.sav to avoid potential issues with restore / backup of saves.

To tell just check the size in the agbsave header, if it's 8kb or 512b it's EEPROM and needs swapped.

example:
```
Typical Emulator/Cartridge Save Dump:
0D 63 02 65 45 41 4D 41 
00 00 00 00 00 69 00 8E 
00 01 19 FE 00 01 9D 9C
```
```
AGBFIRM save:
41 4D 41 45 65 02 63 0D 
8E 00 69 00 00 00 00 00 
9C 9D 01 00 FE 19 01 00
```

**Comment by cheatfreak47** [comment]
Another thing, it'd be nice if you could have the option to inject clipboard data into gbavc.bin instead of having to make absolute sure the file name copied is "gbavc.sav" each time before pasting it into sysnand virtual.

If it was possible to inject clipboard data, this would also negate the need for manually trimming improperly saved gba save files, in general I think it'd be a good addition.

**Comment by d0k3** [comment]
A quick, clumsy workaround (i.e. byteswapping the virtual file) on GM9 side is not the right course of action here and will do more bad than good in the long run. There is also a copy of the AGBSAVE on SD, which I plan to support soon (CMAC still has to be figured out), and which would require figuring out a workaround over again.

I suggest you instead support these two issues with additional info:
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/150
https://github.com/mgba-emu/mgba/issues/878

Also, the gbavc.sav does not have to have the right name. GM9 will suggest the correct location if the size matches. As for the trimming issue - yes, that's a pita. Take note that my feature requests would actually also fix that issue.

**Comment by cheatfreak47** [comment]
Are you positive that EEPROM type chips in real GBA games don't store the data byteswapped already? 
I highly doubt all emulators are deliberately byte swapping just one save type like this for no reason, I've dumped saves off of real carts using various tools and all of the EEPROM ones came out byte swapped, but all the rest didn't. (Unless all GBA dumping tools are also deliberately byte swapping just one save type too???)

In addition, I don't think that it would ever lead to more confusion or do any bad, since AGBFIRM is the only thing in the world dealing with manually un-byteswapped EEPROM type GBA save files, the byte swapping being done on your end would lead to nobody ever ending up with unswapped EEPROM saves to begin with (negating the need for tools to reswap the bytes on a PC, etc.) 

This is an idea created out of convenience. Granted, you would have to make it do the same thing later when implementing support for the SD GBA save, but that's kind of a smaller concern for now. 

If you think you can do a better job with it, by all means, but a simple byte swap on your end would be a lot easier for everyone, not needing to convert existing saves to some new format before injection just adds another step for everyone, and for no tangible purpose either.

**Comment by d0k3** [comment]
From a chat with @AuroraWright yesterday (I hope it's okay to quote you, Aurora):

> I just talked with the mGBA dev
> they said that it's that way because no one really knew how the 8 bytes are stored on the hardware
> and now they can't change it because it'd break existing saves
> so rip

Also, no offense meant, but you're underestimating the effort required for proper random byteswapped access - this is not a 10 minute job by far. For SD AGBSAVE access, we'd have to change the whole thing (I'd have to provide AGBSAVE mounting), in turn breaking basically all existing tutorials on it. That all doesn't even take into account the other inconvenience issues you brought up and the fact that at some point someone may have legit complaints about the byteswapping (f.e. when writing to carts). So... my philsophy here is, do it once, do it proper.

Best outcome here would be, the respective authors support the AGBSAVE save format natively, you'd just copy the whole partition and provide that to the emulator as save file. With the AGBSAVE format, the byte ordering is 100% clear, and an AGBSAVE file always has the correct size. Sure, that would also require a change in existing tuts, but a small one.

**Comment by cheatfreak47** [comment]
Alrighty, as long as a convenient solution comes about in the end, I'm cool with it, I just figured this was the least effort solution, but of course least effort isn't always the best.

**Comment by d0k3** [comment]
Let's see what the respective authors have to say. We may not come up with a quick solution, but with one that works in the long run.

**Comment by WinterMute** [comment]
Some quick research shows that no$gba stores saves in the correct (unbyteswapped )order but EZF IV has byteswapped saves.

I don't really understand how something like this happens tbh.

Interesting historical info - http://zork.net/~st/jottings/GBA_saves.html

**Comment by endrift** [comment]
The EEPROM saves are read and written 8 bytes at a time. You can't address them more finely. What most emulators do is say "ok address 1 is actually address 8, now let's write out the 8 bytes we get in the order we get them". Turns out that puts them in the file *backwards*, but VBA people didn't notice. It's been a few years but I think I intentionally did this in mGBA to keep compat with VBA saves, although I did notice it was backwards.

**Comment by d0k3** [comment]
Interestingly, the VBA people haven't commented on this yet :). Anyways, I'm still unsure as to how to handle this from GM9 side. I know, there is no way to know about the byte ordering of a GBA savegame by just looking at it, so mGBA can't take GM9 extracted eeprom saves and vice versa.

Changing that behaviour in GM9, and doing it proper would require larger changes to how GM9 handles this, in turn breaking all tutorials on GBA VC save transfers. Oh, and did I already mention that, due to the way the console handles these transfers, GBA VC save transfers have always been sort of a pita?

I'd also strongly assume that this issue will also make a comeback once Switch GBA VC savegame transfers are a a thing.

Anyways, @endrift - you have my full support in getting imports / exports of the AGBSAVE format working.

**Comment by cheatfreak47** [comment]
@d0k3 this might be a surprise to you, but it turns out that there might not be any way to have it so all EEPROM save games are "correct" byte order no matter what.

Something I came across earlier is that some games seem to be _purposely_ swapping the bytes on write to the save file, and other do not.
The first few human readable bytes of Super Mario Advance are "EAMA" (meaning, are swapped) on saves dumped from a real cartridge, but some other games, such as The Legend of Zelda A Link to the Past & Four Swords, are not swapped when dumped from the cartridge, I noticed this myself looking through all the dumps of cartridges I made earlier.

Because of this, AGBSAVE for ZELDA is swapped on 3DS and Super Mario Advance is not.

There's no winning with this one.

**Comment by d0k3** [comment]
The changes required for a byteswap inside GM9, if done proper, will break all existing tutorials (in addition to the implementation not being exactly trivial). Once we got the SD AGBSAVE working, we may break stuff again. Then, once GBA VC save transfers on Switch will become a thing (I'm pretty sure this will work similarily), the next problem will pop up.  Whatever solution we come up, it's better to do it once and do it right and not make this even more of a clusterfuck than it is now.

Also, yeah, fucking great. Not even Nintendo seems to know how to handle that clusterfuck. Also, thanks for this helpful info!

**Comment by cheatfreak47** [comment]
@d0k3 Well here's some more helpful info:
Nintendo's own GBA VC Seems to save in the reverse format that our typical emulators today use as well.
Meaning, even Nintendo doubled back to allowing the bytes to be swapped. 

[https://i.imgur.com/LhWWJLd.png](Proof)
This is the save data for Super Mario Advance on Wii U VC.

**Comment by d0k3** [comment]
Well... you're right, implementation wise, stuff is not as easy as it may sound. Also, we can break all tutorials in existance, but we should do so only once (not twice, when we got the SD CMAC thingy figured out). Anyways, can you, maybe confirm or reasearch a bit of stuff? There's some questions that I'm still unsure of.
1. Is 128kB the actual upper limit? From the AGBSAVE header, the upper limit would be roughly 4GB, but we all know this will not happen. There may be also a technical limit from the GBA game side. How does the limit relate to what you get out of emulators? Do emulators write smaller or bigger files? Maybe @AuroraWright can shed some light on this.
2. Are we 110% positive the size is enough to determine if the save chip is an EEPROM or not? If so, can you provide some kind of additional info that would prove this? (maybe also @endrift can shed some light here).
3. This one will be very difficult. We know GBA savegames don't have a universal identifying header or magic number (only AGBSAVE has this) and are thus not easily recognizable, but you apparently used some kind of magic number to check if byteswapped or not. So, what I wonder about right now is, do savegames at least have a _unique_ identifying header? Meaning, do we have some means to easily decide a savegame belongs to one game, given we already have another savegame from that game?
4. And another difficult one - there are two mistery dwords in AGBSAVE, at offsets 0x60 and 0x64. How are they related to the save? Maybe they have something to do with flipping occuring or not?

**Comment by cheatfreak47** [comment]
@d0k3  
1. Well, I'm not sure that it is a "limit" so much as none of the existing games on the market ever had a save with higher than 1mbit of FLASH type memory (or 128 kilobyte) storage. The only games I know of personally that use this are the Pokemon titles, and Super Mario Advance 4, which used it because it needed storage for the e-Reader level cards.
2. Definitely, as far as storage goes, there's only 5 main types, each with their own distinctive sizes. The only ones here with the weird byte swapping business going on is EEPROM, though I will verify this myself with some additional testing- which I'll post when I get the chance. Some of these individually have variation- like chip manufacturer and such, but as far as I can tell, EEPROM actually has no such variance, except for what appears to be an unknown one, that no commercial games appear to use- I did actually check that too, games won't work with it or will not save with it.
- EEPROM with 512 bytes
- EEPROM with 8 kilobytes
- SRAM/FRAM (either 32 kilobytes of “static RAM” with a long-life battery attached, or 32 kilobytes of ferro-electric RAM)
- Flash RAM with 64 kilobytes
- Flash RAM with 128 kilobytes
3. Actually the way I was checking this is probably rather silly, but essentially, by wiping out the save data on various EEPROM games on both an emulator (and in one case, real hardware) and on a 3DS, I was able to generate identical save files for the same game on both, and look at both files with a hex editor, and notice the difference this way, just by looking at the bytes. Games all handle this differently, and most of the time have no way to identify whether or not they are swapped or not, but, my findings were that agbsave is always like this with EEPROM saves, it's not selective. This is likely due to [how the EEPROM saves work](http://problemkaputt.de/gbatek.htm#gbacartbackupeeprom). 

As for the question about telling what save belongs to what game- on occasion, games have a identifying string in them, but it's never consistent where in the file, so it's not something that can be machine processed, the only possible solution is making sure the save being injected is the same size at least, chances are, no user will try injecting a Mario Advance 2 Save into Zelda unless they aren't particularly smart.

4. No clue on that one, perhaps @AuroraWright might know or have some ideas? 

---

One other thing that could be improved as I mentioned in my second post on this issue- is making it easier to inject GBA save files generally. As of now, the way you have to do it is to rename the save you want to inject as "gbavc.sav" and copy/paste it into S:/ -- which is functional, but the thing is, this makes it considerably more work/setup to do multiple jobs, or work with more than one save file for different games on the SD card- or even multiple saves from the same game. It'd be wise to make sure the user can have the save filenames on the SD be whatever- and inject them from the clipboard regardless of the filename- or perhaps when clicking on a .sav in the SD card, it'll give an option to inject it into AGBSAVE right there, which would simplify the process quite considerably- though that probably depends on how you implement this in practice, I suppose.

**Comment by WinterMute** [comment]
> And another difficult one - there are two mistery dwords in AGBSAVE, at offsets 0x60 and 0x64. How are they related to the save? Maybe they have something to do with flipping occuring or not?

From that link I found earlier - http://zork.net/~st/jottings/GBA_saves.html

> At start up, the code in the SDK would talk to the Flash chip and say “what’s your manufacturer code?” and use the protocol corresponding to that manufacturer. 

So my theory would be that arm7_save_cfg_t probably contains a response to that request or something that tells the firmware how to respond.

**Comment by d0k3** [comment]
Thanks @cheatfreak47 and @WinterMute - this does sound reasonable.

Now, one unanswered question - how does actual save size relate to what emulators give you? Is the savegame from an emulator typically bigger? Fixed size?

**Comment by WinterMute** [comment]
@dok3, heh some emulators detect save size better than others. Most emulator savefiles are typically bigger

**Comment by cheatfreak47** [comment]
@WinterMute Is that actually true? All the games I've tried seem to have 1:1 exact sized stuff for the most part- at least on any modern emulator, like VBA-M and mGBA. (though up until recently, mGBA was giving the wrong size for EEPROM8K (512b), which I reported and endrift subsequently fixed.)

Regardless, this would would work well with my idea of injecting from clipboard as any emulator creating files larger than the actual file always just pad out the extra space with 00s or something at the end of the file, meaning that if you injected a incorrectly sized file into the correctly sized one, only the good part of the file would be injected anyway.

**Comment by WinterMute** [comment]
@cheatfreak47 yeah, auto-detect stuff got a lot better but I think people still use some old VBA builds (but m'uh accuracy) which err on the side of caution, It's not a big deal really, just a matter of ignoring stuff outside the size - emulated games won't use the extra space.

**Comment by dok3** [comment]
Sorry, some body include me in this thread by an error i'm @dok3 not @d0ke :)

But im seeing that you are working on game emulation?

I was talking a week a go with a Designer about to construct a product and a network like PSN but for game emulation. 

What do you think about this idea?

Too crazy ? or existent idea ?

**Comment by d0k3** [comment]
Oh, some other guy chiming in! This is not about emulation, @dok3, it's about a clusterfuck someone (none of us) was responsible for years ago. Your idea sounds good, though, but pls no derailing my issues section.

Anyways (sigh)...
@cheatfreak47 can you please thoroughly test this build and tell me if it does - not only for eeprom saves - exactly what you'd expect?
https://transfer.sh/QcsSc/GodMode9-v1.4.0-20-g5beab1c1-20170920214115.zip

Also, all tutorials in existance broken, but w/e.

**Comment by cheatfreak47** [comment]
@d0k3 sure can, working on that now, so far the dumped saves match up well to what I would expect for each game- next I'll try injecting some EEPROM saves for various games and see how that works, and edit this post with some examples of the games I tested.

All Saves Injected were dumped with GBA Backup Tool w/ a real DS Lite and GBA Game
- Super Mario Advance [EEPROM 512b] - Dump: Works | Inject: Works
- The Legend of Zelda - A Link to the Past & Four Swords - Dump: Works | Inject: Works
- Banjo Kazooie: Grunty's Revenge [EEPROM 8kb] - Dump: Works | Inject: Works
- WarioWare Inc. Mega Microgame$ [SRAM 32kb] - Dump: Works | Inject: Works
- Sonic Advance 2 [FLASH 64kb] - Dump: Works | Inject: Works
- Super Mario Advance 4: Super Mario Bros 3 [FLASH 128kb] - Dump: Works | Inject: Works
Conclusion: Everything is working that matters.
---
Injecting Larger Save than AGBSAVE has avaliable: Works
[situation for this happening: emulators producing oversized saves]

Injecting Smaller Save than AGBSAVE has available: Fails
[situation for this happening: injecting a smaller eeprom emu save into an SRAM patched GBA title, people shouldn't be using SRAM patched titles anymore, but people are lazy- fix: pad out remaining space with FF bytes]
[situation 2 for this happening: Pokemon maybe, no idea if this will work, but before, pokemon wouldn't work due to FLASH128K being unsupported, now that it is supported _maaaaybe_ people will be able to migrate to the fixed FLASH128K GBA titles by exporting the save, and importing the old 64KB file into the 128KB new one, and allowing the game to repair the save, since half of the Pokemon Saves was used as a backup anyway. The solution would be to just again, fill missing space with FF bytes]
