### ISSUE TITLE
Feature Request: List Game titles next to title ids

### ISSUE THREAD

**Issue by CCF100** [d0k3/GodMode9#207]
Could you make gm9 list title ids in title path and list the game name? This would make it significantly easier to find the game you want to dump/build cia from. Also, could you have gm9 offer to add game name to the end of the cia/decrypted 3ds file?

**Comment by Terathiel** [comment]
This functionality already exists for SD contents at least: highlighting a folder such as A:/title/ (or A:/title/00040000/ if you only wanted games & not DLC/updates) and hitting R+A then selecting "Search for titles" will give you a list of clearly labelled TMDs from which CIAs can be built (and will automatically have the name included in the end result).

**Comment by d0k3** [comment]
What @Terathiel said. There is also a file renamer for CIA / NCCH / NCSD / NDS files already included (check inside the context menu), and you can show game info for each of these file types.

Besides, the title search does already work from root, it works for all applicable drives (at least `1:/`, `2:/`, `4:/`, `5:/`, `A:/` and `B:/`).
