### ISSUE TITLE
Large File Deletion > SD Corruption

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#208]
It's happened twice now that when I manipulate a large file, SD corruption occurs. It happened when I moved a file from one location on the SD to another. It was about 370 MB and the file never showed up in the target location. Error scan revealed a lot of file system errors. The second time it happened I attempted to delete a 2.9 GB file. This time the error scan revealed so many errors and corruptions of various files that I decided to reformat the card and restore its data from a backup.

**Comment by d0k3** [comment]
That sounds an awful lot like there are other problems on your SD card. Filesystem entry moves within one filesystem and file deletes are pretty quick and simple operations, regardless of file size. These operations never require modifying more than two (moving)  or one (deleting) sectors.

In short: the problems on your filesystem didn't happen when you did these two operations, but rather at some point before. Moving / deleting only made these issues manifest, when you were previously unaware. You already reformated the card, which is what I would have recommended anyways. I'd suggest you keep that card under observation now, maybe do a chkdsk from time to time.

Also, if you're convinced GM9 has something to do with it, try reproducing these issues and give me the steps.

**Comment by CecilFF4** [comment]
I run a scan after every backup, and I occasionally get errors after using an FTP app too much. That seemed to stop once I started using the MicroSD Manager instead (I'm on an Old btw). Anyway, the filesystem errors I received only became apparent after doing those operations in GM9. Just now I ran a scan, deleted the largest file I had on my SD using GM9, then ran another scan (all good). So maybe I did have a corrupt file that was fixed when I reformatted and restored. I still felt that you should be aware that GM9 was part of this error process, even if it didn't actually cause the error, and hopefully that will be useful information should others have similar issues.
