### ISSUE TITLE
Feature Request - [Scripting] Rebuild CIA from extracted contents with buildcia

### ISSUE THREAD

**Issue by 16BitWonder** [d0k3/GodMode9#211]
Rebuilding CIAs from extracted contents with buildcia would be a pretty handy feature for people wanting to make a few changes or one-click setups for CIA romhacks .

Rather than dumping the CIA, transferring it to a computer, unpacking it and modifying it, and then repacking it and moving it back to the 3DS. They could simply extract all the contents of a CIA to a single directory, copy over their modified files/make their changes, and then use the buildcia command on the folder (assuming all the necessary files are present in the directory), and then reinstall the produced CIA.

Would this be doable or worthwhile?

**Comment by d0k3** [comment]
While I see the appeal of this, nope, it won't work. Most edits will go to RomFS, which is too complex to handle edits for in GM9. RomFS is designed as an archival format, once written, never changed. Even if I did a RomFS rebuilder (which would be a gargantuan task), no one would use it, as it would take much too long on a 3DS to rebuild.
