### ISSUE TITLE
Request: copy support files to both "out" and "support"

### ISSUE THREAD

**Issue by NWPlayer123** [d0k3/GodMode9#213]
I've been trying to decrypt stuff and this kept screwin me up, when decrypting CIAs with a seed, it only checks SD:/gm9/*support*, not out, while building support files only copies to out. It would be ideal to put it in both locations
EDIT: more descriptive error messages would help too but that's another issue

**Comment by d0k3** [comment]
You know, setting up the support file stuff is a one time affair, the only real relevant file there is the seeddb.bin, and you really want to waste a menu entry for that? Don't be that lazy - you can copy that file there yourself.
