### ISSUE TITLE
[Bug?] Top Green Bar disappeared on 0a1a08a

### ISSUE THREAD

**Issue by MelonGx** [d0k3/GodMode9#214]
The Top Green Bar can be re-appeared when:
1) I press a D-Pad button.
2) Wait for 5 seconds and press nothing.

But it can be always re-disappeared when I enter any drive or subfolder.

The Top Green Bar never disappeared in older versions of GM9.
It doesn't effect any function but looks weird.

**Comment by d0k3** [comment]
Can you give me any excact steps to reproduce the vanishing top bar? Is this, perhaps, GM9TD? Most recent nightly?

**Comment by d0k3** [comment]
I may have an idea what happens here... try this build:
https://transfer.sh/iZ2ok/GodMode9-v1.4.1-4-gdcafbaa1-20170923200234.zip

**Comment by MelonGx** [comment]
Thanks very much.
The vanished top bar is back on GM9TD dcafbaa now.
