### ISSUE TITLE
Feature Request - Acekard 2i SD Slot Access in GM9

### ISSUE THREAD

**Issue by s1cp** [d0k3/GodMode9#216]
I know some may have already suggested it, but I think it would be really nice to have some kind of access to the flashcart's SD card slot by implementing the flashcart's DLDI into GM9. This would be really useful for scripting and it would remove the need to switch SD cards to copy files over.

**Comment by d0k3** [comment]
As I already said, no support for single cards. GM9 is meant to be universal. Multiple card support is already considered, though. Closing this now...
