### ISSUE TITLE
Feature Request - Virtual Drive baked in at build time. 

### ISSUE THREAD

**Issue by zaide-chris** [d0k3/GodMode9#219]
Some way to add an archive or set of files that will be included in the firm when GodMode9 is compiled. They should then show up in a new root drive when the firm is loaded. This will allow the possibility of a GodMode9.firm that is complied with an autorun.gm9 to copy files to the SD card. This along with conditional jumps like in #129 would allow a true PC-less setup without requiring any files to be preloaded on to an SD Card. Rather then adding a new root drive, it would also suitable to automatically unpack the files in to the ram drive.

This also would also somewhat push the idea of implementing flashcard SD card access aside as long as the card has enough available space to hold the files needed directly.

**Comment by d0k3** [comment]
Try the current GodMode9 source code with this makefile:
https://transfer.sh/u0AxI/Makefile

Then, put your image (any GM9 mountable format) into the data directory as vram0.img (max size: 3MB!). Compile, you'll get a larger firm then usual. Inside GM9, mount M:/vram.mem for access to your image.

This may make it into the GM9 source, I still need to iron out some quirks, though.

**Comment by d0k3** [comment]
Added in https://github.com/d0k3/GodMode9/commit/ef63219f7078a2cf7d107e945b5b33f07dc9a0d5

Filesystem is available via mount of `M:/vram.mem`. Maximum size 3MB, Either RomFS or FAT make sense (RomFs preferred, I guess).
