### ISSUE TITLE
Odd variables inside scripts

### ISSUE THREAD

**Issue by DMSalesman** [d0k3/GodMode9#221]
Good day. While examining [Backup SysNAND.gm9](https://github.com/d0k3/GodMode9/blob/master/resources/gm9/scripts/Backup%20SysNAND.gm9) and [Backup EmuNAND.gm9](https://github.com/d0k3/GodMode9/blob/master/resources/gm9/scripts/Backup%20EmuNAND.gm9), I noticed the `SUCCESSMSGMSG` variables to be set. Since they're unused and their name clearly resembles the special `SUCCESSMSG`, are they:

 * mistakes?
 * debug variables?

In the first case, why not to delete them? In the second, why not to comment them out?

**Comment by d0k3** [comment]
Yeah, of course that's mistakes. I didn't pay attention. Want to do a pull request? Maybe also check the other scripts while you're at it.

**Comment by DMSalesman** [comment]
Will do. Expect a PR for this evening, or tomorrow at best.

**Comment by d0k3** [comment]
Fixed by yourself. Btw, if you had added something along the the lines of "Fixes #221" or "Fix #221" to the commit message, you'd also have autoclosed this issue.

**Comment by DMSalesman** [comment]
@d0k3 Ah, a fine trick. I'll make sure to remember it.
