### ISSUE TITLE
display rather dim

### ISSUE THREAD

**Issue by MZ-4** [d0k3/GodMode9#223]
EU 2DS, O3DS, O3DSXL, N3DSXL, B9S 8.1.1., Screen brightness: 4(x), GM9 1.4.2
Some of the text is so dim, I can hardly read it. Is there an option to make it brighter?
Especially on the displays of O3DS or 2DS where the pixels are even smaller in size compared to the XLs.

**Comment by sceptios** [comment]
Brightness in GM9 is controlled by the systems volume slider.

**Comment by d0k3** [comment]
As @sceptios said.
