### ISSUE TITLE
Text viewer has issues in v1.4.2. Shows blank page with numbers on the left when viewing .gm9 files in textmode.(Hexeditor is fine)

### ISSUE THREAD

**Issue by essence25** [d0k3/GodMode9#224]
See title.

**Comment by d0k3** [comment]
Try the must recent nightly. Does the problem still persist?

**Comment by d0k3** [comment]
https://transfer.sh/pHmtv/GodMode9-v1.4.2-11-g21c1ae30-20170927155218.zip
This one, for example.

**Comment by essence25** [comment]
Yes working fine in this Nightly... Thank you!

⁣Sent from BlueMail ​
