### ISSUE TITLE
Feature Request - Keyscrambler Constant Dumper

### ISSUE THREAD

**Issue by shinyquagsire23** [d0k3/GodMode9#225]
This might seem like a dumb request, but right now it seems that the 3DS keyscrambler constant doesn't really have an easy-access on-hardware dumper utility. This isn't as big of a deal for some tools, but for something like Citra it would be useful to have a legal way to dump the keyscrambler constant. Luckily, since the constant is identical on all 3DS systems it is possible to generate a random non-Nintendo keyX and keyY along with a normal key using existing key scramblers to test against.

I'll have to verify this since it's been a while but you can get each bit of the key constant you flip one bit in the keyY, and then search for the bit in the normal key that can be flipped to get the same crypto output, and you can use that bit position to derive bits of the constant (see [here](https://smealum.github.io/3ds/32c3/#/121), [here](https://gbatemp.net/threads/aes-key-scrambler.406951/page-8#post-5900033)).

**Comment by d0k3** [comment]
Personally, as this is data that can be gotten elsewhere (and also identical among all 3DS), I'd be inclined to say this doesn't neccessarily belong into GM9. If I start with something like that, well, I can aswell go on having a NATIVE_FIRM key parser (cause, legal way of obtaining keys), and that would be a clusterfuck not even I wouldn't even consider.

But... After some consideration - that feature seems to be popular - I'd be willing to put this into GM9 (most likely into the dump support files feature) as long as someone else does the (library) code for it. Maybe look into what other data requires from a real 3DS?

Anyways, closing this, as I won't do it myself. I'm open for a pull request, though.
