### ISSUE TITLE
Feature Request: Image Viewer

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#228]
It'd be cool to have an image (like, photo, not fat/nand/disc image) viewer, or even basic editor.

**Comment by d0k3** [comment]
Has been asked a few times, I understand the appeal, but, sorry, won't be coming. Would take a lot of effort for what would be in essence sub par results.

**Comment by SirNapkin1334** [comment]
Hmm. I see. Alright, thanks.
