### ISSUE TITLE
Unsupported 32 GB SDcard?

### ISSUE THREAD

**Issue by BenCat07** [d0k3/GodMode9#229]
I heard only one other person had this issue before, but well, i do too now:
When i copy any big file it copies for a short time and then i get the
"Invalid directory object"
error, reformatted sd with allocation unit size 16384 (Fat32, 32GB micro SDXC), error not fixed.

**Comment by BenCat07** [comment]
Chkdisk finds no issues.

**Comment by d0k3** [comment]
The issue is most likely not with the size of the copied file (or the copy operation itself), but rather with a certain area on your SD card.

Fake SD cards (those that are actually smaller in size than they claim to be) exhibit this behavior, f.e, and your issue sounds a lot like that.

Thoroughly check your SD card for errors and for fake memory using appropriate tools, then let me know the results.

**Comment by d0k3** [comment]
Try some large copy operations on PC maybe? Also check for any corruptions afterwards ofc.

**Comment by BenCat07** [comment]
Well, i did backup the entire dirve and copied all files back onto it lateron, worked like a charm, chkdisk didn't find any corruptness nor did i, i'll try the tool recommended by the guide....

**Comment by BenCat07** [comment]
Test finished without errors.
You can now delete the test files *.h2w or verify them again.
Writing speed: 14.7 MByte/s
Reading speed: 29.4 MByte/s
H2testw v1.4

**Comment by BenCat07** [comment]
Not a fake SD, still get the same error tho.

**Comment by BenCat07** [comment]
similar to #126 and #176

**Comment by BenCat07** [comment]
Tried 32KB allocation size, error still persists.

**Comment by d0k3** [comment]
There is one other possibility, a malfunction in the 3DS card reader. Or a case of your 3DS card reader not liking that specific SD card. Could you try a different one?

**Comment by BenCat07** [comment]
i'll try, SDHC should be supported tho.... and this is one of the only 32GB sd's i have....

**Comment by d0k3** [comment]
If you got a large NAND (N3DS, O2DS, N2DS), bonus drive may be a way to test copying large files without the SD card involved.

**Comment by BenCat07** [comment]
it feels like the Nintendo itself foramts it in a specific way, since my old 8gb card always has the message that it's "corrupted"

**Comment by BenCat07** [comment]
Other sd works .-. do you have any clue what's causing this? The type of the file system is FAT32.
Volume Serial Number is 140F-4263

**Comment by BenCat07** [comment]
Only seems to not work with the n2dsxl, if i'd have a script to update data and roms directly from .app...

**Comment by BenCat07** [comment]
i can't quite called this issue closed tho, as this SD should be completely supported by Nindy, and 32GB is in FAT32 Foramt range, and the n2dsxl itself can use this one just fine, just GodMode9 can't.

**Comment by BenCat07** [comment]
Once again, more sdcard information:
32GB Philips MicroSDHC Class 4 FM32MD35B

**Comment by BenCat07** [comment]
Formatted using Guiforamt, let at standard format, formatted using GodMode9, all do not work.

**Comment by d0k3** [comment]
So, the same SD card has no issues at all in a different console? Try that large copy operation in userland, use CTRXplorer or 3DShell.

**Comment by BenCat07** [comment]
testing

**Comment by BenCat07** [comment]
CTRXplorer works fine with it, not sure about 3Dshell as i didn#t know if it crashed or was still coyping since there's no % display

**Comment by BenCat07** [comment]
before i tried copying files from a eshop rom into an other folder, since CTRXplorer can't do that i can't test if the rom's at fault. same happened for it's Update data tho, so i think GM9 is at fault.

**Comment by BenCat07** [comment]
i am very confused though, this only happens on this specific sd and only with godmode9

**Comment by BenCat07** [comment]
i'll close this for now, maybe label it tho.

**Comment by d0k3** [comment]
I'd say it's about an unlucky combo of SD reader / SD card /ARM9 SD drivers. If you get a chance, try the same SD card in a different console with GM9. You can also try older GM9 releases on your current console, but I don't think that will help.

**Comment by BenCat07** [comment]
yeah, older GM9 doesn't help

**Comment by BenCat07** [comment]
well i guess i'll use a 16 gigs instead
