### ISSUE TITLE
Options for TMD/NCCH files do not show up if there are upper case letters in their path

### ISSUE THREAD

**Issue by dogtopus** [d0k3/GodMode9#23]

**Comment by d0k3** [comment]
I guess I need more info... NCCH / TMD are detected via content, not name. Can you give me an example where it does not work  and tell me what options are missing?

**Comment by dogtopus** [comment]
Paths like `title/00040000/55aa55aa/00000000.tmd` works, but paths like `TITLE/00040000/55aa55aa/00000000.tmd`, `title/00040000/55AA55AA/00000000.tmd` or `title/00040000/55aa55aa/00000000.TMD` don't work. That is, any upper case in the path will make it stop working

**Comment by d0k3** [comment]
Okay, I have to ask, did you rename this? Cause, if you did, you most likely borked you installed data.

Why?

Well, the stuff on the SD card has a certain additional crypto layer, one that uses IVs calculated from the name. Change just one char in the name (like lowercase -> uppercase), and the file is no more decryptable. There is a reason why I don't allow GM9 to rename anything in these paths after all.

You can also check in the hex editor. Proper NCCHs have "NCCH" @ offset 0x100. Do you still see this? If not, that's a consequence of the rename and the first crypto layer no more being proper.

**Comment by dogtopus** [comment]
Well my title directory was all upper case and the 3DS system still recognized it. I changed it to lower case and it didn't stop it from working. But on GM9 it matters. I guess the official 3DS system normalizes the case of the content path before deriving IVs from them.

Besides that, isn't fat32 supposed to be case insensitive?

**Comment by urherenow** [comment]
"At least in the case of FAT32, you need to mount the file system with the proper codepage and chacter set. Otherwise the system will be case sensitive and while it may work for Linux, Windows will surely freak out."

@dogtopus does this answer your question?

**Comment by dogtopus** [comment]
@urherenow I know there are ways to make fat32 case sensitive but that is still non-standard and not what fat32 is supposed to be

**Comment by d0k3** [comment]
Okay, can you try this test build?
https://transfer.sh/15DA7N/godmode9-20170205-151408.zip

This should fix crypto for uppercase SD paths.

**Comment by dogtopus** [comment]
@d0k3 It works 👍

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/GodMode9/commit/058fd9f52818ebfc3b90cc85bb356482b47b5f3c

Thanks for testing! Also: zero issues open, yay!
