### ISSUE TITLE
Analyze Drive fail

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#230]
On both GM9 1.4.1 and 1.4.2, I keep getting an "Analyze Drive: Failed!" error every time I analyze my SD card via drive 0 (works on other drives, including drive A). My SD's scans all come back clean. I was wondering if there is some file limit that is preventing this from working? Not sure why it would work on A and not 0...

**Comment by d0k3** [comment]
That should not happen. If it does happen, you got a bad dir somewhere in there. To find that dir, do the directory analysis for all directories in your SD card separately, one by one. Once you found it, let me kniow what's wrong with (or, specific about) it.

**Comment by CecilFF4** [comment]
Well, I forgot about a recent app I installed that caused the problem. There's a new save-backup app called Checkpoint that has a slew of problems, but we can now add to the list that, unlike JKSM, it doesn't substitute bad characters for good ones. When the app scanned my titles and created folders for each, it created one with this name: "Super Smash Bros." That is INCLUDING the period. I verified that that was causing the drive analysis failure (I'm assuming the analysis worked on drive A because it didn't look at files outside of the "Nintendo 3DS" folder). I'll go ahead and close this, but at least you are aware that some apps may put a period at the end of folder names. Thank you for an awesome program!

**Comment by d0k3** [comment]
Okay, that is critical, cause, in FAT drivers  in general, a dot is a control symbol.

An example...
You may have a file called "file.bin". Internally, it is stored as 8 + 3 chars:
"FILE    BIN"

The dot denotes where the extension starts. Even though dirs typically have no extension, they are parsed the same - and  a dot at the end, on it's own, will cause trouble in a lot of FAT drivers, cause it is normally translated to *nothing*. I guess you should notify @BernardoGiordano about this issue.

**Comment by CecilFF4** [comment]
Yeah, I opened an issue for his app. And I commented on the top 3dshacks post he made for the app. Hopefully word will get around because, since I make regular backups of my SD, I'm not stuck with this folder issue on my computer. Probably have to try getting rid of it outside of the OS...
