### ISSUE TITLE
Can't dump my digitally purchased game?

### ISSUE THREAD

**Issue by TheMCNerd2017** [d0k3/GodMode9#233]
I have recently bought the Mario and Luigi Superstar Saga remake off of the Eshop. Every time I attempt to dump it as a CXI file, it spits out a message saying that the dumping process failed. Attempting to dump the individual APP file(00000002.app) gives me an error saying that the Crypto is not set up. Dumping as a CIA file seems to work, but the outputted CIA is corrupted, and cannot have most of it's contents viewed, even with the built-in hex editor.

I have no idea why this is happening, but I am worried that this may be an issue with Godmode9 itself.

**Comment by urherenow** [comment]
Do you happen to have files (such as seed.db) in your gm9/support folder from before that game came out?

**Comment by ihaveamac** [comment]
gm9 should already read from the seeddb in NAND.

**Comment by urherenow** [comment]
Should... but the latest readme does say "get good versions of seeddb.bin and encTitleKeys.bin from somewhere (don't ask me!) and put these two files into sd:/gm9/support (optional but recommended for full functionality)." after all, and the error presented clearly states it's a crypto error.

**Comment by ihaveamac** [comment]
press HOME -> More... -> Build support files

this builds 3 files including seeddb.bin. it should already be reading from NAND but try this.

**Comment by TheMCNerd2017** [comment]
I do not have seed.db and encTitleKeys.bin in my support folder, but I do have the 'perfect' aeskeydb.bin file. I will attempt to build the remaining support files through Godmode9 and report back if it fixes the issue or not.

**Comment by TheMCNerd2017** [comment]
OK, I built encTitleKeys.bin and seed.db using Godmode9, and put them in the support folder. I am still getting the error when attempting to dump the game.

**Comment by d0k3** [comment]
If GM9 does not find the seed in your system, it makes no sense expecting the seed in a dumped seeddb.ini either.

The seed dumper in GM9 is not perfect. It works 99.9% of the time, but sometimes a case like yours comes around, one where it doesn't work. It may never be perfect - we lack understanding of certain filetypes.

So will you maybe follow the Quick Setup Guide and get the support files from an external source?

**Comment by TheMCNerd2017** [comment]
OK, I will follow the Quick Setup Guide and try to get the support files from an external source. Do you have any idea how I should go about finding them? Do I just input the filenames in google and hope I come across good copies?

Either way, once I get home and find the files(I'm at school right now), I will respond back stating if it worked or not.

Also, another thing I forgot to mention, this issue also happens with other titles I've purchased recently, like the Pokemon Gold and Silver VC releases.

**Comment by TheMCNerd2017** [comment]
Never mind the question on how I can find those files; I've already found them.

**Comment by d0k3** [comment]
Fixed?

**Comment by TheMCNerd2017** [comment]
I wasn't able to do it yet. I have found good copies of the two other files you are saying I should find, but since I'm currently on an iPad, trying to download them simply opens the file in another safari tab. I'm still in school right now, but I should be getting back home within about two hours.

**Comment by TheMCNerd2017** [comment]
OK, I got all of the files, put them in the support folder, and attempted to dump the game again. And this time, it worked! So it turns out that I only needed those files. Still kind of weird that Godmode9 couldn't find the seed or key to decrypt the game off of my NAND.

You can close this issue since it has been solved.

**Comment by urherenow** [comment]
@TheMCNerd2017 you can close this issue as well because you're the one who opened it. Glad you got it to work.

**Comment by TheMCNerd2017** [comment]
Oh, OK. Closing this issue right now.
