### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#234]
Since we got [fuse-3ds](https://github.com/ihaveamac/fuse-3ds) to decrypt NAND backups without resorting to copying XORpads, it would be advantageous if you could have the essential.exefs include the boot9.bin file within it (or copied separately into the out folder). This would be a great aid in certain filesystem repairs/transfers, especially in cases where the console is completely dead.

**Comment by d0k3** [comment]
The `boot9.bin` file is only accessible when booted via boot9strap, it is then found inside the M:/ drive, from where you can copy it any time. "Forcing" a `boot9.bin` copy is something I don't really like. You're nagged to do an essential backup, cause the stuff in there really is impossible to bring back once lost. It's not the same for `boot9.bin` file, which is identical to all 3DS consoles.

**Comment by CecilFF4** [comment]
I didn't know the boot9 was identical across all consoles. Thank you for responding and for putting out an amazing piece of software.
