### ISSUE TITLE
Crash when right-scrolling gm9 script

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#236]
The title says it all. GM9 crashes when a certain script is scrolled to the right in the textviewer.
Video:

DAMMIT! It's too big. After I spent 10 minutes using an online MOV to GIF converter (My computer is really slow). If you want a video, I'll send it to you with email or something. I'll get an image up in a few minutes.

Here's the script:

DAMMIT! Again, it doesn't like it. I'll make a TXT version of it.

**Comment by SirNapkin1334** [comment]
Here's a TXT version:
[Restore SysNAND (Full).txt](https://github.com/d0k3/GodMode9/files/1384394/Restore.SysNAND.Full.txt)

**Comment by SirNapkin1334** [comment]
The crash handler says,
Exception: Data Abort (4)
2017-10-13 20:50:07
R00: 600000DF | R01: 00000000
R02: 20202020 | R02: 20202020
R04: 20000000 | R05:20202020
R06: 20202020 | R07: 20202020
R08: 20202020 | R09: 20202020
R10: 20202020 | R11: 20202020
R12: 0000000C | R13: 23E7EC40
R14: 23F27F35 | R15: 2020ECF8
CPSR: 600000DF

**Comment by d0k3** [comment]
Did you try the most recent nightly? That issue should already be solved.

**Comment by d0k3** [comment]
... or try the most recent release

**Comment by SirNapkin1334** [comment]
Lol, you released the newest release a bit after I reported this! I was on 1.4.2. It should be noted that when opening the script no text is shown, but the 'you can scroll to the right' arrows are shown.

**Comment by SirNapkin1334** [comment]
An update feature would be nice, but if not, at least telling you if there's a new release.

**Comment by SirNapkin1334** [comment]
Alright, it is indeed fixed in the newest release.
