### ISSUE TITLE
[Enhancement] GM9 FTP Server

### ISSUE THREAD

**Issue by GRX274** [d0k3/GodMode9#237]
I'm Not Sure If This Is Possible But If You Can, But It Would Be Very Helpful

**Comment by ahoischen** [comment]
This is a duplicate of #188 and #181. Please search *all* issues before opening one.

**Comment by d0k3** [comment]
@ahoischen is right. And yeah, as always. I wish that was possible, but it isn't, and will most likely never be.

**Comment by GRX274** [comment]
@d0k3 Would It Have Access Via The Godmode9 HBL Launcher? Because The OS Would Have Been Fully Loaded

**Comment by d0k3** [comment]
No, the OS is unloaded in that case.
