### ISSUE TITLE
Minor Bug: Drive size improperly shown

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#239]
Hi, I've seen this bug in every release since I first got GM9, and thought that I might point it out, although maybe this is intentional? Anyway, the M: and X: drives always show, on the main menu, to have 0 Bytes of data. Opening the drives, this is quite obviously not the case, but odd nonetheless. The strangest thing is that when showing drive info, it says that is has zero bytes AND it's actual size. For example, upon examining M:, it says:
[M:] MEMORY VIRTUAL

15 files & 0 subdirs
136.1 MB total size

space free: 0 Byte
space used: 0 Byte
space total: 0 Byte
Isn't this weird? It does the same thing for X:, but with obviously different numbers. On an older release this would sometimes happen with the C: drive. Finally, a question, what could happen if I write to Memory? Could it permanently brick? What would be side affects?

**Comment by d0k3** [comment]
That's not really a bug. The `M:` / `X:` / `C:` drives are virtual drives. For M:, you can't really tell the size cause this drive handles volatile memory, many of the entries in there being in mapped areas. The X: drive is zero bytes, of which zero are used - xorpads are created on demand. The C: drive... well, let me ask a question, how much space is there if no cart is inserted?

**Comment by SirNapkin1334** [comment]
Ah. I see. Yes, I know that of course there is no data when a cart is inserted, what I had meant is that sometimes when you insert a cart the value does not increase—one has to restart GM9 to see the new value. I think this was fixed though.
