### ISSUE TITLE
Feature Request - Mass CIA generator

### ISSUE THREAD

**Issue by deadair3210** [d0k3/GodMode9#24]
Since GodMode9 can now generate CIA's based on whats installed into the NAND, I was wondering if it would be possible to have an option to generate CIA's of everything installed to the NAND. 

I use this in Decrypt9 when I want to switch consoles due to the fact that its sometimes much faster to regenerate the cia than it is to re-download it

**Comment by d0k3** [comment]
Use the search function (R+A on drives / folder) and search for *.tmd. Mark all and go. And read the readme before doing a feature request ;).

**Comment by deadair3210** [comment]
Didn't know that you could search, I read readme's multiple times, must have somehow missed that. Will make sure next time, thanks
