### ISSUE TITLE
[Feature request] Simple updater

### ISSUE THREAD

**Issue by thenets** [d0k3/GodMode9#240]
The Luma updater is excellent.
Will be awesome if GodMod9 had an updater as good as Luma.

**Comment by pokecraft98** [comment]
Just use multiupdater https://github.com/LiquidFenrir/MultiUpdater/releases/latest godmode9 doesn't need a updater. Plus I don't even recommend using multiupdater for godmode9 because what if something changes like a folder is rename or scripts get a rewrite.

**Comment by d0k3** [comment]
You could edit the config.json file for MultiUpdater, also taking scripts into account. Anyways, what @pokecraft98 said - use MultiUpdater.

**Comment by ValliantStorme** [comment]
@pokecraft98 I think there's a way to do multiple files in MU now, but I haven't found documentation on it, only mentions in issues (something to do with 'L'?)
