### ISSUE TITLE
Injecting 128KB GBA VC Saves Fails

### ISSUE THREAD

**Issue by liljohn360** [d0k3/GodMode9#242]
Following the recent developments on AGB_FIRM's support for 1Mbit flash saves [here](https://www.reddit.com/r/3dshacks/comments/6znqqg/1_mbit_agb_firm_lennies_%CA%96/), I attempted to dump and inject a save file for Pokemon Fire Red (which is using the header modifications that can be found at the link), the FireRed ROM file itself is untouched. Dumping the save file appears to work fine, creating a 128kb file that opens and works in mGBA on PC.

Attempting to inject a 128kb save file however, fails with the message "Savegame inject failed!", even if I attempt to inject the same file that was dumped. I've been following the usage guide on 3ds.guide to do this.

Is 128kb save file injection unsupported at the moment, or could this be an issue on my end?

I'm using the latest GodMode9 v 1.4.3

**Comment by d0k3** [comment]
You need to check something... you know the dumped save file has the title ID in front?

What's the size of the file located at `A:/title/<title_id0>/<title_id1>/data/00000001.sav`?

Hint: <title_id0> and <title_id1> are just the first and last 8 digits of the title ID, resepectively.

**Comment by d0k3** [comment]
Also, pinging @CheatFreak47 here, cause you did the testing for 128kB saves. Any idea what can go wrong there?

**Comment by cheatfreak47** [comment]
Might be a bad GBA CIA? User really needs to check the size of that file, as the probable case is that it's the wrong size for some reason.

**Comment by cheatfreak47** [comment]
In testing, all 128kb games I tried worked fine, all the the GBA games were generated with Asdolos unreleased tool, which seems to be working as expected.

I'm willing to bet the user here just messed up the footer since he apparently did it manually.

**Comment by d0k3** [comment]
Sounds reasonable, @cheatfreak47 . @liljohn360, most likely our CIA is bad. What tool did you use to create it? Also take note that, if the CIA is actually bad and you continue using this, more problems will come up later.

**Comment by liljohn360** [comment]
Checking the size of the 00000001.sav for the game, it's **64.2MB**, which is very clearly wrong. The method I've been using to create the .CIA is as follows:

-Use "Ultimate GBA VC Injector for 3DS 1.6b" to turn Pokemon FireRed rom into .CIA (with incorrect save size)
-Use the steps in [this script](https://pastebin.com/RHZ7fyTX), to extract the .CIA and set 0x08 to 0xA in the footer file, and 0x00030000 to 0x00040400 in the exheader
-Repack .CIA and install, check save size in GodMode9

The MD5 of the GBA ROM is 51901A6E40661B3914AA333C802E24E8, matching the No-Intro database, ruling out the possibility of a dodgy ROM dump

I tried using "Ultimate GBA VC Injector for 3DS 1.6b" with the SRAM patch out of curiosity, and the save file turned out to be 192kB, which also doesn't seem correct, so I leave this a little more confused than when I began...

I'll wait until Asdolos tool is released with proper support for correct save sizes, since doing the fixes manually seems to not work, and every method of injection seems to give me odd save sizes.

**Comment by cheatfreak47** [comment]
@liljohn360 If that's the case, would you mind closing this? Seems you managed to sort it out on your own.
