### ISSUE TITLE
SUGGESTION - Brightness Control

### ISSUE THREAD

**Issue by x7l7j8cc** [d0k3/GodMode9#244]
My suggestion is to put a configuration in the "home" menu, Brightness 1-2-3-4-5 that can be save in a config file in the gm9 folder as bright.conf with content "bright=4" (example).
Because using the volume control is not the best option (for my personal opinion).

**Comment by d0k3** [comment]
Yup, not everyone likes the brightness slider. However, introducing an actual config file just for this is out of question.

I've got something else for you, though. The most recent commit allows you to fix the brightness when building yourself, use `make FIXED_BRIGHTNESS=x`, whereas `x` is a value between 0...15.

Closing this now.
