### ISSUE TITLE
Parental pin removal

### ISSUE THREAD

**Issue by douglie007** [d0k3/GodMode9#245]
I have installed godmode and all the other goodies, how can I remove the pin?

**Comment by Lordkurzschluss** [comment]
Use that site:https://mkey.salthax.org

Probally not possible since parental pin access needs Arm11?

Correct me if i am wrong.

**Comment by Derek1199** [comment]
If you have a backup of your config save, that doesn't have that pin, you can inject it and that will automatically remove it. However, @Lordkurzschluss is correct about the site. You can use that site to remove a pin. Tested it myself.

**Comment by douglie007** [comment]
Cool thank you that worked.
