### ISSUE TITLE
Scripting - filesel on Z: drive after 'Search for titles' causes a crash

### ISSUE THREAD

**Issue by figgyc** [d0k3/GodMode9#248]
Search for files works normally.
Dump file attached. I found this when I was attempting to implement some script methods of my own but the bug occurs in a vanilla gm9.
[exception_dump_171024125136.txt](https://github.com/d0k3/GodMode9/files/1410672/exception_dump_171024125136.txt)
Example:
```
echo "Please make sure you have ran a search for titles before running this script."
filesel "This will crash" Z:/* SELECTED
echo "never gets here"
```

**Comment by d0k3** [comment]
Yup, that's actually not possible, same as we got no command to actually do a search to the Z:/ drive in scripts. I'm inclined to just disable the Z:/ drive here. Any objections to that?

**Comment by d0k3** [comment]
Accidential close, sorry. I want to hear your opinion on this.

**Comment by figgyc** [comment]
That would probably be a good idea at least for now.
