### ISSUE TITLE
DLC "TMD probably corrupted." Reinstalled, multiple consoles

### ISSUE THREAD

**Issue by Targren** [d0k3/GodMode9#25]
Another "backup to CIA" problem for you. Sorry about this. =\

Tested on N3DS XL (11.2) and 2DS(11.2), both using GodMode9-20170212-180122 
(it also fails in Decrypt9WIP-20170214-134632 on both units, with "CIA Stub has Bad Size(21248)", to save you from having to ask)

Attempted to create CIA from A:/title/0004008c/000edf00/content/00000000.tmd failed. TMD verification failed

1. Browse to above filesystem location
2. Select tmd file->TMD file options->Build CIA (standard)
> Instantly displays "CIA Build Failed" 

TMD file fails verification. 
1. Browse to above filesystem location
2. Select tmd file->TMD file options->Verify file
> Instantly Displays: Error: TMD probably corrupted. 

Completely deleted and reinstalled the title on both units, same result, but the install appears to work properly (added content appears in-game, etc.)  

I just want to verify that the file is the problem rather than a glitch in the verifier.

**Comment by Ordim3n** [comment]
You're trying to build the Sm4sh DLCs you bought (or pirated) to a CIA, if I had to guess, it would be the way how the DLCs Tmd are made.

**Comment by Targren** [comment]
Correct, trying to back them up to CIA (games are expensive, storage is cheap). 

I was just about to update the post to mention that some other DLC TMDs do verify. HWL (0017ea00), e.g.

**Comment by Targren** [comment]
I'm not sure, since I don't have a toolchain setup to compile it, but poking through the source I found this in tmd.h

    #define TMD_MAX_CONTENTS    (100+1) // theme CIAs contain maximum 100 themes + 1 index content

The DLC in question contains 139 .app objects in content/00000000/

I tested it on another DLC (000fd500, theatrythm final fantasy) that has 164 .app items, and that, too failed.

**Comment by d0k3** [comment]
Hey, good catch. You're most likely right about this. Can you try this test build?
https://transfer.sh/fA5lJ/godmode9-20170216-015040.zip

If it still does not work, I'd like to have a look at the .TMD file.

**Comment by Targren** [comment]
"Verification Success" - OK!

"CIA built to 0:/gm9out" - OK!

Re-Installation of generated CIA with FBI - OK! and confirmed working

Do you want me to add a related issue to the decrypt9WIP repo?

**Comment by d0k3** [comment]
Okay, I had a look in the D9 source code and it is not as easily fixable there. Meaning: I won't be able to fix this in a matter of minutes, like I did in GM9. if you can, open an issue in the D9 github repo.

Also, thanks - your bug reports are always pretty useful and clear!
