### ISSUE TITLE
[Question] FBI TitleDB GodMode9 CIA Listed?

### ISSUE THREAD

**Issue by RinMaru** [d0k3/GodMode9#250]
There's a CIA version of GodMode9 listed on FBI's TitleDB and i'm not sure if its legit or not because there's no repositories on your account of a CIA version. It even says you're the developer of it, so im wanting to be sure its not a hoax and its official.

**Comment by d0k3** [comment]
Yup that's fine, you should read the release notes / readme, though. 
https://github.com/Ordim3n/A9SP/releases
