### ISSUE TITLE
[Question] What's an QLZ file and how do i edit it?

### ISSUE THREAD

**Issue by Hotbrawl20** [d0k3/GodMode9#252]
I want to make another banner for a fork of Godmode9. I dont know how to make the qlz file tho.

**Comment by eiiiiix** [comment]
I was asking the same question over on gbatemp and discord, I was told to use quickqlz which is a linux tool

**Comment by urherenow** [comment]
GitHub isn't a support forum. This space is to report bugs. Google WSL or LXSS and use the Linux tool.

**Comment by urherenow** [comment]
Then again, building FBI gives you bannertool In the buildtools directory...

**Comment by d0k3** [comment]
@urherenow - that question is okay here. It's development related after all.

@Hotbrawl20 / @eiiiiix - try this package:
https://transfer.sh/x1au8/splashconv.7z

You need [ImageMagick](http://www.imagemagick.org/script/index.php) installed. Use `imconv [image file]`. Image file can be in any format, PNG is recommended.
