### ISSUE TITLE
Suggestion:Use FSID DAh for created EMUNAND partitions

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#253]
When you create a new Gateway EMUNAND, the FSID in the partition table for EMUNAND data is 1Ch (Hidden LBA W95 FAT32), which some systems, especially some older mobile phones, still think that it is a valid FAT and try to mount and "fix" it, thus screwing everything up.
My suggestion is to change the FSID to DAh (Non-FS data), so those devices do not (mis-)detect that partition.

**Comment by d0k3** [comment]
You may actually got a valid point here. I'm going to discuss this and think about it for a bit, alright? In the meantime, other opinions are welcome.

**Comment by pthfdr-42** [comment]
I have done it manually with Linux `fdisk` and it works as normal.

    Disk /dev/sde: 29.7 GiB, 31914983424 bytes, 62333952 sectors
    Units: sectors of 1 * 512 = 512 bytes
    Sector size (logical/physical): 512 bytes / 512 bytes
    I/O size (minimum/optimal): 512 bytes / 512 bytes
    Disklabel type: dos
    Disk identifier: 0x71c7099b
    
    Device     Boot   Start      End  Sectors  Size Id Type
    /dev/sde1       1933312 62333951 60400640 28.8G  c W95 FAT32 (LBA)
    /dev/sde2  *          1  1931264  1931264  943M da Non-FS data
    
    Partition table entries are not in disk order.
