### ISSUE TITLE
Bug: RTC not setting chosen time

### ISSUE THREAD

**Issue by sebastienrouget** [d0k3/GodMode9#254]
While upgrading from A9LH to B9S, I used the RTC Set feature and chose 2017/11/03 10:21:51. At the then end of Plailect's Guide, I rebooted the console, and the date was 2033/08/17 4:_xx_ (can't remember the exact minutes).

I have a old 3DS XL.

**Comment by d0k3** [comment]
-_-

You missed the hint about setting the system clock after the RTC clock both in GM9 and in the GM9 readme.

So fix your system OS clock once, maybe?

**Comment by sebastienrouget** [comment]
I missed it...
