### ISSUE TITLE
Suggestion:Allow the user to change screen colors

### ISSUE THREAD

**Issue by SSQ123** [d0k3/GodMode9#255]
I just wanted to ask if you could someday allow the user to change the display colors for the EixMode9 UI and Hex editor.

**Comment by d0k3** [comment]
This is not the EixMode9 repo. And, colors can be changed via source code changes (ui.h and godmode.h). No way to let the user do that. You need to recompile.

**Comment by SSQ123** [comment]
Oops. Wrong thread. Sorry. XD
