### ISSUE TITLE
0:/gm9/script...rnand_luma3ds.gm9 line2: unknow cmd

### ISSUE THREAD

**Issue by vincthedwarf** [d0k3/GodMode9#256]
Dear Github members,

Followed that guide for a 2ds installation:

https://3ds.guide/finalizing-setup

**Section VI - CTRNAND Luma3DS**

1. Launch GodMode9 by holding (Start) during boot
2. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has completed
3. If you are prompted to fix the RTC date&time, press (A) to do so, then set the date and time, then press (A) to continue
4. Note that, if you had to fix the RTC date and time, you will have to fix the time in the System Settings as well after this guide
5. Press (Home) to bring up the action menu
6. Select “Scripts…”
7. Select “setup_ctrnand_luma3ds”
8. When prompted, press (A) to proceed

**And got that error:**

`0:/gm9/script...rnand_luma3ds.gm9 line2: unknow cmd`

Downloaded the script from:
[https://3ds.guide/gm9_scripts/setup_ctrnand_luma3ds.gm9](url)

**Here is the code that I have:**

`# Luma3DS CTRNAND Setup script`
`# last changed: 20170716`
`# author: ihaveamac`
`set SUCCESSMSG "Luma3DS copied successfully"`
`ask "This will copy Luma3DS to your CTRNAND,\nallowing for the system to work without\nan SD card.\n\nContinue?"`
`allow 1:/`
`# remove existing files just in case`
`rm -o -s 1:/boot.firm`
`rm -o -s 1:/rw/luma`
`# copy specific files over`
`cp 0:/boot.firm 1:/boot.firm`
`mkdir 1:/rw/luma`
`cp 0:/luma/payloads 1:/rw/luma/payloads`
`cp 0:/luma/config.bin 1:/rw/luma/config.bin`

Any help would be much appreciated.

Bests regards.

Vinc

**Comment by d0k3** [comment]
I actually don't own Github, as much as I have a Facebook account and don't own Facebook 📦 

Let me guess, you did the copying on a Mac? Macs do write garbage files when writing stuff to external memory. 

Try the most recent nightly from here:
https://d0k3.secretalgorithm.com/
... and tell me if that solves it for you.

**Comment by jacopouggeri** [comment]
Thank's a lot this worked!
