### ISSUE TITLE
Bug: Brightness not adjusted mid-operation

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#259]
Hello @d0k3 . I come to tell you of another issue.
(On the latest version) while an operation is underway (i.e. backing up nand or something that involves progress bars), using the Sound slider to adjust the brightness does not work. Once the operation is completed, the brightness automatically jumps to where it should be. I assume this has to do with the fact that when an operation is underway, it does not check for inputs besides B. Anyways, just wanted to tell you. As aforementioned, tested on 1.4.3.

**Comment by DMSalesman** [comment]
Forgot to tell, but confirmed on older versions as well.

**Comment by d0k3** [comment]
Additional note: not a bug - we just can't always check the brightness slider whiel GM9 is busy with other stuff. I added the brightness check to the progress bar now, should already fix a lot of stuff.
