### ISSUE TITLE
Cannot build a cia from .3ds file on sd card 

### ISSUE THREAD

**Issue by Gadget72** [d0k3/GodMode9#260]
I am trying to build a cia from a .3ds (2.0GB) file installed on my SD directory.I cannot download a cia from the internet because the specific file i am trying to build is of an Alpha Sapphire rom hack. I navigated to the file on Godmode9 and chose to build cia from the file, but it instantly says CIA build failed. It wont let me decrypt the rom either. I even bought a new sd card since i thought it was a storage issue, but the problem remains. Is the problem with my console, firmware, rom, storage, or godmode9 build?  pls help

**Comment by d0k3** [comment]
Update to the most recent version of GM9 and provide the aeskeydb.bin I recommend.

However, it is very likely that .3ds file is broken. So, doublecheck that, too.

**Comment by Gadget72** [comment]
Im using godmode9 v.1.4.3 and it still does not work. I added in the aeskeydb.bin, as well as seeddb.bin and enctitlekeys.bin. no luck. The .3ds file does not appear to be broken, since it can run on Citra. However, I downloaded a different .3ds rom (not a rom hack) and it is building the .cia just fine. My best guess is that I can't build the .cia because it is a hacked rom or because the rom is decrypted. I tried encrypting the rom with GodMode9 but nothing works with it. Any more advice?

**Comment by d0k3** [comment]
The .3ds file is broken almost for sure. just not in a part Citra cares for. GM9 has no trouble handling decrypted .3ds (would be strange if it would, right?).

Can you mount the .3ds file and try CIA conversion on content0?

Also, if you reall want to find out what's wrong there, we'd need to know what exactl is changed by the ROM hack. Maybe you can get some useful info out of ctrtool (compare original and hacked).

**Comment by d0k3** [comment]
Okay, @Gadget72 - I need more info, otherwise I need to assume some error on your side and close this issue. Did you get it fixed?

**Comment by d0k3** [comment]
Alright, I'm closing this. @Gadget72 - feel free to reopen if you can add info and feel that this is not resolved.

**Comment by Pokegirl1124** [comment]
I have the very same issue and cannot find a solution anywhere. Please help!

**Comment by d0k3** [comment]
@Pokegirl1124 - try verifying that file in GM9, it will most likely not work. You decrypted that file using some outdated method, on your PC, right?

**Comment by d0k3** [comment]
Okay, this misses info, assuming @Pokegirl1124 has sorted this out on her own. Closing this again now...

**Comment by hYdos** [comment]
this has just occured to me too

**Comment by hYdos** [comment]
im on the latest version

**Comment by hYdos** [comment]
i also just verified the .3ds and its a bad exefs header

**Comment by Gillogster** [comment]
Had this issue. Went to file info on 3ds file, it was set to read-only, disabled read-only, then verified and fixed the file, CIA conversion worked.

**Comment by d0k3** [comment]
Alright, that's a good thing @Gillogster - I'll reopen and fix it

**Comment by marinalunaterry** [comment]
I'm having this problem too. Pokemon X decrypted, works in Citra. I'm using a 256GB SD card.

**Comment by d0k3** [comment]
Okay, I just noticed what's really going on here. You guys are trying to build a CIA from a borked .3DS file (borked as in: decrypted by some tool that didn't do a clean job). I'll close this now. Verify your files, GM9 will offer fixing.

@marinalunaterry - so you couldn't build a CIA from gamecart? Check the remaining space on your SD cart. If it still doesn't work, five me some more info. What game cart is this about? Did you try to convert straight from the gamecart drive?

**Comment by sfranz2422** [comment]
I'm not getting an option to fix the file when I verify.  It just says verification failed.

**Comment by sfranz2422** [comment]
When I mount the image in Godmode and try to convert the content0 file it fails.  Then when I verify it does tell me bad header.  How do I fix that issue?

**Comment by deadpahn** [comment]
I also am running into an issue where I cant build from any of my gamecarts now. I was able too with a couple of games. Thought it might be a space issue but there is plenty left. I'm thinking that maybe the SD CARD is borked. I will copy my games off of it, format, move the files back, and try this all again.

**Comment by mr2meowsYT** [comment]
i have enough space and it says the files good in verification but instantly fails when building a cia

**Comment by ash10121** [comment]
I know this is old ...but if it is stating that it verify the file but won't convert then go back to the root menu in godmode9 choose sd scroll to gm9 in and lick on the game you wish to choose ..then click file info and make sure read only is not crossed as this will stop it ...so then go back verify file and convert ..job done :)

**Comment by ash10121** [comment]
![1606592161689644536175005880625](https://user-images.githubusercontent.com/75103366/100524557-0eab1e80-31b1-11eb-885a-69ee2377ddd9.jpg)




Make sure this is not crossed off ..as this is the reason it fails
