### ISSUE TITLE
.code extract broken for Pokemon USUM?

### ISSUE THREAD

**Issue by exegg** [d0k3/GodMode9#264]
I tried to extract the .code from my UltraMoon install and it failed.

Tried both the 1.4.3 and the lastest hourly. I can extract the Sun version just fine.

Already played the game. My source was the preload from eShop servers.

![img_20171117_132957](https://user-images.githubusercontent.com/19347211/32960802-aa107b8c-cb9c-11e7-9cea-2765e1db4efd.jpg)

**Comment by exegg** [comment]
Also what is seen after I mount the game to a drive

![img_20171117_135827](https://user-images.githubusercontent.com/19347211/32961719-00bdc540-cba0-11e7-9232-67a4407e19b0.jpg)

**Comment by d0k3** [comment]
Good catch, I'll look into it.

**Comment by d0k3** [comment]
Hmm... Do you, by any chance, not have the seed for UM installed? Can you play the game? Get a new seeddb.bin (you'll know from where), then try again.

Can't test this myself, at least not until Monday, but I guess that's what went wrong.

**Comment by exegg** [comment]
Yes I have the seed for UM since I already had two hours playing. Figure, I generated a seeddb.bin from my console using this this https://github.com/d0k3/SEEDconv

Put it in the support folder, and I could extract the code.bin and when the game was mounted I could access the romfs and exefs folders.

**Comment by d0k3** [comment]
Dammit... If that worked, GM9 should have been able to pull the seed from there on itself...

Any chance you can provide me with that file (the save, not the seeddb.bin to have a look?)

**Comment by exegg** [comment]
Sure man. Just tell me where to send it to you.

**Comment by d0k3** [comment]
Either get in touch on GBAtemp or via IRC (freenode #Cakey works, and that's quick, without any registration).

**Comment by exegg** [comment]
Just wrote you on GBAtemp. Inochi.no.zenmai is my user there

**Comment by d0k3** [comment]
Alright, got it. I may already have a clue what happens here, but won't be a quick fix. Leaving that open until we got at least a proper workaround.

**Comment by exegg** [comment]
That'll be fine man! You think this is a general issue or just my console misbehaving?

**Comment by d0k3** [comment]
General issue, just one that rarely happens. I'll see after a workaround, then ask you to test again (without the seeddb.bin you generated, ofc).

**Comment by d0k3** [comment]
Can you try this one?
https://f.secretalgorithm.com/i6hs1/godmode9-v1.4.3-32-gffc053a6-20171120001959.zip

It's a workaround, it's not perfect (a better one will eventually be coming). It should solve your issue though.

**Comment by exegg** [comment]
Tried that last one without the seeddb.bin and worked fine!

**Comment by d0k3** [comment]
Great, closing this now. An even better method may be coming, but for now that workaround should have everyone covered.
