### ISSUE TITLE
Character entry suggestion.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#265]
I find the current way to enter characters (filenames etc.) is too inconvenient and slow.
My suggestion is to use a keyboard similar to the name entry in RPGs, (where you use the D-pad to select letters, A to input, B to erase, and Start key to confirm,) which is still slow but more tolerable.

**Comment by SirNapkin1334** [comment]
Yes, I would love this to be implemented. If possible, a touchscreen keyboard would be even better.

**Comment by d0k3** [comment]
Added the label cause I'm still thinking about this. You may underestimate it - depending on what is entered, GM9 only provides the chars that fit, and that will be very difficult to do via a keyboard layout. So, no guarantees. Need to think about it some more.

**Comment by pthfdr-42** [comment]
>provide chars that fit
Just hide the unavailable ones.

**Comment by d0k3** [comment]
Well, to be blunt, when used correctly, the current system is not slower than a DPAD based keyboard. You know you can hold R to accelerate the scrolling? It requires some getting used to, of course. What I'm considering now is some kind of preview of the available chars (what you get if you press DOWN / UP or R+DOWN / R+UP).

**Comment by SirNapkin1334** [comment]
@d0k3 I'm still a bit confused about "Characters that fit." What do you mean by this?
Also, I spent about 5 minutes retyping the two ID's of the Nintendo 3DS folder, so maybe add the option to set the name to common things, like those ids, or title ids, etc, or be able to select a file and use that file's name without copying the file.

**Comment by d0k3** [comment]
https://github.com/d0k3/GodMode9/commit/973fef9eafe019856039bd22ca62eb65df70339f adds a 'alphabet preview' to the string input tool. Using this, in conjunction with the R + DPAD fast scroll, the input should be as fast, if not faster than a standard DPAD type "name entry" keyboard. Closing this now.

@SirNapkin1334 - I get your point about the file names, but this would again make things more complicated. You have to keep in mind that a DPAD / buttons based UI such as GM9 has it's limitations, and some stuff is better done via a proper keyboard, on a computer.

**Comment by SirNapkin1334** [comment]
Are arm11 payloads unable to use the touchscreen? Or is it too complicated to program just for a keyboard?
