### ISSUE TITLE
Delete/Modify SecureInfo_C on CTRTransfer

### ISSUE THREAD

**Issue by olliz0r** [d0k3/GodMode9#267]
Godmode9 creates a SecureInfo_C when ctrtransfering with a out-of-region image. However, when ctrtransfering back to the original region it does not check/delete/modify a possibly existing SecureInfo_C. The result is a kernel panic on boot (check: https://cdn.discordapp.com/attachments/196635695958196224/383284321424900108/20171124_005358.jpg as an example)

A solution would be to check for the existence of the file before the ctrnand and either deleting it or modifying its region to fit the new image.

**Comment by d0k3** [comment]
I need to confirm this...

In the case of transfering back to the original region, the SecureInfo_C is left as is, in turn leading to Luma assuming the wrong region, correct?

That should be easily fixed by just deleting the SecureInfo_C right at the beginning.

**Comment by d0k3** [comment]
Okay, confirmed it myself. Yup, that was a bug. Please test if you can!

**Comment by SirNapkin1334** [comment]
Odd, I CTRTransfered my 3DSXL back to U (had changed it to E) just after Christmas, and it's still stuck with SecureInfo_C.

**Comment by d0k3** [comment]
You may have used an outdated version... You can retry if you want.
