### ISSUE TITLE
Suggestion:Directly show voltages/percentages instead of battery icon.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#272]
As the title says.No offense intended.
If you can get the exact number of how much battery power is left, then why don't you just show it directly?
If someone is using this firmware and know how to operate it, then he certainly can understand the numbers.
Also, the icon's width is not a multiple of font width, thus makes the title bar not aligned with the file list.

**Comment by d0k3** [comment]
Nope, I only get the percentage from the MCU. Even if I had the choice I'd opt for that, though.

Alignment: yup, but that's a non issue.
