### ISSUE TITLE
Feature Request: Display free space & check for free space before dump

### ISSUE THREAD

**Issue by Flauscheloni** [d0k3/GodMode9#281]
I'd be lying if I said it happened only once, but yet again I was dumping a title and I was sure it was going to fit on the SD card, but _it didn't._ Meaning I waited for about half an hour for the dump to finish when at the last second it canceled. That's a bit annoying and admittedly I could have double-checked if it would fit on the SD card, but who does that and why couldn't GM9 throw me a quick reminder that I'm going to waste 30 minutes for nothing?

So I would suggest 2 things:
- display the available free space of the SD card (it displays max. capacity already and if I check the SD card it will show the used up space, but not the free space)
- run a quick check before a dump to see if the available free space is sufficient for the dump and if not, give a quick notification that there's insufficient space and don't even start dumping.

I hope it's not a huge issue to implement this functionality and that you find this useful as well.
Thanks

**Comment by SirNapkin1334** [comment]
Only problem, is sometimes it's hard to calculate precisely how big a dump will be. It'll probably be reasonably accurate, but if it just barely fits on it might not calculate it correctly.

**Comment by Flauscheloni** [comment]
I'd rather have GM9 tell me "Warning, game dump might not fit on SD card. (Game size: 3.5GB Available space: 3.6GB) Do you really wish to proceed?" than wait for a long time and have it fail regardless.
I'm not saying a database should be maintained where dump sizes are recorded and compared, that would mean either internet access or a copy stored in a file on the SD, that's a bit much. (Although I'm sure such a database probably exists or that one datapoint could be added to an existing one)
At the very least it could tell me again how much space is left before I ultimately let it dump, often you know what kind of title you are ripping and if it's in the "few/dozens/hundreds MB" range that you can fit in on the remaining say 2 GB or if it's a "gigabyte/s" title where you need to look closely.

**Comment by d0k3** [comment]
It's actually not really easy to tell how much space will be needed before doing that. A warning if it *may* not fit is also ugly, and so is just starting the process with no idea if it will fit. You can always check your free space via the drive info, ofc (R+A on a drive of your choosing).

We will not always display free space, that was how it was before and it lead to huge boot delays. Even a proper check will take long. Let me think about that one for a bit, will ya?

**Comment by SirNapkin1334** [comment]
Yeah, with people with big SD cards, it takes at least 5, often more seconds to analyze my 64GB SD card. Think of the people with 128GB cards, I mean, my Wii U has a 128GB, and vWii takes almost a minute to analyze it and calculate the number of blocks available in the Data Management section.

**Comment by d0k3** [comment]
Okay - there can't be a real proper solution to this. Commit https://github.com/d0k3/GodMode9/commit/b5a0f6cfcff969d3f6af3b5935771afc5c637736 tries to catch low space on game crypto and CIA build operations, and it should be succesful most of the time.

You may notice a slight delay before the actual operations starts now, the operation itself will actually be a bit faster than before. @Flauscheloni - can you please test this?

**Comment by Flauscheloni** [comment]
Hey, I'd sure test it but I need this precompiled (I don't know why but setting up devkitARM and other environment variables never worked for me on my Mac and at the moment I don't have another machine available)

**Comment by d0k3** [comment]
Alright, here's a test build:
https://f.secretalgorithm.com/CK6F0/godmode9-v1.4.3-78-gb5a0f6cf-20171228152901.zip

This should fail quickly in cases where there is not enough space available. It will not work in case of exceptional bad luck (cause, as I said, can't estimate the required space correctly).

**Comment by SirNapkin1334** [comment]
I would test it, but I don't have any SD's big enough to fit all my data but small enough to run into these kinds of errors.

**Comment by Flauscheloni** [comment]
Thanks a lot, I will look into it when I get home to my 3DS, maybe tonight already.

@SirNapkin1334 you could always fill your SD card with some big files to restrict your capacity ;)

**Comment by d0k3** [comment]
The modifications required for this were actually what caused that other bug (and that other bug is what forces me to do a release now, ugh). Anyways, should work fine. @Flauscheloni - if you think the change does not work for you, feel free to reopen.
