### ISSUE TITLE
S:\essential.exef does not update

### ISSUE THREAD

**Issue by Kalanyr** [d0k3/GodMode9#283]
This may be me missing something obvious or a misunderstanding on my appear but it appears that essential.exef cannot be recreated/updated after it's initially created, this is a problem if eg you've done a system transfer and now have a different moveable.sed  (both on the source and target,  the source because if you wish to sell the system you probably don't want them to have access to your moveable.sed and the target because it gives a backup with the wrong moveable.sed). 

I suggest an option in S:\essential.exef to rebuild essential.exef with the current files.

**Comment by d0k3** [comment]
It's doubtful this is a good idea... you know, that backup is for keeping, and a user may do later edits to their header, `SecureInfo_A`, etc... which they may not want in that one backup.

As for selling, don't worry - that one part of `movable.sed`  does not contain any private data or even data that is useful without the exact SD card data that it created. Also, needless to say, but the `essential.exefs` is meant as a last resort backup.

You can already update the backup, it's in the options for `S:/nand.bin`, though. Thinking if I may make that easier, but honestly having my doubts there.

**Comment by Kalanyr** [comment]
I had the same thoughts about people updating it after changing things
after I posted and it does make it very tricky.

I'm happy to hear that it doesn't contain any private data, that eliminates
the risks beyond potentially being unable to read the new SD card but I'd
hope people take a new SysNAND backup in such cases anyway.

I was wondering what that option did and had guessed it updated the
embedded essential backup in the SysNAND but your explanation makes more
sense.

On 27 Dec. 2017 13:34, "d0k3" <notifications@github.com> wrote:

It's doubtful this is a good idea... you know, that backup is for keeping,
and a user may do later edits to their header, SecureInfo_A, etc... which
they may not want in that one backup.

As for selling, don't worry - that one part of movable.sed does not contain
any private data or even data that is useful without the exact SD card data
that it created. Also, needless to say, but the essential.exefs is meant as
a last resort backup.

You can already update the backup, it's in the options for S:/nand.bin,
though. Thinking if I may make that easier, but honestly having my doubts
there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/d0k3/GodMode9/issues/283#issuecomment-354045905>, or mute
the thread

**Comment by d0k3** [comment]
After thinking this through thoroughly: I won't provide a more convenient way of updating the essential backup, cause that will only encourage people to update frequently (which we don't want). I instead added a hint on how to do it to the readme: https://github.com/d0k3/GodMode9/commit/28ba5a85b3c64d2944d6844aa55d71da061fc87f

As for the `movable.sed` - I actually thought about resetting it to factory state before adding it to the essential backup, or leaving it out (cause you can totally rebuild your factory state `movable.sed` from the `LocalFriendCodeSeed`). Guess that would help no one, though. Anyways, closing this now...
