### ISSUE TITLE
Key Functions in Bootloader Menu

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#284]
During bootloader mode, it'd be nice to have more key functions in the menu. You can already press B to power off, but I think you should also be able to press START to reboot, and X to boot GM9. Just some small suggestions. Also, don't you think we should have a minor suggestion Megathread? Like #752 for Luma3DS.

**Comment by d0k3** [comment]
While this is not a bad idea per se, implementing it woudl require far more effort than the possible gain. Anyways, rebooting from the boot menu makes no sense - you want to continue the bootloader? Then just select the menu entry and press A.

I did, however switch the positions of the bootloader and GodMode9 entries in the menu, figuring that, if you went to the bootmenu, you're more likely to want to boot into GM9 than just continue.

Re megathread: Better not. That would only lead to more hard to track bugs and ideas. Also, users can't really estimate how hard it is to implement something most of the time. So, 'minor suggestion' is relative.

**Comment by SirNapkin1334** [comment]
@d0k3 Then why is there the option to reboot from the bootloader anyways?

**Comment by urherenow** [comment]
Huh? Rebooting from the bootloader would just boot the bootloader. What's the point in that? The option is to choose which .firm file the bootloader should boot.

**Comment by SirNapkin1334** [comment]
Precisely.

**Comment by urherenow** [comment]
Anyway @SirNapkin1334 just use fastboot3DS instead of boot9strap or GM9. I'm pretty sure you'll end up with exactly what you want.

**Comment by SirNapkin1334** [comment]
Nah, I like GM9 best. Kinda attached to it, and the bootloader menu is useful.

**Comment by d0k3** [comment]
You got somewhat of a point regarding the reboot entr in the menu. It is useful in one case, though. Assuming you had a FIRM in FCRAM (put there by [A9NC](https://github.com/d0k3/A9NC)), `Continue bootloader` would boot that FIRM, while `Reboot` would clear that FIRM and start fresh.
