### ISSUE TITLE
3DS freezes when building .cia file

### ISSUE THREAD

**Issue by Juaner33** [d0k3/GodMode9#286]
I'm trying to build a .cia from a .3ds file, but every time I try, it just freezes at some point (the ETA stops decreasing and the % stops increasing).
I'm using a 3DS XL and firmware version 11.6.0-39E.

**Comment by d0k3** [comment]
What version of GodMode9 are you using? Can you try the most recent nightly from here:
https://d0k3.secretalgorithm.com/
... then tell me if something changed.

Also check your SD card for problems and enough space.

**Comment by Juaner33** [comment]
I've checked the SD card with h2testw and it says everything's okay, so I'm going to blame the SD card's capacity (4 GB, and the .3ds file was 2 GB).
The only game I tried was a hack of Pokémon Alpha Sapphire.
I'll try with a larger SD card as soon as I have one (hopefully soon).

**Comment by d0k3** [comment]
This can't have anything to do with the SD card size - if the card is full, CIA building simply stops. You should try the latest nightly, or the next release (which will be coming soon).

**Comment by d0k3** [comment]
@Juaner33 - can you maybe try the latest release and tell me if the problem still happens? As I said, doesn't look like the SD cards capacity is to blame.

**Comment by SirNapkin1334** [comment]
I will test this when I get home.

**Comment by d0k3** [comment]
I don't want to nag, but I also want to get this issue solved... soooo... had a chance to test it?

**Comment by SirNapkin1334** [comment]
Sorry! I have been unable to test this due to homework, and issues with my 2DS. I will hopefully be able to test it Tuesday subevening.

**Comment by SirNapkin1334** [comment]
Tested on Old 3DS XL
Used Mario Kart 8 .3ds from cart.
64GB SDXC Card
Results:
Success.

**Comment by SirNapkin1334** [comment]
Likely an SD issue for him. If you want, I can test it on a 4GB SD card.

**Comment by SirNapkin1334** [comment]
Tested on half-full 4GB, built fine, but when it was about 5 minutes away from being done, the bar flashed, a few times, and then the ETA changed to 0 and started counting up, a bit slower than usual I think, and when it got to about 6, it said CIA Build Success. Odd.

**Comment by d0k3** [comment]
Not neccesarily a problem... have you tested the resulting file? Verified it in GM9 and maybe installed in FBI?

**Comment by SirNapkin1334** [comment]
Verification success. Didn't install in FBI though, since I used MK7 and it would just reinstall and I would have to redo savedata and .trim.3ds files already take a long time to install.

**Comment by d0k3** [comment]
Alright, I'm assuming this solved or another case of SD failure. @Juaner33 - if you still have that issue or can add to it, feel free to reopen. @SirNapkin1334 - thank you for testing!

**Comment by SirNapkin1334** [comment]
No problem! Happy to help test! @d0k3 I'd gladly test stuff before it was added if you're implementing something and your not sure of the safety. I am the prime tester for installing stuff to FIRM partitions!
