### ISSUE TITLE
Feature Request - "filesel" but for folders

### ISSUE THREAD

**Issue by Uupo03** [d0k3/GodMode9#287]
I need this for a script im making, it would work the same as filesel but would allow the user to select folders.

**Comment by d0k3** [comment]
Well... would it help to be able to display files & folders? That's pretty easily done.

**Comment by Uupo03** [comment]
Yes, that will work too :)

**Comment by d0k3** [comment]
Tadaa, have your `dirsel` command. Looking forward to all the stuff you guys will do with the new possibilities.
