### ISSUE TITLE
Feature Request : Verify match of serial number before nand image restore

### ISSUE THREAD

**Issue by deadair3210** [d0k3/GodMode9#288]
Was wondering if it would be possible to modify the restore scripts for nand image restores to check the serial of the current device matches the serial of the nand image, since it is recorded in the filename. Could help cut down on accidental bricks

**Comment by d0k3** [comment]
Bad idea. Have you ever tried restoring a NAND backup from another console? That's not possible cause the *console unique crypto* is checked. Checking the serial is a bad idea in itself cause that can be changed. Closing this now...
