### ISSUE TITLE
Feature Request : Add a way to revert bonus drive to stock

### ISSUE THREAD

**Issue by deadair3210** [d0k3/GodMode9#289]
Sending my 3DS in for repair and trying to remove as much chance of Big N seeing anything weird and throwing it out of warrenty. Do we have to remove the Bonus Drive or is there even a way to? Also, would you recommend doing anything else other than running your remove_cfw script

**Comment by d0k3** [comment]
I'll tell you what I tell everyone in your position - *everyone* should have a backup of their NAND (full size recommended) of an as-close-to-original-as-possible state. If that backup is done right after the b9s / fb3ds install, that's fine, the removal script will take care of it.

If you don't have such a backup, you'd have to blank sectors 0x01...0x95 (and sector 0x96 on O3DS! only), and everything behind the NAND min backup. I'll see about adding something to scripting, so a script author can take care of that.

**Comment by d0k3** [comment]
Okay, with the new `fill` command I introduced to scripting, it is possible to automate what I mentioned above. If you don't have a original NAND backup of your console, I suggest you ask in the GM9 thread, or in some GM9 scripts thread. Closing this now....
