### ISSUE TITLE
Cart to CIA fails

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#290]
A user on the 3dshacks [posted](https://www.reddit.com/r/3dshacks/comments/7lyszw/3ds_hacking_qa_general_itsudatte_my_santa_edition/drz7djz/) an issue regarding a cart dump > CIA failing. They downgraded back to 1.4.3 to get the issue resolved. Here are more details:

The test cart is Link Between Worlds. Have not tested with other carts yet.

Copied the 3ds to the SD. The trimmed version, and, thus, the CIA, are about 700 MB. Creating a CIA yields a file that is about double what it should be (1.3 GB). Mounting the CIA works and looks *mostly* normal; the 0001.00000001.app (the manual) is not decrypted. The file fails to verify. In addition, attempting to show the title info causes a crash of godmode9. The exception dump is below.

Exception: Data Abort (4)
2017-12-31 22:19:40

R00: 000000FF | R01: 00000000
R02: 00000007 | R03: 984869BA
R04: 00000000 | R05: 00000001
R06: 00000000 | R07: 00000000
R08: 000000FF | R09: 984869BA
R10: 2277F23F | R11: 00000000
R12: FFFFFFFF | R13: 2277F1B0
R14: 00000017 | R15: 08006BFA
CPSR: 000000FF

Stack dump:
2277F1B0: 00 00 00 00 FF 00 EF FF 00 00 00 00 54 0E 04 08 
2277F1C0: 01 00 00 00 FF FF FF FF 00 00 00 00 3F F2 77 22 
2277F1D0: 17 00 00 00 29 F2 77 22 58 00 00 00 00 70 47 18 
2277F1E0: 31 00 00 80 9D 6C 00 08 FF FF FF FF 00 00 00 00 
2277F1F0: 00 02 00 00 58 00 00 00 00 70 47 18 3C 02 00 20 
2277F200: 00 00 00 00 31 00 00 80 90 64 04 08 00 00 00 00 

Code dump:
08006BC0: 9A03 464B 5DD4 2207 E00B 4641 7059 4661 
08006BD0: 7018 7099 21B4 0089 468A 3A01 4453 2A01 
08006BE0: D013 0021 4111 420D D1EF 9901 428E D0F1 
08006BF0: 4659 7019 4669 7A09 3A01 7059 21B4 0089 
08006C00: 468A 709E 4453 2A01 D1EB 2303 425B 469A 
08006C10: 3701 44D1 2F0A D1D3 B005 BC3C 4690 4699

**Comment by d0k3** [comment]
Okay, should be fixed in the latest commit, here's a testbuild to try (testing appreciated):
https://f.secretalgorithm.com/10I4BJ/godmode9-v1.5.0-3-g0dd72ceb-20180101214052.zip

**Comment by CecilFF4** [comment]
Looks good! Thanks!
