### ISSUE TITLE
Allow mounting of enc/decTitleKeys.bins

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#291]
I'd be nice to be able to mount enc/decTitleKeys.bin files, to take a look at all the title keys inside. Like ticket.db or aeskeydb.bin mounting. You should also be able to inject new keys via this, or allow you to inject an enc/decTitleKeys.bin file into another, where it will combine them, and add any new keys found in only one.

**Comment by windows-server-2003** [comment]
Mounting? Already implemented. If you can't, your file is broken.

@d0k3 
1:/rw/gm9 for everything the same as 0:/gm9 maybe ?

**Comment by SirNapkin1334** [comment]
You can't mount titlekeys. Titlekey Options -> You can only build an enc or dec title key.

**Comment by windows-server-2003** [comment]
Oh, sorry

**Comment by d0k3** [comment]
@windows-server-2003 - `1:/gm9` already works for everything but the `out` path (there are good reasons not to support this on drives with limited space). Just try it.

@SirNapkin1334 - yup, can't mount this. Doesn't make much sense for several reasons. For once, there is nothing much you can do with the titlekeys. Also, the typical size of such a database (= containing thousands of titlekeys) breaks the GM9 limit of displayable entries (that's 1024) and it makes little sense to lift the limit for this. Won't be supported, closing this now.

**Comment by windows-server-2003** [comment]
Wow, nice...

**Comment by SirNapkin1334** [comment]
@d0k3 will injecting an enc/decTitleKeys file into another (of the same kind, i.e. enc -> enc) combine the keys inside? If not, you should add that, as that would would be helpful.
