### ISSUE TITLE
make SCRIPT_RUNNER=1 issue

### ISSUE THREAD

**Issue by IvanMolina99** [d0k3/GodMode9#294]
Hi d0k3!

Since the latest commits, I have a problem when i'm trying to compile the autorun.gm9

I set the make SCRIPT_RUNNER = 1 , but it always throw this error message at the same point
What should I do exactly?  

Thanks for your attention!
![img_20180113_234210](https://user-images.githubusercontent.com/17816606/34941102-965f442c-f9f2-11e7-84b6-c6fc80d9982f.jpg)

**Comment by d0k3** [comment]
The problem is known as '@d0k3 not paying attention'. Anyways, fixed!
