### ISSUE TITLE
Buggy CMAC fix on empty drive

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#295]
So, I broke my N2DSXL's screen, so I restored the NAND backup that I made before I turned it on (lol booted into GM9 w/ NTRBoot before I even booted into initial setup), and decided to try to fix the CMACs for all the drives (to make the system as unsuspicious as possible, in terms of software), CTRNAND was fine, but when I tried to fix [A:] SYSNAND SD, it got interesting. [A:] Has no files in it (I switched SD cards to my 64GB before I even turned the system on), so when attempting to fix the CMACs, it goes to [root], and it's like nothing happened, except on the bottom screen, along with the button combos and drive data on top, in the middle (above the button combos), it says:
```
[A:] SYSNAND SD
Fixing CMACs for drive...
```
Just floating there, in white text. Doing anything (enter drive, switch pane, drive options, unmount SD, bring up HOME menu) will cause it to go away. Image:

Edit: Due to 7zip being a completely useless program and not actually compressing my files, I can't upload anything here.

**Comment by d0k3** [comment]
Fixed. I still wonder how that drive could even mount to `A:/`. I'm assuming there's an empty dir there.

**Comment by SirNapkin1334** [comment]
Also, I tested it on another system (Old 3DSXL I believe) and this also happened on [A:], even though it wasn't empty (I believe), so I think that this is just a general bug with [A:]

**Comment by d0k3** [comment]
Yeah, I had a look. Apparently it always worked, but the output on screen wasn't perfect. I amde another commit to make it looks a little better.
