### ISSUE TITLE
[REQUEST] Hide 'Press B' in operations when disallowed

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#297]
The title says it. When an operation is under way and the --no_cancel/-n switch is in effect, then the "Press B to cancel" text under the progress bar should not be shown, to make it a bit more obvious. You could also then remove the "B button disallowed (or whatever the prompt says" prompt, or have it say "Cancel Disallowed" for a moment underneath the progress bar when you press the button. Just a minor request, but it would look better IMO.

**Comment by d0k3** [comment]
That would require too much effort for what can - at best - count as a minor cosmetic issue. You already get a prompt about cancel being not allowed. Closing this now...
