### ISSUE TITLE
[URGENT] NEWEST COMMIT (PERM)BRICKED ME!!!!!!

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#298]
Okay, this is urgent. I just compiled the newest commit, and installed it to SysNand. This somehow broke my 3DS. Now, when I turn it on, the system turns on for a fraction of a second and then turns off. Tried to boot into chainloader/boot menu, no avail. It doesn't even boot far enough to perform NTRBoot! Seriously, this is BAD. I have NO WAY of restoring my NAND besides a hardmod, and the people at bestbuy are gonna be awfully suspicious. The firm was verified. I have no idea what happened.
Literally, it had a successful install. Then, I rebooted, holding START, and I got a black screen. Now, it does not turn on. The thing that freaks me out is that I cannot NTRBoot. Is this an MCU brick? Or in that case, does the console not turn on? At this point, my only choice may be to have the system hardmodded, but still.... (I have a NAND backup). Please, help, @d0k3. I do not know what the problem is. No blue screen. I have no idea what's going on. If I can't find any answers here, I'll ask on GBATemp, if I can't get anything there, I'm going to have to have a hardmod done. I have no idea what's happening.
Clarification: firm partition is the earliest thing in the boot chain that can be influenced?
Again, what I've tried: Booting without SD, booting without Flashcart inserted (sometimes Flashcarts can cause glitches, happened to me once after I improperly flashed it (don't worry, it's fine now)), trying to use NTRBoot, trying to boot normally.
Since NTRBoot is not working, I think it's something far worse. Can someone provide an explanation/fix?

**Comment by SirNapkin1334** [comment]
Note: there were 10 items in VRAM on the FIRM I compiled, though it's under 3MB. Oversized VRAM would just result in a compile error, right?

**Comment by ihaveamac** [comment]
it is highly unlikely any of the recent commits would have caused a permanent brick. make sure your ntrboot cart works properly on another system.

**Comment by SirNapkin1334** [comment]
Alright. I'll see.

**Comment by SirNapkin1334** [comment]
Works fine on my brother's o3DSXL.

**Comment by SirNapkin1334** [comment]
And my testing o3DS.

**Comment by SirNapkin1334** [comment]
Here is the version of the repository that I cloned (newest commit) including all files still in vram, and built files in /output/
I built with `make SALTMODE=1`, my usual.
[GodMode9.zip](https://github.com/d0k3/GodMode9/files/1641636/GodMode9.zip)

**Comment by SirNapkin1334** [comment]
Okay. I'm a moron. Failed FIRM boot, and cart slot was dusty, so I couldn't use NTRBoot. No idea how it got dusty, but it worked. Thank you so much @ihaveamac.
