### ISSUE TITLE
Cannot make Sysnand or Emunand backup

### ISSUE THREAD

**Issue by ninkid** [d0k3/GodMode9#301]
The "scripts..." option doesn't appear for me.

**Comment by SirNapkin1334** [comment]
Where are your scripts? They should be under SD:/gm9/scripts
Make sure they have the .gm9 extension.

**Comment by SirNapkin1334** [comment]
You should also change the title to "No scripts option in HOME menu" since this is misleading.

**Comment by ninkid** [comment]
The scripts folder isn't there, I haven't created a scripts folder either. I only just got godmode9 algonside B9S

**Comment by SirNapkin1334** [comment]
![image](https://user-images.githubusercontent.com/31591796/35191046-08e6fca6-fe26-11e7-9c6f-779741c22026.png)
Please. Just look at the instructions again before making an issue.

**Comment by ninkid** [comment]
Thanks mate, I watched a video from Skullator and I don't think I was thinking straight. Massive legend, good night.
