### ISSUE TITLE
Add notice for missing/empty scripts folder

### ISSUE THREAD

**Issue by fox8091** [d0k3/GodMode9#302]
As many users post issues that resolve to an empty/missing script folder, perhaps give notice in those cases?

**Comment by SirNapkin1334** [comment]
Come on, it's not that difficult! You just have to read instructions!:
![image](https://user-images.githubusercontent.com/31591796/35191054-24a665bc-fe26-11e7-8fb4-21227361c8ad.png)

**Comment by fox8091** [comment]
Maybe not, but that doesn't change the fact that a large number of "issues" are simply user error.

**Comment by urherenow** [comment]
Useless. Doesn't take much more coding time to simply create the directory if it doesn't exist. Of course in this case, there would be no scripts to run and we'd be right back here with people complaining about the scripts menu being blank ¯\_(ツ)_/¯

**Comment by d0k3** [comment]
Oh well... One thing is for sure - I won't take away the possibility to run GM9 without the scripts folder and *I won't nag people for not having that folder*. What I could do is move the scripts folder to the `V:` drive, but you won't like this either, cause that will mean that no customizability is possible anymore.

So, what now? Will we need an actual installer for the gargantuan task of copying one .FIRM and one folder to the SD card? Will I need to simplify the already uber-simple quick setup instructions in the readme? I guess you notice the sarcasm here.

Only leaving this open in case some valid idea pops up here. Looking for a way to make noobs notice (and copy) that folder *without annoying advanced users*.

**Comment by fox8091** [comment]
How about always show the scripts menu option, and simply show a message that says "You have no scripts on your SD" or similar. Advanced users who don't want any scripts will know they don't have any, and just ignore it.
