### ISSUE TITLE
Searching ejected SD card

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#303]
It's possible to search the SD card, as you know. However, if you search the SD card, then exit to [root], then eject the SD card, the [Z:] drive is not unmounted. Then, if you attempt to open [Z:] while the SD card is not in,  it will say on the bottom screen:
```
Invalid directory object
(<A> to continue)
```
Then, if you press A, things get weird. Once you press it, your cursor will get moved to [1:], and pressing <A> to enter SYSNAND CTRNAND causes a weird, glitched prompt to appear on the lower screen:
```
1:
-> Open this folder
   Open containing folder

(<A> select, <B> cancel)
```
The selection cursor `->` appears on `Open this folder` by default, and can be moved between the two options like normal. However,  both of the two options do the same thing, which is Opening the [1:] Drive. This is really weird, and I don't know why. Note: if you press any button after selecting [Z:] btu before selecting (including dpad) [1:] this glitch doesn't happen. It's weird.
So: if you search the SD card and unmount it, then the [Z:] drive should also be unmounted. Also, you should be able to manually unmount the [Z:] drive, perhaps by hovering over it and pressing R+A (pressing R+A on [Z:] does the same thing as pressing A).

**Comment by SirNapkin1334** [comment]
Oops, I accidently pressed enter while still in the title. Will be providing description shortly....

**Comment by d0k3** [comment]
Good catch, thank you!

**Comment by SirNapkin1334** [comment]
No problem! Happy to help!
