### ISSUE TITLE
large files freeze hex editor

### ISSUE THREAD

**Issue by eiiiiix** [d0k3/GodMode9#306]
files bigger than FFFFFFFF (I think 4,294,967,296 bytes) cause a freeze
a really interesting one too
you can exit the hex editor to unfreeze but whenever you open the file it moves to the end and freezes

**Comment by ihaveamac** [comment]
when would you encounter a file of this size though?

**Comment by d0k3** [comment]
Short answer: you don't cause it makes no sense. The 3DS OS can't deal with it.

If you absolutely must try this, you learn how FATFS works and edit the config.

**Comment by eiiiiix** [comment]
i was just fooling around with some stuff
i decided to make a 4gb dummy file so i could see how much randomisation goes into pulling bytes from other files but when i opened it it froze the hex editor

**Comment by ihaveamac** [comment]
but you can't actually have a file on fat32 larger than 0xFFFFFFFF (4,294,967,295 bytes), so...

**Comment by d0k3** [comment]
I guess that means the problem exists with files almost 4GiB in size. @eiiiiix can you find out exactly how big that file was?

**Comment by eiiiiix** [comment]
4,294,967,295
