### ISSUE TITLE
[BUG] labelsel

### ISSUE THREAD

**Issue by annson24** [d0k3/GodMode9#308]
Labelsel nesting bug.

The first labelsel menu will display one item (in random characters) that isn't supposed to be displayed on top of the selections, and it doesn't do anything also. Sub-menu on the other hand works just fine without the extra item.

```
@MainMenu
labelsel -s -o "Main Menu" MainMenu_*
goto MainMenu

@MainMenu_Option1
labelsel -s -o "Option 1 Sub-Menu" MainMenu_Option1_*
goto MainMenu

@MainMenu_Option1_A
echo "This is Option 1 A"
goto MainMenu_Option1

@MainMenu_Option1_B
echo "This is Option 1 B"
goto MainMenu_Option1

@MainMenu_Option2
echo "This is Option 2"
goto MainMenu

@MainMenu_Option3
echo "This is Option 3"
goto MainMenu

@MainMenu_Reboot
reboot

@MainMenu_Shutdown
poweroff
```

this will result in

```
**Main Menu**
[BUG]
Option1
Option2
Option3
Reboot
Shutdown
```

```
**Option 1 Sub-Menu**
A
B
```

EDIT: I think i figured out what's happening. The [BUG] item is actually the Main Menu item because the Main Menu's label partially matched its wildcard. But since it's only partially matching, this shouldn't be happening, right? Also, i think this bug has nothing to do with nesting at all, sorry.

**Comment by d0k3** [comment]
Great catch, thank you! I'll look into it later.

**Comment by d0k3** [comment]
... and fixed! Thank you again, that was one of these hard to find bugs. Testing is appreciated!

**Comment by annson24** [comment]
Tested and can confirm fixed. Thanks for your hard work.
