### ISSUE TITLE
Displayed Name mumbled up.

### ISSUE THREAD

**Issue by Nyquis** [d0k3/GodMode9#31]
In the latest commit of godmode9 where you have to select to build a legit or standard cia the displayed name gets mumbled up. 

This appears as well in the decryption view for a CIA where the options are given for decryption or encryption.

It seems that it is linked with special characters such as a . or a )

**Comment by d0k3** [comment]
Okay, I could actually reproduce this issue, thank you! I'll be looking into it, more later.
