### ISSUE TITLE
[Feature Request][Script]Multiple conditions in an 'if' command

### ISSUE THREAD

**Issue by annson24** [d0k3/GodMode9#310]
Is this possible?

```
if {condition 1; condition 2; condition N}
   command
else
   command
end
```

**Comment by d0k3** [comment]
Boolean operators for conditionals are not possible and will most likely never be. You can do if nesting, though:

`if condition 1
   if condition 2
      if condition 3
         command
      endif
   endif
endif`

I know this is not nice to look at, but with some smart coding something like the above should rarely be required.

**Comment by annson24** [comment]
That's actually what I did, was kinda hoping it'll be possible here, kek. Thanks anyway.
