### ISSUE TITLE
Special letters like é are not recognized

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#311]
I notice all my Pokémon games searched by tmd and built into CIA files lack the accented e. 
I tested all these letters on a renamed text file.

à è ì ò ù 
á é í ó ú ý
â ê î ô û 
ã ñ õ
ä ë ï ö ü ÿ

Does GodMode9 has the resolution to display these?

**Comment by SirNapkin1334** [comment]
No. Since d0k3 has to keep FAT compatibilty, he cannot display these characters. This is the reason for #57.
I suggest you close this.

**Comment by TurdPooCharger** [comment]
Okay, I'm closing this issue. Doing a quick title glance doesn't intuitively show others experiencing this phenomena.
