### ISSUE TITLE
Feature Request - Logging

### ISSUE THREAD

**Issue by annson24** [d0k3/GodMode9#312]
Is it possible to have an option to dump a log of all the commands, errors, etc. made in gm9? Just only during the duration that gm9 is running.

**Comment by d0k3** [comment]
This would require a lot of effort. While I do like the idea, I am unsure if it's worth it. Leaving this open for a few days to think about it.

**Comment by d0k3** [comment]
Okay, though about it, and it would take too much effort for the possible gain. It was not a bad idea, though. Closing this now...

**Comment by SirNapkin1334** [comment]
You could have the system try to generate a log file if the system notices that something is wrong.
