### ISSUE TITLE
MegaScript in official release

### ISSUE THREAD

**Issue by Leafgreen26** [d0k3/GodMode9#313]
Is it possible that you could incorporate the GM9 Megascript into official releases? Like, instead of all of the scripts in the gm9 folder it would just be the megascript. Even though GodMode9 can already do all of these things without the script, it would make things easier for noobs. You could even contribute to cleaning up/optmizing code (provided you have time).

**Comment by SirNapkin1334** [comment]
I think it should not be there instead of the regular scripts, but with them, or available within the .zip somewhere else.

**Comment by d0k3** [comment]
Well... unsure. As I stated earlier, I'm not adverse to the idea of adding more scripts to the official ones. These script should be well tested, stable and error resistant. A Megascript may be too much (being realistic here, the bigger it gets, the more likely it is something goes wrong). By your wording I also assume the script is still in development, so the answer may also be "later".

Sooo... can you provide a link and tell us what it does, and why we want it?

**Comment by Leafgreen26** [comment]
https://github.com/annson24/GM9Megascript/

It is basically a script that, when you use it, goes into a menu that has most gm9 scripts available (including ones in the official guide). Each script can then be used as normal. It is being updated constantly, but it is fully functioning, i.e. not in development. I have tested out every script and I haven't come across a problem yet (granted, I am only one person and I only tested out each script twice). I was just thinking using this script in the official release would be more of a quality of life thing.

**Comment by d0k3** [comment]
Okay, looks nice and clean. The only thing I notice on first glance is, the preview should not have just been set to off, but rather something else (some custom text or PCX graphic, looks better).

Still, @annson24 himself should have made the request. And, as I said, the answer may be "later". 

There are also other very advanced, very useful scripts that haven't made their way into the official GM9 scripts yet, either. @AnalogMan151's Lazarus3DS script for example, so it may make sense to think of several additions that could make it into the official GM9 repo.

**Comment by annson24** [comment]
I was actually planning on asking this but didn't feel that it's the right time yet. As @d0k3 said, some important scripts are still missing. I also think I can do a cleaner job with the script because honestly speaking, I'm in now way near being good with coding. I just saw the other scripts, saw the gm9's sample scripts and took a liking in making one. I'm no developer, I just thought it would be fun to try and next thing I know, I've already written 1000 lines. But that being said, I think in the near future I can do a much better job. When I feel it's ready, I'll give everybody a heads up. Thanks for suggesting this.

**Comment by d0k3** [comment]
Okay, alright. I'll be closing this now. @annson24 - we can talk about including this in the GM9 repo later, once you think it's in a somewhat "final" state. Just get back later.
