### ISSUE TITLE
Large CIAs aren't recognized (?)

### ISSUE THREAD

**Issue by NWPlayer123** [d0k3/GodMode9#314]
I'm on 1.5.1 stable, compiling from latest breaks CIA decryption entirely? (only tried with Dark Moon, breaks halfway in, just stops and time goes up infinitely)
Anyways, I was trying to decrypt all the themes and it doesn't even recognize it as a CIA, maybe it has too many contents or something? only one that it recognizes is 8F01, presumably cuz it doesn't have that many contents
![img_20180215_233815__01](https://user-images.githubusercontent.com/3280345/36296317-fe558f76-12a9-11e8-8946-58baa2b5ab1a.jpg)

**Comment by d0k3** [comment]
I guess I need clarifification.... does that happen on the 1.5.1 release or on the latest nightly? If it happens on the latest nightly, then the recent refactor may be at fault. If it already happens on 1.5.1 release, I need to know of a version that does not have that problem.

And, you say 8F01 is recognized, (it's 200MB in size), and smaller ones are not?

**Comment by SirNapkin1334** [comment]
Heck, I've seen MUCH bigger CIA's (just look at USUM, 3.4GB). Perhaps the amount of data in them is so much that it overloads the buffer?

**Comment by NWPlayer123** [comment]
@d0k3 this is 1.5.1 release, the bigger ones (8200, 8201) aren't recognized but 8F01 is
@SirNapkin1334 that's why I say number of contents, 8200 has 270 contents, 8F01 has 70

**Comment by d0k3** [comment]
Does every one of these CIAs have a large number of contents?

**Comment by d0k3** [comment]
Does every one of these CIAs have a large number of contents?

**Comment by NWPlayer123** [comment]
0004008C00008200: 272 contents
0004008C00008201: 263 contents
0004008C00008202: 281 contents
0004008C00008203: 277 contents
0004008C00008204: 274 contents
0004008C00008205: 272 contents
0004008C00008F00: 276 contents
0004008C00008F01: 72 contents
0004008C00009800: 289 contents
0004008C00009801: 193 contents
0004008C00009802: 169 contents
0004008C00009803: 190 contents

8F01, 9801, 9802, 9803 are recognized, seems like it's maybe a single byte overflow in GM9 and fails some check? all of those are below 256, but the ones that fail are 263+

**Comment by d0k3** [comment]
Okay, I need to ask, what are these CIAs? That's more themes than homemenu can hold, and no title out there has that many DLCs. Are these installable in FBI?

**Comment by SirNapkin1334** [comment]
Why is the theme even in a .cia? I thought they were supposed to be in a .zip with specially formatted contents?

**Comment by ihaveamac** [comment]
@SirNapkin1334 that's how official themes are stored....

**Comment by d0k3** [comment]
@NWPlayer123 - you haven't replied yet, but you actually mentioned another issue, one that I assume happens with large CIAs (>= 2GiB). Does that also happen on the 1.5.1 release? Can you be a bit more specific about this?

**Comment by NWPlayer123** [comment]
@d0k3 okay, so, I downloaded them all with CDN-FX cuz make_cdn_cia breaks, it's treated as DLC afaik with all the multiple contents, here's the ctrtool output for a big one and small one:
https://pastebin.com/mHZNBG9U
https://pastebin.com/BLnzWXCA
tested on 1.5.1 and compiled latest version (https://github.com/d0k3/GodMode9/commit/0eaa971b504c5f409c16b36e8cb7f0d844ff920a), neither recognize the big ones

**Comment by d0k3** [comment]
@NWPlayer123 - can you please contact me via some other means? IRC (freenode #Cakey or efnet #3dsdev) or GBAtemp. I may need some data fro myou which shouldn't be publicly shared.

I may already know the issue behind those CIAs not being recognized, what bugs me more is the problem you had decrypting Dark Moon. Using the latest nightly, I could not reproduce this. Can you give me more info, and maybe re-test with this and other CIAs?

**Comment by d0k3** [comment]
Okay, good. Try building from the latest commit. All the CIAs in your list should be handled correctly now. I'd still appreciate if you'd check and try find ones with even more contents inside.

Also, leaving this open because of the Dark Moon issue.

**Comment by NWPlayer123** [comment]
looks like Dark Moon is fixed too @d0k3, we good here
