### ISSUE TITLE
Certain info not shown on System Info

### ISSUE THREAD

**Issue by Marenthyu** [d0k3/GodMode9#318]
On my system info prompt, the following information is <unknown>:
Friendcode seed, SD keyY and System ID0.

Screenshot attached.

I do not know why it is happening, every other function of gm9 seems to be working just fine.
Current Firmware is newest, Luma is on 9.0.

The issue can be reproduced by @zetadesigns on an other European o3DS.

![screenshot](https://share.marenthyu.de/nF6uN3kI.png)
(censored other data for privacy, but i can provide them if they help with identifying the issue.)

**Comment by SirNapkin1334** [comment]
Do you have an aeskeydb.bin for support? This happened to me once, I can't remember how I fixed it.

**Comment by Marenthyu** [comment]
I suppose that's created by "create support files"?
Can provide that; but i'd prefer a personal channel - do DM me on discord or send an email.

**Comment by SirNapkin1334** [comment]
You can't get that from the Build Support Files. And what I'm asking is if you have one, as GodMode9 needs it for extra functionality, including accessing CTRNAND in entrypoints beside Boot9Strap. Is there an aeskeydb.bin in SD:/gm9/support?
DM me in discord. @SirNapkin1334#5144

**Comment by d0k3** [comment]
Okay, this is weird. The `aeskeydb.bin` is not required here. Can you check if you have the `1:/private/movable.sed` file? Maybe something is special with it. I guess I may even have to have a look, but don't post it publicly.

**Comment by Marenthyu** [comment]
I do have it, it is 288 Byte and i have successfully extracted it previously using @zoogie 's seedstarter.cia for use with TADPole before.

**Comment by Marenthyu** [comment]
My Discord is Marenthyu#4211 if you want to contact me

**Comment by d0k3** [comment]
It's only 288 byte if the system has never been started. Is that the case? A standard, initializied `movable.sed` is 320 byte. An uninitialised system does not have a SD key Y or a system ID0. The LocalFriendCodeSeed is there, though.

**Comment by Marenthyu** [comment]
I have been using this 3DS for the past 7 years now, it certainly has been started - it has never been formatted or reset, however, if that changes things.
As far as i can tell, my ``movable.sed`` is fully stock, untampered with.
But comparing it to the other ``movable.sed``s i have mined as well as mining it again by dumping my movable_part1.sed and using seedminer, i do see that my exported/copied ``movable.sed`` has a lot more "stuff" in it.
All my mined ``movable.sed`` have a lot of 00 bytes before and 32 ``00`` bytes after a part that's written to - this "written to" part is identical in my dumped/copied ``movable.sed``.

Sorry if this is no news, i am not 100% educated.

But yes, if you want to examine my file, shoot me an email or discord message.

**Comment by Marenthyu** [comment]
I updated [https://www.3dbrew.org/wiki/Nand/private/movable.sed](3dbrew) with the information of talking and testing with @d0k3 . Feel free to reword/rewrite it if i missed anything.

**Comment by Marenthyu** [comment]
Also to note from olliz0r on discord, the 0x120 data is written on system ``FORMAT``, not system ``startup``, so it may be just the fact that these early systems never got formatted before being shipped, yet newer systems were?
Idk. Just throwing the idea out there.

**Comment by d0k3** [comment]
As far as I know, your system is auto formatted when first booting up. Also, the CMAC inside the initialized part of the `movable.sed` is crucial. It's used for checking the validity of your own movable.sed, and it's also the reason why an uninitialised one from another console will not work.

**Comment by SirNapkin1334** [comment]
Formatted? I'm not sure. I believe there's a difference between format and initial setup.

**Comment by d0k3** [comment]
Okay, should be fixed in https://github.com/d0k3/GodMode9/commit/37cdb26f91c78857364e7e1dc8145499509b58e2

@Marenthyu - can you try this?

**Comment by Marenthyu** [comment]
Tomorrow afternoon, in 17ish hours. (Not home right now)
I dont have the homebrew devkit set up, so if you could ``make`` me a ``firm``, I'd appreciate.

**Comment by SirNapkin1334** [comment]
I'll send you a compiled firm over Discord once I get home (about 50 minutes)

**Comment by mariohackandglitch** [comment]
I have a NAND backup from a 1.0.0 console that was updated to 4.5. I checked the movable.sed and indeed, it's 288 bytes. I don't remember if I formatted it before making the NAND backup, but in any case, the backup was made after updating to 4.5 (using the gateway ram dumper)

**Comment by Marenthyu** [comment]
was it also a european console?

**Comment by mariohackandglitch** [comment]
Yes, it is european.

**Comment by Marenthyu** [comment]
I can confirm that it is fixed with g84bfac6a

Issue may be closed at project's discretion, but it may be left open for documentation on the uninitialized movable.sed

**Comment by d0k3** [comment]
It will still be viewable after it's closed. Any further  discussion / research regarding this should happen elsewhere (IRC or other platforms). I'm still interested in what causes this, ofc.
