### ISSUE TITLE
Improperly displayed data on mounted exeFS image

### ISSUE THREAD

**Issue by SirNapkin1334** [d0k3/GodMode9#321]
I was fiddling around with my 3DS, and browsing through the file on my SD, when I happened to look into freeShop's image cache. But, for some reason, the iconsx.bin (x = number 0-5) files were recognized as exeFS images. Odd, but, I figured, why not look at the images inside?
So, I mounted it to G:, and then weird stuff happened. Despite each file being quite full of data in the hexeditor (okay, well, later on, at first it's only 00's and FF's, but if you scroll down for a moment then you'll find data), there was nothing inside. "Well, that's strange" I thought to myself, so I exited the mounted image to [root] (I didn't unmount it though), and for some reason entered [C:] GAMECART. Then, it froze, on [root] with C: highlighted. The system didn't respond to and buttons, including START and R+START, so I had to force power it off. The second time, I tried again, and the same result. So, I got off the couch, came over here, and tested it a third time and....it did exactly what it should have done-open the C: drive to show nothing (the currently inserted cart was an R4i Gold 3DS RTS flashed with GodMode9, which never shows anything when flashed with ntrboot). I've  tested it a few more times, exact same file, exact same pattern of inputs even, and same thing-doing what it's supposed to. Oh well, time to get to the actual issue I was talking about in the title.
All 6 of the iconx.bin files are the same size, precisely 524,288 Bytes [512.0 kB]. When mounted, when you go to [root], on the right it displays that, 512.0 kB. However, Drive Info shows that there are 10 files & 0 subdirs, despite the fact that there is a stunning lack of files inside the image. However, underneath that, it goes on to say **39.9 GB total size**. WHAT? There aren't even any files that I can browse! Only 10 "imaginary" files, that somehow take up just under 4GB each? That, while still saying on the right 512.0 kB.
So, then it says:
`space free: 0 byte`
`space used: 512.0 kB`
`space total: 512.0 kB`
WHAT? In the same prompt, it tells two different total sizes. Yeah.
And, all 6 files are exactly the same in terms of size and analyzed data (only difference is name and the data they contain inside, they have different SHA-256's). All have 10 "imaginary" files, 39.9 GB, then 512.0 kB, etc.
I will include these 6 files (they may be from the freeShop, but they don't contain any copyrighted content, and I have no idea how to derive the icons from them, so they shouldn't be a problem) for you to analyze.
Here's a crappy image of the weird analyzation prompt:
![img_0390 231](https://user-images.githubusercontent.com/31591796/36941374-6f66aa40-1f0e-11e8-85d8-0c1c8830ca6a.JPG)
You know, we should be able to take screenshots in prompts, rather than not only in the filesystem.
And, the buggy files:
(I just took the cartridge out of the system and almost tried to insert it into the SD reader. Wow, should probably get the right card.)
[icons.zip](https://github.com/d0k3/GodMode9/files/1778100/icons.zip)
It should be noted that I am using the newest commit of windows-server-2003:sdlock

Also, something unrelated, but when you unmount the SD, it unmounts the currently mounted image if there is one. This makes sense, since it's most likely stored on the SD, but if the image is stored somewhere else, say CTRNAND, it will still be unmounted.
(sorry for the huge wall of text)

**Comment by d0k3** [comment]
That's the filetype detection failing. I'll look into it.

**Comment by d0k3** [comment]
Okay, fixed. Would be great if you could test the other two commits before it, too.

**Comment by SirNapkin1334** [comment]
Okay, I'll test it soon.

**Comment by SirNapkin1334** [comment]
@d0k3 yes, it works as it should now, not displaying "mount as exeFS image."
