### ISSUE TITLE
Add support for importing gba saves with the .srm and .sram extensions.

### ISSUE THREAD

**Issue by nl255** [d0k3/GodMode9#323]
I noticed that when I try to copy over and import a RetroArch GBA save the inject fails however it works fine if I change .srm to .sav.  It would be nice to not have to do that.  In addition, bubble2k16's emulators typically use .sram for the save extension so it would be good to add that to the list as well even though he hasn't done a GBA emulator at the moment.

**Comment by d0k3** [comment]
So... all you need to do is change the extension, is that correct? Or do you need to convert the file in some way?

**Comment by nl255** [comment]
Yes, all you need to do is change the extension for .srm.  It is impossible to test .sram at the moment since bubble2k16 has not made a GBA emulator port yet but assuming he uses mgba as a base then it should be the same as retroarch/mgba.

**Comment by d0k3** [comment]
Okay, added `.srm` as allowed extensions. Left out `.sram` for now. Ocne your properly tested the compatibility, I'm okay with including `.sram`, too.
