### ISSUE TITLE
Ability to install any CIA?

### ISSUE THREAD

**Issue by NWPlayer123** [d0k3/GodMode9#324]
IDK what all would have to be modified but it would be useful for (half)bricked systems, when I've accidentally uninstalled some important OS module and need to reinstall it (e.g. the Home Menu cuz FBI lets me uninstall but not reinstall without rebooting when it's already too late)

**Comment by SirNapkin1334** [comment]
No. We can't install CIA's from arm9 (payloads) because that code runs on arm11 and would be an extremely complicated and potentially impossible to do. Short answer: no. Long answer: still probably no. And citfa9mwsa isn't going anywhere right now.

**Comment by crispycola** [comment]
A CTRTransfer would be the solution if you ever ended up in the situation you described, rather than installing a CIA. As SirNapkin1334 explained, installing CIAs in a non-arm11 environment is borderline impossible.

**Comment by windows-server-2003** [comment]
We can run arm11 code as .firm but installing CIAs needs kernel functions(=need to be .cia).

**Comment by NWPlayer123** [comment]
answers my question, thanks anyways 😛

**Comment by ihaveamac** [comment]
if you didn't delete any safe-mode titles, you can probably update using that.

**Comment by urherenow** [comment]
And if you would just make another nand backup after completing the "reinstall process" you speak of, you wouldn't be starting from square 0 every time. Backups rule.

**Comment by SirNapkin1334** [comment]
@urherenow yeah, I make NAND backups at lest every two weeks, often more.
