### ISSUE TITLE
issue with build support files option

### ISSUE THREAD

**Issue by zweilous** [d0k3/GodMode9#326]
regardless of selecting yes or no, the "build support files" option will build and replace the files in the output folder. is either option doing anything differently from the other?

**Comment by SirNapkin1334** [comment]
Yes, this happens as well. However, the prompt will only come up if the support file(s) in question already exist in 0:/gm9/out. Pressing B to decline will still "build" the files, I will check if it actually creates and updates the files.

**Comment by SirNapkin1334** [comment]
It does indeed update them. Also, despite saying "Okay (SYS&EMU)" it never builds a seeddb.bin (doesn't matter, I have a fully updated one from *that titlekey site*, but still odd. It used to say that it couldn't build a seeddb.bin, but now it thinks it built it despite not actually.

**Comment by d0k3** [comment]
I just tested and I see no problems. You get the update prompt if the file in question already exists. If you select `yes`, data will be added to the existing file. If you select `no`, existing data will be deleted and a fresh file will be created.

Also, no trouble creating the `seeddb.bin` here. Can you be more specific?

**Comment by SirNapkin1334** [comment]
@d0k3 basically, it looks like the `seeddb.bin` was created in every way except that the file is not in 0:/gm9/out.

**Comment by d0k3** [comment]
I need steps to reproduce. Maybe try the latest nightly? As I said, it turns up for me.

**Comment by SirNapkin1334** [comment]
I swear I was using the latest nightly...it just happens when I choose "Build Support Files" nothing special. I'll look into using the latest nightly, but I'm already using my compiled version of the latest commit. I'll get back to you.

**Comment by d0k3** [comment]
Alright, just for the record: @SirNapkin1334 tried this on a 'virgin' N2DS, which actually had no seeds installed. The most recent commit gives you a proper error message in that case.

@zweilous - if you feel your issue is resolved, please close this. Otherwise, I will need more details.

**Comment by zweilous** [comment]
i was just confused by what is exactly done when “no” is selected. what you said clarified it though. thank you
