### ISSUE TITLE
[TAD] TAD Mounting crashes GM9

### ISSUE THREAD

**Issue by knight-ryu12** [d0k3/GodMode9#327]
- ~~Affected TAD/File: 4B454E4A.bin (ほぼ日の健康手帳)~~
- Crash screen: https://cdn.discordapp.com/attachments/426369881752076319/426371742307713024/IMG_20180322_222834.jpg
- When it happens/ how to reproduce: Open any dsiware.bin in A:\Nintendo DSiWare, Mount as drive; then immidately fails.

**Comment by knight-ryu12** [comment]
Update: All other TAD crashes as well

**Comment by d0k3** [comment]
I think you're right, and I have an idea what's happening there. Does it also happen with non-japanese TADs? And is it somehow affected by the length of the names?

**Comment by knight-ryu12** [comment]
as I mentioned it, all other tad I own causes this crash.
No matter of length of names... I think.

**Comment by knight-ryu12** [comment]
Well seems, turns out auto mountpoint switching is broken
manually going to mountpoint works
but this is still bug...

**Comment by knight-ryu12** [comment]
yeah,
according to my test, auto mountpoint switching fails if there is no previous mountpoint.

**Comment by knight-ryu12** [comment]
wait hmmm

**Comment by jason0597** [comment]
i can try dumping EUR TADs

**Comment by d0k3** [comment]
Okay... I think we fixed it. @knight-ryu12 can you try again, building from the latest commit (or using the hourly build)? @jason0597 - further testing is helpful, too.

**Comment by knight-ryu12** [comment]
Sure, I will.

2018年3月26日(月) 9:41 d0k3 <notifications@github.com>:

**Comment by knight-ryu12** [comment]
@d0k3, Confirmed fix. 👍

**Comment by knight-ryu12** [comment]
Sorry I will leave this open

**Comment by d0k3** [comment]
@knight-ryu12 - nope, it's okay to close it after you tried it. Thanks for tetsing this so quick!
