### ISSUE TITLE
[Feature Request] Keep old SD card name when format

### ISSUE THREAD

**Issue by knight-ryu12** [d0k3/GodMode9#333]
Formatting will give default name "GM9SD"(you can change it manually to something else), But I think if it keeps old name prior to format like "3DSSD".

**Comment by SirNapkin1334** [comment]
Similar to #282

**Comment by knight-ryu12** [comment]
not really;
I don't want "specific pattern name".

**Comment by d0k3** [comment]
Yeah, nice idea. I'll look into it.
