### ISSUE TITLE
Restore SysNAND (Safe) script error

### ISSUE THREAD

**Issue by DilandDuck25is** [d0k3/GodMode9#335]
When I try to use the script to try and fix my (I think) bricked O3DS.

`0:/gm9/scrip...ysNAND (safe).gm9
line 8: unknown cmd
chk -u $[HAX] " "`

**Comment by SirNapkin1334** [comment]
What version of GodMode9 are you using?

**Comment by SirNapkin1334** [comment]
Are you on version <1.4.1?

**Comment by DilandDuck25is** [comment]
I'm using 1.4.0

**Comment by SirNapkin1334** [comment]
You need to use a newer version - the `chk` command does not exist in that version.
https://github.com/d0k3/GodMode9/releases/latest

**Comment by DilandDuck25is** [comment]
Worked! :D Thanks!

**Comment by SirNapkin1334** [comment]
Please close this now. Happy to help =D
