### ISSUE TITLE
1.6.2

### ISSUE THREAD

**Issue by ltlynx** [d0k3/GodMode9#336]
Is this April Fool's? :( I don't find funny that it is loading random interfaces, including one with the texts upside down.

**Comment by Wolfvak** [comment]
Yes, it is.
If you have a problem with that, just use [v1.6.1](https://github.com/d0k3/GodMode9/releases/tag/v1.6.1), or the next release.

**Comment by SirNapkin1334** [comment]
What's so bad about it? With the "bricked" mode, you can fit 3 times as much data into one screen on the Hexeditor!
