### ISSUE TITLE
[Feature Request] GM9 script, 'hexget' COMMAND

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#339]
>'hexget' COMMAND
>The 'hexget' command is used to extract hex values from a file.
>The second argument is a variable that temporarily stores the hex values.
>The syntax is: hexget origin@x:y variable
>	x: origin offset (in hex)
>	y: origin size, starting at x (in hex)
>Both x and y must be provided
>-r / --reverse the order of extracted hex values
>-s / --space between each of the hex values

```
set HEX_VALUES ""
set DUMMY "$[GM9OUT]/dummy.bin"

fill $[DUMMY]@00:01 00
fill $[DUMMY]@01:01 01
fill $[DUMMY]@02:01 02
fill $[DUMMY]@03:01 0A

hexget $[DUMMY]@00:04 HEX_VALUES
echo $[HEX_VALUES]		# 0001020A

hexget -s $[DUMMY]@00:04 HEX_VALUES
echo $[HEX_VALUES]		# 00 01 02 0A

hexget -r $[DUMMY]@00:04 HEX_VALUES
echo $[HEX_VALUES]		# 0A020100

hexget -r -s $[DUMMY]@00:04 HEX_VALUES
echo $[HEX_VALUES]		# 0A 02 01 00
```

As for why, see [post 159](https://gbatemp.net/threads/release-godmode9-scripts-megathread.482150/page-8#post-7890912) and below. I hit a limit in GM9 scripting.

Edit - Meant post 159, not 169.

**Comment by d0k3** [comment]
Do you really need -r and -s for that? Looks quite gimmicky to me.

**Comment by fox8091** [comment]
@d0k3 While -s may not be useful, I could definitely see -r being useful.

**Comment by TurdPooCharger** [comment]
The -s flag, probably not. That would have been used for easier read out when using echo command. 

For the -r flag, almost all the hex offsets in CIA files are read from right to left. I could do with single hex copying going backwards. I don't know how complicated programming would be for this type of command.

**Comment by SirNapkin1334** [comment]
@d0k3 Actually, we could perhaps make -r a separate command, allowing you to reverse a string or otherwise modify it according to a set of rules.

**Comment by TurdPooCharger** [comment]
![headerexefs_fbi](https://user-images.githubusercontent.com/35666439/38414700-3ab555f8-395d-11e8-9841-af559144b5f7.png)

The script I would be using 'hexget' modifies a title's **exefs.bin** by swapping out for a different **icon** and/or **logo**.

_FBI's ExeFS files hex offsets for injection purposes_
**.code** = 0000000   (**00 00 00 00**)
**banner** = 0004E600   (**00 04 E6 00**)
**icon** = 000ACE00   (**00 0A CE 00**)
**logo** = 000B0600   ( **00 0B 06 00** )

@d0k3, this request can go at the back burner. I'm not in any rush because the script in question already gets by using 'shaget' and 'chk' hoopla, albeit very slowly. It's a very niche feature for the sake of optimizing injection speed.

**Comment by SirNapkin1334** [comment]
We could modify `inject` to allow us to inject a specific amount of data starting from a specific point instead of just injecting a whole file.

**Comment by TurdPooCharger** [comment]
Inject command already does that with how much to inject. My issue is trying to read hex values to know where to inject.

**Comment by d0k3** [comment]
We can't modify existing commands in a way that would introduce incompatibilities. You'll get that command in one form or another, @TurdPooCharger, but you'll have to wait for a bit.

**Comment by SirNapkin1334** [comment]
@TurdPooCharger Oh. I hadn't realized that. Though, that suggestion is a good idea.

**Comment by TurdPooCharger** [comment]
@SirNapkin1334, sorry for the confusion. I didn't do a good job separating the different commands in my explanation. I was trying to provide the purpose behind the requested `hexget` while linking it back to `inject`.

@d0k3, take all the time you require. Do it super leisurely. In fact, I insist you leave it out until the next or 2nd next major GodMode9 release. I would like nothing to do with GM9 scripting for a while. So long as I know that hex command is out of reach, I'll have no reason to want to code. :laughing:

Okay, I'll be closing the issue. In case you're like me, I'd gets panic attacks seeing issues stay open for too long.

**Comment by d0k3** [comment]
Reopened :P. Yeah, we actually need a command such as that, and I want to do it shortly. This is here so we have a reminder.

**Comment by d0k3** [comment]
Okay, this commit adds `fget` and `fset`commands to scripting:
https://github.com/d0k3/GodMode9/commit/4f8dfc1eaf7b4d231bd2caadbdf277a5d8061b83

Please test and tell me if that works for you.

**Comment by TurdPooCharger** [comment]
Will need script instructions on how commands are used. I'll test the next following day. Thanks!

**Comment by TurdPooCharger** [comment]
Update: Cooking up a new script to try out `fget` and `fset`. I could easy-peasy this, but where's the fun in that?

This might a take a while, expected release and testing results later today. Here's a preview of the script.

> GodMode9 script for checking selected .cia
> file against a homebrew database.
> 
> This also tests for and validates two 
> new GM9 script COMMANDS, 'fset' and 'fget'.

**Comment by TurdPooCharger** [comment]
@d0k3, I think I found a bug not related to this feature request. Is there a char limitation for ' - '?
 
> echo "d0k3"
> echo "TurdPooCharger"
> echo " "
> echo "-"                           # error message fail

**Comment by TurdPooCharger** [comment]
`fset` and `fget` are scrutinized and get my approval. :+1: 

I was not able to reproduce the supposed bug in my original test script with this second test script. Gonna chalk it up to programming error on my part. Unless noted otherwise, I have no reason to believe the commands are the cause of something funny that happens with `00`. Perhaps someone else can lead a helping set of eyes?

[fget_fset_debug.zip](https://github.com/d0k3/GodMode9/files/1905497/fget_fset_debug.zip)

Can someone else check the 'fget' and 'fset' debug test script? There's a support hex table file that contains all hex numbers from **00** to **FF**. The script recreates that 1st table with an exact 2nd and 3rd tables through two different methods.

The second table is recreated individually piece-wise for all 256 hex numbers.

The third table is recreated using double endian (reversing) with sets of (0xF) 16 bytes. The `-e` flag is used for both `fget` and `fset`.

Both 2nd and 3rd table are hash checked against the 1st table.

**Comment by d0k3** [comment]
Alright, so I'm assuming the feature working as intended and no bugs left (except the one you opened another issue for). If anything comes up, feel free to reopen. Gotta weed out those Github issues :).
