### ISSUE TITLE
Weird lines upon shutdown

### ISSUE THREAD

**Issue by jupitteer** [d0k3/GodMode9#34]
On an o3ds, when shutting down with godmode9, gray vertical lines appear on screen. They slowly fade away.

**Comment by d0k3** [comment]
This sounds like a non-issue to me. Is there actually any disadvantage for you, that comes from these grey lines?

**Comment by d0k3** [comment]
Alright. Unless there are some issues coming from this, and unless there are display issues while running GM9, there should be no problem with those gray lines. they are unusual, but it may be just some hardware quirk, like a slightly different LCD screen.

Closing this now, feel free to reopen if you disagree.
