### ISSUE TITLE
help please!

### ISSUE THREAD

**Issue by bouleakaslim** [d0k3/GodMode9#341]
So i bought a 2ds (the one that doesnt fold)    and i tried to do the same as my 2ds XL, flash it with r43ds b9s

on my 2ds xl i did it and it all worked well

now on my 2ds, i flashed it by with installfirm.zip     like i did with 2dsxl

then i extract ntrpack_1.2-sd.zip on my formated sdcard and put it in the DS

when i try to turn it on.   the light just blinks once blue, and nothing happen..just black screens

could u help me please? 

thank u very much

**Comment by SirNapkin1334** [comment]
This is not a support forum. Ask at [Nintendo Homebrew](https://discord.gg/C29hYvh) or the [GodMode9 Discord](https://discord.gg/EGu6Qxw).

Though, what guide did you use? I've never heard of installfirm.zip or ntrpack_1.2-sd.zip
You should be using the [3DS Hacks Guide](https://3ds.hacks.guide/ntrboot).

**Comment by bouleakaslim** [comment]
its in french

http://jeux-linker.com/blog/tuto-francais-r4i-b9s-hack-3ds-new2ds-pour-rom-3ds-telecharge-gratuit/

it worked very well for my 2ds XL

but doesnt with my 2ds

**Comment by d0k3** [comment]
Besides, you should ask the people who made that guide.
