### ISSUE TITLE
GM9 script char bugs for # % -

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#344]
While script testing new `fset` and `fget` commands from issue #339, these char misbehavior were found when using either `echo` or `set`.

line 1: bad # of args
> echo "#"

This works.
> echo "check #"

The % symbol disappears.
> echo "%"
> echo "check %"

error message fail
> echo "-"

This works.
> echo "check -"

Probably not bug. Syntax abuse but adding it here anyway.
>echo """

**Comment by SirNapkin1334** [comment]
the # issue makes sense since # is a comment character. It's commenting out the rest of the line, so the scripting engine sees this:
>echo "
Odd that the second thing works though.

**Comment by fox8091** [comment]
It seems that the easiest way to fix all of these at once is to add an escape character, where the following character is always treated as text. Perhaps `\` would be a good escape character? And of course, if you needed to display a `\`, you would simply do `\\`.

**Comment by d0k3** [comment]
Ugh. I can see how the `"#"` and '"%"` fails, but no idea yet about `"-"`, and the `""` thing should work, too.

**Comment by TurdPooCharger** [comment]
@d0k3, the last one is really three (3) `"` quotation mark chars, not two (2).

That one is script abuse, unless you intended the `"` char to appear-able in `echo` command.

**Comment by d0k3** [comment]
Explanation for this: This won't fix the triple quotation marks (this is clearly abuse), and to have a `%` you will have to write a `%%`. I deliberately didn't fix the last one (1) because the implementation would make things complicated and (2) because you actually expect escape sequences to work in `\n`.

**Comment by TurdPooCharger** [comment]
@d0k3, I tried retesting with nightly `GodMode9-v1.6.3-34-g7d675372-20180417024506.zip`.
The `#` and `-` ones are fixed. Yay!

Can you help me with the `%` one? How to use the double `%%` to get a single one to appear?

The percent symbol still missing.
`echo "%%"`
`echo "check %%"`

**Comment by d0k3** [comment]
Dammit. Alright, then I'll have no other choice than to reopen. I'll look into it.

**Comment by d0k3** [comment]
Explanation: Yup, now it should also work with just a single `%`. Testing is appreciated, ofc.

**Comment by TurdPooCharger** [comment]
Char_Arsenable.gm9
three times (less) buggier
```
echo "%"
echo "check %"
echo "% check %"
echo "%%"
echo "check %%"
echo "d0k3% is not d0k3 with two spaces like before."
set PERCENT "%"
echo $[PERCENT]
echo $[PERCENT]$[PERCENT]
echo $[PERCENT]-$[PERCENT]

# need " before - or less script checks for flag
echo "-$[PERCENT]"

echo "GodMode9 gets a 100$[PERCENT] return \nin Ethereum investment.\n \nDogecoin, however, is still the future."
```

:+1:

**Comment by TurdPooCharger** [comment]
Yes, everything checks out. Latest nightly beats the Gundam referenced test script. You good.
