### ISSUE TITLE
[Documentation] We need a scripting Wiki!

### ISSUE THREAD

**Issue by d0k3** [d0k3/GodMode9#345]
As basically everyone involved with scripting may have noticed, GM9 scripting has gotten far more complex and providing a few sample scripts just don't do it justice anymore. So, we need to step up the documentation a bit. Best course of action (open for discussion) would be a Wiki, right here on Github, and for that I will need your help as contributors.

What I have in mind is a complete list of commands, with descriptions and examples for each. Each Wiki page should have a unified layout (like, command, description, flags description, example). For contributors, starting may be as simple as just copy-pasting the respective sections from the sample scripts.

Bear in mind that, besides contributing, I have never set up a Wiki myself, so I'd need help with that as well. As of now, only putting this up for discussion. If you're willing to contribute, help me set it up or maybe even help moderating contributions (as I said, I'm a Wiki noob), discuss here.

**Comment by annson24** [comment]
I'll be happy to help out in any way I can.

**Comment by TurdPooCharger** [comment]
I'll pitch in when I can. Right now, gotta detox from too much programming. Hiatus!

**Comment by SirNapkin1334** [comment]
I was going to message you about this but totally forgot. I would be happy to help! Despite not actually being a scripter, it'd be fun for me and I would like to help as much as I can.

**Comment by d0k3** [comment]
Alright, I created the Wiki and enabled editing for everyone (in case of digital vandalism, I can still revert). I'll try to set up a hub page soon (wouldn't mind if one of you guys started, either).

The way I have this planned in my mind is that the Wiki is divided into two main areas - GodMode9 usage and Scripting. The hub would have a short intro text plus links to these sections. The scripting section would have subpages for each and every command. The usage section... unsure. For now, I may just link to the guide for that.

**Comment by TurdPooCharger** [comment]
First entry is up. Bare minimum. Baby steps. :)

**Comment by SirNapkin1334** [comment]
I've created a [#wiki](https://discord.gg/7v3aPeE) on the GM9 Discord to talk about this and help each other out. That'll probably work a lot better than GitHub issues.

**Comment by TurdPooCharger** [comment]
Yah, this GitHub issue doesn't work for on-the-go flow communications. Also, writer's block is a big killer especially for most programmers. Something about analytic brains don't do well with putting words down.

Don't fret, guys. When you can and feel like it, add or edit one sentence. If you think what you wrote doesn't strike a balance of being concise and technical, that's okay, too. 

I think for upfront groundwork is figuring out the structure of the wiki pages. Once that's figure out, we can determine how writing task will be split.

This is especially important because us GM9 scripters do not know the entire ins and outs of the script quirks nor how each command works in actual practice.

**Comment by TurdPooCharger** [comment]
@SirNapkin1334 , I'm not a fan of installing apps on my devices after seeing the rise of Facebook and related services. Their less than stellar track record of respecting user privacy has led me to use only desktop web-based services. Even for the Nintendo 3DS, I keep WiFi off unless absolutely required for digital acquisitions, if you catch my drift. ;) 

I've never used IRC either. If it's anything like TwitchTV setup, where they did **Twitch Plays Pokemon**, then I'd be okay with Discord. There are a lot forms of internet communications I haven't kept up in learning with the changing times.

Sorry for this, but I still haven't looked into what Discord is. Unrelated to GodMode9, I took an unplanned detour these past few days helping out fellow 3DS homebrew devs hunting down a bug of theirs.

I'll contribute with the wiki when possible. Got some life-work-hobby rebalancing in order. :)

**Comment by d0k3** [comment]
Alright, seeing that the Wiki is already on a good way and that this issue has served it's purpose (a call for action), I'm closing it now. @TurdPooCharger - yup, a Guthub issue doesn't serve the purpose of discussing various aspects of the Wiki well.

Thanks a lot to everyone who contributed so far, especially @SirNapkin1334 who by now holds the record for most edits to the Wiki.

Discussion will be continued in the [GodMode9 Discord](https://discord.gg/EGu6Qxw) (or anywhere you like). Thank you all!

**Comment by TurdPooCharger** [comment]
Okay, I'm not liking the GitHub wiki. There's trouble trying to type sentences with Enter.

If you type something like this:

> Sentence one.
> Sentence two.

It'll just end up looking like this:
> Sentence one. Sentence two.

If you skip two lines with Enter key twice, writing this:

> Sentence one.
>
> Sentence two.

It'll end up looking like this:

> Sentence one.
>
> Sentence two.

Even though your intention was to have the sentences appear like this:
> Sentence one.
> Sentence two. 


Oh gawd forbid if you want two lines between sentences. You type this:
> Sentence one.
>
>
> Sentence two.

And you end up getting this:
> Sentence one.
>
> Sentence two.

*Fuming* !!!!

**Comment by SirNapkin1334** [comment]
@TurdPooCharger That’s markdown for ya. Try the other edit modes. This can’t be changed - that’s how markdown works.

**Comment by TurdPooCharger** [comment]
@SirNapkin1334, the other modes has wide spacing between top and bottom adjacent sentences, too. If this wiki formatting issue cannot be satisfactorily resolved, I either recommend linking to a different website that's not GitHub or a **GodMode9 Scripting Bible**.pdf  built upon the Hello Scripts with precise control over document formatting.

**Comment by ihaveamac** [comment]
it uses markdown. add two spaces to the end of one line -->  
to have the next one start on the next line.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
https://guides.github.com/features/mastering-markdown/

**Comment by TurdPooCharger** [comment]
@ihaveamac, I can't find anything about having one sentence exactly below another without spaces between them. What did I do wrong? 

![markdown_help_plz](https://user-images.githubusercontent.com/35666439/39090234-6594938c-45a7-11e8-913b-d386455a9d2a.png)


I tried adding two spaces ` ` in between the first and second sentences as show in the bottom example for the picture. It gets me to show Example 7 as intended.

**Comment by ihaveamac** [comment]
"add two spaces to the end of one line"
```
line 1<space><space>
line 2
```
> line 1  
> line 2

**Comment by TurdPooCharger** [comment]
@ihaveamac , **THANK YOU.** :grin: 

Well, adding one more thing I hate working with: Linux, hex editing, now Markdown. Blah.
