### ISSUE TITLE
Extract .code fails when run from mounted cartridge

### ISSUE THREAD

**Issue by Hyarion-SS** [d0k3/GodMode9#346]
Mount C:\titleid.3ds, then go to G:\content0.game.app>NCCH Image Options>Extract .code. Every cartridge I've tested this on fails. Building as CIA, installing, then navigating to the equivalent 00000000.app>NCCH Image Options>Extract .code, however, does succeed.

A quick test indicates that the failure is happening somewhere in the main decompression loop of DecompressCodeLzss. Hopefully this is a simple fix, as getting the decompressed code.bin directly from the cartridge would be quite useful to us.

**Comment by d0k3** [comment]
I'll look into it.

**Comment by SirNapkin1334** [comment]
Yes, extracting straight from .3DS would be ideal. I'll look into it when I get home (it's Friday =) ). I'll test with multiple carts.

**Comment by Hyarion-SS** [comment]
Sorry, didn't notice the edit. Yes, extracting from .3ds directly also works.

**Comment by Hyarion-SS** [comment]
Extracting .code from a .3ds also fails, as it turns out.

Digging into it a bit further, I disabled the decompression function and instead got the original compressed code.bins from .3ds on cart, .app on cart, and .app from sysnand sd. The filesize and first 0x100000 bytes are the same, but past that the two from cart are seemingly random garbage. file_size, the bytes-to-read parameter when copying into memory, is the correct value however.

Using copy to 0:/gm9/out on G:/exefs/.code also produced a correct compressed .code, identical to the one from the installed version. Could this be an issue with the NCCH decryption function called immediately beforehand? (gameutil.c line 1555) The cartridge ncch flags are 00 00 00 01 01 03 00 00, for reference.
