### ISSUE TITLE
Feature tequest - Show remaining space on a drive w/out R+A

### ISSUE THREAD

**Issue by YYoshi241** [d0k3/GodMode9#347]
This is one feature that was removed due to adding a RTC. Even if it would only show on the drive labels, that's still more convenient that pressing R+A, and one of my consoles has a broken R button.

**Comment by SirNapkin1334** [comment]
Iirc this was removed due to the fact that that massively increased boot time, especially with large SD cards, due to the fact that it would have to scan the SD on every boot, rather than just when you press R+A. This will not be implemented, and for good reason.

**Comment by SirNapkin1334** [comment]
Option in Makefile perhaps.

**Comment by d0k3** [comment]
I actually wanted to decline this feature request, but the code is already in there. It's just not yet possible to activate it via a Makefile parameter. Anyways, @YYoshi241 - not recommended. The remaining space being displayed is simply not worth the delay it introduces. But, you wanted it, so I'll just make it accessible.

**Comment by SirNapkin1334** [comment]
Yes, Makefile would perhaps not be that good. If GM9 ever gets good write support for TAR (to allow writing directly to VRAM via `V:`) then file-based config would finally be possible in an effective manner. This would allow many things, but then we  could have a flag in there for this. That would probably be the ideal solution.

**Comment by d0k3** [comment]
Okay, added in https://github.com/d0k3/GodMode9/commit/4c97a0939372474989470e63b37da6f9770d3dcf

Compile like this: `make SHOW_FREE=1`.

@SirNapkin1334 - there will never be something like this.
1. TAR is not a writable format. Any size changing operation would require rewriting the whole file from scratch.
2. The actual VRAM TAR resides in the FIRM, which we will not write to for safety reasons.
