### ISSUE TITLE
Support for partition-less SD cards.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#348]
Sometimes, SD cards do not have an MBR and are formatted across the entire block device.
Also, if you do not use EMUNANDs, SD partitioning is totally not necessary and is a waste of space.
Here is an example to format the card partitionless:

    mkfs.fat -D 0x00 -I /dev/sda
Both the 3DS system and CFWs can use such cards.Flashcards (DS and
 3DS) can use such cards too.
The problem:
If you boot into GodMode9 with a partitioned card, unmount it, then insert an unpartitioned card, it says "Initialising SD card failed! Retry?", or it simply freezes.
Suggestion:
1.Proper support for such cards.
2.If possible, an option to format the entire card if the user decides not to use EMUNANDs.

**Comment by d0k3** [comment]
That's a FatFS issue. If FatFS supports this, GM9 will as well. FatFS should support MBR-less SDs, apparently there is a bug when using a SDs with an MBR, then switching to one without. That's a FatFS issue, and is best brought up on their forums.

As for formatting - afaik, FatFS always includes an MBR. You may think there is space wasted there, but the way FatFS formats these SDs is the way the SD association itself suggests and is aligned to the erase blocks. Forcing a certain formatting of the SD card is really not worth the small gain in space you get out of it (how much is it, 4MB?).

**Comment by d0k3** [comment]
Okay, here's a GodMode9 build with an updated FatFS library:
https://f.secretalgorithm.com/7at3V/godmode9-v1.6.3-17-gc5c02a8d-20180418231404.zip

Could you try it and tell me if the problem still persists?

I also made the FatFS authors aware of this issue, but we need to know if the problem still happens with the newest release of the FatFS library.
http://elm-chan.org/fsw/ff/bd/?show=3151

**Comment by pthfdr-42** [comment]
It freezes when I insert the partitionless card.

**Comment by d0k3** [comment]
That looks a lot like a hardware issue. Can you build yourself? You can try building GodMode9 like this: `make SD_TIMEOUT=10` (or a lower value). Be warned, though, this will only battle the symptoms and most likely not solve the issue. Also, building like this causes other problems.
