### ISSUE TITLE
Issue Extracting Dumped File

### ISSUE THREAD

**Issue by Noodlz0797** [d0k3/GodMode9#350]
Hi, I'm having an issue while extracting the dumped .cia file using GodMode9. I dump the .trim.3ds file as a .cia, and when I try to extract it, I do not get the extractedRomFS or extractedExeFS folders, only .bin files. I was told that GodMode9 had not decrypted my file properly. Is there anything else I need to do to properly dump and decrypt my game file?

**Comment by SirNapkin1334** [comment]
You will need a seeddb.bin file in your gm9/support folder. This is required to decrypt certain files (such as CIAs) properly. We cannot provide one here - perhaps you could get some help on the [GodMode9 Discord](https://discord.gg/EGu6Qxw).

**Comment by MadScript77** [comment]
For one thing, you need to make sure your aeskeydb.bin is proper.  There's an AIO out there that both builds it into it's copy of GM9, and includes the file outright (as an added bonus, it can also configure any chainloader from the 3DS).

As SirNapkin explained, you may also need a "seeddb.bin" that contains the game's seed info if it uses seed encryption.  We can't provide that here for what should be obvious reasons.  Google is your friend.

**Comment by d0k3** [comment]
@Noodlz0797 - normally, a `seeddb.bin` file should not be needed for actual carts. Still worth a try, though. Did you get the `seeddb.bin` file and is this still an issue? Can you maybe tell us what cart this was?

**Comment by SirNapkin1334** [comment]
Guess we'll take that as a "it worked."

**Comment by d0k3** [comment]
Fastest fixed issue ever \o/
