### ISSUE TITLE
GM9 cannot display files which names starts with "%".

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#351]
When a file's name starts with a "%", it is hidden from the file list.You can still select it if you know its position, but the cursor does not appear.If you try to rename such files, the filename would be empty.
It is a concern since many people prepend special characters to make a file/directory appears at the top/bottom of a list.

**Comment by MadScript77** [comment]
I don't think this is a bug.  GM9 automatically hides garbage files.

Besides, why would you even do that?  I can see wanting to put "&" in filenames (and that causes plenty of problems in it's own right).  But putting "%" in a file's name, with that being THE character the Windows CMD shell uses for it's variables?  That's not just asking for trouble.  It's BEGGING for it.

**Comment by TurdPooCharger** [comment]
I named a folder `%` and GodMode9 sees it as `dir` . If you name it as `% <insert whatever>`, you get scrambled char.

You still can navigate into the folder and put/retrieve stuff in there.

**Comment by SirNapkin1334** [comment]
@TurdPooCharger that looks like a problem with FatFS. Try doing those things in Windows Explorer on your SD card, or, even better, with CMD, and you might have similar bugs.

**Comment by windows-server-2003** [comment]
I noticed it's displayed correctly on the top left of the bottom screen.
Meaning, curr_entry->name is still correct.
The problem should be in somewhere in DrawDirContents();

**Comment by windows-server-2003** [comment]
I noticed it's displayed correctly on the top left of the bottom screen.
Meaning, curr_entry->name is still correct.
The problem should be in somewhere in DrawDirContents();

**Comment by windows-server-2003** [comment]
Oh, godmode.c#L327
`DrawStringF(ALT_SCREEN, pos_x, pos_y, color_font, COLOR_STD_BG, tempstr);`
This is the problem.
Should be
`DrawStringF(ALT_SCREEN, pos_x, pos_y, color_font, COLOR_STD_BG, "%s", tempstr);`

**Comment by d0k3** [comment]
You could have just made a pull request, @windows-server-2003. Anyways, I'll do it :P
