### ISSUE TITLE
[Feature Request] chainsel/hotkeysel command

### ISSUE THREAD

**Issue by MadScript77** [d0k3/GodMode9#352]
I've been thinking of redoing the kids mode in my AIO project, and maybe creating an easy mode in general (since the primarily appeal is currently to power users).  So that there are not a lot of hotkeys to remember, I was thinking of using a menu-based chainloader like CBM9.  But there's no way to lock CBM9 down for kids, since it's menu has an always-present option to run any payload on the card.

Then it hit me.  Why not just use a script runner as my chainloader?  It has the "boot" command, after all, and I can even build in any scripts I want to use (no need to make them separate script runners).  The only problem is, I can't set a default payload nor hotkey the menu.

However, I'm thinking this would be relatively easy to implement via a single command.  A "chainsel" or "hotkeysel" that uses labels for the options would be simple yet flexible.  It could use a fixed number of characters for that hotkey (one should be enough).  "@chainmenu_r_Settings" for example would assign the R hotkey to that label, and "@chainmenu_d_Luma" would assign that label as the default.  Setting a default should be optional though.  The script waits for input if none is set.  The command would have the usual text string parameter for the purpose of letting the user know it is waiting for input (we could just use two double quotes to leave it blank if using a default).  A hotkeyed label could of course do anything GM9 scripting is capable of, arguably making scripts and script runners using it the most flexible and powerful chainloaders ever.  The possibilities are endless.  People could even add hotkeys to their favorite mega-scripts for fast access to the parts they use the most often.  Just add a new "chainsel" line at the start, place a label for, say, "B" under the main menu label, and place others at whatever parts you use the most.  Instant shortcuts.

To avoid "default" conflicting with "down" on the d-pad (never mind d-pad left and right conflicting with the L and R buttons), the d-pad could use cardinal map directions (n,s,w,e).  And select and start could be "c" and "t" respectively.

The fixed number of characters used for the hotkeys would ensure they could easily be excluded from a labelsel menu.  It could simply use "chainmenu_?_*" for it's wildcard with the above examples, and the options would be listed cleanly without the hotkey being included.

I guess I could just use an existing chainloader to set a default and hotkey the script runner.  But that's a less than optimal solution.

**Comment by SirNapkin1334** [comment]
Well, one thing I like about fb3DS is that you can set a hotkey with multiple buttons held (I.e. R+A+B), so then you could use a longer sequence for the “settings” on kids mode. Thoigh, HOME is much more easy to press.
 
On a completely unrelated note, once GodMode9 gets zip/7z support then all you have to do is download the AIO package, and run a separate “starter” script that allows you to extract everything and which then runs the “main” script.

**Comment by MadScript77** [comment]
See what I mean?  Not easy to come up with something foolproof.  That's why the current implementation uses BootCTR9.

As for the unrelated note, that will be nice.  In the meantime, R12 has added the next best thing -- an "Auto-Setup and Upgrading" option that lets you just copy the configuration folder(s) over as is and have the 3DS set it all up for you.

**Comment by d0k3** [comment]
You now got a `keysel` command at your disposal. Try and let me know what you think, @MadScript77 .

**Comment by MadScript77** [comment]
I'd say with the addition of the "keysel" and "keychk" commands, anyone so inclined can now roll a chainloader that fits them like a glove.  But the "keysel" command's functionality doesn't stop there.  It's functionality can make any menu faster and easier to navigate.  That is a game changer for every megascript author out there.  No more need to "tap, tap, tap" though menus.

Thanks again, @d0k3.  As usual, you've outdone yourself.

There's the slight issue of the splash screen pausing if a key is being held.  So, when using a script runner as a chainloader, you have to press the hotkey, release it when the screen pauses, and quickly press it again.  IIRC, you disabled pausing unless you held R1+Up months ago, but it's apparently still in script runner mode.  Still, I guess that's a separate issue.  I'll consider this one closed.

**Comment by d0k3** [comment]
I'll remove the pause from scriptrunner mode and limit it it to the same keycombo.
