### ISSUE TITLE
NCCH Image Options not showing up

### ISSUE THREAD

**Issue by goombado** [d0k3/GodMode9#357]
In GodMode9, when I press <A> on any .app file inside the content folders of their respective title IDs, I am not given the NCCH Image Options button. I have tried uninstalling and updating GM9, and I can also still view NCSD options of .3ds files. Is there something I haven't done properly when setting up GM9? I'm on an o3ds btw.

Thanks, 

goombado

**Comment by goombado** [comment]
![snap_180423192935](https://user-images.githubusercontent.com/5777750/39118619-212db2fa-472d-11e8-8b63-00b5c4d11ffa.png)

Here's a screenshot for reference

**Comment by goombado** [comment]
I can also confirm that after mounting a 3ds file from my gamecart to its own drive and selecting a .app file from there, I was given the NCCH Image Options option. It just seems that this is not appearing with any of the .app files on my SD Card

**Comment by d0k3** [comment]
To access the installed .apps on your SD card you need to use drive `A:/`. The contents on `0:/` are encrypted, only `A:/` gives you unencrypted access. Does that solve it? If so, please close.

**Comment by goombado** [comment]
Yes it did, thank you
