### ISSUE TITLE
[Feature Request] Increase MAX_DIR_ENTRIES

### ISSUE THREAD

**Issue by gingerbeardman** [d0k3/GodMode9#360]
I have a directory containing 1966 files

GodMode9 only lists the first 1025

```c
#define MAX_DIR_ENTRIES 1024
```

Thanks for your consideration.

https://github.com/d0k3/GodMode9/blob/master/arm9/source/filesys/fsdir.h#L5

**Comment by wabberz** [comment]
Having too many files in a directory will make listing them _very_ slow. Of course it is possible to raise the limit (if that doesn't create memory issues), but I would advise you to sort the files into multiple folders. It will speed things up dramatically.

**Comment by gingerbeardman** [comment]
I think you're right, though GodMode9 has the fastest directory listing I've seen on 3DS.

**Comment by SirNapkin1334** [comment]
The real problem is not the entries limit, but why you would have so many entries in the first place. 1024 is a good number, and the 3DS doesn’t have much memory. I suppose you’re welcome to edit that value and compile yourself.

**Comment by gingerbeardman** [comment]
Original 3DS has 128 MB RAM
New 3DS has 256 MB RAM

How much extra memory is used increasing MAX_DIR_ENTRIES from 1024 to 2048?

A quick calculation shows that the DirEntry struct takes up about 270 bytes,
so DirStruct with 1024 entries takes up 270KB
and DirStruct with 2048 entries takes up an extra 270KB, so 540KB total.

Surely that's a really reasonable request?

**Comment by gingerbeardman** [comment]
It's funny because @urherenow assumes I have no idea what I am doing because they have no idea what they are doing 😄 

I calculated it based on the contents of `fsdir.h` 

char* = 1 byte
char[256] = 256 bytes
u64 = 8 bytes
EntryType  = 1 or more bytes (I picked 5 bytes to be generous)
u8 = 1 byte
TOTAL = 256+1+8+5+1 = 270

I'm interested what the results of sizeof() are @linouxis9

**Comment by urherenow** [comment]
1) I was asking a question, hence the question mark at the end of the first sentence.

2) Github isn’t a kiddie forum. There’s no need for name calling, and it will not be tolerated. Grow up.

3) How exactly does using sizeof tell you how much ram is being used? I’ll ask again: Does every entry use a whole buffer block (maxlen of an entry) regardless of actual length? Or are you simply calculating the maximum possible amount of RAM needed for 2046 entries of maxlen? If the former, that would be very inefficient.

**Comment by Wolfvak** [comment]
Gonna chime in to settle the size once and for all...

Current DirEntry:
```C
typedef struct {
    char* name;         -> 4 bytes (it's a pointer)
    char path[256];    -> 256 bytes
    u64 size;              -> 8 bytes
    EntryType type;   -> 2 or 4 bytes, depending on how GCC is feeling today
    u8 marked;          -> 1 byte
} DirEntry;                -> not packed, so it'll be aligned to the higher 4 byte boundary
```

This gives it a size between 272 and 276 bytes, pretty close to the one estimated in the first post.

Now, MAX_DIR_ENTRIES could be increased but the heap is already pretty close to it's limit as-is, mainly due to stuff we can't control like lodepng. Taking space from the ramdisk would be the only feasible option, and I don't see why it can't be done (4-8MB less wouldn't hurt too much, I think).

In the end, though, what about when people starting complaining about directories with >2048 files? What about >4096, >8192, etc? Increasing this value isn't a fix, it's merely a temporary solution.

The real solution is either being sane for once and have directories with less than 1024 files.

**Comment by d0k3** [comment]
Eh, be nice to each other. ~300kB is around right. Problem is, if I just increase it, the next guy comes around and wants more. Not good. You shouldn't even have that many files in one dir. But I get the problem. Let me think about that one for a bit, alright?

**Comment by Wolfvak** [comment]
@urherenow "Does every entry use a whole buffer block (maxlen of an entry) regardless of actual length? [...] If the former, that would be very inefficient."

Depends on what you mean by "inefficient". It does take a lot of memory (relatively speaking) but it's also _really_ fast.

Having to allocate and free 272-276 byte blocks every time you open a directory would be the inefficient choice.

**Comment by gingerbeardman** [comment]
Thanks all, and thanks @d0k3 for your consideration

**Comment by urherenow** [comment]
Awesome. Thank you very much! For both explanations.

**Comment by SirNapkin1334** [comment]
Is this a romFS dir/subdir? Because perhaps the best solution would be to set it to above the amount of files in the romFS dir/subdir known to have the most. No sane person should have that many files in a dir besides that.

**Comment by d0k3** [comment]
Alright, I did it. I don't like this solution for the reasons mentioned earlier, but I guess it works for now. If we ever have to increase that again, I'll have to think of something better.

**Comment by gingerbeardman** [comment]
Thank you

**Comment by d0k3** [comment]
Ugh

**Comment by SirNapkin1334** [comment]
Oh, dear.

**Comment by d0k3** [comment]
Handling that properly would require either reserving an unreasonable amount of memory or putting in an unreasonable amount of time and rewrite a lot of stuff. Both are off the table for now, I may think about it later.

Also: goddammit, who in their right mind puts that many files into one dir? :/

**Comment by gingerbeardman** [comment]
A computer program? 😂
