### ISSUE TITLE
Issue building updates and DLC as CIAs

### ISSUE THREAD

**Issue by ClubShrimp91** [d0k3/GodMode9#361]
Hi there, I'm new to the 3DS hacking scene, and I can't seem to build CIAs from the .tmd files in the directories for update and DLC files (for use with Citra). I download and install them via freeshop. Am I trying to build CIAs from the wrong files? Should I be building them from the .app files instead?

FYI: I'm trying to make CIAs of the episode DLC for Moon Chronicles, the 2.3 update for Yo-Kai Watch Busters: Akanekodan, and the update for Go! Go! Kokopolo 3D. There's also "content data" DLC for Yo-Kai Watch Busters Akanekodan which was installed in the DLC directory alongside said update. Attempting to make CIAs from all these things' respective .tmd files fails.

Sorry if this is a total noob question and not a real issue, I just can't seem to find any information about this through google.

P.S. I know that Citra can't handle DLC just yet, but I'd like to have any DLC ready for when they inevitably (?) figure it out.

**Comment by d0k3** [comment]
Should be fixed in the meantime. @ClubShrimp91 - try with the most recent release. If there are still issues, feel free to reopen.
