### ISSUE TITLE
[Feature Request] Hotkey-based equivalents of the 'filesel' and 'dirsel' commands.

### ISSUE THREAD

**Issue by MadScript77** [d0k3/GodMode9#364]
The "labelsel", "filesel", and "dirsel" commands all work seamlessly together because they all use the same form of navigation.  That is, they all use cursor-based navigation.  So selecting menu items, files, and folders all works the same way.

That seamless nature goes to Hell in a handbasket when you switch to 'keysel' though.  Now you have hotkeys for your menus, but it's back to "tap, tap, tap" whenever you bring up a file or folder list.

To resolve this lack of uniformity, I propose 'filekey' and 'dirkey' commands that will list each file/folder with a hotkey next to it that you simply press, instead of having to use a cursor.  Whether you want to let users specify the order, or just have it be fixed, I leave to you.  Fixed order works for me.  For example:

A, X, Y, L, R, LEFT, RIGHT, SELECT, START

If there are more than 9 files/folders, UP and DOWN would provide Next/Previous page functionality.

IMHO, a fixed order keeps it simple.  The first thing listed would always be A, the second thing listed would always be X, and so on.  This may take some getting used to at first, but once people get accustomed to the notion of picking a hotkey based on a file/folder's location on the list, they will love it.  Think of it like having a numbered/alphabetized menu in an app or game (i.e. USAAF for the Atari 800).  The entries on that menu may change, but 1/A always picks the first one on the list.

**Comment by d0k3** [comment]
Can you give me a usage example where this would make a lot of sense? Selecting files in that manner sounds confusing to me.

**Comment by MadScript77** [comment]
Well, I do still have two menus that I cannot make work with 'keysel' due to their dynamic nature.

The "Switch Chainloader" section of "Settings" since it uses dummy files to list the inactive ones.  That would be the more confusing one to place it on, since position is naturally going to be affected by the one that is missing.  The same chainloaders will be selected by more than one key.  This would take some getting used to because your mind has to learn to associate the key with the on-screen position as opposed to a specific name.

Then there's the "Toggles" app (the new Extra Options) that has, well, toggles.  One says "ReiNAND Defaults to SysNAND" for example.  If you hit it, it changes and says "ReiNAND Defaults to EmuNAND" then.  If you hit it again, it switches back.  It's a 'filesel' menu, and this fake toggle is really just two labeled sections.  In this case they create and delete the "loademunand" dummy file that tells ReiNAND to load EmuNAND as the default.  Each one deletes their own dummy file and creates the other's.  The other two are "Kids Mode is Disabled/Enabled" (adds/removes the "Kids Mode" chainloader to Settings) and "Stealth Mode is Disabled/Enabled" -- my attempt to make an invisible mode for public use, say Pokémon tournaments, that's only partially working atm).  Nothing moves around on this one, so it would not be confusing at all.

I also have my custom chainloaders (the one I had you add 'keychk' for) use renamed payloads to self-configure.  Even the easy mode and kids mode ones let you pick Luma or Rei as the default.  The 'hardcore power user' one sets it's hotkeys by doing a 'filesel' on the chainloader's payloads folder, then another 'filesel' on the main payload folder, then copying the latter to the former.  Given all the payloads I include in my AIO, selection would be much faster with something like this.

While we're on the subject, an option to hide extensions would improve the look of said feature.  Seeing, for example, "R+A.firm" instead of simply "R+A" on the menu that says "Select a hotkey" just doesn't look right.

**Comment by d0k3** [comment]
Okay, after some thinking... these dummy files have always been some kind of a workaround, right? What if you introduced config files instead? That idea is still a bit raw, but you could, f.e., have one file and write bytewise to it (one byte = one setting) via `fread` and `fwrite`. Sure, it would make the script more complicated, but you could hold stuff in global variables and just only read / write the config file at the end / beginning.

**Comment by MadScript77** [comment]
That would work for keeping track of some things.  Like which chainloader is currently active.  Still looking at label doubling per toggle to account for every possible combo though.  Just those 3 would need 8 a piece (4 for the on position, 4 for the off position, to account for the possible settings of the other two).  

I think a good alternative might be to have keysel accept multiple entries (with or without wildcards).  They could be comma/semicolon delimited or something).  I could set the initial wildcard up at the start (which would automatically list all static options that do not change), then check the toggle states and add the correct labels for them.  I could have something like $[LABELWILD] set to a default wildcard, then "set LABELWILD "$[LABELWILD],ReiEmu" to have it add "Rei-Six Defaults to EmuNAND" if the "loademunand" file is found.

**Comment by d0k3** [comment]
@MadScript77 - is this issue still relevant? If it is, I'll try to look into it (can't promise when, though).
