### ISSUE TITLE
[Feature Request]Support importing/exporting/editing/clearing save data and extra data for titles

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#367]
As the title said. There are utilities like Save Data Filer, JKSM, and Checkpoint that can back up such data, but they do not work on system titles. Also, you have to install another application.
I do not think that the function is hard to implement.

**Comment by ihaveamac** [comment]
it's actually much harder than the other tools, which are running in the "3DS OS", and so can use system functions to access save data. GodMode9 is an arm9 program, so it would have to interact with the raw save archives directly.

**Comment by d0k3** [comment]
As @ihaveamac said - doing so on ARM9 would require research and a lot of coding. Not possible for now.
