### ISSUE TITLE
Option missing

### ISSUE THREAD

**Issue by chronoss09** [d0k3/GodMode9#37]
There is no “Restore H&S” in “More…” option with the last build of GodMod9 when i press "Home" boutton...

**Comment by d0k3** [comment]
Well... you injected in an earlier version of GM9 (v1.0.0) and now you can't find the option to restore it, right?

Try this test build:
https://transfer.sh/LIbng/GodMode9-20170405-003025.zip

.. then let me know if that worked for you

**Comment by chronoss09** [comment]
I used the last version (1.07), and it's ok now, i've “Restore H&S” in home menu :)

and can you tell me why i can't launch Luma without SD card, I have the file "arm9loaderhax.bin" from Luma in SYSNAND CTRNAND but it can't boot :(, i use the last build for Luma...

**Comment by d0k3** [comment]
Tha last one is an issue for Luma 3DS rather than here. I suggest you check the guide again and then, if you still haven't found a solution, open an issue there. Closing this now...
