### ISSUE TITLE
Make screen turn off when lid switch triggered

### ISSUE THREAD

**Issue by ParzivalWolfram** [d0k3/GodMode9#370]
Making the screens turn off when the lid switch is triggered would be a good thing to add (and probably easy...)

It'd let people who dump files/NAND or convert 3DS-format ROMS to CIAs on battery without worrying as much about whether or not they have the battery for it (basically it'd let long operations not eat as much battery, aways a good thing IMO)

**Comment by d0k3** [comment]
Thought about it, and, nope, we won't do that. It's also not as easy as you may think.

Additional info: You don't need to worry about the screens that much. The 3DS screens seriously don't need that much power when compared f.e. to a ongoing file operation on the SD. Plus, with the lid closed you won't even notice when your console turns off. Either have a fully charged battery or plug it in when doing large file operations or, in general, running GM9 for a long time.

**Comment by ParzivalWolfram** [comment]
It'd also prevent screen strain/burn-in/whatever-the-temporary-screen-burn-in-thing-for-LCDs-is-called if you did add this, but yeah, I see what you're saying.
