### ISSUE TITLE
Compiler warnings with latest devkit

### ISSUE THREAD

**Issue by urherenow** [d0k3/GodMode9#371]
Just installed a fresh environment with dkp-pacman and it may be showing a bunch of possible bugs (or 1 that affects a lot) Many warnings similar to this:

source/virtual/virtual.c:102:5: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
     strncpy(lpath, path, 256);
     ^~~~~~~~~~~~~~~~~~~~~~~~~

and these

source/virtual/vcart.c:47:13: note: 'snprintf' output between 11 and 34 bytes into a destination of size 32
             snprintf(vfile->name, 32, "%s.split.001", name);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source/virtual/vcart.c:43:42: warning: '.split.000' directive output may be truncated writing 10 bytes into a region of size between 9 and 32 [-Wformat-truncation=]
             snprintf(vfile->name, 32, "%s.split.000", name);
                                          ^~~~~~~~~~
source/virtual/vcart.c:43:13: note: 'snprintf' output between 11 and 34 bytes into a destination of size 32
             snprintf(vfile->name, 32, "%s.split.000", name);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by d0k3** [comment]
Yeah, known issue. Some of them are false positives. There is nothing too severe in there. There are still some places in the code that I can make a little safer. Will be fixed.
