### ISSUE TITLE
Add functionality to check the SD/NAND FAT filesystem.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#372]
It is not uncommon to hold the power button on 3DS' to force shutdown.
Especially with CFWs where the system hangs.
I think that add a `fsck` function would be beneficial, as you do not need a PC to do so. There are already utilities on NDS flashcards that could run on an OG NDS, and you can have 4MiB of space for a FIRM, resources should not be a problem.

**Comment by d0k3** [comment]
Agreed that this would be a nice addition, but, you know, FAT stuff is handled by FATFS, and that doesn't provide any functionality like that. Add to this that checking the filesystem is not exactly trivial (neither is FAT in general).

Anyways - no, you don't need to check your SD card everytime you force shut down. Even in that case corruption is not that likely. You can check it just to be safe, of course.
