### ISSUE TITLE
Directly show battery percentage instead of battery icon.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#373]
Judged by [this commit](https://github.com/d0k3/GodMode9/pull/247/commits/376d9a109fe474df3bb58f7edb3e614ee2655c95), it looks like that GM9 is already able to read the battery percentage.
Then just show that value.

**Comment by d0k3** [comment]
Not the first one to ask this. We also need to save space in the top bar. The icon should be good enough. An actual percentage is for OCD people.

Also, @SirNapkin1334, correct. That's why we only check each 15 seconds.

**Comment by d0k3** [comment]
So, closing this. We'll stick with the icon.

**Comment by pthfdr-42** [comment]
Then maybe you could make it a compile option in the Makefile.

**Comment by d0k3** [comment]
Well, custom stuff like that makes the source hard to read. I Decided against even making it a compile option. If you want to try it for yourself, I can give you some pointers where to start. In that case, contact me on the GM9 Discord, on IRC or on GBAtemp.
