### ISSUE TITLE
Suggestion:Change the color scheme.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#376]
Maybe you should use a color scheme like [Solarized](http://ethanschoonover.com/solarized)?
It should be simple since it seems that only this file needs to be modified:
GodMode9/arm9/source/common/colors.h

**Comment by d0k3** [comment]
If you want a new colour scheme, do it yourself. You already know where to look. You can even submit it back to me, and I may make it the new standard or provide it as an alternative.
