### ISSUE TITLE
Suggestion: Add support for CRC32 and MD5 and SHA-1

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#377]
Most ROM dats only use those, so this would be useful for encrypted ROM dump verification without actually having to dump the ROM.

**Comment by d0k3** [comment]
While this may sound like a good idea on paper, I doubt it will be that useful in actual usage scenarios.

So, you want to use the 3DS' slow SD card reader to calculate the checksum of a 1GB+ dumped rom file. After you got the checksum (will take a few minutes), you need to pull up a checksum from the web to compare to. Manually. That won't be quick.

Taking out the SD card and using a proper computer tool for the job sounds a lot more appealing in comparison and will not take longer.

I may rethink this if you can give me a proper usage scenario. For now I just think it is not worth the effort.

**Comment by ihaveamac** [comment]
SHA-1 is in the hardware too I think so it shouldn't be too hard to support that.

https://www.3dbrew.org/wiki/SHA_Registers

**Comment by Wolfvak** [comment]
@ihaveamac you can't do both SHA-1 and SHA-256 at the same time, the engine just doesn't support it.

**Comment by ihaveamac** [comment]
"same time" as in, calculating both at once? It wouldn't have to be that though. or did I miss something?

**Comment by Wolfvak** [comment]
The SHA engine is used implicitly in a lot of places - using SHA1 could cause bugs like [this](https://github.com/d0k3/GodMode9/issues/346) (AES code in cart was breaking against the main AES code, the solution is mutual exclusion, which can't be done as easily with the SHA engine since you can't store the internal state).

**Comment by d0k3** [comment]
In theory, we could calculate all those checksums at once and it would only take a little longer. We would need a SHA-1 software implementation of course. 

I doubt that would be any useful though (see above). Displaying all those checksums would rather confuse users.

**Comment by Whovian9369** [comment]
If possible easily, why not write all the hashes you are willing to make to a text file (along with the usual SHA file)?
For the "power users" like myself, it would certainly be QUITE useful for checking the dump on a computer later, without the need of a hex editor to get the SHA256 from the SHA file.

**Comment by d0k3** [comment]
Okay, after some consideration - SHA-1 doesn't really make sense. We already have a CRC32 implementation (thanks @Hyarion-SS), but we don't have a MD5 one, and I won't do one from scratch. I simply don't see the usefulness of this request yet, so I'd rather work on other stuff.

Anyways, that being said, I'm closing this request now. Pull requests are accepted, though. If anyone is willing and able to do a quality MD5 implementation, I'm willing to take it over.

**Comment by Dimensional** [comment]
Sorry to bring this old topic back up, but the only reason I see the use of SHA1 and MD5 is for archival purposes similar to the Dat-o-Matic project by No-Intro. Currently their records only use CRC32, MD5, and SHA-1.

**Comment by mariomadproductions** [comment]
I basically said that in my post :P.
I think at some point in the future No-Intro should (maybe optionally) add SHA-256.
