### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by catkid15368** [d0k3/GodMode9#378]
I would like to be able to put my own ds roms onto another cart. Like say I have a CoD: Modern Warfare cartridge. I would like to be able to put a CoD: World at War nds rom on it.
   It always tells me... "Not allowed in virtual path." Please add this feature.

**Comment by urherenow** [comment]
Not ever going to happen. In what world do you think game carts can be written to? Not. Possible.

**Comment by catkid15368** [comment]
It would be a good thing. I figured if you can do it with a card reader, you could do it with gm9 or something.

**Comment by Wolfvak** [comment]
wtf? That's not how it works. At all. Can't be done, at least not without specialized hardware.
