### ISSUE TITLE
Cannot build CIA from game cart

### ISSUE THREAD

**Issue by geetry** [d0k3/GodMode9#379]
I'm trying to build a CIA from a game cart of a Pokemon game. I have gm9 set up on my SD correctly, but whenever I launch gm9 to build a CIA of ANY cart (I tried 5 or so), it cannot build the CIA. I'm not sure if I'm doing anything wrong, I've done some googling around and can't seem to find anything. The carts themselves aren't damaged whatsoever. I do have the latest version of gm9 on my SD.

Thanks.

**Comment by d0k3** [comment]
Is there enought space on your SD cart?

**Comment by d0k3** [comment]
This needs more info, or I'll have to close it. @geetry, can you just copy the roms? Also, check your SD card.

**Comment by d0k3** [comment]
Okay, this misses info and was user error, most likely. @geetry - feel free to reopen and/or add info at a later point. I'm closing this now.
