### ISSUE TITLE
GM9 Data abort error

### ISSUE THREAD

**Issue by Theorvolt** [d0k3/GodMode9#38]
My console:
2ds on 11.3.36-E
Luma CFW + A9LH
Attempting to launch GM9 using chainloading but shows the following:

Here is the error displayed: http://imgur.com/a/xx02b

And here is the dump: https://www.dropbox.com/s/xgekh5in7cyhyzj/crash_dump_00000002.dmp?dl=0

The build of GM9 on 3ds.guide did work for me but this keeps on failing.

**Comment by d0k3** [comment]
Okay, I need more info. Is anything special about your console? Can you try with a different SD card? And, what build of GodMode9 did you use, the most recent nightly? Or v1.0.7?

**Comment by d0k3** [comment]
@Theorvolt - we need more info. I haven't been able to retry this issue on a recent nightly. Maybe you can try this?
https://transfer.sh/PCg1S/GodMode9-20170409-104817.zip

**Comment by MelonGx** [comment]
Personally I never saw any ARM9/ARM11 error happened on chainloading.
May you try re-installing A9LH by the entire steps of 3ds.guide 's "Updating A9LH" session?

**Comment by d0k3** [comment]
Nah, this can't be related to the A9LH install. A9LH either works or it doesn't, there is nothing in between. @Theorvolt - I'd at least need to know what version of GM9 this happened on and where you got it from. Otherwise, if no more info is provided, I'll have to close this pull request.

**Comment by d0k3** [comment]
Alright, I have to assume @Theorvolt has got this solved. Feel free to reopen if you can add anything to this issue.
