### ISSUE TITLE
cannot extract exefs and romfs from file

### ISSUE THREAD

**Issue by MirrorKnight95** [d0k3/GodMode9#382]
Hello, i have been following the most recent guide on youtube on how to randomize pokemon alpha sapphire and ive done everything they showed to do but when i click on the "extract" file to extract the exefs and romfs the command window just opens and closes immediately, not having done anything. I tried finding the solution and cant seem to find anything.

Thanks

**Comment by d0k3** [comment]
You know that this is the GodMode9 issues section and not a general support forum? For command line tools ask elsewhere. I'm closing this now.
