### ISSUE TITLE
[Rename not working]

### ISSUE THREAD

**Issue by catkid15368** [d0k3/GodMode9#386]
Whenever I click on the .app to rename it to "Something good", it says it can't and I should try decrypting. When I try to decrypt it, it says file not encrypted.

**Comment by SirNapkin1334** [comment]
More detail needed. Where is this .app located? Is it a gamecart? What’s the game?

**Comment by catkid15368** [comment]
Here is what I do...
I Go to 0:/cias
I click on my SmileBASIC (U).cia.
The options come up I press [A] on "CIA image options..."
I press [A] on "Mount image to drive"
I goto the 0001.000000005 and click on it
I click on "NCCH image options"
I click "Rename file"
It says...
**Rename to a good name?**
I press [A] and it says "Unlock write permission for game images is not allowed."
I press [A] to continue and it says "Could not rename" "(Maybe try decrypt)" What does that even mean. Does it mean use decrypt9?
Please help.

**Comment by SirNapkin1334** [comment]
You can’t do that. You have to copy it out of the mounted image to another place. It’s because it can’t unlock the write permission. Please Close this.

**Comment by d0k3** [comment]
Ah, hold on. @SirNapkin1334 - you are right. But I should change the error message, this is a little misleading. Better to keep this open for now.

**Comment by d0k3** [comment]
I just asked to keep it open :).

@catkid15368 - I'll change the error message. You really can't rename stuff there, but the error message is misleading.

**Comment by d0k3** [comment]
Okay, this is all I can do for now. Error message is now less misleading.
