### ISSUE TITLE
[feature request] .sarc ; .arc ;and .szs file mounting +

### ISSUE THREAD

**Issue by YYoshi241** [d0k3/GodMode9#389]
many 3ds games use these formats and they should just be archives and wiiXplorer can mount .arc

and show two places past the decimal in folder/file size ie:sdcard=3.72 GB instead of 3.7 GB (or when pressing R+A)

**Comment by YYoshi241** [comment]
I know the second thing is not related. So what?

**Comment by legoj15** [comment]
From my experience, there are A LOT of different types of .arc files. Supporting even the most common of them would probably fill the issues page with "godmode9 does not read arc file" or something similar. Can't say anything for the rest though.

**Comment by YYoshi241** [comment]
makes sense

**Comment by d0k3** [comment]
In GM9, mounting is only possible for uncompressed contents and recursive mounting (that means mounting something from inside a mounted file) is not possible. All of these formats seem to be compressed ones, there is only little documentation for each, and, on top of that, what @legoj15 said.

So, not looking too good for this. Leaving this open in case something is added to the discussion.

**Comment by mariomadproductions** [comment]
There isn't that much use for this, as these archives are usually relativity small, so moving them to a PC for decompression there shouldn't be a problem.

**Comment by d0k3** [comment]
Okay, I'm deciding against this. Closing this now...
