### ISSUE TITLE
[feature request] GodMode9-NTR: Adding access to flashcart's sd storage 

### ISSUE THREAD

**Issue by MrTSXV** [d0k3/GodMode9#390]
Hi,
Is it possible to add file system access to the sd inserted to an flashcart?
This would be awesome, because removing the NEW3DS back-plate every time to add files is a pain. The back-plate also has some  limitation in durability. It also take some time to do it carefully and not destroying or banding it.

**Comment by SirNapkin1334** [comment]
Short answer: no. Long answer: yes, but this is very complicated, and if we try to implement it, we’d have to implement it on other flashcarts, and on top of that each one is different - for example, a parsing command on one is a deletion command on another (this example is true). While it’s possible, it’s not worth it.

**Comment by knight-ryu12** [comment]
Also addition:
not all flashcart even support SD card access from cart bus.

**Comment by d0k3** [comment]
What @SirNapkin1334 and @knight-ryu12 said. I'll add it - if someone else does the lib for it. No one did so far, though, and for a very good reason.

@MrTSXV - why not use FTP? It's faster than you may think and it's what I do. I basically only open the backplate for very large transfers. [3DShell](https://github.com/joel16/3DShell/releases) has an excellent FTP server built in.

**Comment by MrTSXV** [comment]
Okay, I understand that even if it would be a great addition to GodMode9.

@d0k3 Because using homebrews on a 3ds (arm11) connected to the internet is a risk of being banned sooner or later by BigN.

OT: Is it possible to implement wifi access to Godmode9? Maybe console to console transfer, like the phone from the 90s did over bluetooth. But I doubt it. (limitation of the ARM946 code)

**Comment by d0k3** [comment]
> @d0k3 Because using homebrews on a 3ds (arm11) while connected to the internet is a risk of being banned sooner or later by BigN.

Aw come on, just disable telemetry and you're good to go. Each and every case of a ban so far could be traced back to either telemetry or something even more reckless (playing an unreleased game online, anyone?). 

We've got no wifi driver in baremetal ARM9, and I doubt we will ever have one, so that won't work either as a means of file transfer.

**Comment by MrTSXV** [comment]
@d0k3 
Since you are one of the most talented coders in the 3ds scene, I will believe you. Whatsoever, see how far GodMode has become, at this point it in time it is truly a "God" mode. Only time will tell how far it will improve even further.

Best regrets.

**Comment by SirNapkin1334** [comment]
There’s a reason it’s GodMode9 and not GodMode11.
