### ISSUE TITLE
[Feature Request] Option to manually trim .nds files

### ISSUE THREAD

**Issue by DMSalesman** [d0k3/GodMode9#392]
First of all, please excuse me as I might be saying a bunch of nonsense.

I noticed that, by browsing the contents of a DS cart, two files can be seen, ending with `.nds` and `.trim.nds` respectively. As the first one's size is a power of two, I'm assuming that the latter is an `.nds` image whose padding garbage has been scrubbed away.

Would it be possible to allow an user to manually trim non-trimmed `.nds` roms?

**Comment by d0k3** [comment]
Okay, while this wouldn't be hard to do, I'm unsure it would make sense. It would further clutter the menu, and the menu is already somewhat full for NCSD files.

**Comment by fox8091** [comment]
It makes sense to clean up existing dumps, and the NDS menu shouldn't be that cluttered?

**Comment by d0k3** [comment]
Yup, but if I do it, I do it right, meaning for NCSD, too. Maybe even add .gba trimming.

**Comment by d0k3** [comment]
Whatever, I guess I'll do it. Not for GBA files (there's no proper way of trimming them), but for all files that support it, including FIRMs.

**Comment by DMSalesman** [comment]
Perfectionism in a dev is always appreciated, d0k3. Thanks for considering the proposal.

**Comment by d0k3** [comment]
Okay, it's in there and will be in the next release (or, in the nightly, for now). Testing is appreciated.

The trimmer will work for FIRMs, NAND images, NCSD (.3ds files), NCCH (which are almost always already trimmed) and NDS images. Did I miss a file format?

**Comment by legoj15** [comment]
I trimmed an nds rom that I use with DSiMenu++, and it still booted, so from what I've seen the trimming works properly. Great addition.
