### ISSUE TITLE
RedNAND partitions not visible in gm9

### ISSUE THREAD

**Issue by CecilFF4** [d0k3/GodMode9#399]
The implication of your app's readme is that rednand partitions should be visible (i.e. rednand ctrnand should be drive 4). Yet my freshly formatted SD with the sysnand cloned to the rednand doesn't show up in the drive menu, no matter how many times I format it. Is gm9 only meant to show the partitions of full nands (like the GW emunand)?

**Comment by d0k3** [comment]
How did you clone the SysNAND to the RedNAND? Did you format the card in GM9? And yes, I have a minimum size RedNAND myself, it shoudl show up.

**Comment by d0k3** [comment]
Also, does it also not turn up after a reboot of GM9?

**Comment by CecilFF4** [comment]
I created the rednand on a freshly formatted 2GB card and cloned the sysnand to the rednand using the gm9 sd format menu. I restarted the app and I reseated the sd card. Also redid the process a couple times. No emunand partitions in the menu.

I'm on a N3DSXL and used a 2GB card mostly to just experiment with a part of gm9 I've never used and also to help another user troubleshoot their problem. My minsize nand is 1240MB, leaving 650MB free space formatted as fat32.

**Comment by CecilFF4** [comment]
Just tested with a 32GB card formatted with the gm9 sd format menu. Still no luck; it does the same as the 2GB. It clones the sysnand to rednand and says it was successful. I can even direct luma to boot from it fine, but no emunand partitions show in the gm9 menu.

**Comment by d0k3** [comment]
Are you really sure? I can explain the 2GB card not showing the RedNAND, that was a safety thing implemented earlier for small SD cards (might not be relevant anymore, I have to check). There should be no trouble at all with a 32GB card, though.

**Comment by CecilFF4** [comment]
Well, it's a pretty simple process, isn't it? I put my 32GB micro SDHC ADATA card (which is verified with h2testw) into my console which has GM9 v1.6.3-56-g6a04bfca running, I select the SD format menu, then select RedNAND size (min), then let it clone my SysNAND to my RedNAND. Afterward, I restart the app and no RedNAND partitions show in the main menu.

As part of troubleshooting, I've also booted into the last stable version of decrypt9 and it says "EmuNAND ready," yet any operation dealing with the EmuNAND leads to an error accessing it ('NAND Backup/Restore: failed!").

**Comment by d0k3** [comment]
Here's a test build for you:
https://f.secretalgorithm.com/nY3kI/godmode9.firm

Should recognize the RedNAND right after formatting. Please test with both SD cards.

**Comment by CecilFF4** [comment]
No, these cards have never had a GW EmuNAND. They were both freshly formatted with a RedNAND. I just remember from a very long time ago that the GW EmuNAND I had back then was a full-size version and decrypt9 could access that.

**Comment by d0k3** [comment]
GW EmuNAND ist *always* full size. And a format doesn't wipe all the data from a card (in fact, a quick format just recreates the MBR, the FAT header, the FAT tables and the root dir). Anyways... let me know if the test build helps. Also, don't forget about that other issue :).

**Comment by CecilFF4** [comment]
No, sorry, that didn't show anything different. No RedNAND partitions. This is what it always looks like after setting up the RedNAND.
![snap_180723143547](https://user-images.githubusercontent.com/12663305/43098791-c5a9a4e8-8e85-11e8-8a2f-5db895b21e3b.png)

**Comment by d0k3** [comment]
Try this one:
https://f.secretalgorithm.com/Ezv1X/godmode9.firm

And, make sure to format and clone again in case still nothing shows up.

**Comment by d0k3** [comment]
Okay, just found something else I actually fucked up. Please wait a bit for the next test build.

**Comment by CecilFF4** [comment]
Yup, that worked. Thanks! I'll get to work on that other issue later tonight probably.
