### ISSUE TITLE
Unable to decrypt game

### ISSUE THREAD

**Issue by arcues19875** [d0k3/GodMode9#406]
Hi there, new to this modding experience so please forgive me.

I'm trying to decrypt my Ultra Sun game.. but every time I go to do so, I just get Decryption failed.

Have I done something wrong? Thanks

**Comment by d0k3** [comment]
No I've done something wrong. It's already fixed, though. You can grab the fixed script from here:
https://transfer.sh/%28/mkHBZ/NANDManager.gm9%29.zip

**Comment by d0k3** [comment]
Ooops, mixed up the issues.

**Comment by d0k3** [comment]
Okay, @arcues19875 - I will need some more info? Is Ultra Sun installed? If not, you may need an up to date `seeddb.bin`. Maybe also an up to date `encTitleskeys.bin`. Put both into `0:/gm9/support`. Does that fix it?

Can't help on sources for these two files. There may be some well known titlekey site somewhere.

**Comment by d0k3** [comment]
@arcues19875 - can you provide more info?

**Comment by arcues19875** [comment]
@d0k3 sorry for the late response. I'm trying to decrypt my Ultra Sun game directly from the cartridge. Haven't installed it by making it a .CIA if that's what you mean. Nor have I got the seeddb file.

**Comment by d0k3** [comment]
I need to confirm this by having someone else try decrypting that cart. In the meantime, can you tell me the exact steps you did?

**Comment by d0k3** [comment]
Hold on, which file did you try tp decrypt? You can't decrypt the split parts (.000 / .001). You need to use the .trim version to decrypt. Does that solve it?

**Comment by arcues19875** [comment]
I've tried to decrypt the .trim file instead of the parts.

Steps I used were as follows


   1. From the root GodMode9 menu, navigate to [C:] GAMECART.
   2. Select [TitleID].trim.3ds, then select NCSD image options..., then
   select Decrypt file (0:/gm9out).
   3. Once this process completes, the game will be a .3ds file inside
   /gm9/out/.

**Comment by d0k3** [comment]
So, it worked now?

**Comment by arcues19875** [comment]
No sorry. I made a mistake in my post.

I used the .trim originally. I followed the steps that were pasted in my
previous reply. Its still not working. I can try again tonight.

**Comment by d0k3** [comment]
Okay, does it fail immediately? Or does it do something before it fails? Also, what's the size of the trimmed file?

**Comment by d0k3** [comment]
Might be a dumb question, but do you have enough space free on your SD card?

**Comment by arcues19875** [comment]
As far as I'm aware.

On 4 Aug. 2018 10:05 pm, "d0k3" <notifications@github.com> wrote:

Might be a dumb question, but do you have enough space free on your SD card?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/d0k3/GodMode9/issues/406#issuecomment-410446445>, or mute
the thread

**Comment by d0k3** [comment]
Doublecheck that. Not enough free space is a very likely reason. Also make sure the SD card is okay (check it in a computer, using `chkdsk` for example).

**Comment by arcues19875** [comment]
Not going to lie I feel derpy. Turns out I didnt have enough space. Oops.
My bad. Thanks for the help

**Comment by d0k3** [comment]
Nah, don't worry. Can you retry the decryption to some SD card that has more space free?

**Comment by d0k3** [comment]
Alright, please try and close this issue if everything works as it should.
