### ISSUE TITLE
NANDManager unknown cmd

### ISSUE THREAD

**Issue by Filo97** [d0k3/GodMode9#407]
"0:/gm9/scripts/NANDManager.gm9
 line 3: unkown cmd
 keysel -o -s "Select an option." nmopt_*"

**Comment by d0k3** [comment]
Yeah, that's already fixed. You may grab the fixed script from here:
https://transfer.sh/%28/mkHBZ/NANDManager.gm9%29.zip

**Comment by Filo97** [comment]
Oh, i see, thank you very much!
