### ISSUE TITLE
NANDManager.gm9 error

### ISSUE THREAD

**Issue by Flik210** [d0k3/GodMode9#408]
Using the latest godmode9 1.7.0
When starting the nandmanager.gm9 script i get this error:

```
0:/gm9/scripts/NANDManager.gm9
line 3: unknown cmd
keysel -o -s "Select an optio...
(<A> to continue)
```
Pressing a stops the script

**Comment by RaulPPelaez** [comment]
Replacing keysel to labelsel in line 3 of nandmanager.gm9 fixes this, the last commit solves this issue, but apparently it has not reached the release.

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/GodMode9/commit/df67d1de58bd65cd9383eaabc6eabb13ab9c88d0
