### ISSUE TITLE
Error dumping/decrypting Puyo Tetris DLC

### ISSUE THREAD

**Issue by z235** [d0k3/GodMode9#409]
0004008c00101200

Maybe N did something weird with this but trying to install this on a new 3DS with a ticket via FBI and while I can install it it's not possible to dump it with GM9. Also tried grabbing it with the python script and CDN-FX but then it's not possible to decrypt it with GM9. GM9 does not detect the undecrypted CIA as a valid file. With a generic ticket there are 701 content files being downloaded in this package (most are fake(?) and only 20 KB, total size is about 109 MB).

Please close/delete if inappropriate.

**Comment by d0k3** [comment]
There recently was something changed about how these DLCs work. Can you maybe contact me via some other means? GBAtemp, GM9 Discord or IRC (freenode Cakey).

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/GodMode9/commit/5e51805ea033b9f4b6e8ca5f3516432788438cf2
