### ISSUE TITLE
request allow for cia title.db etc options

### ISSUE THREAD

**Issue by MarioMasta64** [d0k3/GodMode9#410]
allow op menus when not in specific places (exa: say a nintendo 3ds folder is in sd:/backup/)

**Comment by d0k3** [comment]
Unsure. What exactly is it you intend to do? You know that the `sd:/Nintendo 3DS` folder and the CTRNAND belong together?

**Comment by d0k3** [comment]
Okay, this misses info and is already 5 days old. @MarioMasta64 - feel free to reopen or continue writing here if you can add info.

**Comment by MarioMasta64** [comment]
so essentially say i have a copy of a nintendo 3ds folder from a broken system and wish to create titles from the sd card tt was used (because nintendo only lets you transfer like twice (or thrice?) every two years iirc) and the nintendo folder is stored in a folder named backup so thay they arent merged

it would be nice to r+a on that the same way as on root, also to be able to process certain files (if possible) from not standard locations

**Comment by urherenow** [comment]
Well, that is unless the consoles in question share a moveable.sed (like when you backup the old NAND, do a system transfer, then restore the NAND from before the transfer). I swapped my sd info back and forth a lot before the FULL transfer was figured out (plaza progress and such), between an o3ds and n3ds.

**Comment by d0k3** [comment]
Correct, @urherenow. For that specific case FUSE3DS is the best solution, though.
