### ISSUE TITLE
Copy function doesn't check if enough space is available when pasting 

### ISSUE THREAD

**Issue by zacchi4k** [d0k3/GodMode9#411]
When copying a file from one drive to another, Godmode9 doesn't appear to check if enough free space is available to hold the file, and will proceed to copy it until it errors out when there isn't any space left. Godmode9 should instead check if enough space is available _before_ it starts copying the file. Tested on the latest version (1.7.1)

**How to reproduce:**

1. Copy a large file to the clipboard (a good place to get one is SysNAND Virtual).
2. Paste it in a drive smaller than the size of the file (eg: the RAMdrive or the Bonus drive).
3. The file will start copying anyway.
4. When space inevitably runs out, it will error out with "Failed copying path".

**Comment by d0k3** [comment]
I think you're getting this wrong. GM9 does check for free space, but it also to check how the file will be layed out in the filesystem (think fragmentation), which will take slightly longer than just comparing sizes.

It's bad only on filesystems with little space left and / or that are badly fragmented - and there's not much that I can do about that. No actual copying is started before the file system is checked (copying only starts when the progress bar starts showing progress).

So... does that explain it for you?

**Comment by zacchi4k** [comment]
[The progress bar does start showing progress](https://i.imgur.com/sgQgjhG.jpg), plus judging by the take it takes until it errors out, and comparing it to the time it takes to copy a file that barely fits in the drive, they are basically the same

**Comment by d0k3** [comment]
The space is checked here, and there shouldn't be a way for the check to not work.
https://github.com/d0k3/GodMode9/blob/master/arm9/source/filesys/fsutil.c#L527-L531

I'll see about this later, you may have found a legitimate bug here.

**Comment by zacchi4k** [comment]
I've just tried it on an SD Card too (since it's more "common" to use), and the same thing happens

**Comment by d0k3** [comment]
Okay, should be fixed now. Please test the nightly.

**Comment by zacchi4k** [comment]
Just tested it, it works
