### ISSUE TITLE
HELLPPP!!

### ISSUE THREAD

**Issue by NOOB-MANTIS** [d0k3/GodMode9#415]
When ever I turn on my old 3ds it keeps on launching Godmode9. I dont know what to do.

**Comment by al3x10m** [comment]
that sounds like an issue other than a godmode9 one.....

**Comment by Wolfvak** [comment]
You're not really giving any information and it sounds like you're following some kind of instructions, ask the author for help on how to proceed.

**Comment by MasterGamingYT** [comment]
You probably renamed the payload to boot.firm
