### ISSUE TITLE
Battery displaying incorrect values in GodMode9

### ISSUE THREAD

**Issue by pitrako** [d0k3/GodMode9#416]
Also I opened an issue in FBI installer with the same problem, what can cause this in a 2DS?, the hour is incorrect too:

![](https://image.ibb.co/hARo5p/snap_180813214506.png)

![](https://image.ibb.co/fBXWrU/IMG_20180813_225156.jpg)

**Comment by d0k3** [comment]
GM9 is not wrong, it is *more accurate*. What gets shown as a still full battery (all bars) in HOME menu can actually be a lot less.

To put this in correlation:
50% battery is 3 of 4 bars
30% battery is 2 of 4 bars
15% battery is 1 of 4 bars
(not entirely sure about the percentages, but it's somthing like that)

Guess you can't open an issue for HOME menu ;).
