### ISSUE TITLE
Suggestion: Add option to dump DS carts without on-the-fly decryption.

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#417]
Suggestion: Add option to dump DS carts without automatically decrypting the Secure Area, leaving you with an unmodified ROM. I know there are tools on PC to encrypt decrypted ROMs but I'd like to test how well they work by comparing their output with actual dumps of the encrypted data straight from a cart.

**Comment by d0k3** [comment]
If this is about 100% authentic dumps, we got another problem there:
https://github.com/d0k3/GodMode9/issues/332

Decrypted secure area is the standard, agreed upon format for Nintendo DS cartridge dumps. No way that will be changed. I also have my doubts a feature such as the one you described would actually be put to use - that's a very specific request.

If you want this just for yourself, disable this line:
https://github.com/d0k3/GodMode9/blob/master/arm9/source/gamecart/secure_ntr.c#L335
... then compile the code.

Does that solve it for you?

**Comment by mariomadproductions** [comment]
It's not really about 100% authentic dumps.

It is basically the standard format, yeah. But encrypted dumps are still datted and shared.
Yeah it wouldn't have much use.

Thanks for the info about commenting out the line. I guess that does solve it for me.

**Comment by mariomadproductions** [comment]
Reopening this, as I think while decrypted ROMs are the standard for playing ROMs in emulators/flashcards, I don't think its good to "start" with a modified ROM for preservation purposes. I think it'd be pretty useful if there was an "_enc.nds" virtual file in the C: drive that allowed you to dump NDS carts without running the decryption code. That way it avoids any potential issues (which have cropped up the past) with the secure area decryption (which to this day has not been emulated fully accurately, even if it the code that's been created does apparently work). People wouldn't need to worry about if the decryption process in GM9 works on that particular cart. I know I could just make a build that dummies out that code, but I think relying on forks probably isn't a good idea

**Comment by d0k3** [comment]
Just so everyone is on the same page - here's a test build with the possibility to dump DS carts with the secure area intact:
https://f.secretalgorithm.com/RHMwg/godmode9-v1.9.2pre1-29-g647d5722-20201229211456.zip

Needs proper testing cause I don't have any carts to test right now.

An important test case:
1. Dump standard (.nds), check with known good case
2. Dump encrpyted (.enc), check with known good case
3. Dump standard (.nds), check with known good case
4. Dump encrpyted (.enc), check with known good case

It's important to check each case twice, in one go.

**Comment by mariomadproductions** [comment]
Here are the results. Sonic Classic Collection and GM9 didn't provide a .enc file, even though it should presumebly due to this being a TWL game and this build not having support for providing .enc files for TWL games.

| filename                      | size     | crc32    | correct crc32 | matches |
|-------------------------------|----------|----------|---------------|---------|
| S.MARIO64DS_ASMP01_00.nds     | 16777216 | 29715DEC | 29715DEC      | yes     |
| S.MARIO64DS_ASMP01_00.nds.enc | 16777216 | 54E4A30A | 3D5C4603      | no      |
| S.MARIO64DS_ASMP01_00.nds     | 16777216 | 29715DEC | 29715DEC      | yes     |
| S.MARIO64DS_ASMP01_00.nds.enc | 16777216 | 54E4A30A | 3D5C4603      | no      |
| SONICCOLLECT_VSOV8P_00.nds    | 67108864 | D58E1404 | D58E1404      | yes     |
| NEW_MARIO_A2DP01_00.nds       | 33554432 | F443F9BF | F443F9BF      | yes     |
| NEW_MARIO_A2DP01_00.nds.enc   | 33554432 | 8C47D8B7 | 8869FC03      | no      |
| NEW_MARIO_A2DP01_00.nds       | 33554432 | F443F9BF | F443F9BF      | yes     |
| NEW_MARIO_A2DP01_00.nds.enc   | 33554432 | 8C47D8B7 | 8869FC03      | no      |

**Comment by d0k3** [comment]
That didn't go to well. Here's a new test build:
https://f.secretalgorithm.com/lTEgy/godmode9.firm

This should fix the issues with non-TWL games. As for TWL games - these have an encrypted secure area by default (apparently cause flash carts want it that way, thus an .enc file makes no sense.

**Comment by d0k3** [comment]
Tested by @mariomadproductions and now included in master.
