### ISSUE TITLE
S:\essential.exefs can be edited without any warning

### ISSUE THREAD

**Issue by zacchi4k** [d0k3/GodMode9#418]
S:\essential.exefs can be edited with the hex editor without any warning or write protection whatsoever, which probably isn't ideal for a file which contains console-unique keys that could be crucial in certain situations. I believe the file should be either read-only, or should ask to unlock write permissions for it when trying to edit it

**Comment by d0k3** [comment]
I agree. That file will be added to the list of protected files.
