### ISSUE TITLE
Do not show the progress bar for very short file operations.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#419]
Currently GM9 shows the progress bar for every file operation.
However if the process is very short, like copying lots of small files, the bar is completely unnecessary, and seizure-inducing.
Suggestion: Add a 1-second delay between starting a file operation and showing the progress bar, so for short operations, the bar won't appear.

**Comment by d0k3** [comment]
I do agree that the progress bar doesn't have much of an informative value for these very small file ops. However, you may have a copy operation of 1000 files sized 1kiB. If I did what you suggested, nothing at all would be shown on screen, and that would make users uneasy.

So... any idea about that?

**Comment by legoj15** [comment]
I prefer having the progress bar go really really fast, because if you hide it when doing small files, then how would you know that it hasn't inexplicably frozen? You would just be waiting there with a black bottom screen. That, and what @d0k3 mentioned above about many small files in succession.

**Comment by d0k3** [comment]
Alright, I'm closing this. As you see, just not showing the progress bar on small operations is not an option, @pthfdr-42. There is already some logic implemented so the progress bar does not update faster than the screen refresh rate, though.

If you can come up with a better idea, feel free to reopen or create a new feature request.
