### ISSUE TITLE
REQUEST: Sound on CIA generation complete or batch CIA building.

### ISSUE THREAD

**Issue by YoItsTrev** [d0k3/GodMode9#42]
Could you please add some form of  audible warning to let you know when something completes. Since dumping CIAs takes a long while, obviously I am not gonna sit there and stare at the 3DS till it completes. But I also don't want to forget that I am doing it, and waste a half hour before I realize what I was doing, and check to see if is done. 

Could you also try to add batch 3DS->CIA, eshop->CIA conversion, CIAngel has a queue, having one for converting files to CIA would be a huge help.

**Comment by d0k3** [comment]
Short answer: no. We neither have access to sound, nor to internet on ARM9, and we most likely never will. .3DS to .CIA conversion is already possible (cart to .CIA, too), and you can already convert basically any input file (where it makes sense) to .CIA. If by queue you mean, do the conversion in background, not possible either and wouldn't make much sense.

**Comment by YoItsTrev** [comment]
I don't mean in background. I mean create a queue, then convert one file after another. That way I don't have to start a CIA dump, wait for it to finish, then start another. Just make a queue of all the games I want to dump to CIA, and let it go to work.

**Comment by d0k3** [comment]
You really should at least consult the readme or a guide before opening feature requests. Github issues is not for support -_-. Select multiple convertible files (.3DS f.e.) via L, then press A on one and start the conversion. You will be asked if all files should be converted.

**Comment by YoItsTrev** [comment]
Will this work with files installed in SYSNAND SD/title?

**Comment by YoItsTrev** [comment]
I did what you said, and it did not work. I went SYSNAND\Title\00040000\<titleid>\content\00000000.tmd, and use L to select it. I then press B to go back to 00040000, and select another titleid, and do the same thing, but when I go back to the original titleid to verify that the first tmd file is still selected, it is not.

**Comment by d0k3** [comment]
From the readme:

"*Search drives and folders*: Just press R+A on the drive / folder you want to search."

"*Build CIAs from NCCH / NCSD (.3DS) / TMD (installed contents)*: Press A on the file you want converted, the option will be shown. Installed contents are found (among others) in 1:/titles/(SysNAND) and A:/titles/(SD installed). Where applicable, you will also be able to generate legit CIAs. Note: *this works also from a file search*."

Again, Github issues is not for support or spoonfeeding. Consult the readme. You may also ask questions, but not here. Maybe [here](https://www.reddit.com/r/3dshacks/comments/62d6im/where_is_my_dragon_a_guide_from_hourglass9_to/) instead?

**Comment by YoItsTrev** [comment]
Awesome! Thanks a ton.
