### ISSUE TITLE
GM9Megascript cannot restore EmuNAND

### ISSUE THREAD

**Issue by LeddaZ** [d0k3/GodMode9#420]
When I try to restore an EmuNAND backup with GM9Megascript it fails at line 165 inject -n I:/nand_minsize.bin E:/nand.bin@0 beacuse there isn't the imgmount $[NANDBAK] command to mount the backup
![gm9](https://user-images.githubusercontent.com/35930217/44464901-49aa6900-a61c-11e8-96b3-982d31429545.png)

**Comment by d0k3** [comment]
@annson24 - will you doublecheck and fix this, then sent me a pull request? Also, thanks @LeddaZ for the find.
