### ISSUE TITLE
[feature request] warning for existing dump

### ISSUE THREAD

**Issue by Ninjistix** [d0k3/GodMode9#423]
gm9's building of a cia does not confirm if their is already a built cia/xci version of whatever file already in the gm9/out folder.. you can build the same cia/cxi  over and over without a duplicate warning of  file already existing 

Edit: it seems like trying to dump the same title just overwrites the previous one without any sort of warning.

**Comment by james-d-elliott** [comment]
Maybe add a choice at the start of the process as to what to do? i.e. "During the batch process if existing files are detected, do you want to overwrite, skip, or skip until the end?"

First two explain themselves, last one it just comes back to those files at the end. May also want to display a summary at the end with what actions were taken i.e. cia1 - skipped (existing) cia2 - completed, cia3 - skipped (space). Though the last one is realistically just cream - hell, all of them are. I'd personally not use it, just figure it may be a logical solution that makes sense.

**Comment by Ninjistix** [comment]
Wait there's an option to batch convert them all? I was doing it 1 by 1 and
forgot which ones I did already which is why I brought that up

**Comment by d0k3** [comment]
Just select multiple entries before pressing A, @Ninjistix.

**Comment by d0k3** [comment]
Alright, I'll decide against handling this for now, in part because it's not that easy to implement. Also because of what I explained earlier. @Ninjistix - you should have used the batch thingy right from the start.

If you feel handling this is still required or if there's bigger demand for it, feel free to continue the discussion / reopen.
