### ISSUE TITLE
SaltMode9 crashes to home after certain application soft-resets. 

### ISSUE THREAD

**Issue by Kalanyr** [d0k3/GodMode9#424]
Not sure if this is a GodMode9 issue or a Luma issue or some weird intersection. 

However I use SaltMode9 instead of B9S for my bootloader and that's fine 99% of the time.  In game soft resets (like Pokemon work) but certain ones like returning to Settings after doing SD Card management or the soft-reset in DSiMenu++ after changing it's global settings result in what seems to be a crash to the home menu.  

This doesn't happen on my US 3DS which uses B9S as it's bootloader 

I only realized this was probably something to do with SalteMode9 when I was troubleshooting DSiMenu++ and realised that SD Management was doing the same thing (returning to Home when it should Soft-reset). 

ETA - I do only install SaltMode9 to Firm0 but I don't think that should matter.

**Comment by d0k3** [comment]
Can you clarify this a bit? Shouldn't DSiMenu++ return to home menu when it is reset (that's the expected result, no?

GodMode9 (and SaltMode9) don't alter the boot in any way, all of it should be handled by NATIVE_FIRM, which is booted by Luma 3DS.

Do you have an up to date installation of SaltMode9 or is it outdated? Pretty sure you already know, but the most recent one is found here, at the bottom:
https://d0k3.secretalgorithm.com/

**Comment by Kalanyr** [comment]
On my other 3DS (b9s) , DsiMenu++ resetting after saving global settings ,
restarts DsiMenu++.  The maintainer thinks this is the expected behaviour
too.

And on leaving SD Management returns to the settings menu , not the Home
Menu.

It's not the very last commit of SaltMode9 I think but it's very recent (I
try to keep fairly up to date) and none of the missing commits seem
relevant.


(I'll try installing B9S and check the behaviour, when I get a chance).

**Comment by d0k3** [comment]
Alright, I may already know what causes.

**Comment by Kalanyr** [comment]
Confirming that changing to boot9strap on my saltmode N3DS XL causes it to behave the same as the one that's always been on boot9strap did.

**Comment by d0k3** [comment]
Alright. So, what happened there is not a crash - we just didn't protect certain stuff that is required to get back to the place you came from.

Here's something that you can try:
https://f.secretalgorithm.com/EmW0f/saltmode9.firm

Let me know if that worked for you. Also: great catch. This went unnoticed for a long time.

**Comment by Kalanyr** [comment]
That's good to know. 

Yes, that fixes this issue. 

I can see how it did, considering I've only seen the 2 instances where it's detectable, and I wrote the SD management thing as being a difference between PAL / US firmware originally and thought the DsiMenu++ was a bug in it and I had two otherwise same model 3DSs to compare on.

**Comment by d0k3** [comment]
Alright, thanks for testing!
