### ISSUE TITLE
I can't copy or dump anything to gm9/out

### ISSUE THREAD

**Issue by IdiotDuh** [d0k3/GodMode9#426]
I tried to dump a physical game and it doesn't work. I tried creating support files and when i try that it also fails. It always says "Failed Copying Item".

I'm using a microSD card with 32 GB class10 if that helps.

**Comment by d0k3** [comment]
Is your SD card full or write protected? First check if you can write there from anywhere else (Windows for example). Your SD card may also be formatted in the wrong way. Do you have games installed to it?

**Comment by d0k3** [comment]
@IdiotDuh (why did you give yourself that nick... (☉_☉)) - I really need more info for this. If you already got it solved, it helps if you just close thsi issue. If not, it looks like there's something wrong on your side, I cannot be sure, though.

**Comment by d0k3** [comment]
Okay, closing this for lack of information and possible user error. Feel free to reopen if you can add info this.

**Comment by unmoving-javi** [comment]
Similar issue here, but I can't remove read-only from the folder in Windows browser. Games are installed, e-shop and basically everything else seems to work fine. No clue why.

**Comment by unmoving-javi** [comment]
The error when copying to gm9/out says that there's not enough space available. However there's 29 gigs free on the microSD?????

**Comment by unmoving-javi** [comment]
Formatted and re-copied everything over and it worked. Seemed to be missing my title keys as well. Took like an hour, which sucks, but at least it works now.

**Comment by JohnTravolski** [comment]
I'm running into this same problem, but it works if the file is small (like just copying the .txt files) but fails when trying to copy the game. Is formatting the SD card the only solution?
