### ISSUE TITLE
Copies luma crash dumps to ctrnand

### ISSUE THREAD

**Issue by mtheall** [d0k3/GodMode9#427]
The `Setup Luma3DS to CTRNAND` script copies luma crash dump files to ctrnand.

**Comment by d0k3** [comment]
@annson24 - that's in the GM9 Megascript, I assume.

**Comment by annson24** [comment]
Alright, while this is just very minor cleanup and no functionality is broken, I'll still try to fix it when a free time comes by. Thanks for reporting.

**Comment by annson24** [comment]
Can you try this? Sorry I cannot test anymore, I've already gave my 3dses away.

Just rename to .gm9

[GM9Megascript.txt](https://github.com/d0k3/GodMode9/files/2365394/GM9Megascript.txt)

**Comment by d0k3** [comment]
@annson24 - what exactly needs to be tested? I'll try to look into it.

**Comment by annson24** [comment]
Just the `Setup Luma3DS to CTRNAND`

It should work fine but we cannot be too sure. heh. I'll try to test it (somehow).

**Comment by d0k3** [comment]
Okay, I tested it. It just copies `config.bin`, `splash.bin`, `splashbottom.bin` to `1:/rw/luma` and `0:/boot.firm` to `1:/boot.firm`. Is that the expected result, @annson24 and @mtheall ?

**Comment by annson24** [comment]
@d0k3 yes, that's about it. It will also suppress errors and force to continue if you don't have the config and splashes. Gonna make a pull request maybe this afternoon GMT+4

**Comment by james-d-elliott** [comment]
Wouldn't you want to copy the 0:/luma/payloads folder too?

**Comment by annson24** [comment]
@james-d-elliott that's what the script did, and so are everything inside is, which resulted in this issue. So what the new test script does instead is just create the `payloads` directory and copy all essential files to it.

@everyone sorry I still haven't made a pull request, I've been very busy for the past couple of days. I think my busy schedule will subside after a day or two.

**Comment by james-d-elliott** [comment]
Think you're missing what I'm saying. 0:/luma/payloads folder shouldn't include any dumps, they should be under 0:/luma/dumps - see https://github.com/AuroraWright/Luma3DS/blob/master/source/exceptions.c#L178-L193

**Comment by annson24** [comment]
@james-d-elliott well I totally did miss it because as far as I can understand your first message, you wanted the 0:/luma/payloads folder to be copied too (which it actually does). Anyway, dumps is not essential to setup luma3ds to ctrnand so it won't be included anyway.

**Comment by Plailect** [comment]
#430 should probably copy the payloads folder too, yeah.

**Comment by annson24** [comment]
Ah I see the problem @james-d-elliott was pointing. Give me a bit.

**Comment by d0k3** [comment]
Merged @annson24's fix. This should do it. If not, feel free to add comments here.
