### ISSUE TITLE
[Feature Request] overwrite confirmation for CIAs

### ISSUE THREAD

**Issue by SamothJtM** [d0k3/GodMode9#429]
When building a CIA from a 3ds file for a second time I miss a confirmation request whether to overwrite the already existing output. This only exists for copying files.

**Comment by d0k3** [comment]
You're not the first to ask this... Read the discussion here: https://github.com/d0k3/GodMode9/issues/423

In short, a confirmation would be pretty bad in case of a batch operation. Only doing one when processing single files, on the other hand, is not easy to implement.

**Comment by d0k3** [comment]
Okay, closing this for teh reasons mentioned in #423
