### ISSUE TITLE
Error GodMode9 Nightly

### ISSUE THREAD

**Issue by yonaikerlol** [d0k3/GodMode9#431]
I am using version v1.7.1-18-g8f24ccec-20180925030010 of GodMode9 Nightly, and when entering unid options -> Search for titles.

The titles appear to me like this:

![](https://i.imgur.com/kHSrFhM.png)

When they first appeared with the name, serial and the region.

**Comment by legoj15** [comment]
I'm experiencing this issue too.

**Comment by d0k3** [comment]
Thanks, that was a good catch. Should be fixed now.
