### ISSUE TITLE
 bfc3363 Breaks compiling

### ISSUE THREAD

**Issue by urherenow** [d0k3/GodMode9#432]
source/filesys/fsgame.c: In function 'SetDirGoodNames':
source/filesys/fsgame.c:19:9: warning: 'strncpy' output may be truncated copying between 0 and 255 bytes from a string of length 255 [-Wstringop-truncation]
         strncpy(entry->name, goodname, 256 - 1 - entry->p_name);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ARM9] source/filesys/fatmbr.c
[ARM9] source/filesys/fsdir.c
[ARM9] source/filesys/vff.c
[ARM9] source/filesys/fsdrive.c
source/filesys/fsdrive.c: In function 'SearchDirContents':
source/filesys/fsdrive.c:185:57: error: 'entry' undeclared (first use in this function)
         contents->entry->name = contents->entry->path + entry->p_name;
                                                         ^~~~~
source/filesys/fsdrive.c:185:57: note: each undeclared identifier is reported only once for each function it appears in
Makefile:34: recipe for target 'build/filesys/fsdrive.o' failed
make[1]: *** [build/filesys/fsdrive.o] Error 1
Makefile:78: recipe for target 'arm9/arm9.elf' failed
make: *** [arm9/arm9.elf] Error 2

**Comment by d0k3** [comment]
I really wonder how that could have slipped through.... anyways, already fixed it locally, but needs testing - will push in a few hours.
