### ISSUE TITLE
Suggestion: Check padding before making trimmed dump

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#437]
I think it might be a good idea if godmode9 checked the padding of a 3DS/NDS cart-dump ROM to see it is all FF bytes before making a trimmed dump, just in case the ROM has non-FF data there for some reason. If there was non-FF data, it would display as message saying that the dump is not "losslessly trim-able". I know it is very unlikely a cart would have non-FF data in the padding region of its ROM, but I think it is worth taking this precaution.

**Comment by d0k3** [comment]
Thought about it, but checking the padded area would simply take too long on console. It would also eliminate part of the reason behind providing access to the trimmed game image (faster dumps, smaller files). If you suspect data there (and there is *no* known case besides card2 games, which are handled), dump the full thing and inspect it on a computer.
