### ISSUE TITLE
h&s inject failed

### ISSUE THREAD

**Issue by Leerz** [d0k3/GodMode9#44]
following the guide, godmode9 inject .app of FBI didn't work - inject failed

so i tried the old way which is through dump hourglass9 then inject the fbi injectable .app

hourglass returned:
code / crypto: ctr-n-hace / 7x
slot0x25keyx not setup
this won't work on o3ds < 7x or a9lh

health & safety dump: failed

Details:
System is a freshly downgraded 11.3U (successfully installed a9lh+luma)

thanks

**Comment by d0k3** [comment]
You din't follow the guide correctly. Get informed about aeskeydb.bin, but not here, this is not for support.

**Comment by Leerz** [comment]
ohhhh! my bad - sorry for flooding the issues page -

actually i used the old aeskeydb file - just checked the hashes -

F258C135A7909EA39765CAEFE7E796F0 new 

042891E750204B38E2C8BACAE6151AB8 old

Thanks. -closed
