### ISSUE TITLE
CXI build failing when selecting "Dump CXI/NDS file"

### ISSUE THREAD

**Issue by Bwang9923** [d0k3/GodMode9#441]
I recently hacked my 3ds using [this](https://3ds.hacks.guide/) guide. Now I'm trying to randomize my pokemon ultra moon game. I'm trying to dump the cxi/nds file but every time i try it I get CXI build failed.

These are the steps I'm taking:
1) I boot the 3ds holding start.
2) I navigate to and open [A:] SYSNAND SD
3) I navigate to and open title
4) I navigate to and open 00040000
5) I navigate to and open 001b5100
6) I navigate to and open content
8) I navigate to and select 00000000.tmd
9) I select TMD file options...
10) I navigate to and select Dump CXI/NDS file
11) The bottom screen stays blank rather than showing a progress bar for approximately 10-15 seconds
12) The bottom screen displays A:/title.../content/00000000.tmd CXI build failed. (<A> to continue)

Does anyone know why it keeps failing? Am i doing something wrong?

My SD card already has a gm9/out folder. The sd card has 2.78/14.8 GB free. I don't have a different SD card to try but i do have a 32GB one coming in 3 days.

**Comment by d0k3** [comment]
You already know what's going wrong there... 2.78GiB is not enough space for the CXI. You need a larger SD card to dump that one. It's almost 4GiB, you only got 2.78GiB free.

Feel free to reopen or add comments here if it keeps on failing with your new SD card.
