### ISSUE TITLE
Payload Hash not recalculated when encrypting a BOSS File

### ISSUE THREAD

**Issue by Slattz** [d0k3/GodMode9#442]
So I noticed that when encrypting a BOSS file, the sha-256 in the Payload Content Header doesn't get updated. This leads to the file failing the checks in the BOSS sysmodule, thus considered invalid. 
I checked by editing the actual content data of a decrypted boss file, then encrypting it and decrypting it again. The hash remained unchanged, and the encrypted file wouldn't work with the game. 
However, if I manually update the hash so that it's correct, then encrypt the file, it then works with the game.

I'm not sure if this is intended behaviour and it's expected of the user to manually update the hash or not? 
Either way, GodMode9 already seems to have the ability to calculate sha hashes, so it would be alot more convenient if it could automatically fix the hash before encrypting the file.

**Comment by Slattz** [comment]
BOSS files don't work when decrypted afaik, but that's not my point.

What I'm asking is for Godmode9 to fix the payload hash during encryption, or perhaps in the "Verify file" option, when it detects there's a hash mismatch, give the user the the ability to fix the hash there and then. Just something to avoid the user needing to manually do it.

I understand that fixing the hash isn't really the job of the encryptor, but I'm speaking mainly so the user experience can be improved.

**Comment by d0k3** [comment]
Okay, I looked further into this issue. The problem here is that BOSS files provide little data to identify them, thus we also use the hash itself to help properly identify BOSS files. Fixing that hash on the fly is not really an option.

I do wonder why you want to edit that data, though. The hash is calculated from the 18 byte located at 0x28, followed by 2 zero bytes (hash is calculated from 20 byte in total).
http://3dbrew.org/wiki/SpotPass#Content_Header

It shouldn't make sense to edit anything there. Sooo... did you mean something else?

**Comment by d0k3** [comment]
Okay, I've got something for you to try:
https://f.secretalgorithm.com/FrBeZ/godmode9.firm

This will offer fixing after a failed verification, and it should work for both, encrypted and decrypted BOSS files. I'm relying on you to test this, so please give me feedback!

**Comment by Slattz** [comment]
I just tried it, can confirm it works fine 🙂

**Comment by d0k3** [comment]
And you tried with decrypted and encrypted files?

**Comment by Slattz** [comment]
Yep, it worked fine 🙂 
It was able to fix the hash on both an encrypted and decrypted file, then verify it was correct the next time I tried to 'Verify File'.
I also used Fiddler to return the encrypted BOSS file that had the fixed hash to the game (ACNL), and can confirm it also worked fine.
