### ISSUE TITLE
full .3ds file in game cart virtual directory of 4GB cart shows up as 3.9GB

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#444]
![imag1828](https://user-images.githubusercontent.com/9919020/49524630-08288b80-f8a4-11e8-9ae3-2de572baa18c.jpg)
The full .3ds file in the game cart virtual directory of a 4GB cart shows up as 3.9GB
As you can see in the picture, the split files are 2GB each. And it should go without saying - the ROM image is meant to be 4GB.

**Comment by knight-ryu12** [comment]
what you can to obtain raw dump of cart, is dump split one, merge on PC.
there's no way 3DS to handle 4GB data. (as pointed out by @legoj15)

**Comment by d0k3** [comment]
As @legoj15 and @knight-ryu12 said - closing this now.

**Comment by mariomadproductions** [comment]
I should have made clear - I know about the file size limitation legoj15 and knight-ryu12 are correct. I just thought it was a bit odd that it displays like this in the "virtual directory".
