### ISSUE TITLE
GM9Megascript error

### ISSUE THREAD

**Issue by Jeevie16** [d0k3/GodMode9#446]
Dear d0k3,

I am a fan of your work, i've always used it.
But now there's a slight problem...
Could you please help me out?

My 2ds says:
0:/gm9/scripts/GM9Megascript.gm9
line 3: too many arguments
if not find $[GM9IN] NULL

(<a> to continue)

Please tell me what i can change so the megascript wil work.

Greetings,

Rajeev

**Comment by d0k3** [comment]
Can you tell me which version of GodMode9 you used? Is that the `GM9Megascript.gm9` that came with the release package?

**Comment by Jeevie16** [comment]
v1.2.7 and the GM9Megascript.gm9 that came with the latest release package

**Comment by knight-ryu12** [comment]
that's too old. update to latest GM9.

**Comment by Jeevie16** [comment]
damn i'm sorry man...
That was my mistake...
Thanks man for replying!!

**Comment by d0k3** [comment]
@Jeevie16 - did you really mean 1.2.7, or did you mean 1.7.2?

**Comment by legoj15** [comment]
@d0k3 1.7.2 isn't a release version (yet), so I think they actually were using 1.2.7

**Comment by d0k3** [comment]
Oooops correct.

**Comment by d0k3** [comment]
@Jeevie16 - can you test with the most recent GodMode9 version?

**Comment by d0k3** [comment]
@Jeevie16 - we need more info, haven't heard from you in 2 weeks.

**Comment by d0k3** [comment]
Closing this for lack of info. No known problems like this in the most recent GM9 version, so assuming this is due to using an outdated version.

**Comment by Alelih** [comment]
Hello, same problem here..... V1.8.0

**Comment by aspargas2** [comment]
@Alelih the error is the same word for word?

**Comment by Alelih** [comment]
Exactly

**Comment by Alelih** [comment]
https://3ds.hacks.guide/ctrtransfer.html
Step 15 section 2 from Thiago tutorial
O have a Old 2DS

**Comment by Alelih** [comment]
![IMG-20190513-WA0067](https://user-images.githubusercontent.com/50600542/57661073-bd800d80-75bf-11e9-8440-ff05710cd565.jpeg)

**Comment by Alelih** [comment]
![P_20190513_184547_vHDR_Auto](https://user-images.githubusercontent.com/50600542/57661125-f4eeba00-75bf-11e9-863a-a781637b1d7e.jpg)

**Comment by Alelih** [comment]
Openned a New Issue #483

**Comment by d0k3** [comment]
Let's discuss that further in the other issue...

**Comment by Alelih** [comment]
Ok d0k3, thanks.
