### ISSUE TITLE
can not modify/delete read-only file in sd card

### ISSUE THREAD

**Issue by akizuha** [d0k3/GodMode9#447]
how did a “godmode” can not modify/delete a file?
btw. same in the CTRXplorer

**Comment by d0k3** [comment]
Press R+A on the file and remove the read-only attribute. Does that solve it?

Hint: you're not supposed to be able to modify/delete read-only files.

**Comment by akizuha** [comment]
Oh, didn’t notice that, thanks.
Btw. Is this operation possible in CTRXplorer?

**Comment by d0k3** [comment]
Not possible in CTRXplorer, sorry. Would be harder to do there, too.

**Comment by akizuha** [comment]
Wondering why? All other programs like FBI seem can’t delete read-only file too.

**Comment by urherenow** [comment]
What about READ ONLY don’t you understand? Anyway, this is NOT a support forum.

**Comment by d0k3** [comment]
@urherenow - come on, stay friendly. @akizuha, well, he has a point. files *are* read only for a reason. A file browser can ignore the flag, but is that a wise choice? If you ask me, it isn't. Just remove the write protection on a computer, and you're good to go.

Closing this now...

**Comment by akizuha** [comment]
Sorry I didn’t’ make myself clear. What I mean is why homebrew program like CTRXplorer/FBI can not remove the read-only flag then delete a file or why is hard to implement. 
Btw. Open the back panel for file manage every time is really annoying.

**Comment by d0k3** [comment]
You don't have to do it everytime, @akizuha. Do it once, remove the read-only flag *for all files* on a computer, then do all your file management stuff on 3DS.
