### ISSUE TITLE
Current CTR Transfer has difference & issue

### ISSUE THREAD

**Issue by MelonGx** [d0k3/GodMode9#448]
I just performed an O3DS-O3DS CTR Transfer by executing foreign ctrnand_full.bin.
The result is different from the latest Decrypt9WIP release's CTR Transfer:
1) NAND data, such as StreetPass data, Pokémon Shuffle / Megami Meguri savedata NAND verification, etc., haven't been changed. But D9's CTRT will change all of them to make it just like a duplication of source NAND.
2) Current G9's CTRT breaks some external RAM required games, such as Dragon Quest XI, it flashbacks to home menu without entering to the game's intro video. D9's CTRT doesn't break it.
It doesn't break all external RAM required games though.

**Comment by MelonGx** [comment]
The Target O3DS's CTRNAND is a Source O3DS's CTRNAND's old duplication, which is created by Backup NAND -> System Transfer -> Restore NAND.
This means both consoles have a same movable.sed and all related data.

**Comment by d0k3** [comment]
Well... I'll need to check about the actual differences, but GM9 actually transfers less stuff (only the required stuff). It's still the better way. D9's CTR Transfer was actually pretty hacky. It simply backed up some files, copied the whole CTRNAND image to your NAND, then replaced stuff with files from the backup. GM9 only takes what it needs.

Can you find out which files are associated with the functionality you're missing there?

**Comment by d0k3** [comment]
Okay, I looked into this and there may be some stuff that we could transfer. I can only do this if someone is willing to test the results @MelonGx - would you be willing to help?

**Comment by Ammako** [comment]
I've got a throwaway unit which can be used for testing stuff, if needed.

**Comment by d0k3** [comment]
Thanks @Ammako. I'll come up with a test build then, we'll try to transfer more stuff.

**Comment by d0k3** [comment]
@MelonGx, @Ammako, I decided to try manually first. The way this works is:

1. Do a regular CTR Transfer
2. Now delete everything inside `1:/data/id0/`
3. Mount the CTRNAND image you transferred from
4. Copy everything from `7:/data/id?/` to `1:/data/id0`
5. Go back to root, R+A on [1:], select `Fix CMACs for drive`

Done! Now all the data @MelonGx complained about should be transferred. You can also do this in a script. In fact, you can write your own CTR transfer, catered to your own expectations, in a script.

So, can you try this first? @MelonGx - the external RAM required games need further looking into, but I'm unsure if most users doing a CTR transfer actually want to overwrite their own Streetpass data, etc...

**Comment by d0k3** [comment]
Okay, closing this for lack of interest. @MelonGx - if you want to replicate D9's CTRtransfer behaviour, do as I described above. Also feel free to reopen and/or add comments if you feel there's an actual bug in GM9's CTRtransfer.
