### ISSUE TITLE
Help restoring H&S.

### ISSUE THREAD

**Issue by Magicrafter13** [d0k3/GodMode9#449]
I had to inject FBI into H&S because I was far behind on lumaupdater and FBI updates on one of my SD cards. However I can't restore the H&S app.

I know how to. You push the home button, and a menu is supposed to pop up, problem is, my home button is broken. Is there any other way I can restore H&S?

**Comment by Magicrafter13** [comment]
Are you referring to Decrypt9? And if so, will Decrypt9WIP work?

**Comment by Jerry-Shaw** [comment]
ah... I mean Decrypt9WIP. Yep, it works.
You need another H&S exported file using Decrypt9WIP, from the same firmware version in the same region from others, then, restore it back to your console.

**Comment by d0k3** [comment]
Cannot recommend this, Jerry-Shaw. @Magicrafter13 - just try the POWER button instead of the HOME button (short press, not long press).

**Comment by Jerry-Shaw** [comment]
Power button short press works like HOME button? That could be much better than Decrypt9WIP.

**Comment by Magicrafter13** [comment]
> Cannot recommend this, Jerry-Shaw. @Magicrafter13 - just try the POWER button instead of the HOME button (short press, not long press).

(I know this post is old, but I don't go through my tabs often.)

This doesn't work for me, if I push it _really_ fast, nothing happens. If I push it not quite fast enough, it turns off. Was this by chance changed in an update?

**Comment by d0k3** [comment]
I'll look into it.

**Comment by d0k3** [comment]
@Magicrafter13 - what's your GM9 version? The POWER button works fine for me (GodMode9 v1.7.1), and it's behaviour was never changed.

**Comment by Magicrafter13** [comment]
Yep, that's probably the issue. I have 1.2.1
________________________________

**Comment by Magicrafter13** [comment]
> @Magicrafter13 - what's your GM9 version? The POWER button works fine for me (GodMode9 v1.7.1), and it's behaviour was never changed.

Alright, so I'm using 1.7.1 now, and the menu pops up. Just trying to find the H&S restore option. If I find it before you reply I'll just close the issue.

Thanks for your help.

**Comment by Magicrafter13** [comment]
Well I injected with 1.2.1, so do I just need to inject again with this version?

**Comment by d0k3** [comment]
You can also fix it manually... if no one beats me to it (wouldn't be too unhappy if someone does), I'll provide the instructions later today. You can start by getting the H&S CIA or NCCH (for your region, up to date).

**Comment by d0k3** [comment]
Closing this now, cause this is an issue with an older version of GM9. @Magicrafter13 - well, you injected using an old version of GM9 (maybe even D9?). The instructions to fix it are above. Feel free to contact me again if you're having trouble.
