### ISSUE TITLE
Suggestion: Add way to print folder or title listing to file

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#453]
Or is this possible with scripts?

**Comment by d0k3** [comment]
Not yet possible with a script. Also, this is not a bad idea. I'll just need to consider how to do it.

**Comment by d0k3** [comment]
The last commit added the `dumptxt` command to scripting.

See this sample script:
`set DUMPFILE 0:/list.txt 
rm -o -s $[DUMPFILE]

dirsel "Select a dir to dump" 0: SELDIR

for $[SELDIR] *
    dumptxt -p $[DUMPFILE] $[FORPATH]
next
`

Is that what you needed? Won't allow dumping a list of titles, of course.

**Comment by mariomadproductions** [comment]
If that works recursively in the title folders in SYSNAND CTRNAND and SYSNAND SD and the contents of ticket.db then you could get a basic title version/ticket listings. I can't test this currently as my 3DS is temporarily out of action.

**Comment by d0k3** [comment]
Sure, 'for' works recursively. I'll close this then as solved.
