### ISSUE TITLE
AGBSAVE save injection

### ISSUE THREAD

**Issue by jamesfoley** [d0k3/GodMode9#454]
I've injected a Pokemon save into my AGBSAVE file, and the game loads and plays fine, but it seems to now crash when saving back to the save (well, it hangs rather than crashes, music continues to play while I get stuck at a message saying do not turn off the console).

Other games that I've not injected a save to load and save perfectly fine, so not sure if there is something wrong with what I injected originally.

Can I clear the AGBSAVE file manually to try again? Could this be an issue with the save I injected initially, or something wrong with the game?

**Comment by d0k3** [comment]
One thing is for sure... it is very unlikely GM9 has anything to do with this issue. You're right about the two possible causes of this, too. Either you used a corrupted rom (you may have reached some place in the game where trouble starts), or there is something seriously wrong with your save.

I'd suggest you try again with a known good rom (these usually have `[!]` in their filenames) and a new CIA with that rom injected. If that doesn't help either, you need to try to get it to save anew somehow. You could also use the save you injected and continue in an emulator up to the next savepoint. Maybe that will solve it, too.

**Comment by jamesfoley** [comment]
That's fair, I wasn't sure if GM9 had changed some form of permission causing writes to fail, but you're right in that a corrupt rom or save is a possibility. The rom and save actually came directly from a cartridge I own though, I guess even more reason for it to be something I've screwed up.

Corrupt rom or save aside, is it possible to clear the AGBSAVE file completely within GM9?

**Comment by d0k3** [comment]
The AGBSAVE is a partition inside your system. Can't get rid of it. it always contains the last GBA VC save you did. That means, start a different game, save, and it is overwritten. The save for a specific game is also stored on the SD card, and, sure, you could delete that file - but what good would you expect out of it?

**Comment by jamesfoley** [comment]
Would just help figure out what end the problem is really...

Deleting the save and trying to save again inside the rom would hopefully rule out one or the other. Can't save with a clean save file, then I guess the rom is bad. If I can save, then I know the save is bad.

**Comment by d0k3** [comment]
Can't you just delete the save from inside the game? You could also uninstall and reinstall the game CIA.

**Comment by d0k3** [comment]
Yup, correct. Also, as I said. Just continue that save file in an emulator, save at a later point, then inject inside GM9 again. Might already solve it.

Also, maybe check your SD card for corruption? Windows chkdisk may help.

**Comment by jamesfoley** [comment]
Cool, alright, will give those a go. Thanks for your help 👍

**Comment by jamesfoley** [comment]
Sorry, yep, this can be closed.

Turns out the cart is pushing out a corrupt save.
