### ISSUE TITLE
Add support for importing gba saves with the .SaveRAM extension

### ISSUE THREAD

**Issue by Ammako** [d0k3/GodMode9#455]
Just like [#323](https://github.com/d0k3/GodMode9/issues/323)

As for why the weird extension... probably the same reason why the people behind RetroArch decided to use .srm for saves. And yes, it's identical to the raw .sav from cartridges.

(There's also Higan which uses .ram, but I can't see anyone using Higan for GBA emulation over anything else, so I'm not sure if that's worth the trouble.)

I am not sure which kind of extra info you need about it, but feel free to ask. The percentage of people using BizHawk for GBA emulation is likely much lower compared to RetroArch, but since it didn't look like it would be too much work to do, I thought it might be worth adding. That way, whenever someone needs it in the future, it'll be there and they won't even have to ask. :p

Of course, just like with RetroArch, it's easy to just rename the file extension before importing, but it would be a nice convenience.

**Comment by d0k3** [comment]
Added in the most recent commit. Can you please test?

**Comment by Ammako** [comment]
Looks good to me!
