### ISSUE TITLE
SUGGESTION: Brightness control with 3D slider

### ISSUE THREAD

**Issue by Ketchup901** [d0k3/GodMode9#456]
I was looking at https://github.com/d0k3/GodMode9/issues/244 where you rejected the idea of a brightness config file, but how about supporting brightness control using the 3D slider, in addition to the current method of using the volume slider? I think it's a better solution, provided you can read the value of the 3D slider inputs in some way.

**Comment by Wolfvak** [comment]
There's no 3D slider in (new)2DS consoles, a d the 3D slider is known to be a lot flimsier than the volume slider on O3DS (not XL) versions.

**Comment by Ketchup901** [comment]
I was thinking it could work in parallel.

**Comment by Wolfvak** [comment]
So what, if the last thing changed was the 3D slider use that, or if it was the volume slider use that instead? That's too much logic for something that should be simple, especially since you'd then have to detect the console version and ignore any 3D slider updates on non-3DS consoles.

**Comment by Ketchup901** [comment]
No, that it just takes whichever value is the highest and uses that.

**Comment by d0k3** [comment]
Really not a good idea, @Ketchup901 - that would only be confusing.

**Comment by Ketchup901** [comment]
Why do you think so @d0k3?

**Comment by d0k3** [comment]
> No, that it just takes whichever value is the highest and uses that.

So, you're aware you'd have to move two sliders to lower brightness then?
