### ISSUE TITLE
Not working on Luma 11.9

### ISSUE THREAD

**Issue by Paloys** [d0k3/GodMode9#458]
Sorry for my bad English, I'm French.

I can't open godmode9 on my O2DS 11.9.0.42E.
I already have Luma installed, and I have access to Homebrew Menu and to FBI.
I put the `gm9` folder in the root of my SD card and the `GodMode9.firm` in the `luma/payloads` folder.
When I start my 2DS while holding `Start`, the normal home menu of my 2DS open.
Why ?

Thank you in advance,

Paloys

**Comment by d0k3** [comment]
Well... if that really is a bug, it's a Luma bug, not a GM9 one. Luma is the software in charge of booting GM9, and you don't even get into GM9. Revisit the guide and doublecheck you did everything right. if you are 100% sure, open a issue for Luma 3DS. 

Closing this now, feel free to reopen or add comments if you are still convinced this is a GM9 issue.
