### ISSUE TITLE
GM9 doesnt boot when presented with foreign file system

### ISSUE THREAD

**Issue by SomberlySober** [d0k3/GodMode9#459]
GM9 ignores the input on boot when an ad is inserted with an ext3/ext4 file system. The system behaves as if GM9 isn't installed to begin with.

**Comment by d0k3** [comment]
I guess I'll need more info... what's your bootloader? Where is GodMode9.firm booted from?

**Comment by d0k3** [comment]
Okay... this is still missing info.

However, this sounds a lot like you're trying to load GM9 from an ext3/ext4 formatted SD card, which will of course not work. None of the available ARM9 bootloaders on 3DS (boot9strap, fastboot3DS, Luma 3DS, GodMode9) support the file system (and why should they?). You're also not running GM9 as bootloader, cause in that case it would either work, or you couldn't boot into the 3DS OS either.

So, closing this now. Feel free to add info or reopen if I'm mistaken.
