### ISSUE TITLE
shaget/cp -h bad output

### ISSUE THREAD

**Issue by ihaveamac** [d0k3/GodMode9#460]
There seems to be a problem with hashes generated by `shaget` and `cp -h` (and maybe related commands). The output doesn't match SHA-256 generated on a PC, or though the GodMode9 interface. This did not seem to happen when copying a section with all null bytes. Tested with 10ec95b8fe626b492f878354ce0022a4aa6a7224 and v1.7.1.

Compare SHA-256 of resulting files with sha, the result is different. 

Example 1:
```bash
# currently unsure if these directories are causing issues,
#   but this matches the setup just in case
mkdir 0:/nanddump
mkdir 0:/nanddump/chunks

# copy first 0x100000
inject -o -s S:/nand_minsize.bin@0:100000 0:/nanddump/chunks/0x00000000p0x00100000.bin@0

# attempt to generate hash, but it might result in bad output
shaget 0:/nanddump/chunks/0x00000000p0x00100000.bin 0:/nanddump/chunks/0x00000000p0x00100000.bin.sha
```

Example 2:
```bash
mkdir 0:/nanddump
mkdir 0:/nanddump/chunks

cp -w -h S:/nand_minsize.bin 0:/nanddump/nand_minsize.bin
```

**Comment by d0k3** [comment]
Thanks a lot for opening that issue and providing detailed info!

**Comment by ihaveamac** [comment]
Turns out all hashes generated with any method were bad. This may actually be a result of a change in devkitARM r51, since building with r50 didn't seem to cause this issue.

**Comment by d0k3** [comment]
... and fixed. The problem was actually in some `memcpy` optimizations that r50 didn't but r51 does.
