### ISSUE TITLE
(Request) GodMode9 CIA

### ISSUE THREAD

**Issue by MasterGamingYT** [d0k3/GodMode9#461]
It will be really cool to have a GodMode9 CIA so that I don't have to constantly turn the power off just to go to GodMode9

**Comment by DMSalesman** [comment]
As far as I know, the 3DS would have to reboot anyway, since GodMode9 runs on ARM9 and not ARM11.

**Comment by SirNapkin1334** [comment]
Not possible. You can try [A9NC](https://github.com/d0k3/A9NC) though.

**Comment by d0k3** [comment]
Look here:
https://github.com/Ordim3n/That-Shortcut-Thingy/releases/tag/1.0

Buuut! This will only work with fastboot3DS installed and boot from FCRAM enabled. Read the readme for instructions on setting it up.

And, no, it doesn't get easier than that.

**Comment by MasterGamingYT** [comment]
How do I install fastboot3ds?

**Comment by MasterGamingYT** [comment]
Nevermind
