### ISSUE TITLE
[Feature Request] Build .cia from DSiWare .nds

### ISSUE THREAD

**Issue by DMSalesman** [d0k3/GodMode9#465]
Would it be possible for GM9 to distinguish between a retail and a DSiWare .nds and offer the choice to build a .cia from the latter, à la `make_cia`?

**Comment by d0k3** [comment]
Should be possible, feature will be coming up.

**Comment by d0k3** [comment]
Okay, here's a test build - can you please test this with some titles and give me feedback?
https://f.secretalgorithm.com/EaCrg/godmode9.firm

New release coming up very, very soon. If you want that feature in there I'll need feedback fast.

**Comment by DMSalesman** [comment]
Tested with Shantae: Risky's Revenge, works perfectly.

**Comment by d0k3** [comment]
Okay, assuming this working. Further testing is still encouraged.

**Comment by DMSalesman** [comment]
Tested four more games with a bulk conversion, and every one of them works.

**Comment by pthfdr-42** [comment]
What about normal NDS roms?
I remembered that WarioWare Touched has a standalone version and a DSiWare version.

**Comment by ihaveamac** [comment]
The reason "WarioWare: Touched!" has a DSiWare version is because Nintendo recompiled it to work as such. It is not a repackaged version of the retail rom. Use nds-bootstrap/TWiLight Menu++ if you want to load NDS games from the SD card.

**Comment by DMSalesman** [comment]
Exactly what @ihaveamac said. By contrast, converting a DSiWare to .cia is necessary on 3DS, because nds-bootstrap can't run it as a .nds file.

**Comment by bosskay972** [comment]
Hello,
I'm just curious about this conversion... Because I have a simple question:
How do you find DSi ware in .nds format ?
It's more difficult to find it in .nds format than .cia format.
So where did you get those rom ?

**Comment by DMSalesman** [comment]
@bosskay972 Assuming you're talking to me, I found them over at the big archival site, The Eye. Last I checked, though, they removed DS ROMs from the public directories.

**Comment by Wolfvak** [comment]
First and last reminder: we do not support piracy, nor any "archival" sites. If you want to find stuff, use google, it's not super hard.
