### ISSUE TITLE
Version 1.8.0 - Bottom screen is black; unable to see options

### ISSUE THREAD

**Issue by jducci25** [d0k3/GodMode9#467]
Reverted to older version 1.7.1

**Comment by james-d-elliott** [comment]
https://github.com/d0k3/GodMode9/issues/466

Probably related. See this issue to keep up to date.

**Comment by d0k3** [comment]
@jducci25 - that's the same issue as #466. You can chime in there. Maybe try running GM9 v1.8.0 as `0:/boot.firm` or try running it from Luma with multiple .firm files inside the payload folder? Closing this now...
