### ISSUE TITLE
Mario Kart DS multiplayer kiosk demo cart won't decrypt properly

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#469]
Someone I know trying to dump the Mario Kart DS european multiplayer kiosk demo cart (AM3P), but its either not being decrypted properly or not at all. The GameHeader printout for the dump is attached. GameHeader normally displays the hashes of the ROM after re-encryption at the end, but it isn't doing that here.
[MKDS_VS.txt](https://github.com/d0k3/GodMode9/files/3013850/MKDS_VS.txt)

**Comment by d0k3** [comment]
That's not enough info... You're talking about Mario Kart *DS*? DS games are not encrypted.

**Comment by d0k3** [comment]
You're talking about problems with the gamecart dump, right? You'll need to compare the CRC with a known good dump (demo carts are special), and we may also need to see the dump itself (don't share it here, tho, because of copyright).

**Comment by mariomadproductions** [comment]
This is a previously undumped DS kiosk demo cart. DS games [are](http://www.akkit.org/info/gbatek.htm#dscartridgesecurearea) encrypted. I'll DM you on discord about the ROM.

**Comment by d0k3** [comment]
The Secure Area is, nothing else. Is there a known good dump for this cart? If it is different, it's best to compare the two in a hex editor,.

**Comment by mariomadproductions** [comment]
No this is a very rare cart so there aren't any other dumps.

**Comment by d0k3** [comment]
Okay, just to keep you updated... it looks like this is a special unencrypted cart.

See here:
https://problemkaputt.de/gbatek.htm#dscartridgesecurearea

> Avoiding Secure Area Encryption
> WLAN files are reportedly same format as cartridges, but without Secure Area, so games with Secure Area cannot be booted via WLAN. No$gba can encrypt and decrypt Secure Areas only if the NDS BIOS-images are present. And, Nintendo's devkit doesn't seem to support Secure Area encryption of unreleased games.
> So, unencrypted cartridges are more flexible in use. Ways to avoid encryption (which still work on real hardware) are:
> 1) Set NDS9 ROM offset to 4000h, and leave the first 800h bytes of the Secure Area 00h-filled, which can be (and will be) safely destroyed during loading; due to the missing "encryObj" ID; that method is used by Nintendo's devkit.

I checked the cart dump and the bytes from 0x4000...0x4800 are indeed zero. So, the first entry seems to apply.

**Comment by d0k3** [comment]
Alright, after talking with @Myriachan (thanks, as always!) and confirming with ppltoast (cart runs), my assumption seems to be right. I'm closing this issue now, feel free to reopen or comment if anything comes up.

**Comment by mariomadproductions** [comment]
I'll make sure to check the secure area stuff on gbatek next time :P

But there's still one thing - wooddumper (latest - r89) actually produces some data:
```
97 C3 86 E3 7E 5B 77 82 1A 16 A5 53 0F B8 17 60
1A 16 A5 53 0F B8 17 60 1A 16 A5 53 0F B8 17 60
```
[then 1A 16... repeats]

**Comment by d0k3** [comment]
That's because Wood Dumper decrypts data that isn't there. The Wood Dumper dump is bad.

**Comment by mariomadproductions** [comment]
Yeah, I thought I cancelled that post, sorry.
