### ISSUE TITLE
CTRNAND is fragmented or corrupt

### ISSUE THREAD

**Issue by LioMajor** [d0k3/GodMode9#47]
GM9 Build: 7299970 (Apr 12, 2017)

Example after using GodMode9 CTR Transfer FW 9.2 to 11.2.
new3DS boots 11.2 fine, but it is no longer possible to dump
ticket.db or to create a new CTR Transfer file in Decrypt9.

Error: CTRNAND is fragmented or corrupt

But using Decrypt9 CTR Transfer FW 9.2 to 11.2, everything is ok.

**Comment by d0k3** [comment]
Well... not much that can be done about it, unless we had a defragmenter. FATFS allows for fragmentation by default. Only D9's legacy FAT routines never introduce fragmenatation, but they are also very limited. Defragmentation would take a long time (on 3DS hardware), and wouldn't really be worth it, as it would increase time requirements greatly and would be required only for D9 ocmpatibility.

We can discuss this on IRC, for now I can just tell you, use GM9. A transferable image is just a copy of the ctrnand_full.bin.
