### ISSUE TITLE
Godmode9 gamecart says empty

### ISSUE THREAD

**Issue by ShadowKnight1771** [d0k3/GodMode9#470]

**Comment by ShadowKnight1771** [comment]
when i boot up godemode9 to dump a game the gamecart section says gamecart (empty) but i have a physical game card in the system. Was wondering if anyone can help me with this. Thanks in advance.

**Comment by ShadowKnight1771** [comment]
Btw it is on a old 3ds xl

**Comment by d0k3** [comment]
Broken cart slot, apparently. Do these carts show up in 3DS home menu? Can you play them?

**Comment by SirNapkin1334** [comment]
Have you tried taking out the card and putting it back in? Seriously, sometimes it doesn't recognize it on boot and requires it to be taken out. It's happened to me.

**Comment by ShadowKnight1771** [comment]
yes it reads the game card on the home screen an can be started an played. i have also tried taking it out an putting it back in as well an it doesn't seem to help.

**Comment by al3x10m** [comment]
does any other cart show in gm9?

**Comment by ShadowKnight1771** [comment]
No

**Comment by d0k3** [comment]
Can you try with this software?
https://dl.dropboxusercontent.com/s/hh000foctxm96x1/fastboot3DS_gamecard.firm

Choose "Credits" to start the Gamecart Dumper. Don't choose anything else inside the menu. You can leave the software via the POWER button.

**Comment by d0k3** [comment]
@ShadowKnight1771 - can you test with the new dumper I just provided? I think it may also help if you told us which gamecarts you tried.

**Comment by david4444** [comment]
I'll test it, since I have been experiencing this issue also.

**Comment by david4444** [comment]
It dumps the cartridge.
Tested with Pokemon X

**Comment by d0k3** [comment]
@david4444 - so you had the same issue? That makes it look less like a hardware failure. Does it work for no carts at all? Not even DS ones? And, can you try some test builds to help me get to the bottom of this?

**Comment by david4444** [comment]
@d0k3 I'm really confused.
Just a minute ago I tested with GodMode9 if it can detect the cart. I went to check in the home menu, wasn't there. Rebooted, its there again. Got into GodMode9 and went inside the drive and its working now???
I think my cart slot is broken.
And now I booted again and it doesn't work.
Well, I apparently have a different issue.
Though, OP's issue seems different. Doesn't detect it in GodMode9 but in the home menu it does doesn't seem like a broken cart slot.

Sorry for all of this!

**Comment by d0k3** [comment]
@david4444 - no problem at all. And, thanks for trying to help!

@ShadowKnight1771 - we really need more info. Can't fix this without.

**Comment by ShadowKnight1771** [comment]
Sorry been very busy dealing with an family emergency but i have tried it
with both pokemon ultra sun an ultra moon

**Comment by ShadowKnight1771** [comment]
This is now what it looks like if i take the card out an put it back in.

**Comment by d0k3** [comment]
@ShadowKnight1771 I hope all is well now. Of course family comes first.

Does your last comment miss a picture? And, if you got time, can you try the alternative dumper (I posted that 5 days ago).

**Comment by ShadowKnight1771** [comment]
Yes there was suppose to be a pic. An i can later today right now getting
ready to leave for work.

**Comment by d0k3** [comment]
@ShadowKnight1771 - we still need more info. Can you provide that pic and try the alternate dumper?

**Comment by d0k3** [comment]
Okay, closing this due to lack of info, assuming hardware failure. @ShadowKnight1771 - feel free to reopen or add comments in case something comes up.
