### ISSUE TITLE
(Feature Request) Convert .cia to .3ds

### ISSUE THREAD

**Issue by MasterGamingYT** [d0k3/GodMode9#472]
Is it possible that you can add a feature that converts cia to 3ds so I can use them with my sky3ds flashcard?

**Comment by d0k3** [comment]
Why would you even want that? it's not completely impossible, but, you know, you won't get a proper one. Playing it would still require CFW, as we can't rebuild a proper signature. We'd also have to take some guesses for some data in there .Even those .3ds files made from eShop titles earlier when GW was still a thing are Frankensteinian creations and in no way proper.

So, in short, that's not a feature I'd want in there. Give me a good reason and I may reconsider.

**Comment by MasterGamingYT** [comment]
I understand, anyways I'm gonna close this issue
