### ISSUE TITLE
Switching between multiple EmuNANDs is not working

### ISSUE THREAD

**Issue by cbig6464** [d0k3/GodMode9#48]
_Update: I found a workaround, please see the next comment._

Hello, I can't get GodMode9 to switch between my multiple EmuNANDs. At this screen:
`Current EmuNAND offset is 000001. Switch to next offset?` pressing 'yes' does nothing. The top display blanks for ~50ms, then that screen reappears with the exact same message.

I set up my EmuNANDs using this tool: https://gbatemp.net/threads/release-3ds-multi-emunand-creator.381603/ Luma switches just fine between the EmuNANDs and they all boot without problems.

Using the tool above, I imported the same O3DS SysNAND dump (length `0x1D7800` 512-byte sectors) three times. This is the resulting disk geometry:
`EmuNAND 1: LBA 0x000001 Len 0x1D7801  (then gap at LBA 0x1D7802 Len 0x07FE zero-filled)`
`EmuNAND 2: LBA 0x1D8000 Len 0x1D7802  (then gap at LBA 0x3AF802 Len 0x07FE zero-filled)`
`EmuNAND 3: LBA 0x3B0000 Len 0x1D7802  (then gap at LBA 0x587802 Len 0x07FE zero-filled)`
`Normal FAT32 partition: LBA 0x588000 Len 0x071F7800 (to end of disk)`
The signature at LBA0 is `GATEWAYNAND`. Only the FAT32 partition is actually in the partition table.
EmuNAND 1 is bit-for-bit identical to the source SysNAND dump. There's one trailing sector (relative `0x1D7800`) filled with `0x0D0A`.
EmuNANDs 2 & 3 are bit-for-bit identical to the source, except for the first sector and the 2 trailing sectors: The first sector (relative `0`) and the last sector (2nd trailing, relative `0x1D7801`) are filled with `0x0D0A`. The pre-last (1st trailing, relative `0x1D7800`) sector is the first sector of the original image (bit-for-bit identical). I'm assuming this slight data shifting is by design.

Please let me know if this is not a bug, but rather the tool above laying out the EmuNAND partitions in a non-recommended way. I could not find any documentation at all on this matter.

Thanks for any assistance on this.

**Comment by cbig6464** [comment]
I found out that if I use the 'Inject RedNAND' option instead of the 'Inject EmuNAND' option in 3DS Multi EmuNAND Creator (link in prev. comment), both GodMode9 and Luma see the 3 EmuNAND partitions correctly. I suppose all that means is that GodMode9 doesn't support the full EmuNAND spec (if there even is such a thing). I don't know if this even deserves a fix, since the RedNAND partition layout is better in my opinion (details below), so please feel free to close this issue.

Thanks for your work on GodMode9! It's awesome.

Technical details:
By performing the same procedure in the prev. comment, but this time using the RedNAND option, this is the resulting disk geometry:
`EmuNAND 1: LBA 0x000001 Len 0x1D7800 (then gap at LBA 0x1D7801 Len 0x0800)`
`EmuNAND 2: LBA 0x1D8001 Len 0x1D7800 (then gap at LBA 0x3AF801 Len 0x0800)`
`EmuNAND 3: LBA 0x3B0001 Len 0x1D7800 (then gap at LBA 0x587801 Len 0x0800)`
`Normal FAT32 partition: LBA 0x588000 Len 0x071F7800 (to end of disk)`
This time, all 3 EmuNAND partitions are bit-for-bit identical to the source SysNAND dump! This means that I could have just imaged a raw SysNAND or EmuNAND dump to LBAs `0x000001, 0x1D8001, 0x3B0001` with any hex editor/imager (like I wanted to do in the first place) without using any other tools. (Why was this not documented anywhere?) One minor technicality: each EmuNAND partition is surrounded by one leading and one trailing sector filled with `0x0D0A` (except, of course, for LBA 0 on the disk). The remaining space of the gaps is zero-filled (and _probably?_ ignored by readers).

**Comment by d0k3** [comment]
Alright, first of all, thanks for the detailed bug description.

> Please let me know if this is not a bug, but rather the tool above laying out the EmuNAND partitions in a non-recommended way. I could not find any documentation at all on this matter.

Well, you actually hit the nail. The only real reason to actually use the GW EmuNAND layout is for GW compatibility. GW hardware, however, does not support multi EmuNANDs. So... there is no reason at all to have any EmuNAND but the first one in GW EmuNAND format.

Now, does this deserve a fix? Unsure. EmuNAND is already no more as widely used as it has been, and multi EmuNAND is pretty niché. And your multi EmuNAND setup is special (that tool shouldn't even provide that way of setting it up). Luma3DS supporting this way of setting it up is the only real reason I may  add support for it. I'll have to think about it.

As for this:

> One minor technicality: each EmuNAND partition is surrounded by one leading and one trailing sector filled with 0x0D0A (except, of course, for LBA 0 on the disk). The remaining space of the gaps is zero-filled (and probably? ignored by readers).

Leading and trailing sectors, as well as the padding, are always ignored. They can contain anything.
