### ISSUE TITLE
Decryption failed 

### ISSUE THREAD

**Issue by Zero52CZ** [d0k3/GodMode9#480]
So when i try to decrypt a game to the gm9/out folder it gives me an error saying the decryption failed. It was working for me for a very long time and suddenly stopped, but i have no idea why. I also checked if I have enough space on my Sd card and it appears I do. Does anybody know what is going on?

**Comment by Wolfvak** [comment]
Would you mind telling us why you closed the issue? Maybe it'll help solve other issues faster, should they come up.

**Comment by Zero52CZ** [comment]
I closed the issue because you said I should post this issue on GbaTemp. Bit
it actually got resolved later on, therefore I closed the issue.

---------- Původní zpráva ----------
Od: Wolfvak 
Datum: 4. 5. 2019 v 17:40:12
Předmět: Re: [d0k3/GodMode9] Decryption failed (#480)


Would you mind telling us why you closed the issue? Maybe it'll help solve 
other issues faster, should they come up.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
(https://github.com/d0k3/GodMode9/issues/480#issuecomment-489337719), or 
mute the thread

**Comment by d0k3** [comment]
Can you tell us how you resolved it, @Zero52CZ?

**Comment by Zero52CZ** [comment]
Sure, I downloaded the 3 files in the gm9/support folder and replaced the 
old ones. After rebooting the system it was working again.

---------- Původní zpráva ----------
Od: d0k3 
Datum: 6. 5. 2019 v 15:18:53
Předmět: Re: [d0k3/GodMode9] Decryption failed (#480)


Can you tell us how you resolved it, @Zero52CZ(https://github.com/Zero52CZ)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
(https://github.com/d0k3/GodMode9/issues/480#issuecomment-489617042), or 
mute the thread
