### ISSUE TITLE
System not turning on when trying to boot GM9

### ISSUE THREAD

**Issue by cwyn-ne** [d0k3/GodMode9#481]
Following [this ](jhttps://www.youtube.com/watch?v=g7xCx-E_5Uo)Fredminer CFW tutorial, and I got to the section where I'm to create a SysNAND backup in Godmode9, but when trying to boot it up (START + Power) the blue power light turns on for a few seconds then fades (the screen remains dark). I've checked everything, my firm file is in the correct luma/payloads folder, I have the gm9 folder in the root. Not really sure what to try at this point, and I'm assuming skipping the SysNAND backup wouldn't be very wise (I've never tried doing anything like this before so I'm completely new to everything). Also created a GitHub account purely to post this so I'm not really sure if this is in the correct place lol.

**Comment by Wolfvak** [comment]
I see you've already posted on the other issue - the solution is to either not use luma, or use the release v1.7.1 binary of GM9 which is known to work with most luma builds

**Comment by cwyn-ne** [comment]
Using v1.7.1 worked, thank you so much!

**Comment by Maurogch** [comment]
Using the chainloader menu also works (having more than one firm file in Luma payloads). Just put two godmode9.firm files, you can even have the v1.7.1 and the v1.8.0 at the same time.
