### ISSUE TITLE
Does G9 have a way to remove the upgrade installation package for EmuNAND system?

### ISSUE THREAD

**Issue by Aeuko** [d0k3/GodMode9#482]
I accidentally downloaded the upgrade package automatically, I tried to find a way to delete it, otherwise I will be prompted to upgrade every time.

**Comment by aspargas2** [comment]
I'm going to a assume that by "upgrade package" you mean a system update. These days, there's really no reason to be using emunand or to be on anything other than the latest version, but if you insist downloaded updates can be deleted by entering recovery mode but not actually updating with it (unrelated to gm9).

**Comment by Aeuko** [comment]
Is a system update. I understand what you mean, I have a special reason to use the low version EmuNAND, recovery mode deletion is only suitable for sysNAND, not for EmuNAND, so I have been looking for a way!

**Comment by d0k3** [comment]
Make a backup of your SysNAND, safe restore your EmuNAND to your SysNAND, then do what @aspargas2 said. Then copy your EmuNAND back to your EmuNAND and your SysNAND back to your SysNAND.

Not exactly comfortable, but, well, pay better attention in the future. I'm closing this now.
