### ISSUE TITLE
Error GM9MegaScript GodMode V1.8.0 on 2DS

### ISSUE THREAD

**Issue by Alelih** [d0k3/GodMode9#483]
Hello guys.

I have a problem on:
https://3ds.hacks.guide/ctrtransfer.html
Step 15 section 2 from this tutorial
I have an Old 2DS
![P_20190513_184547_vHDR_Auto](https://user-images.githubusercontent.com/50600542/57687672-37d97d80-7612-11e9-8982-3b3b537a6f66.jpg)

**Comment by AlvaroAlmeida** [comment]
Hello, i have the same problem, pls if you solve, tell me, i am trying to uninstall the CFW
i appreciate it

**Comment by Alelih** [comment]
Ok Álvaro!

**Comment by AlvaroAlmeida** [comment]
actually my godmod9 dont update. He keeps on version 1.4.0 and i just cant update and i dont know why.
When i turn on the 3ds i have to remove the sd card before press power button, then i put the card back. finally 3ds is on. do you see?

**Comment by AlvaroAlmeida** [comment]
im brazilian, sorry my english

**Comment by d0k3** [comment]
Everyone, can you try this GodMode9 testing version?
https://transfer.sh/CMEnW/GodMode9-v1.8.0-50-ge5b18342-20190515143901.zip

**Comment by Alelih** [comment]
Hello d0k3. This link is working?

**Comment by AlvaroAlmeida** [comment]
yep, it's broken

**Comment by AlvaroAlmeida** [comment]
yep, but i cant update godemod9 using the file. do i have to update boot9strap? thats why i cant update godmode?

**Comment by aspargas2** [comment]
@AlvaroAlmeida Ok, first off, how are loading GodMode9? Luma's chainloader?

**Comment by AlvaroAlmeida** [comment]
nope, i am loading using an godmode9 cia that i installed on 3ds home menu. I cant use luma chainloader. my sd card is corrupted thats why i have all these problems and im tryng to reset everything on 3ds.

**Comment by AlvaroAlmeida** [comment]
using godmode9 to uninstall CFW

**Comment by Alelih** [comment]
@d0k3 same error in the testing version.....

**Comment by d0k3** [comment]
Okay, that's weird... can you try GodMode9 v1.7.1? (just download it from releases)

**Comment by AlvaroAlmeida** [comment]
i tryed v1.7.1 and the same error

**Comment by Alelih** [comment]
Me too

**Comment by Alelih** [comment]
@d0k3, any more ideas?

**Comment by d0k3** [comment]
@Alelih @AlvaroAlmeida - I'll think abotu something and will get back.

**Comment by Alelih** [comment]
Hey guys, mine worked, first I updated Luma and boot9strap BEFORE GodMode9. So GM9MegaScript worked. Everything is perfect, apparently, I will test more and return to you.
Thanks @d0k3.

**Comment by d0k3** [comment]
Everyone still having that issue... could you try this version of the GM9MegaScript?
https://f.secretalgorithm.com/ctNIR/gm9megascript.gm9

Tell me what is shown on screen or make a photo / screenshot.

**Comment by AlvaroAlmeida** [comment]
yep like as i think. i need to update boot9strap and luma 3ds,but my sd card is corrupted

**Comment by AlvaroAlmeida** [comment]
i cnat  update lumaou boot9strap, is there something more that i can do?

**Comment by d0k3** [comment]
@AlvaroAlmeida - try the alternative script I posted.
https://f.secretalgorithm.com/4ZHT5/gm9megascript.gm9

**Comment by AlvaroAlmeida** [comment]
I took for maintance, if he return's with the same problem i try the alternative script. I guess at friday he's back

**Comment by Alelih** [comment]
My SD card broke ... I'll be back after buying a new one.

**Comment by AlvaroAlmeida** [comment]
guys my 3ds returned from maintance and is working. thanks you everyone for the attention, you are awesome

**Comment by d0k3** [comment]
Okay, apparently this magically solved itself for everyone. If there are still complaints, feel free to continue writing here.

**Comment by chemicalcorsair** [comment]
The same thing happened to me, and I've been following the same 3ds.hacks.guide guide to install Luma3DS and homebrew my 3ds. I'm using GodMode 1.8.0 and tried installing the GM9Megascript V1.2 https://github.com/annson24/GM9Megascript/releases/tag/v1.2 still can't access Plialect's script even after manually changing the third line in case the code was missing something. I tried creating a folder GM9IN as I think it's missing from the in folder in GM9? Not sure what the code is trying to find but it still didn't work before and after the folder was created. 
Thanks!

**Comment by d0k3** [comment]
@annson24 - we need your help here. @chemicalcorsair - I'd suggest you open an issue in the GM9Megascript repo.

**Comment by chemicalcorsair** [comment]
I've opened an issue https://github.com/annson24/GM9Megascript/issues/14

**Comment by d0k3** [comment]
@hajarbeni - this is a three year old issue for a three year old version of both GM9 and the Megscript. It's highly doubtable you got the same issue. If you want to, do a proper bug report with a proper description and open a new issue.
