### ISSUE TITLE
help converting 3ds to cia

### ISSUE THREAD

**Issue by ThatDudeGuy13** [d0k3/GodMode9#484]
I'm trying to build a .cia from a .3ds of persona q and it fails when i try. im using a 2ds on 11.9.0-42e

**Comment by knight-ryu12** [comment]
please see [this](https://github.com/knight-ryu12/godmode9-layeredfs-usage/wiki/Godmode9-CIA-Dumping-and-Building)

**Comment by d0k3** [comment]
Maybe you simply don't have enough space free?

**Comment by d0k3** [comment]
Okay, closing this for lack of info. @ThatDudeGuy13 - if not yet solved, please continue writing here and I'll reopen.
