### ISSUE TITLE
Sysnand Backup failed but... worked??

### ISSUE THREAD

**Issue by xXKlamba05Xx** [d0k3/GodMode9#485]
Heey people of the Internet,
so I have a sort of big problem with gm9. When I try to make a Sysnand Bacykup it says after a while it **failed**, but when I look in to F:(my Sd)/gm9/out I can se the Sysnand file: 190525_*************_sysnand_01.bin . So is that normal... And is the NAND ok? I checked
https://github.com/Plailect/Guide_RedNAND/wiki/NAND-Size and it looks like I have a **SAMSUNG** NAND.(cuz the file is 1.21GB) _If someone could show me how to check the nand or something i'd be great._

p.s. sorry for my bad english im from germany and not the best in english

**Comment by ihaveamac** [comment]
If it failed, it likely didn't actually read the full NAND, so most of the space is garbage data. Is there an sha file?

**Comment by xXKlamba05Xx** [comment]
What do you mean? Like a *.sha ?
Thanks for the help btw.

**Comment by xXKlamba05Xx** [comment]
I could make a Mega Link to my NAND if you could say then if its garbage or not? And can i just use the NAND reader from FBI?

**Comment by d0k3** [comment]
Sounds like SD card failure, @xXKlamba05Xx. GodMode9 can also verify a NAND backup (A button on the file), but we can't verify everything, thus even if the verification passes, there may be some problem.

Is there any chance your SD card is corrupted or full?

**Comment by xXKlamba05Xx** [comment]
So i don‘t really know what I did. I just tried again (I did it really often) but now it worked...? Well... IDC how but it worked.
