### ISSUE TITLE
Godmode9 not working on 11.10

### ISSUE THREAD

**Issue by hunttung** [d0k3/GodMode9#487]
all the firms and payloads are in the right folders, luma>payloads> Godmode9.firm. no matter what it will not show up.

**Comment by Ectalite** [comment]
Same here, can't boot it  and  it is freezing

**Comment by hunttung** [comment]
Damn! Nintendo!

**Comment by aspargas2** [comment]
This has nothing to do with 11.10. The latest GodMode9 not working on some systems is a [known issue](https://github.com/d0k3/GodMode9/issues/466). Temporarily using [GodMode9 1.7.1](https://github.com/d0k3/GodMode9/releases/tag/v1.7.1) instead should fix it.

**Comment by hunttung** [comment]
Will it ever get fixed?

**Comment by d0k3** [comment]
Assumed duplicate of https://github.com/d0k3/GodMode9/issues/466

GodMode9 does not care about the system version installed. OS version 11.10 can't have anything to do with it.
