### ISSUE TITLE
Legit CIA is broken???

### ISSUE THREAD

**Issue by BpyH64** [d0k3/GodMode9#488]
I bought the game SKYPEACE without account NNID and made Legit CIA it through Godmod9.After removing the game, I installed the game through FBI. At the end of the installation I received error 'Cert signature or hash failed'

**Comment by d0k3** [comment]
Nah, that does not sound broken. If you make a legit CIA from game you purchased, that CIA is only installable on the system you bought it from (yeah, that also means it's no more installable once you use a different eShop id).

Can you tell me the output of the CIA Checker Tool in GM9?

What do you mean by "without account NNID"?

**Comment by BpyH64** [comment]
"without account NNID" -buying a game does not require creating an account.

I create two CIA files. 
When created the standart CIA no error at installation.
When created the Legit CIA is error at installation

**Comment by redunka-zver** [comment]
Non-universal legit CIAs can't be installed even on the system they were purchased from, it's not GM9's fault.
As mentioned [here](https://gbatemp.net/threads/wip-release-ctrcdnfetch-tool-to-download-3ds-eshop-content-after-11-8.519928/#post-8318488), AM rejects console unique tickets, the ConsoleID must be zero'd out for them to be installable.
Perhaps this could be changed with a CFW patch (if someone makes one).

**Comment by d0k3** [comment]
@thanks for the hint, @redunka-zver !

**Comment by d0k3** [comment]
AM issue, not a GM9 issue. Thus closing this. I did improve the legit CIA build warning for personalised tickets, tho.
