### ISSUE TITLE
Latest build (1.8.0-58) on the hourlies site is unbootable.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#490]
The size of the FIRM files is significantly smaller (96kiB v. 527kiB).  
Attempting to boot them results in a black screen.

**Comment by Wolfvak** [comment]
That's a a firmtool bug, it needs to be updated to the latest version in the build server.

**Comment by RShadowhand** [comment]
Build server has been updated. You should see proper builds, starting next hour.

**Comment by d0k3** [comment]
Fixed by @RShadowhand, thanks!

**Comment by d0k3** [comment]
@pthfdr-42 - if you still experience broken builds after that, let us know!

**Comment by Ammako** [comment]
Could a manual rebuild be done? Because the latest builds on the site are still the broken ones, as far as I can tell.
