### ISSUE TITLE
fastboot problem

### ISSUE THREAD

**Issue by zjthang** [d0k3/GodMode9#491]
ok so initially i had problems with running godmode9 as i had no top screen i was advised to install fastboot.. everything runs fine now i get the godmode9 when i boot it up but now i cannot run pokemon sun.. when i run the game, a few seconds later i get an error code the process name is niji_loc

**Comment by zjthang** [comment]
the error says
    error type: generic
> process ID: 42
> process name: niji_loc
> process title ID: 0x0004000000164800
> 
> address: 0x006b39d8
> error code:0xc9604523

**Comment by zjthang** [comment]
the pokemon sun game i am using is the legit cartridge not the installed one btw.. im not sure if its the fastboot causing the problem but i really need help :( thanks very much to whoever can help

**Comment by d0k3** [comment]
It's not fastboot causing the problem. Apart from that, even if it was (it isn't I guarantee it), that would be a fastboot issue, not a GodMode9 one.

Maybe check your fastboot3DS config (HOME button on boot)? It's best to install it via the latest version of OpenFirmInstaller, btw.
