### ISSUE TITLE
Minor bug: inserted cart not detected on startup

### ISSUE THREAD

**Issue by dratini0** [d0k3/GodMode9#492]
I really like the new feature that shows the cart ID next to the C: drive. However, if I start GM9 with a cart already in the slot, it just shows it as empty. Reinserting the cart fixes the issue. I have tried both NTR and CTR carts. I have no DSi enhanced carts.

For the record I am using a N3DSXL, with B9S and Luma3DS.

**Comment by dratini0** [comment]
Oh, and before I forget: this is visual only, I can still open the C: drive, and when I close it, the correct ID is shown.

**Comment by d0k3** [comment]
Can you try this test build?
https://f.secretalgorithm.com/m5jCR/godmode9.firm

**Comment by Validusername16** [comment]
The test build does indeed do what it's supposed to.

**Comment by dratini0** [comment]
Thank you! I just got around to testing it.

However, it seems that in this build hotswapping carts doesn't work, it keeps the same cart ID in the menu. Additionally, even when I open it, it keeps the same listing.

A notable exception is starting empty, in which case it keeps the first cart that I open.

**Comment by d0k3** [comment]
@dratini0 - does everything work as expected on the latest release version (v1.8.0)?

**Comment by dratini0** [comment]
Other than the initial report, yes

**Comment by d0k3** [comment]
Okay, detecting cart changes should work now. As for cart detection on boot - we don't do that, it takes too much time. Instead, the CART drive now says `INIT` as long as it is not initialized.

**Comment by mariomadproductions** [comment]
If you are talking about the 8-hex-digit cart ID - this can sometimes be the same between different carts. Something to keep in mind.
