### ISSUE TITLE
A GodMode9 script with the command “bkpt” crashes GodMode9

### ISSUE THREAD

**Issue by Validusername16** [d0k3/GodMode9#493]
A script that has the command “bkpt” in it will cause godmode9 to crash to [this screen](https://media.discordapp.net/attachments/441119928334942218/590739924454604811/image0.jpg) upon executing that command, which I don’t think is intended.

**Comment by Validusername16** [comment]
(Please ignore the fact the picture is from a dev release, it happens on normal gm9 1.8.0 as well)

**Comment by Wolfvak** [comment]
It's intentional
https://github.com/d0k3/GodMode9/blob/master/arm9/source/utils/scripting.c#L1454
