### ISSUE TITLE
Feature request: Build CIA from multiple NCCH files.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#497]
On a Linux computer I used `decrypt.py` to decrypt CIAs in batch, however, the output is in the format of multiple files which names are `[Title ID].[Number].ncch`.
GM9 can build CIA files from a single NCCH but if I select every NCCH GM9 generates multiple CIAs which is not desired since they belong to the same game.
(Also you should make a tool to decrypt CIA files from a PC in batch since they can be compressed for archival.)

**Comment by aspargas2** [comment]
You can generate a multi-ncch CIA in gm9 by building a CIA from the tmd

**Comment by d0k3** [comment]
As @aspargas2 said. You need a TMD file to create a CIA file with multiple contents. The TMD file contains additional info that makes sure the multi content CIA works as expected.
