### ISSUE TITLE
Script_Runner mode is broken with latest commits

### ISSUE THREAD

**Issue by De1v1d** [d0k3/GodMode9#499]
Compiling a GodMode9 script with the latest commits break everything.

1. Brightness is broken with FIXED_BRIGHTNESS=15
2. Some images are not loading
3. Load a .firm payload freeze the 3DS.

No issues compiling the script with the latest april commit.

**Comment by Wolfvak** [comment]
1. The meaning of FIXED_BRIGHTNESS has changed a bit, I'll document it later (also did you try with the absolutely latest commit in the `staging` branch?)

2 & 3. Which images and FIRMs in particular cause this behavior? And are you trying this on an O3DS/2DS or N3DS/2DSXL?

**Comment by De1v1d** [comment]
> 1. The meaning of FIXED_BRIGHTNESS has changed a bit, I'll document it later (also did you try with the absolutely latest commit in the `staging` branch?)
> 
> 2 & 3. Which images and FIRMs in particular cause this behavior? And are you trying this on an O3DS/2DS or N3DS/2DSXL?

1. I tried with latest commit in the staging branch, no changes
2. Every image I tried (GodMode9, OpenFirmInstaller,...) freeze
3. Im trying this on a 2DS

Also I tried to compile GodMode9 with latest commits and it doesnt boot, white screen.

**Comment by Wolfvak** [comment]
I thought you meant a PNG image when you said "image". So problems 2 and 3 are the same.

So these problems only show up when in Scriptrunner mode, and not in a regular build? Or do they show up there too?

I just tried my own build (staging branch, no Scriptrunner, compiled with dkA r52-2) on a O3DS and I can't reproduce your FIRM loading issues.

**Comment by De1v1d** [comment]
> I thought you meant a PNG image when you said "image". So problems 2 and 3 are the same.
> 
> So these problems only show up when in Scriptrunner mode, and not in a regular build? Or do they show up there too?
> 
> I just tried my own build (staging branch, no Scriptrunner, compiled with dkA r52-2) on a O3DS and I can't reproduce your FIRM loading issues.

I have these issues

1. I cant load a .firm payload cause my 3DS freeze
example
boot V:/GodMode9.firm
boot V:/DECRYPT9WIP.firm
boot V:/ntrboot_flasher.firm
boot V:/OpenFirmInstaller.firm
boot V:/luma.firm

2. I cant inject a .firm payload to the firm0 
example
find 0:/boot9strap.firm B9S
cp -w -n $[B9S] S:/firm0.bin
cp -w -n $[B9S] S:/firm1.bin

**Comment by d0k3** [comment]
Okay, try the latest commit on master. Booting firms from a script should work again.

What do you mean you can't copy stuff to FIRM0 / FIRM1? There should be no trouble doing that. What happens for you?

FIXED_BRIGHTNESS is now a value from 0...255 (instead of the 16 values we had before).

**Comment by d0k3** [comment]
@De1v1d - can you help us testing / giving us more info?

**Comment by Wolfvak** [comment]
Closing due to lack of feedback.
