### ISSUE TITLE
[Feature Request] Allow changing directory attributes like files

### ISSUE THREAD

**Issue by vaguerant** [d0k3/GodMode9#500]
In "show file info" we can mark files as hidden and various other attributes, but "show directory info" is not interactive. Especially with the latest release of @fincs' new-hbmenu, the ability to hide directories from GodMode9 would be extremely nice.

**EDIT:** Also tagging d0k3/CTRXplorer#21 for anybody who happens to find that old issue.

**Comment by d0k3** [comment]
Unsure about that. GM9 does not hide "hidden" entries. There's also other stuff to think about, for example, a user may expect setting a directory to read-only also changes all the files within to read-only, but that's not the case.

**Comment by vaguerant** [comment]
Sorry, to be clear, by "hide directories from GodMode9", I didn't mean I wanted things to be hidden **from** GM9's directory listings, just that I wanted to be able to hide directories **using** GodMode9.

The just-updated new-hbmenu now respects the "hidden" attribute, and that's the primary place users would see the advantage of this feature, since they can hide directories like `/3ds/data` or similar, which some homebrews use to store files.

I see the difficulty with changing a directory's attribute not changing that attribute recursively. Windows's solution to that is to prompt the user asking if they want to change the attribute recursively or just on the directory itself, but I don't know how practical that would be in GodMode9.

**Comment by Wolfvak** [comment]
@vaguerant would you mind testing the latest `staging` commit? It should allow you to set directories to be hidden (and system/archive/read only, like files)

**Comment by vaguerant** [comment]
@Wolfvak I can confirm the latest commit in `staging` is working exactly as expected, I can set and unset the "hidden" attribute and it is read correctly both on and off the 3DS.

**Comment by Wolfvak** [comment]
Great!
Closing this issue
