### ISSUE TITLE
Keyboard bug

### ISSUE THREAD

**Issue by Ammako** [d0k3/GodMode9#501]
oops

1000 word picture

https://gfycat.com/harmfulmarvelousitalianbrownbear

**Comment by Ammako** [comment]
Okay, hourlies site is just broken, and the latest build for GM9 is not actually the latest build. I just saw that this was fixed already. The _actual_ latest commit for SafeMode9 is available, though, except the keyboard just doesn't recognize input, which is arguably worse.

**Comment by d0k3** [comment]
I'll look into the SafeMode9 thing....
