### ISSUE TITLE
Gamecart on godmode9 says empty

### ISSUE THREAD

**Issue by Coledusklycanroc** [d0k3/GodMode9#505]

**Comment by Coledusklycanroc** [comment]
hey i have godmode9 and im trying to dumb pokemon moon through the .trim but whenever i download it it doesnt work my gamecart says empty but when i take it out and put it back in it shows some letters maybe having to do with the game title

**Comment by Coledusklycanroc** [comment]
D0k3 i hope you can help me because ive tried to get your attention because ive seen you try to help other people

**Comment by Wolfvak** [comment]
That's standard behavior when starting up.
It'll only try to read the data from the gamecart when you first open the gamecart drive (or when you insert one).

If GM9 tried to grab data from the gamecart on boot, it'd slow down startup by about 1-2 seconds.

**Comment by Coledusklycanroc** [comment]
heres a link to the video im following to do this just watch like the first 3 mins [https://www.youtube.com/watch?v=k-pnqSsJBv0
](https://www.youtube.com/watch?v=k-pnqSsJBv0)

**Comment by Coledusklycanroc** [comment]
right now im downloadin the .3ds

**Comment by Coledusklycanroc** [comment]
> That's standard behavior when starting up.
> It'll only try to read the data from the gamecart when you first open the gamecart drive (or when you insert one).
> 
> If GM9 tried to grab data from the gamecart on boot, it'd slow down startup by about 1-2 seconds.

**Comment by Wolfvak** [comment]
Please, edit your message for status updates, don't spam like this.
Also, the person in the video you linked is using a _legit_ Pokemon cartridge, not a pirated copy like you're using.
We don't really condone piracy, but we don't support it either. Closing this issue as non-bug.

**Comment by Coledusklycanroc** [comment]
im using a legit cartridge

**Comment by Coledusklycanroc** [comment]
when i bot up gm9 it says gamecart [empty]

**Comment by Wolfvak** [comment]
Just go to the gamecart drive, press A and it'll show up (if there really is a drive)

**Comment by Coledusklycanroc** [comment]
it recognizes the cartridge while its down loading but it wont convert the data to something that i can extract

**Comment by Coledusklycanroc** [comment]
i need it to become a .cxi
