### ISSUE TITLE
when i download a .trim on godmode9 it doesnt come out as a .cxi

### ISSUE THREAD

**Issue by Coledusklycanroc** [d0k3/GodMode9#506]

**Comment by d0k3** [comment]
We obviously need more info. What did you use to trim it? Does it actually still work on hardware? It may be overtrimmed, meaning some minor padding data (we're talking something in the realm of a few byte) is missing at the end.

**Comment by legoj15** [comment]
From what I've gathered from the previous issue they opened, they are opening the [C:] (Gamecart) drive, copying their game.trim.3ds to the SD card (what they refer to as 'downloading'), and are confused because they want a .cxi, not a .trim.3ds

**Comment by d0k3** [comment]
@Coledusklycanroc - is @legoj15 right about this? If so, no, using GM9s trim feature is not the way to get a CXI. You can use the A button menu to extract the CXI.
