### ISSUE TITLE
[Feature Request] preview SMDH icon in scripting

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#507]
GM9 script has the ability view PNG images in the top screen.

- `set PREVIEW_MODE "V:/GodMode9_splash.png"`

In user mode, it is possible to view icons with **Show SMDH title info**.
- `icon`
- `icon.bin`
- `example.smdh`

Would it be possible to add script support for icons?

Like this:
- `set PREVIEW_MODE "0:/gm9/GBAVCSM/cache/F-Zero Max. Velocity (PAAE)/icon"`

![smdh_view_1](https://user-images.githubusercontent.com/35666439/61176378-c6746780-a58d-11e9-9071-7f17a5736136.png)

**Comment by d0k3** [comment]
Okay, I'll think about it, Btw, why are there two descriptions for the <b> button in the bottom screen?

**Comment by TurdPooCharger** [comment]
I used **labelsel** with the `-k` flag. One of the them points to `@SAVE_CHOICE_B_Exit`.

The bottom **< B > cancel** is the script's built-in label.

**Comment by d0k3** [comment]
@TurdPooCharger - this is not forgotten. Will be added soon. Also saw that project of yours, nice!

**Comment by d0k3** [comment]
@TurdPooCharger - can you please test the most recent commit in staging? It works like you would expect, just set the preview mode to any game file of your choosing (yes, all types work).

**Comment by TurdPooCharger** [comment]
@d0k3, is the d0k3.secretalgorithm.com website ever coming back online building the latest hourlies?

After many failures trying to get devkitARM working on my Windows 8.1 laptop even up til now and my backup Linux Mint netbook died months ago, I've decided to extract the SSD from the dead computer and swap it in my main lappy with a fresh install of Linux Manjaro. Since that distro is based off of Linux Arch, that should mean perfect (ha!) compatible with devkitARM. I should have done that earlier to avoid this scenario of being unable to independently build and verify GodMode9. Once my folks goes to sleep for unhindered Internet access (for downloading and updating), my setup should be up and running within the next 12 hours. 

If anyone else is reading this and can build GodMode9, feel free to test the commit by seeing if the smdh icons show up in this [script](https://github.com/TurdPooCharger/GBAVCSM/releases).

**Comment by TurdPooCharger** [comment]
Hitting that `make` command for 3DS homebrews have always been a hit or miss. This went... better than expected!

Either I'm used to Linux B.S. at this point, or Arch-based distros got their shtick better together compared to their Debian counterparts. Going from SSD swap, partition reformat, USB install for Manjaro, pacman install of devkitARM, some struggle with the terminal commands in terms of typical linux permission granting and the needed firmtool dependency, building GodMode9 was a rather pleasant experience.

***
This is exactly what I wanted. @d0k3, thank you so much. :-)

<img width="800" alt="make_GM9_linux" src="https://user-images.githubusercontent.com/35666439/65875180-db72c280-e354-11e9-94cb-6bec52a3e2d3.png">
