### ISSUE TITLE
Dumped 3ds cartridge ROMs aren't running right on Citra

### ISSUE THREAD

**Issue by DomsDomain** [d0k3/GodMode9#513]
![halp!](https://user-images.githubusercontent.com/53106617/61764645-f3075b00-ada7-11e9-9cc0-1222ba246660.png)
Whether or not I use a .3ds or .cia file format, I get this weird _dragging_ effect. For example, This is the intro to TLOZ: Ocarina of Time 3D after a successful dump. If this is not a Godmode9 problem, then I'm sorry for posting this in the wrong spot, and please redirect me.

**Comment by Wolfvak** [comment]
If this _really_ is a "successful" dump, then it's a Citra problem. You can create an issue [here](https://github.com/citra-emu/citra)

**Comment by DomsDomain** [comment]
It was a Citra Canary problem, thanks!
