### ISSUE TITLE
Problems in latest build.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#514]
I used the latest commit (SaltMode) on the hourlies site.
1. If I installed GM9 to boot0, LUMA (or any payload) no longer boots, no matter where I put boot.firm. It always falls back to the GM9 main screen. Also the Model, Serial and Region in system info is shown as "unknown".
2. [The touch inputs are moved outwards every time I boot.](https://i.ibb.co/T15T4cB/IMG-20190725-143746.jpg)

Also, I suggest that you list versions of SaltMode files as well, instead of just linking to the latest version at the bottom of the page.

**Comment by Wolfvak** [comment]
Don't know about problem 1, but have you calibrated the touchscreen in NDS mode? It's required for GM9 calibration. Either way, there should be a way to recalibrate the touchscreen from GM9 itself (and it's planned to store the recalibration data in non-volatile storage to be reloaded on boot)

**Comment by d0k3** [comment]
@pthfdr-42 - can you try with the standard build? I need to know if this is a SaltMode specific problem. As for calibration - duh. I guess we'll include a calibration dialogue then.

**Comment by d0k3** [comment]
@pthfdr-42 - here's an up to date build:
https://f.secretalgorithm.com/FXy42/godmode9-v1.8.0-77-g65c605f5-20190727115541.zip

Can you please try this and tell me if the same issues persist?

**Comment by pthfdr-42** [comment]
[It now moves inward, but at least it is bearable.](https://user-images.githubusercontent.com/42509223/61993307-6fe24f80-b09c-11e9-944f-cb7879682b0e.jpg)
Although, the touchscreen keyboard is not worth it. I still prefer the "name-select" style input as I have suggested some years ago.

**Comment by Wolfvak** [comment]
Okay, the entrypoint detection bug was my bad, it should recognize it's being booted from firm0 just fine.

For the touchscreen stuff, did you re-run the touchscreen calibration setup in 3DS mode?

**Comment by d0k3** [comment]
And, the latest build stores manual calibration data in a file. please test both, @pthfdr-42. Manual calibration is found in HOME menu -> Testing -> Calibrate touchscreen. Also make sure it still works after a reboot.
https://f.secretalgorithm.com/13FKZ4/godmode9-v1.8.0-79-g431d9d8e-20190728233044.zip

As for a button controlled keyboard. Duh. Maybe I'll think about it later. Unlikely though. Do you want a way to go back to the old input tool?

**Comment by pthfdr-42** [comment]
Well, GM9 is mainly controlled by buttons.

**Comment by Wolfvak** [comment]
@pthfdr-42 if you do manual calibration, does it fix the touchscreen issue?

**Comment by pthfdr-42** [comment]
Yes.

**Comment by Kalanyr** [comment]
I just compiled both saltmode and normal mode from the staging branch. System Info is still showing a lot of unknowns. 

Saltmode on staging  does work a passthrough bootloader to Luma but holding down start just shows the splash screen and the word booting... indefinitely rather than loading GodMode9 

So this issue isn't properly fixed.

**Comment by d0k3** [comment]
@Kalanyr - can you show us a screenshot of system info? I hope you also kept in mind you should have that `aeskeydb.bin` file when using GM9 as bootloader.

What other problems are there with normal mode? Does it work as a bootloader for you?

**Comment by Kalanyr** [comment]
Woops. Sorry, I didn't see this because I forgot to subscribe. I'll grab you that stuff in the nexy day or so.

Yes, I have aeskeydb , I've used SaltMode as my bootloader for ages.

**Comment by Ammako** [comment]
This interests me. bf45ee3 is where it breaks, if that helps.

**Comment by Wolfvak** [comment]
I'm going to close down this issue because it's getting a bit out of hand - the missing system info bug will get fixed shortly.

If there are any other bugs (tagging @Ammako and @Kalanyr to get their attention...) please create separate, individual issues for them.
