### ISSUE TITLE
Corrupted/Black Topscreen at most of starts

### ISSUE THREAD

**Issue by Sparrix** [d0k3/GodMode9#515]
I Currently have reinstalled the newest Version of Boo9strap and Luma, before i completely ereased my 3ds.
Now i installed your latest Version 1.8 godmode9 on my new3ds xl via copying the gm9 folder to root and the godmode9.firm to luma payloads.

And very often, if i try to start godmode9, the Topscreen is just black. The buttom screen always works, but the top screen is often just black with background light.
Sometimes i saw a little bit of the menu in the top screen, but the colors and everything else was currupted and slowly disappeard.

Its just fixable by just holding the start button for a restart, and that 2-5 times.

**Comment by Wolfvak** [comment]
Known issue https://github.com/d0k3/GodMode9/issues/466
