### ISSUE TITLE
Cant back up emuNAND

### ISSUE THREAD

**Issue by CommicKick69ing** [d0k3/GodMode9#516]
I cant abck up my EmuNAND because it wont allow me to. Can anyone help?

**Comment by TurdPooCharger** [comment]
For the GodMode9 dev team, see ongoing development:
- [[Help] Emunand wont back up](https://gbatemp.net/threads/help-emunand-wont-back-up.544350/)
- [Fastboot not working](https://gbatemp.net/threads/fastboot-not-working.544363/)

**Comment by d0k3** [comment]
@CommicKick69ing - try backing it up manually. We need to know if this is a problem with the script. Check the E: drive for the `nand.bin` file there. That's your EmuNAND. Copy it somewhere.

**Comment by d0k3** [comment]
Okay, I tried to reproduce this issue, with no success.

@CommicKick69ing - try this build (based on the latest staging branch):
https://f.secretalgorithm.com/FXy42/godmode9-v1.8.0-77-g65c605f5-20190727115541.zip

This sounds a lot like there is an issue with either your SD card, or your SD card slot. Check the `E:` drive for `nand.bin`, but also try a different SD card.

**Comment by Wolfvak** [comment]
There hasn't been any updates from OP in over a week so this issue will be closed.

Feel free to reopen it if you still suffer from the bug, and please try to provide a reproducible test case (or a picture/video footage of the steps performed to trigger it).
