### ISSUE TITLE
What is SALTMODE9?

### ISSUE THREAD

**Issue by daemonspudguy** [d0k3/GodMode9#518]
It's never mentioned in the documentation what SALTMODE9 is. What is it?

**Comment by Wolfvak** [comment]
It merely changes a couple of keycombos and some very minor details.
Default builds are recommended, and that's why there's no mention as to what it does exactly.
https://github.com/d0k3/GodMode9/blob/e87f69dc200d88231f00677646f81bb5c8bbe8f1/arm9/source/godmode.c#L40
