### ISSUE TITLE
All GodMode9 releases are stuck on the booting screen

### ISSUE THREAD

**Issue by stampylongr** [d0k3/GodMode9#520]
Hello,
So I have a friend who wanted CFW on his O3DS, and I installed the latest version of boot9strap and Luma3DS. Problem is, whenever I try to boot GM9 (On ANY release), it is stuck on [this](http://imgur.com/a/blla73x) screen (Yes that is v1.7.1, it is the same on the latest release).

Now I'm not sure if this is a Luma3DS bug or a GM9 bug, but either way it won't boot.

**Comment by TurdPooCharger** [comment]
1. Try the [battery trick](https://gbatemp.net/threads/o3ds-b9s-luma-black-home-screen-on-boot-after-sleep-mode-no-sound.526372/#post-8432609).
2. Despite using GodMode9 v1.7.1, see if adding another FIRM at **sdmc:/luma/payloads** helps.
3. Download [Luma3DS v9.1](https://github.com/AuroraWright/Luma3DS/releases/tag/v9.1) and replace that as **sdmc:/**`boot.firm`
4. If the above two does not work, rename `GodMode9.firm` and place that as **sdmc:/**`boot.firm`

**Comment by stampylongr** [comment]
1. Unfortunately, I cannot perform this, because I haven't installed GM9 and Luma3DS to the CTRNAND, as that is what I'm trying to use GM9 for.
2. I added the ntrboot_flasher FIRM, and that did nothing.
3. Tried, and again, it did nothing.
4. Again, nothing.

I do want to point out that the TWLNAND is not working. Could this be the source of the problem?

**Comment by stampylongr** [comment]
Closing this, as when I installed fastboot3DS, it was fixed.

**Comment by loki2199** [comment]
I have the exact same problem. Tried all the above mentioned tipps but still doesnt work. Even when i load it with Fastboot3Ds it still stucks in the first screen.

**Comment by stampylongr** [comment]
@loki2199 I would suggest checking the integrity of your CTRNAND, as well as your TWLNAND. Also, please do not try to revive dead threads. As you can see, this thread is more than a year old. Several new versions of the tool have been released, as well as new troubleshooting steps. I would suggest opening a new thread and/or checking <https://3ds.hacks.guide/troubleshooting> for more information.
