### ISSUE TITLE
[Feature request] Cache the "Search for titles" search result when switching panes

### ISSUE THREAD

**Issue by zacchi4k** [d0k3/GodMode9#521]
If an user does a title search with R+A, switches pane, and then goes back, the whole search process will restart from beginning. Caching the result of the search for titles when switching panes would make things a bit faster.

**Comment by d0k3** [comment]
The problem here is, when you go back, search results may have changed (due to manipulation in another pane, not unlikely). Unsure about this. I know search is not always fast.

**Comment by zacchi4k** [comment]
I don't know if this solution is too complicated, but would it be possible to have a flag that gets set when a title gets edited in a meaningful way so the search function can tell if it needs to perform the whole process again?
Correct me if I'm wrong, ll this would have to worry about is titles changing the ID or the name, or titles being added/removed, because that's all gets shown in the results.

**Comment by Wolfvak** [comment]
Other operations would also invalidate this cache - like reinserting the SD card or gamecart.
Sounds difficult to cover every possible case that could come up.

**Comment by d0k3** [comment]
Okay, I thought this true, and I'm still unsure wether this is possible in a way that makes sense. @zacchi4k - well, normally you wouldn't do anything that requires that much reloading after a title search, or would you? Can you give us a scenario where you are massively slowed down by the reloading?

What we could do is, cache everything, reload only when the user asks for it (R+down). That would be bad in many scenarios, though.

**Comment by TurdPooCharger** [comment]
Is it possible to make a `.cache` file that when launched, it acts like a virtual list or instantly populated **Search for titles** from previous a result. It does not necessarily have to match what's in the actual **[A:] SYSNAND SD**.

When you select a `.tmd` from old result, have GodMode9 checks if that title is in the (real) **[A:] SYSNAND SD**. Either ask the user to update the cache if it is not or do nothing.

I'm not sure if that cache can or should be mounted as it's own virtual drive.

**Comment by d0k3** [comment]
Okay, I decided against this. While I understand that it would be nice to have stuff a little speedier, it's really hard to keep track of all changes that could affect search results. If you want to do stuff in batch there, mark multiple files, do your operations then.

@TurdPooCharger - while I don't think that idea is bad, I think it would be confusing for users.
