### ISSUE TITLE
H&S Injection failed [V1.8.0] |[BUG]

### ISSUE THREAD

**Issue by 0n1cOn3** [d0k3/GodMode9#525]
GODMODE9 ALL-IN-ONE MEGASCRIPT
by annson24

FBI to H&S  Options
Inject FBI to H&S

>0:/gm9/scripts/GM9Megascript.gm9
>line: 558: mount fail
>imgmount "$[FBISRC]"

**Comment by Wolfvak** [comment]
Did it find the FBI.cia file on its own or did you select it yourself?

**Comment by 0n1cOn3** [comment]
I had to choose the FBI.cia manually.

**Comment by TurdPooCharger** [comment]
Line 558: `imgmount "$[FBISRC]"`

The `fbi.cia` you selected is not image mountable. 

To manually check if it is, press (A) → **CIA image options...** → **Mount image to drive**.

**Comment by d0k3** [comment]
@0n1cOn3 - please do what @TurdPooCharger said. I think that sounds a lot like your fbi.cia is corrupted in some way.

**Comment by d0k3** [comment]
Okay, that bug is not reproducable for me. @0n1cOn3 - check for SD card corruption, make sure your fbi.cia is 100% correct, and maybe get the `aeskeydb.bin` file (yes, the one mentioned in the readme). We need more info from you, otherwise we will have to close this issue.

**Comment by 0n1cOn3** [comment]
It seems to be a dying SD Card. Have issues sometimes to mount the drive. 
I have also replaced the files again. After that step, the problem has being gone.
    	
    	

    	Freundliche Grüsse
Stefan Kuny
    
  




On Sun, Aug 25, 2019 at 9:42 PM +0200, "d0k3" <notifications@github.com> wrote:












Okay, that bug is not reproducable for me. @0n1cOn3 - check for SD card corruption, make sure your fbi.cia is 100% correct, and maybe get the aeskeydb.bin file (yes, the one mentioned in the readme). We need more info from you, otherwise we will have to close this issue.

**Comment by d0k3** [comment]
@0n1cOn3 - thanks! And be careful not to add your full name at the bottom of your comments. We know that's how you finish german letters, but  that doesn't belong here :^).

**Comment by 0n1cOn3** [comment]
Oops... iv replied over e-mail. ._.
