### ISSUE TITLE
Holding down start button while pressing power button won't power on the system

### ISSUE THREAD

**Issue by Pheenic** [d0k3/GodMode9#527]
i'm currently setting up hacking for my 3ds and when on the step to have this setup my N3DS won't stay powered on if i have the Start Button pressed down before or shortly after I power it on. did i do something wrong or is it my N3DS?

**Comment by Validusername16** [comment]
You may want to read through #466 , as you seem to have the same issues and there are at least two  solutions in the comments.
(also iirc this means you have dual IPS screens so you're cool or something)

**Comment by Wolfvak** [comment]
what @validusername16 just said

**Comment by Pheenic** [comment]
it worked thank you!
