### ISSUE TITLE
[Bug?] Only 1024 files are shown when file count >= 1025

### ISSUE THREAD

**Issue by ParzivalWolfram** [d0k3/GodMode9#528]
If a folder has over 1024 files in it, only the first 1024 are shown. Folder info (from R+A) does list the right number of files, and the correct total size, but going into the folder and selecting all shows that only 1024 files are visible. Any attempt to scroll farther does nothing.

I have several No-Intro sets on my 3DS, and it's fairly annoying to only be able to see all of them in RetroArch or on a PC. RetroArch saves a few things next to the ROM, so if I need to copy or delete said file, I have to remove the SD card and use some other machine, which is quickly ruining my SD slot. I'd love to see this fixed, assuming it is, indeed, a bug...

**Comment by Wolfvak** [comment]
for reference, this is known and discussed in https://github.com/d0k3/GodMode9/issues/57 and https://github.com/d0k3/GodMode9/issues/360

**Comment by ParzivalWolfram** [comment]
@Wolfvak didn't see them, whoops...

**Comment by ParzivalWolfram** [comment]
So it seems this has been a very firm no, so I guess i'll just deal with it, then...

**Comment by Wolfvak** [comment]
If you have a good reason to increase the value then it can be discussed, but it's not a long term solution since the memory usage grows linearly and some games would need limits of ~20k items per directory.
