### ISSUE TITLE
action menu dont show up/back screen stay black

### ISSUE THREAD

**Issue by Lanoixdecoco** [d0k3/GodMode9#531]
hello, I searched for a few hours, but I couldn't find a solution so here I am.

When I start gm9 the back screen stay black, and I can't use the action menu at all.
When I press the action menu button (home), bm9 freeze, until I press b.
I think bm9 don't show the menu, but its open behind.
I saw some pics of the others gm9 and their back screen they have a menu.
![IMG_20190906_214232](https://user-images.githubusercontent.com/55001492/64456440-7e3a7700-d0f0-11e9-99bd-7542c40f0d5f.jpg)
![IMG_20190906_214215](https://user-images.githubusercontent.com/55001492/64456477-9611fb00-d0f0-11e9-9a72-b562b049e3ef.jpg)
(Sorry for my English I'm not a native English)

**Comment by Validusername16** [comment]
You may want to read through #466  , as you seem to have basically the same issue and there are at least two solutions in the comments.
(also iirc this means you have a bottom IPS screen so you're cool or something)
