### ISSUE TITLE
How to make fonts?

### ISSUE THREAD

**Issue by Witherking25** [d0k3/GodMode9#536]
I want to make my own font for gm9. How would I go about doing that?

**Comment by Wolfvak** [comment]
You have to create a PBM sheet containing every single character between 0x20 to 0x60, in a 16x16 arrangement (16 characters per line, 16 characters per row), for a total of 64 printable characters.

The width and height of each character will be calculated at runtime but there's a hard limit of 8 pixels wide and 10 pixels tall.

If you don't have a tool that's professional/old enough to edit the PBM file you can just use ffmpeg to convert it.

Finally, if you have any non-issue questions like this one please contact us directly on freenode IRC (#GodMode9 channel) or the Discord server, you can get a link to it at the bottom of the readme.
