### ISSUE TITLE
"Search for data" not display properly

### ISSUE THREAD

**Issue by HIDE810** [d0k3/GodMode9#537]
I'm in the latest SaltMode9.
![A28293D1-3F53-42B5-804C-2B08B73A6C41](https://user-images.githubusercontent.com/48782538/65164199-64e1e500-da77-11e9-8239-bc9d2ea6f28f.png)

**Comment by aspargas2** [comment]
Am I correct in saying that this only happens if you do a search for data beforehand?

**Comment by HIDE810** [comment]
This happens without even doing that.

**Comment by d0k3** [comment]
I'll look into it.

**Comment by Wolfvak** [comment]
@HIDE810 could you please give more information? Which build does this happen on, does it happen in the latest one, how to reproduce this behavior...?

Personally I can't reproduce it in the latest staging build, regular GodMode9 (although SafeMode doesn't affect this behavior in the slightest...). On the first "search for data", the keyboard always shows the hex string "00".

Are you sure this is a bug? Because if you do a search for a string, and then search for data it'll keep the previously searched string in the buffer and allow you to change it.

**Comment by HIDE810** [comment]
@Wolfvak OK.Please check this.
https://youtu.be/sWuCqgbWqbQ
It doesn't matter which file you choose. This happens randomly.

I use the latest SaltMode9.
https://d0k3.secretalgorithm.com/SaltMode9/latest.zip

I tested on
- New3DS(Luma10.0.1, 11.10.0-43J, via fastboot3ds)
- Old3DS(Luma9.1, 11.10.0-43J, via boot9strap)

The results will be the same regardless.

**Comment by Wolfvak** [comment]
Wow, that video is extremely helpful. Thanks!
Will look into it, too.

**Comment by Wolfvak** [comment]
Ok, small update: I found where the first bug happens and managed to fix it (use [this](https://github.com/d0k3/GodMode9/files/3665888/GM9-searchdata-fix.zip) and try it yourself - it's a regular GM9 build but good enough for verification ).

However, the second bug still happens and I think it'll be better to simply rewrite bits of how the hex viewer & search are handled.
That might take a while, but I'll keep this issue open until a proper fix is commited, although you can consider it solved for the next release.

**Comment by HIDE810** [comment]
@Wolfvak I tried some files on it. It works fine!

And one question:
What is `found_size`? It's displayed when I select "search for data".

> That might take a while, but I'll keep this issue open until a proper fix is commited, although you can consider it solved for the next release.

I'm looking forward to the fix.

**Comment by Wolfvak** [comment]
Um... oops. found_size is a variable related to the search function, and I added a tactical printf to make sure it was the expected value. It won't be there in the final fix.

**Comment by HIDE810** [comment]
Oh, I see. Thank you for your work.

**Comment by Wolfvak** [comment]
Ok, fixed. If any other errors pop up, make sure to upload a video like this one, it helps out a ton!
