### ISSUE TITLE
try to build enctitlekeys.bin fail

### ISSUE THREAD

**Issue by srwgin** [d0k3/GodMode9#54]
Press the HOME button, select More... -> Build support files
do I need mount some files first?

**Comment by d0k3** [comment]
Try the most recent nightly from here:
http://d0k3.secretalgorithm.com/

Does that fix your problem?

**Comment by srwgin** [comment]
failed too
do I need any files in files9 folder

**Comment by d0k3** [comment]
No, you don't need any other files to build this.

Is anything in your console special?

What is the exact output you get in GodMode9 when it fails? The output should be more detailed than just a failed message. What files do you have in 0:/gm9out after it finishes?

Is it maybe possible that just the building of secret_sector.bin fails? That would be perfectly okay.

Can you try the A button on 4:/dbs/ticket.db, then "ticket.db options..." -> "Build encTitlekeys.bin"? What is the output?

**Comment by srwgin** [comment]
my bad
I do not create gm9out folder
now it is ok
thank you

**Comment by d0k3** [comment]
Note: I tried it myself, works. Thus closed.
