### ISSUE TITLE
GM9 crashes when mounting an encrypted new3DS NATIVE_FIRM

### ISSUE THREAD

**Issue by Wolfvak** [d0k3/GodMode9#541]
Steps to reproduce: on an old3DS, mount any file, then try to mount an encrypted new3DS NATIVE_FIRM. Not sure if it also happens on new3DS models.

Happens on the latest staging commit as of today (d0c1597e)

Link to the generated exception dump: https://gist.github.com/Wolfvak/69ee432847806b33e4c353383f1ecea8

arm9.elf:
[arm9.zip](https://github.com/d0k3/GodMode9/files/3678303/arm9.zip)

Creating this issue to keep track of it and make sure it gets fixed, originally reported by @validusername16

**Comment by Wolfvak** [comment]
Update: turns out you don't need to mount any other data before, just mounting a new3DS native firm crashes the system when switching to the FIRM drive

It happens due to a NULL deref on `DecryptFirm`, after the function to find the ARM9 section returns NULL.

**Comment by HIDE810** [comment]
I can reproduce it on new3DS but not on old3DS. I think it doesn't matter whether old3DS or new3DS.

I used
https://f.secretalgorithm.com/NXaEH/godmode9-v1.8.0-101-g0796cdfd-20190930221617.zip
