### ISSUE TITLE
Script discrepancy when using `fixcmac` command.

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#543]
Not sure if this is a bug in gm9 scripting.

***
**Example 1**: `fixcmac "1:/"`

This seems to go through every file inside CTRNAND. It works as expected. 

(Example 1 is GOOD.)

***
**Example 2**: `fixcmac "A:/"`

When done on the SD card, this one finishes instantly. 

(Example 2 is the one that's questionable.)

***

For run time comparison to the script counterparts, fixing a drive's CMACs in user mode:

1. Hold (R)-shoulder and press (A) on either **[1:] SYSNAND CTRNAND** or **[A:] SYSNAND SD**.
2. **Fix CMACs for drive**.

***

Edit - Found out that the forward slash `/` char might be a root cause.

- `fixcmac "1:"` seems to give the same result as `fixcmac "1:/"`.
- `fixcmac "A:"` does run.

**Comment by d0k3** [comment]
Okay, I'll need a little bit more help on that one. My SD card just broke and I'm waiting for a replacement, so my hands are bound.

Can you clarify this a little bit? `fixcmac "A:/"` does not work, while `fixcmac "A:"` or doing it manually, via the GM9 interface gives the expected result? Is that correct?

And, while `fixcmac "A:/"` does not work, `fixcmac "1:/"` does?

If I got that right, that bug was in there from the beginning.

**Comment by TurdPooCharger** [comment]
> Can you clarify this a little bit? fixcmac "A:/" does not work, while fixcmac "A:" or doing it manually, via the GM9 interface gives the expected result? Is that correct?

That is correct.
- `fixcmac "A:/"` does not work.
- `fixcmac "A:"` works.
- **Fix CMACs for drive** on **[A:] SYSNAND SD** works.
***
> And, while fixcmac "A:/" does not work, fixcmac "1:/" does?

Also correct.
- `fixcmac "1:/"` works. This requires Lvl1 write permission.
- `fixcmac "1:"` also works. This requires Lvl2 write permission.
- **Fix CMACs for drive** on **[1:] SYSNAND CTRNAND** works.

***
Other observation,

When using `fixcmac "1:/"`, the bottom screen output looks like this:

- `1://dbs/ticket.db`
- `1://data/<ID0>/extdata/00048000/f0000001`

**Comment by d0k3** [comment]
Okay, here's a testbuild with a small fix (yet uncommited). Can you try?
https://f.secretalgorithm.com/DiK7N/godmode9-v1.8.0-111-g2372340e-20191009211914.zip

Also, thanks! Your bug reports are always very helpful. Some other people could learn from that example :^).

**Comment by d0k3** [comment]
Okay, ignore the earlier test build. I failed to notice you also found a way to circumvent the write permission system. Try this one:
https://f.secretalgorithm.com/k2stl/godmode9-v1.8.0-111-g2372340e-20191010200713.zip

**Comment by TurdPooCharger** [comment]
## Test setup.
- Test system is old 2DS with EmuNAND on SD card.
- Both its SysNAND and EmuNAND are using the same (but separate copies) `movable.sed` sourced from the o2DS.
- Manual (partial) CTRTransfer the n3DSXL's **extdata** and **sysdata** to the o2DS.
- Manual SDTransfer the n3DSXL's **dbs**, **extdata**, and **title** to the o2DS.
- These are the freshly installed SD `*.cia` titles with quick game saves for SDTransfer.
      - _The Legend of Zelda - Link's Awakening DX_ (GBC VC)
      - _The Legend of Zelda - The Minnish Cap_ (GBA VC)
      - _Link-a-Pix Color Update v1.01_
      - _Yo-kai Watch 3 DLC (USA)_
      - _FBI v2.6.0_
- The script below was used to run different test cases.
- CMACs of individual files are checked with **Calculate CMAC** after running each case.
- After running a test case and checking their CMACs, the NAND and SD **extdata**, **sysdata**, **dbs**, **extdata**, and **title** folders are deleted from the **[#:] ???NAND CTRNAND** and **[X:] ???NAND SD** drives. Backed up (not fixed) copies are added back in for the next test case.

***

**fixcmac_testing.gm9**
```
@MENU
labelsel -o -s "Choose your fixmac." CHOICE_*
goto MENU

@CHOICE_SysNAND_(no_/)
fixcmac "1:"
fixcmac "A:"
goto CHOICE_EXIT

@CHOICE_SysNAND_(with_/)
fixcmac "1:/"
fixcmac "A:/"
goto CHOICE_EXIT

@CHOICE_EmuNAND_(no_/)
fixcmac "4:"
fixcmac "B:"
goto CHOICE_EXIT

@CHOICE_EmuNAND_(with_/)
fixcmac "4:/"
fixcmac "B:/"
goto CHOICE_EXIT

@CHOICE_EXIT
```

***
## GodMode9 v1.8.0-111-g2372340e-20191010200713 (Results)

**SysNAND**

`fixcmac "1:"` - passed
`fixcmac "A:"` - passed

`fixcmac "1:/"` - FAILED
`fixcmac "A:/"` - FAILED

**EmuNAND**

`fixcmac "4:"` - passed
`fixcmac "B:"` - passed

`fixcmac "4:/"` - FAILED
`fixcmac "B:/"` - FAILED

**Comment by d0k3** [comment]
Wait, what? You actually say it got worse? And now fixcmac "1:/" doesn't work anymore either? How did it fail?

**Comment by d0k3** [comment]
Okay, that was harder than I expected it to be. This one should finally solve all the problems:
https://f.secretalgorithm.com/31vjZ/godmode9-v1.8.0-113-gbeb2a881-20191011161359.zip

**Comment by TurdPooCharger** [comment]
@d0k3, due to inconsistency in the first round of testings done on v1.8.0-111-g2372340e, I wasn't able to pinpoint what went wrong.

On my o2DS for the **[1:] SYSNAND CTRNAND**, the injected files within the **extdata** and **sysdata** folders didn't have their CMACs fixed. When I ran the test case on v1.8.0 stable release, it too also didn't fix them.

On my n3DSXL, I took the **dbs** folder from the `11.5.0-38U_ctrtransfer_n3ds.bin` [image](https://3ds.hacks.guide/ctrtransfer.html) and put that in sysnand. The `fixcmac "1:/"` did fix the `*.db` files' cmacs.

***

On the next round of testing for **v1.8.0-113-gbeb2a881**, I will include my n3DSXL alongside the o2DS. For the CTRNAND, I will also include the `*.dbs` files, and hex edit the `movable.sed` at offset 0x12F (change the **00** → **FF** to trigger failed cmac check).

**Comment by TurdPooCharger** [comment]
Late reply.

I had to write additional codes to the **fixcmac_testing.gm9** script that automated deleting the NAND and SD card files and folders and then injecting a fresh set of them unfixed. Manually deleting and adding them back was tedious, and I caught myself messing up early on. I made sure to check their CMACs before and after when running each test case. 

**Adjustments to the testing.**
- For the o2DS and n3DSXL, the **dbs** folders from 3ds.hacks.guide's ctrtransfer (USA) images were borrowed from their old/new series.
- Their `movable.sed` files were hex edited at single point at offset 0x12F. 

***

Re-emphasizing the items that were tested.

CTRNAND
- **data/ID0/extdata**
- **data/ID0/sysdata**
- **dbs**
- **private/**`movable.sed`

SDMC (decrypted form of **Nintendo 3DS/ID0/ID1** folder)
- **dbs**
- **extdata**
- **title**

***

## v1.8.0-113-gbeb2a881 (Results)

**old 2DS**

`fixcmac "1:"` - passed
`fixcmac "A:"` - passed

`fixcmac "1:/"` - passed
`fixcmac "A:/"` - passed

`fixcmac "4:"` - passed
`fixcmac "B:"` - passed

`fixcmac "4:/"` - passed
`fixcmac "B:/"` - passed

:+1: 

***

**New 3DS XL**

`fixcmac "1:"` - passed
`fixcmac "A:"` - passed

`fixcmac "1:/"` - passed
`fixcmac "A:/"` - passed

`fixcmac "4:"` - passed
`fixcmac "B:"` - passed

`fixcmac "4:/"` - passed
`fixcmac "B:/"` - passed

:+1: 

Everything checks out. :-) 

***

For giggles, I also tested these additional cases on the o2DS. They do not fit the scope of the original issue, so should not be considered 

```
@CHOICE_SysNAND_(no_:)
fixcmac "1" - 
fixcmac "A"
goto CHOICE_EXIT

@CHOICE_SysNAND_(with_two_/)
fixcmac "1://"
fixcmac "A://" 
goto CHOICE_EXIT

@CHOICE_SysNAND_(with_three_/)
fixcmac "1:///"
fixcmac "A:///"
goto CHOICE_EXIT
```

`fixcmac "1"` - nope
`fixcmac "A"` - nope
**Result:** Didn't work but then again, this is considered bad syntax or lazy programming.

`fixcmac "1://"` - works
`fixcmac "A://"` - works
**Result:** This style is most common on web browsers. Double forward slashes is a yes!

 `fixcmac "1:///"` - works
`fixcmac "A:///"` - works
**Result:** lol.. @d0k3, you mad lad.

**Comment by d0k3** [comment]
@TurdPooCharger - thanks a lot!
