### ISSUE TITLE
"Show title info" on no-icon files doesn't show the prompt automatically 

### ISSUE THREAD

**Issue by GlaZedBelmont** [d0k3/GodMode9#549]
The best way to reproduce this issue is just to do "Show title info" on something like an .app of a system title (not limited to system titles) that would show "Title info: not found" (discovered that bug with agb_firm which is at 1:/title/00040138/00000202/), it instead requires you to press A or B to show that "not found" prompt instead of showing it automatically

Old 2ds, b9s, using latest release which is 1.9.0

**Comment by Wolfvak** [comment]
Can reproduce, will look into a fix.

**Comment by Wolfvak** [comment]
@GlaZedBelmont can you try a build made from the latest commit in the `staging` branch and see if it fixes the issue? It works in my system, with the testcase you provided.

**Comment by d0k3** [comment]
@GlaZedBelmont - here's a test build if you need one:
https://f.secretalgorithm.com/ZtTEy/godmode9.firm

**Comment by GlaZedBelmont** [comment]
Yep, issue doesnt occur anymore 👍🏻
