### ISSUE TITLE
Feature Request - Add the the current rate (MBps) to the progress bar screen for long-running operations.

### ISSUE THREAD

**Issue by Poryhack** [d0k3/GodMode9#55]
Low-priority, but it'd be nice to see how well a given NAND/gamecard/SD card is performing.

**Comment by d0k3** [comment]
I thought about this, and, while it would be definitely nice-to-have, the source changes required for this (in essence, turning a universal prorgess bar function into a much more specific one) don't justify the added value this may have. Closing this...
