### ISSUE TITLE
Notification LED blinking while no operation is happening and the lid is closed

### ISSUE THREAD

**Issue by androidian5980** [d0k3/GodMode9#551]
The LED is constantly blinking green when GodMode9 is at the main screen and not doing any file operations while the lid is closed.

I am using a 2DS XL 11.10, Luma3DS, B9S, 64GB SanDisk MicroSD card and using latest release (1.9.0).

**Comment by aspargas2** [comment]
The blinking when an operation is done works by blinking whenever input is expected, which is always the case on the main menu. As far as I know, this is intended behavior.

**Comment by Wolfvak** [comment]
I've been able to reproduce it, will fix ASAP.

@aspargas2 no, it's only supposed to happen after any operation is done AND the lid is closed, in order to notify the user that the operation is done. We had this working at one point, not sure why it's broken now but I'll look into it.

**Comment by aspargas2** [comment]
Oh lol, it's always done the behavior described in the original post for me throughout a few different nightlies so I just assumed that was intended.

**Comment by d0k3** [comment]
Okay, can you try this test build?
https://f.secretalgorithm.com/ZtTEy/godmode9.firm

**Comment by androidian5980** [comment]
> Okay, can you try this test build?
> https://f.secretalgorithm.com/ZtTEy/godmode9.firm

The issue is no longer happening with the version linked.
