### ISSUE TITLE
[BUG] Last Search Drive is not displayed

### ISSUE THREAD

**Issue by HIDE810** [d0k3/GodMode9#554]
After a search operation, `Z: LAST SEARCH` is not displayed. On v1.8.0, this doesn't happen.

tested:
- new3ds, Emu11.10.0-43J, godmode9 v1.9.0 via fastboot3ds
- old3ds, Sys11.10.0-43J, godmode9v1.9.0 via b9s+luma chainloader

[short video](https://youtu.be/RCuq5hc6nac)

**Comment by d0k3** [comment]
Good catch! Fixed in latest staging, here's a test build if you want to try:
https://f.secretalgorithm.com/b244q/godmode9.firm

@aspargas2 - you forgot about that one. Granted, it was easy to miss.
