### ISSUE TITLE
[BUG] Fastboot3ds-chainloaded GM9 Crash

### ISSUE THREAD

**Issue by daemonspudguy** [d0k3/GodMode9#564]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?). 
I chainloaded GM9 from fastboot3ds
* Give us clear steps to reproduce 
1. Chainload into GM9 from fastboot3ds
* Give us info about your system (where did it happen?).
Exception: Data Abort (4)
GodMode9 v1.9.0
2019-11-04 08:59:15
 
R00: 027FD660 | R01: 08061EF4
R02: 00000019 | R03: 08061F04
R04: 6E696552 | R05: 08061F14
R06: 00000019 | R07: 227FD350
R08: 0806A068 | R09: 0806A068
R10: 227FD364 | R11: 00000019
R12: 0000000 |
**Info about your system**
Include this info to make our work easier:
N3ds
* Anything special about your console? (defects, custom modifications,...)
* Bootloader fastboot3ds
* Did you chainload GodMode9 via Luma?
No

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[X] I have read the information above

**Comment by Wolfvak** [comment]
That exception dump looks cut off, could you post the file that got dumped? It should be in `sd:/gm9/out`

**Comment by daemonspudguy** [comment]
That's what I got from the QR code

**Comment by Wolfvak** [comment]
Okay, but the version in-disk should be more complete, please upload that one.

**Comment by daemonspudguy** [comment]
0001 Exception: Data Abort (4)
0002 GodMode9 v1.9.0
0003 2019-11-04 09:55:13
9004
0005 R00: 027FD660 R01: 08061EF4
0006 R02: 00000019 R03: 08061F04
2007 R04: 6E696552 R05: 08061F14
0008 R06: 00000019 R07: 227FD350
0009 R08: 0806A068 09: 0806A068
0010 R10: 227FD364 R11: 00000019
0811 R12: 00000000 R13: 227FFFB8
0012 R14: 0804A508 R15: 0804A508
0013 CPSR: 600000D7

0015 Code:
00160804 A4F0: E2815020 E0855003 E1A0C22C E2813010
00170804 A500: E280E010 E5134010 E50E4010 E513400C

**Comment by knight-ryu12** [comment]
have you tried checking your SD?

**Comment by daemonspudguy** [comment]
It works!
