### ISSUE TITLE
SaltMode9 on d0k's site is not up to date (and also broken)

### ISSUE THREAD

**Issue by Kalanyr** [d0k3/GodMode9#565]
**Info about your system**
Not relevant

**Have you actually read this?**
[X] I have read the information above

The SaltMode build on https://d0k3.secretalgorithm.com/ is significantly out of date and broken (it's still the borked one from September).

**Comment by RShadowhand** [comment]
Solved.

**Comment by Kalanyr** [comment]
It's still the borked version for me but this may be a caching/routing issue.

**Comment by RShadowhand** [comment]
I've made sure it's 1.9.0 version, latest commit. What's broken?

**Comment by Kalanyr** [comment]
I just tried the https://d0k3.secretalgorithm.com/SaltMode9/latest.zip link again and for me at least, it's still a version 1.8.0 build  (same zip size , internal files are dated 9/9 and  the CRCs match)

**Comment by RShadowhand** [comment]
I think you may have some form of cached results. 

```
1.9M Sep  9 10:20 GodMode9-v1.8.0-72-g3c8fe0f6-20190909101900.zip
1.8M Nov  7 08:32 GodMode9-v1.9.0-9-g499e301b-20191107083105.zip
1.8M Nov  7 08:32 latest.zip
```

Here are the md5sum of the files
```
47e0c64661baf051ea995e79f5c8318a  GodMode9-v1.8.0-72-g3c8fe0f6-20190909101900.zip
d2815bf45fa5d63cd907ec8b2e836791  GodMode9-v1.9.0-9-g499e301b-20191107083105.zip
d2815bf45fa5d63cd907ec8b2e836791  latest.zip
```

**Comment by Kalanyr** [comment]
I'm definitely getting this one: 
47e0c64661baf051ea995e79f5c8318a  GodMode9-v1.8.0-72-g3c8fe0f6-20190909101900.zip


So might be getting cached somewhere. I'll give it a couple of days and check again and report back.

**Comment by Kalanyr** [comment]
Yep, was a caching issue, it's come through now. 

Thank you.
