### ISSUE TITLE
DSi areas missing from TWL ROM dumps on GM9 v1.9.0

### ISSUE THREAD

**Issue by RocketRobz** [d0k3/GodMode9#567]
At the NDS(i)Brew Scene server on Discord, a user named ubergeek77 reported that TWiLight Menu++ says that the DSi binaries are missing, on his Pokemon Black dump by said GM9 version.

I've heard before that it wasn't making proper TWL ROM dumps, but this recent report seems to confirm this.

**Comment by d0k3** [comment]
Okay, thanks!  I will need help here...

@ubergeek77 (hoping he's also on here) needs to test dumping the same cart on GodMode9 v1.8.0. Also, compare the dumps' CRC with a known good one from [NoIntro](https://datomatic.no-intro.org/). What we really need, long term, is a git bisect, to identify the commit that caused this.

Everyone, we will also need someone else to check dumping this cart (or other DSi enhanced ones) on v1.9.0 and, if required, on v1.8.0, too.

@dratini0 - is it possible you're recent changes could have caused this? Cart handling is a fickle thing, just inserting some delays here and there can already cause stuff to not work.

**Comment by RocketRobz** [comment]
Good news!

```
I can't find my copy of Black right now but I tried it with White
On GM9 1.8.0 specifically, TWiLight Menu actually attempts to boot in DSi Mode
```

So, it means that GM9 v1.8.0 has properly dumped the ROM with the DSi areas.

**Comment by RocketRobz** [comment]
Ok, so before, he didn't dump it with the latest version. He has now tried v1.9.0, and the dump is still fine, like with v1.8.0.

Sorry for the inconvenience.

**Comment by d0k3** [comment]
No worries. Better one bug report too much than missing out on something critical. Thanks!
