### ISSUE TITLE
[BUG] Script Runner crash when using applybps

### ISSUE THREAD

**Issue by wabberz** [d0k3/GodMode9#568]
Script Runner crashes on using the `applybps` command, which worked just fine in previous versions.

Here is the crash dump:
```
Exception: Data Abort (4)
ScarletStudy v1.9.0-9-g499e301b
2019-11-13 19:52:21
 
R00: 20163058 | R01: 2029F468
R02: 00100000 | R03: 00000000
R04: 08057A9C | R05: 20163058
R06: 00000004 | R07: 0805B2AC
R08: 2029F468 | R09: 00000000
R10: 00100000 | R11: 20163058
R12: 0000021C | R13: 227EC0F8
R14: 0802D3C4 | R15: 080366AC
CPSR: 600000DF

Stack:
227EC0F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
227EC100: 00 00 00 00 00 00 00 00 00 00 00 00 9C 7A 05 08 
227EC110: 58 30 16 20 04 00 00 00 AC B2 05 08 68 F4 29 20 
227EC120: 00 00 00 00 00 00 10 00 58 30 16 20 C4 D3 02 08 
227EC130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
227EC140: 00 00 00 00 00 00 00 00 68 F7 7E 22 00 00 00 00 
227EC150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
227EC160: 00 00 00 00 00 00 00 00 68 F4 29 20 A4 A5 03 08 

Code:
08036690: 000001FF 000001FE E92D4FF0 E1A09003 
080366A0: E3A03000 E24DD014 E1A08001 E5893000
```
System is an N3DS using fastboot3ds, chainloaded via Luma3DS.
I already talked with d0k3 about this via Discord and I provided the files I used to him which I cannot do on Github for obvious reasons.

**Comment by Wolfvak** [comment]
Since you're using a custom build, would you mind uploading the ELF files? (they're useful for debugging, if they contain some kind of secret key you can always zero it out and fix-up any hashes manually)

**Comment by wabberz** [comment]
Sure, here you go
[scriptrunner.zip](https://github.com/d0k3/GodMode9/files/3852127/scriptrunner.zip)

**Comment by d0k3** [comment]
Okay, just my 5 cents - the applybps code had issues from the start, and, tbh, I'm more surprised it hasn't happened until now than I am surprised about the fact it happened.

We'll think about this for a little bit more, but if no one rewrites that code, deprecating it is a real option here.

**Comment by wabberz** [comment]
OK, sorry for the delay. Put the 4 files from the attached ZIP file in the `data` subfolder of a vanilla GM9 and build as script runner:
```
make SCRIPT_RUNNER=1
```

It should first show the logo of our fan translation, patch that logo to the GM9 logo and display it, then patch the logo to the sequel of our fan translation and display it.

Source and info about the beat format:
https://code.byuu.org/beat

[data.zip](https://github.com/d0k3/GodMode9/files/3963909/data.zip)

**Comment by Wolfvak** [comment]
Latest commit should fix this issue, although I'm uncertain whether any others remain in the BPS code (lots of magic...).

Feel free to close this issue if it works.
