### ISSUE TITLE
.3DS to .CIA not working

### ISSUE THREAD

**Issue by Blackstargmr321** [d0k3/GodMode9#571]
Ive been trying to convert my Alpha Sapphire .3ds file to a .cia file. Every time I do this, it ends and gives me the error "Operation failed." If you can, please send help.

**Comment by Wolfvak** [comment]
No information was provided, nor was the template followed. Closing as invalid.
If you want to, open a new issue with the information asked in the template (and make sure you _fully_ read it),

As a quick workaround, try redumping the cartridge.
