### ISSUE TITLE
[BUG] Renaming files with 3-letter extensions to have a full-capital name changes the extension to have two capital letters and one lowercase

### ISSUE THREAD

**Issue by suburbGira** [d0k3/GodMode9#572]
I was using GM9 to dump my DS cartridges, and upon dumping WALL-E, when i tried to rename its name from the standard internal name to "WALL-E.nds", the extension became ".NDs". This also happened with the sav file becoming a SAv. I know this is just cosmetic, but it's ugly. It's possible to change the extension to all-caps by adding another letter at the end, changing the last normal letter to a capital, and removing the extra letter, but this cannot be done to make the extension lower-case.

**Comment by Ammako** [comment]
It's a weird 8.3 filename thing, it's probably supposed to display it all in all caps but for some reason it doesn't.

If you use a filename longer than 8 characters, you can avoid the issue.

**Comment by d0k3** [comment]
Looks fixed after an update to the FatFS R0.14 library. Can you test it, @suburbGira ?

Here's a test build?

**Comment by Ammako** [comment]
LGTM

**Comment by d0k3** [comment]
Whoa, that was quick, thank you (and I even forgot the test build link)!

I'll still wait for @suburbGira. Here's the proper test build link (I also fixed it above):
https://f.secretalgorithm.com/LW9Wu/godmode9.firm

**Comment by suburbGira** [comment]
Visiting my grandma's house at the moment, not currently able to test. I'll be back in about two days though, and will test then.

**Comment by d0k3** [comment]
@suburbGira - did you already have a chance to test?

**Comment by suburbGira** [comment]
Sorry, I completely forgot about this. I'll test today.

**Comment by d0k3** [comment]
As @Ammako already confirmed the fix works we can close this. I'd still like to know about your test results, @suburbGira.
