### ISSUE TITLE
[BUG] Textviewer not correctly displayed

### ISSUE THREAD

**Issue by HIDE810** [d0k3/GodMode9#573]
When I entered textviewer, the string was not displayed correctly. I think once entering hexeditor before entering textviewer, this problem goes away.

for example:
- titleID: 000400db00017202
- path: romfs/titleversion.txt

[image](https://user-images.githubusercontent.com/48782538/70873014-de459100-1fee-11ea-9075-f76bc3a3f455.png)

I used a custom build(v1.9.0-21-gaf95f038). So maybe it was caused by this(https://github.com/d0k3/GodMode9/issues/556)...

**Comment by d0k3** [comment]
I don't really know how that can happen. Can you upload that file for me to try? (Don't worry, there's no copyrighted and/or identifying info in it)

**Comment by Wolfvak** [comment]
Looks like junk data not being properly cleared to me. By the way, you didn't follow the issue template, so this issue is _technically_ invalid. I won't close it because you're already known to more or less know your stuff, but still, please follow the template in the future.

**Comment by HIDE810** [comment]
@d0k3 OK.
[titleversion.zip](https://github.com/d0k3/GodMode9/files/3973505/titleversion.zip)

@Wolfvak Sorry. I'll do so for the next time.

**Comment by Wolfvak** [comment]
Can't reproduce, I tried both opening it straight from text viewer, and going through the hex editor beforehand. Are there any other particular instructions? I placed the file on the SD card root without any modifications.

**Comment by HIDE810** [comment]
Please open another text file from text viewer before opening titleversion.txt (or another file).

**Comment by Wolfvak** [comment]
Okay yeah, I was able to reproduce the bug. Definitely looks like garbage data being left over, will try to locate why it happens and fix it.

**Comment by Wolfvak** [comment]
Okay I think this one fixes the issue, thanks to d0k3 for the tips on the `line_len` routine.
@HIDE810 please close this issue if it's fixed.

**Comment by HIDE810** [comment]
OK. I'll close this. Thanks.
