### ISSUE TITLE
[BUG] ... Build CIA from .3ds isn't working anymore?

### ISSUE THREAD

**Issue by Sonickid-Gaming** [d0k3/GodMode9#575]
I have an OLD 3DS and I never had any problems with this option until today. I don't have anything I know of that would have caused this, plus I checked to see if there were any corruptions on the SD card and there was none. I did install a custom splash screen on my 3DS when it boots, but I don't think that's what caused the error. I haven't used this option in a while though, I had to wipe my SD card and restore everything because of having the 3DS crash whenever I press the home button while playing a large space game like Smash. So i was in the middle of re downloading games I had before and then all of a sudden I can't build a cia from the decrypted .3ds games. Hell, all the options fail for them when I know they worked perfectly fine before because they are the same games and files that I backed up a while back. So is there a way to fix this?

**Comment by d0k3** [comment]
Are you really sure these .3DS files worked before? You wrote that you redownloaded those CIA files, so I'm wondering how you can be sure. What did you use to decrypt them?

Decrypted 3DS files from certain sources are known to be not properly decrypted, which would cause them to fail the CIA conversion.

**Comment by d0k3** [comment]
Okay, I just tried to reproduce that issue, and I couldn't. Just to be safe, try this current build of GodMode9:
https://f.secretalgorithm.com/155c8Z/godmode9.firm

**Comment by d0k3** [comment]
Okay, try this one instead:
https://f.secretalgorithm.com/H5gld/godmode9.firm

If converting to CIA still doesn't work, verify the file using the A button menu. Confirm the prompt to fix bad crypto flags if you get one.

**Comment by d0k3** [comment]
Assuming this solved, closing it now. @Sonickid-Gaming - feel free to continue adding info if you think this is not solved.
