### ISSUE TITLE
[BUG] Chainload booting to GM9 v1.9.1 from v1.9.0 or v1.9.1 will black screen.

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#578]
Sorry about not writing a complete bug report. Basically, while you're in an GodMode9 v1.9.0 or v1.9.1 session, 
- `GodMode9.firm` (v1.9.1) → **FIRM image options...** → **Boot FIRM**

***

Edit - (Jan-10-20, 3 PM EST) I might be able to reply back anytime soon. On errand.

**Comment by Wolfvak** [comment]
Can't reproduce on O3DS, tried booting from GM9 1.9.0-33 and the 1.9.1 release to itself and it always works.

The attempted chains are: fb3DS -> {GM9 1.9.0-33, GM9 1.9.1} -> GM9 1.9.1

**Comment by TurdPooCharger** [comment]
I wanted to demonstrate chainload booting between v1.8.0 , v1.9.0 , and v1.9.1 but decided against uploading a +500 MB video clip of it. My n3DSXL has dual TN panels and B9S v1.3 installed in both FIRM0/1. 
- https://streamable.com/itkh7

**Comment by Wolfvak** [comment]
Maybe it's the new3DS, we've had a lot of problems with those before. Only suggestion I can make is increasing the time spent waiting for init/reset on the GPULCD code (https://github.com/d0k3/GodMode9/blob/master/arm11/source/hw/gpulcd.c#L158) until we can get more testers.

**Comment by TurdPooCharger** [comment]
This also happens on my niece's n3DS, which too has dual TN panels and B9S v1.3. I ran into this bug while testing a script that contains a raw copy of GM9 v1.9.1, updates/installs to it onto the SD card if someone is using an older version, and then auto boots to it.

**Comment by fre4kyC0de** [comment]
Same here.
System details: New3DS; boot9strap 1.3; Luma3DS most recent (master); GodMode9 1.9.0 on CTRNAND.

Video attached (sorry for bad quality)
[IMG_3451.zip](https://github.com/d0k3/GodMode9/files/4050051/IMG_3451.zip)

**Comment by Wolfvak** [comment]
Judging from the fact both of you have new3DS', maybe it's _yet another_ screen init problem. We still need more testers though, especially the kind that are available on IRC or discord so we can quickly reach out to you.

**Comment by MaddoW** [comment]
Hey,
i am very new to this 3DS stuff here, but I did three weeks ago the full guide from https://3ds.hacks.guide/ on a new 3DS without any problems. Probably Luma v10.1.3 and godmode9 v1.9.1 .
Today same guide on a new 2DS XL with black screen after pressing start while power on for godmode9 NAND Backup. For sure Luma v10.2 and godmode9 v1.9.1 .

Quick question: Can I just replace Luma 10.2 with Luma 10.1.3 and i can lunch godmode9?

Best regards:)

**Comment by cesardt** [comment]
> Hey,
> i am very new to this 3DS stuff here, but I did three weeks ago the full guide from https://3ds.hacks.guide/ on a new 3DS without any problems. Probably Luma v10.1.3 and godmode9 v1.9.1 .
> Today same guide on a new 2DS XL with black screen after pressing start while power on for godmode9 NAND Backup. For sure Luma v10.2 and godmode9 v1.9.1 .
> 
> Quick question: Can I just replace Luma 10.2 with Luma 10.1.3 and i can lunch godmode9?
> 
> Best regards:)
> 
> Edit: I can confirm that replacing Luma 10.2 with 10.1.3 fixes the black screen issue.

I also have a New 3DS XL and could replicate the issue and the fix. Replacing Luma 10.2 with 10.1.3 fixed the issue for me. From what I could tell, the screen didn't initialize as I accidentally took a screenshot and was able to see GodMode9's interface.

**Comment by Joe-LB-03** [comment]
Another New3DSXL user here, can confirm switching from 10.2 to 10.1.3 works if you're having this issue.

**Comment by waffletacos** [comment]
I just did the hack for a New 2DSXL two days ago using the current 3DS hack guide and mine does the same thing.  Holding start and power leads to a black screen.  I can load it if I hold select and power to get into Luma.  I then tap A to save then hold A as it reboots and Godmode9 works.  I then did revert back to Luma 10.1.3 and it works correctly.

**Comment by jeffyjeffy1023** [comment]
I have a 2DS, O3DS, and N3DSXL. All of them have Luma 10.2 and GM9 1.9.1.
2DS: Boots GM9 perfectly fine if booting from NAND (as in 1:/rw/luma/payloads, with 1: being SYSNAND CTRNAND)
O3DS: Same as 2DS
N3DSXL: Boots fine either way.
