### ISSUE TITLE
[FEATURE REQUEST] Ability to Convert .CIA to .3DS

### ISSUE THREAD

**Issue by DeadSkullzJr** [d0k3/GodMode9#579]
**Got a great idea on how to improve GodMode9?**
A .cia to .3ds converter would be a nice touch to have in GodMode9 alongside the .3ds to.cia converter.

**Describe the feature you'd like**
It's pretty self explanatory, basically this feature allows you to convert from a digital media format (.cia) to physical media format (.3ds).

**Describe alternatives you've considered**
I have looked for various other alternatives on the internet, unfortunately only one method currently exists, it's known as "3DS to CIA Converter (v4.1)". This specific method has more than one converter that you can use, here is a list of the options it has:
- Start 3DS to CIA Converter (Req. Xorpads)
- Start 3DS to CIA Converter (Decrypted 3DS Files, Req. Xorpads)
- Start 3DS to CIA Converter (Decrypted 3DS ROM)
- Start CSU to CIA Converter
- Start CIA to CCI Converter
- Start CIA to 3DS Converter
- Start NES VC to CIA Preperation (Req. Xorpads)
- Start VC 3DS to CIA Converter 
- Start MD 3DS to CIA Converter (Req. Xorpads)

**Reason**
I have a few systems with custom firmware, and honestly I like having a variety of options on how I go about using them. One of which uses a flashcart with EmuNAND, I would like to run my games from that flashcart rather than digitally installing everything to my system.

**Comment by Wolfvak** [comment]
Not doable, the physical 3DS format needs some information that is simply not provided by the CIA file.

[img](https://cdn.discordapp.com/attachments/424654243199320066/665344150954180608/image0.png)
