### ISSUE TITLE
Decryption of .3ds leaves some encrypted junk in exefs

### ISSUE THREAD

**Issue by 0xC0DEDEAD** [d0k3/GodMode9#58]
Decrypting an encrypted game dump does not match that done with Decrypt9. On checking the areas that differ there are a couple of areas within the exefs partition that still contain what is in the encrypted dump and in the D9 decrpted dump are filled with `0x00`. Decrypting with xorpads also matches D9 except for the ncchflag[7], D9 sets `0x04` No Crypto, xorer sets `0x00` _Unknown_

**Comment by d0k3** [comment]
Non-issue, actually, cause these areas are actually padding. Xorer does not set anything, that's why you see zero, there, which means standard crypto.

Can you try this and tell me if that solves your problem?
https://transfer.sh/HKLqy/GodMode9-20170502-231926.zip

**Comment by 0xC0DEDEAD** [comment]
Thanks. That seems to work perfectly. NCSD's fully decrypt to match D9's output. If leaving the padding encrypted was intentional (quicker?), perhaps include a quick decrypt option and full decrypt. That way end users would be aware of the difference, as it stands I think it is fair to assume that people will expect that it is already a full decrypt. Though as you state, it may not be an issue but I think a full decrypt is cleaner.

0x00 means standard crypto? 3DBrew only mentions 0x01, 0x2, 0x04 and 0x20 as possible flags [here](https://www.3dbrew.org/wiki/NCCH#NCCH_Flags)

**Comment by d0k3** [comment]
Well 0x00 is not documented, because it is the standard... because for a long time it was the only flag that existed in NCCHs (there are no unencrypted, legit NCCHs, neither from eShop, neiter in NCSD rom dumps).

And no, the difference in performance is negligible. This will become the new standard. Closing this now...
