### ISSUE TITLE
[BUG] EmuNAND 3 and 4 not being detected.

### ISSUE THREAD

**Issue by PikachuR77** [d0k3/GodMode9#581]
GodMode9 is unable to detect my 3rd and 4th EmuNAND. I created an EmuNAND with Gateway 3DS's tool and then added three RedNANDs with Multi EmuNAND Creator. All of them appear just fine in the program but GodMode9 only detects the EmuNAND at offset 000000 and one RedNAND at offset 400001.

My console is a New 3DS XL with GodMode 9 installed to firm0/1.

Thanks!

**Comment by d0k3** [comment]
I'll look into it, but I'll need your help. Do you know your way around a hex editor like HxD (if not don't worry, I'll help)? I'd need the actual offsets of EmuNAND 3 and 4. Maybe you could also contact me via Telegram or Discord?

**Comment by d0k3** [comment]
@PikachuR77 - still haven't heard from you. We will need more info to get this resolved.

**Comment by PikachuR77** [comment]
Sorry, I haven't been able to get back sooner. According to Multi EmuNAND Creator my offsets are:
1: 0x076000000
2: 0x080000200
3: 0x0F6400200
4: 0x16C800200
I'm not sure how correct those are as going to those offsets by opening the disk in HxD just appear as gibberish I can't decipher. I can't find your Discord but mine is PikaR77#1829. Thanks!

**Comment by d0k3** [comment]
Okay, these offsets are somewhat weird. If these offsets are correct you got:

EmuNAND#1 @ 1888MB
EmuNAND#2 @  2048MB + 512byte
EmuNAND#3 @ 3940MB + 512byte
EmuNAND#4 @ 5832MB + 512byte

What I need is four files: From each of these offsets go back 512 (=0x200) byte, then dump 1024 (=0x400) byte to a file. Name all four files so I know what is what. Also make sure you actually open the _physical drive_ in HxD, not the logical one.

You can send me the files in Discord. They should contain no identifying / unique data at all, but I still understand privacy concerns.

**Comment by d0k3** [comment]
Alright, so, what @PikachuR77 needed was rather specific. He's running the first EmuNAND via GW, and EmuNANDs 3 and 4 were no more recognized by Luma or GM9. What he needed to do was, edit the SD card manually and move the offsets like that
EmuNAND#3 -> 4096MB + 512 byte
EmuNAND#4 -> 6144MB + 512 byte

This is too specific of a usecase and would also take hours on GM9. Manual setup is required for what @PikachuR77 wanted to achieve. As this is fixed for him, I'll close this now.
