### ISSUE TITLE
[BUG] The builds on d0Ks site are outdated

### ISSUE THREAD

**Issue by Kalanyr** [d0k3/GodMode9#582]
The builds on d0ks site are outdated again (the last GodMode build is from 29/10/2019 and the SaltMode is from 07/11/2019

**Comment by Wolfvak** [comment]
Confirmed, will fix.

**Comment by d0k3** [comment]
@RShadowhand - could you look into this?

**Comment by d0k3** [comment]
Was fixed by @RShadowhand a few weeks ago.
