### ISSUE TITLE
Key replacement for gm9 (back to stock)

### ISSUE THREAD

**Issue by golem5G** [d0k3/GodMode9#584]
Hi i have a problem i bought a New 3DS xl a month ago so the device still has warranty.

I have cfw running on my 3ds, but today i realized that the "up button" in the d-pad doesn't work correctly if fact for some reason is stucked and is always reacts like i am pressing on it but i am not.
I tryed blowing to the d-pad but still nothing..

So i want to take my 3ds to Nintendo warranty service, but for this to happened i have to uninstall cfw so i don't get any trouble with them.

For this to happen i have to go through the gm9 to uninstall cfw but my "up-button" in the d-pad is suck and i can't do it 

**Is there any way that i can edit the source code of gm9 so i can replace "up-button" in the d-pad with a another key on the 3ds for example with the "ZL" OR "ZR" button so i can go through and uninstall cfw?**

**Comment by Wolfvak** [comment]
Sadly, handling the ZL and ZR buttons requires a fair bit more code than just changing it, but you _could_ edit [this](https://github.com/d0k3/GodMode9/blob/master/common/hid_map.h) file and use the key mappings from [here](http://3dbrew.org/wiki/HID_Registers) to make any other key work as the up-arrow (of course, that'd make the other key useless, so you should pick one that isn't fully required for normal usage, like the START or SELECT buttons).

**Comment by golem5G** [comment]
Thank you for your time.
I don't know if this the right way to go, 
But the changes i made so far [in the flowing file](https://github.com/d0k3/GodMode9/blob/master/common/hid_map.h)
 are this, 
1.  **I deleted this line (No.6)**
    `#define BUTTON_UP ((u32)1 << 6)`

2.  **And i change the line (No.14) from this** `#define BUTTON_Y      ((u32)1 << 11)` 
**to this**
      **`#define BUTTON_Y ((u32)1 << 6)`**

But i haven't tested yet because i have run in to a problem, i can't build the  `GodMode9.firm`  file 
Because my knowledge in programming aren't as good and the [guide](https://github.com/d0k3/GodMode9/blob/master/README.md#how-to-build-this--developer-info) isn't so helpful 
**Can you help me out with this?**

**Comment by Wolfvak** [comment]
If you want to make the Y button act as up (and make the UP button act as Y) you should just swap the two defines around, rather than delete one and change the other.

There's some build information [here](https://github.com/d0k3/GodMode9#how-to-build-this--developer-info)

**Comment by mostycool** [comment]
I have an interesting variation of this issue. When I load into gm9 the top screen shows me the different drive letter on the top screen of my old 2DS. Here it seems that the down button of the d-pad is stuck. 

when I press the home button and go to the action menu (bottom screen) there is no more stuck scrolling. 

When I try to do a confirmation code (bottom screen) this issue comes back :'( lol. As a result I've been RNG grinding for a combo I can complete. Once I finally got a doable key combo I couldn't push the A button at the end as it seems to be locked out.
