### ISSUE TITLE
[BUG] 'Fix CMACs for drive' on '[A:] SYSNAND SD' will stop on corrupt/uninitialized *.sav.

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#585]
**So you want to report a bug?**
While helping someone at GBAtemp forum try to 'SDTransfer' his **Nintendo 3DS** folder from a (source) system to (target) system as seen in this thread:
- [Copying SD Card content to other system's SD Card (ID0)](https://gbatemp.net/threads/copying-sd-card-content-to-other-systems-sd-card-id0.556297/)

It was discovered by Meercko that his titles were appearing with black icons and missing banners in the HOME Menu. Instructions on how to perform SDTransfer can be seen in [post 15](https://gbatemp.net/threads/copying-sd-card-content-to-other-systems-sd-card-id0.556297/#post-8934048).

My own attempt with a small collection of games with saves (3DS & GBA VC titles), updates, and dlcs SDTransferring from n3DSXL to n3DS produced a similar error.

The files with CMACs in **dbs** and **extdata** are corrected, but the *.cmd and *.sav in **title** report `CMAC verification: failed!` when individually checked.

**Info about your system**
Include this info to make our work easier:
* N3DS (two systems, n3DS and n3DSXL)
* boot9strap v1.3
* GM9 v1.9.1 chainloaded form Luma3DS v9.1

**Have you actually read this?**
[X] I have read the information above

**Comment by Wolfvak** [comment]
bruh

**Comment by TurdPooCharger** [comment]
The proper title and explanation has been now been edited/updated. 

I'm terribly sorry for the faux pas. My right pinky finger slipped trying to hit the backspace, and it instead hit the enter key while I was typing the title. I hope you can forgive me as I didn't mean to disrespect GodMode9.

**Comment by Wolfvak** [comment]
uh no big deal, will reopen

**Comment by d0k3** [comment]
I'll look into that. @TurdPooCharger - does this also happen in 1.9.0? If not, do you know how to do a git bisect (I can give you the instructions if you want to).

**Comment by TurdPooCharger** [comment]
New development.

Did some more SDTransfers and was getting wildly different results. My n3DSXL has five (5) **Nintendo 3DS** folders labelled (A) through (E). Two (2) of those folders crossed over fine with all of their CMACs fixed in GM9 v1.9.1.

I took a closer look on the folder that failed, rerunning back-to-back SDTransfer and comparing the outputs between v1.9.0 and v1.9.1.

Other than leaving alone the CMACs for GBA VC SD saves, GM9 v1.9.0 fixed all the `*.cmd` and `*.sav` in the **title** subfolder.

For my particular case, GM9 v1.9.1 stopped the **Fix CMACs for drive** run upon reaching the first entry in **title**. This was my copy of the game _Mario Kart 7_, which just so happens to have a corrupt save file.

Included in this attachment is the (bad) save file pulled from the **[A:] SYSNAND SD** for you to test in your fix cmacs run.  
- [Corrupt MK7 save (decrypted).zip](https://github.com/d0k3/GodMode9/files/4173801/Corrupt.MK7.save.decrypted.zip)
- **[A:] SYSNAND SD/title/00040000/00030800/data/**`00000001.sav`

When I replaced this with a (good) save from another folders {I have a 2nd copy of MK7} and did the fix cmacs again, the `*.cmd` and `*.sav` for more games were corrected.

This fix cmac run stopped again on a custom NES VC injection of _Metroid_ that haven't been played yet where its `00000001.sav` was uninitialized (first 0x20 bytes filled with 00's).

**Comment by d0k3** [comment]
Sorry @TurdPooCharger, I've been awfully busy these days. You already gave me enough info, though. No need for a `git bisect` (for now). Also, thanks. Your detailed bug reports have made my life easier (and GM9 better) several times now.

**Comment by d0k3** [comment]
Okay, try this one:
https://f.secretalgorithm.com/Z4emB/godmode9.firm

I think this will fix it.

**Comment by TurdPooCharger** [comment]
@d0k3, it's all good. I actually prefer the slower pace these days. Been busy myself lately.
<details>
<summary>Spoiler: IRL rant</summary>
Spring cleaning, family errands, car repairs.. Unending HoA B.S.. :expressionless:

Still got stuff to take care of. Big day tomorrow with my country's FL state early voting for democratic presidential candidate. 
</details>

***

I'll update this post this weekend with the results when I should have some free time (check back Saturday / Sunday Mar 07-08).

**Comment by d0k3** [comment]
@TurdPooCharger - thanks a lot again. Well, we all got a lot of IRL stuff going on. I'm glad you still find some time to help with those issues - it's highly appreciated and you already helped making GM9 better a lot!
