### ISSUE TITLE
[BUG] Building a standard CIA results in some junk data between 'TMD Content Chunks' and the first content file of the CIA.

### ISSUE THREAD

**Issue by Rifu86** [d0k3/GodMode9#587]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).

When creating a CIA (standard) from a TMD file, it results in a different CIA file hash
then building a CIA on a different 3DS System that has the exact same contents installed.
(e.g Two 3DS Systems that have 'purchased the same game from the same region eShop'
or 'have installed a 'Title' using the same CIA file')

Its due to some junk data being included between the 'TMD Content Chunks' section
and the first content file in the CIA. (It appears to be 28 bytes of junk data with CIAs that
have 2 content files, and 44 bytes with 3 content files)

Here is a link to a GBATemp post describing the issue:
https://gbatemp.net/threads/release-godmode9-all-access-file-browser-for-the-3ds.420027/page-55#post-8951505

* Give us clear steps to reproduce (when/how did it happen?).

Have two different 3DS Systems that have the exact same contents (TitleID and Version) installed.
Select [A;] SYSNAND SD. and press R+A (Drive Options) > Search for Titles.
Select the Title that BOTH 3DS Systems have installed.
Press A and Select TMD file options > Build CIA (Standard)
(both 3DS need to have exact same TitleID and Version of the game installed)

Do this on both 3DS and then compare the CIA files, they are different in a few bytes,
usually around offset 0x3900 and 0x4000. This is the data area between the
'TMD Content Chunks' and the first Content File (this area should be 00's)

This GBATemp followup post may have the solution:
https://gbatemp.net/threads/release-godmode9-all-access-file-browser-for-the-3ds.420027/page-55#post-8952682

* Give us info about your system (where did it happen?).
When Building a CIA (Standard) file from a TMD file.

* A photograph or even a short video of the bug happening is always helpful!

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS) - both systems are New3DS
* Anything special about your console? (defects, custom modifications,...) - None
* Bootloader (boot9strap/fastboot3ds) - Both Boot9Strap v1.3
* Did you chainload GodMode9 via Luma? Yes on both systems.
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[x] I have read the information above

**Comment by d0k3** [comment]
Again, thanks a lot for the detailed description! Your solution was almost right, at the very least it pointed me into the right direction. There was no error in the sizes written (the CIA stub is always everything until the content starts).

What went wrong is, I loaded the whole TMD file into the buffer (which is large enough) even if I needed only part of it. What you saw are (as you correctly wrote) leftovers of that file. The solution is, just clean that stuff up, and everything works the way we want it.

Can you try this test build?
https://f.secretalgorithm.com/86w8e/godmode9.firm

**Comment by d0k3** [comment]
This is a better, cleaner fix:
https://f.secretalgorithm.com/ktbg3/godmode9.firm

Instead of cleaning up afterwards, it just gets what we need from the TMD file and nothing more. Can you test this?

**Comment by Rifu86** [comment]
Using the file from the previous post, that has fixed the CIA creation,
no more junk data added, but I noticed when you select '(A:) SysNAND SD'
and then press 'R+A' and select 'Search for Titles', in the results some of files
are named as '00000000.tmd' and then some of the files have a name like
'0004000000FEDCBA00 <GAME NAME HERE> (CTR-P-AAAA) (E).tmd'
in the v1.9.1 release all of the files have the long file name with the TitleID in it.

**Comment by d0k3** [comment]
Okay, looks like something is still wrong. I'll look into it.

**Comment by d0k3** [comment]
Okay, I derped big time. Sorry. This one should work and cause no further issues:
[GodMode9_fixbuild_200306.zip](https://github.com/d0k3/GodMode9/files/4299417/GodMode9_fixbuild_200306.zip)

Can you give it a try?

**Comment by Rifu86** [comment]
That build above works perfectly. Both my 3DS Systems now build the exact same hash-matching CIA.

**Comment by d0k3** [comment]
Thanks! I already pushed the changes to `staging`, but I'll leave this bug open due to your additional comments.

Your first edit:
Well, we don't know the titlekey and we have to put something in there. There exist no legit CIAs for which there is no titlekey, so we have no clue what Big N would want in there in that case. 0xFF is as good as anything else, and it at least shows we know there should be something there.

Your second edit:
Yup, you're right, and that would be a good addition. Expect a new test build during the next few days.

**Comment by Rifu86** [comment]
RE: my first edit: Yes, filling the Titlekey with FF's is fine, as its a game card there is no TitleKey for it.

but when there is an 'EncTitleKeys.bin' file present in the support folder on the SD card,
when building a CIA from the 3ds rom or gamecard, the eShop TitleKey gets copied
into the ticket when the TitleKey should be 'FF' filled (as its a gamecard)

**Comment by d0k3** [comment]
Is it actually wrong to add the titlekey there? In other words: are gamecard NCCHs different from eshop NCCHs with the same title ID and version numbers? And are they different enough so that updates would not work?

Afaik, updates for gamecards are identical to their respective eshop title updates. Might be wrong, though.

**Comment by d0k3** [comment]
Okay, I added a commit for taking over the title version from the cart dump to the CIA. With that I'm closing this now. Feel free to continue adding comments here if there are still open issues.
