### ISSUE TITLE
Can't convert file from 3ds to cia in GodMode9

### ISSUE THREAD

**Issue by ramanio** [d0k3/GodMode9#588]
Every time I try to do it I get an error message operation failed first I thought maybe I don't have enough memory, so I bought a 16 GB SD card but still did not solve my problem. 

**Info about my system**
Include this info to make our work easier:
* I have a N3DS

* The firmware i'm running is 11.13.0.45E
* I  chain load GodMode9 via Luma
### 

![test](https://user-images.githubusercontent.com/61562806/75485995-074daf00-59ac-11ea-8e92-141fec0f8d5a.gif)

**Comment by carlsoncorey16** [comment]
This is an issue with pirated content being decrypted by older worse tools, so the best solution I have for you is to not pirate.

**Comment by Validusername16** [comment]
Alright, lets try this again.
The issue here is the file itself, since it was decrypted by older worse tools. So the best solution I have for you is to not pirate.

**Comment by TurdPooCharger** [comment]
@ramanio, see this post on how to go about converting 3DS roms to CIAs if they have the wrong crypto flag.
- [[Release] 3DS Simple CIA Converter [Post # 787]](https://gbatemp.net/threads/release-3ds-simple-cia-converter.384559/page-40#post-8908674 )

**Comment by d0k3** [comment]
@ramanio - use the latest version (v1.9.1). That one should give you an option to fix the broken file. If it doesn't work via the script then use the A button menu to convert the file.

Let me know if that worked for you.

**Comment by d0k3** [comment]
@ramanio - we need more info from you. Did you try v1.9.1?

**Comment by d0k3** [comment]
Alright, we're assuming you got it sorted out. Feel free to continue writing here, @ramanio, I'll get a notification if you do.
