### ISSUE TITLE
Ability to dump to CXI

### ISSUE THREAD

**Issue by deadair3210** [d0k3/GodMode9#59]
As far as I can tell, while Decrypt9 can dump to CIA and CXI, all GodMode9 can dump to is CIA and Legit CIA. CXI would be useful and would go towards GodMode9 being a complete replacement and unified tool

**Comment by ihaveamac** [comment]
you probably want one of the .app files in a title's content directory.

**Comment by d0k3** [comment]
Correct, you just need to copy / decrypt the biggest .app file. No need to add bloat and a separate menu entry for that.
