### ISSUE TITLE
[BUG] ... 

### ISSUE THREAD

**Issue by xj9808** [d0k3/GodMode9#590]
Attempting to use the .3ds to .cia converter results in a screen that reads "operation failed" after only a few seconds. Currently using a N2DS with boot9strap and Luma. 

**Have you actually read this?**
[Y] I have read the information above

**Comment by d0k3** [comment]
That's not enough info. Tell us what exactly you did, step by step. Also check if there's still room on your SD card.

**Comment by Wolfvak** [comment]
Not enough info, closing after 10 days of inactivity.
