### ISSUE TITLE
[FEATURE REQUEST] Use Serial for dump name of games

### ISSUE THREAD

**Issue by Liger0** [d0k3/GodMode9#594]
**Got a great idea on how to improve GodMode9?**
Some years ago I used to dump my files with, if I recall correctly, Hoursglass 9.
With that, the file had as name the file serial, so it was easy to distinguish the games.
With godmode9 it has the generic file name, which makes it hard to distinguish the files if you dump multiple ones.
Making it possible to name them after the serial would be cool.

**Comment by d0k3** [comment]
Can you specify what you mean by generic filename? Right now, GM9 uses the media ID plus the rom version, which should actually be more unique than just the cart serial.

**Comment by Liger0** [comment]
You're right, by I preferred if it used the serial name. Maybe an option for preference if plausible.

**Comment by d0k3** [comment]
Well, there's no way we'll change an established naming scheme now. You can, however, do your own personal build. It's a simple change, done here:
https://github.com/d0k3/GodMode9/blob/master/arm9/source/gamecart/gamecart.c#L51
