### ISSUE TITLE
[BUG] Certain legitimate tickets do not appear in mounted ticket.db image

### ISSUE THREAD

**Issue by enderghast13** [d0k3/GodMode9#596]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
* Give us clear steps to reproduce (when/how did it happen?).
* Give us info about your system (where did it happen?).
* A photograph or even a short video of the bug happening is always helpful!

When mounting the ticket.db file at 1:/dbs/ticket.db, certain legitimately purchased tickets do not appear. In particular, the tickets for titles 00040000001D9000 (Tank Onslaught (USA)) and 00040000001DB100 (Fatal Fracture (USA)) do not appear in the eshop, hidden, system, or unknown folders for me, as well as a few other tickets. This happens whether or not a SD card is inserted. These tickets do appear in FBI's ticket list. I am using Godmode9 v1.9.1 from the releases page (commit 130ff69).
To reproduce, one can buy and install these titles on the eshop of a USA region system, start GodMode9, go to the sysnand dbs folder, mount the ticket.db file, and not find the tickets in any of the directories. I do have a few hundred tickets installed, both legitimate and homebrew, but I'm not sure whether that is the cause or not.
As a workaround, I was able to delete my ticket for 00040000001D9000 in FBI, open the eshop to redownload it, and extract it from the sysnand tmp folder in GodMode9 and manually trim it on PC.

**Info about your system**
Include this info to make our work easier:
* Console type: N3DS
* Anything special about your console?: Nothing
* Bootloader: fastboot3ds v1.2
* Did you chainload GodMode9 via Luma?: No, loaded through fb3ds button combo
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[X] I have read the information above

**Comment by aspargas2** [comment]
This is likely because of the way gm9 does raw brute-force parsing of ticket.db for the mount; it doesn't properly interface with the filesystem within the file, so I would not be surprised if it missed certain things under certain circumstances, especially if there's been many additions and removals of tickets. I'm currently working on code to change the mounting system to use the filesystem properly which would most likely solve this issue. I do not believe it has anything to do with those specific games, but I may be wrong about that.

In any case, could you try mounting your ticket.db with [this build](https://cdn.discordapp.com/attachments/548903219317833758/701357935732981820/GodMode9.firm) of godmode9, and see if the tickets which are usually missing appear? It has a few debug messages leftover from my debugging of things ("mallocing for <something> returned <something>"); just ignore those.

**Comment by enderghast13** [comment]
Thanks! Unfortunately I'll have to get back to you in a while on this as my sd card is formatting and I need to get some sleep soon. I will test it when I wake up

**Comment by aspargas2** [comment]
That's fine, no hurry. And yeah, more information is always good to include even if it's probably irrelevant.

**Comment by enderghast13** [comment]
I've now tested it. It was able to find all of the tickets that I couldn't find before and they matched the tickets I had previously gotten. The one from the sysnand tmp directory didn't match in the titlekey area, but I don't think that's a problem with this build and think that directory was probably meant for other things. Thank you :)

**Comment by aspargas2** [comment]
Yeah, there's no reason that build should mess with the contents of the tickets themselves as long as it finds them. I'm really not sure what the ctrnand tmp directory is for, but it doesn't surprise me that a ticket from it has something different about it. If you want to leave this issue open until my code is merged to the main godmode9 repository (it's not even pushed to GitHub anywhere yet, and as you can see it's still in development plastered with debug prompts) then that's fine. I'll leave that up to you and the actual godmode9 devs who have the power to close this.

**Comment by enderghast13** [comment]
Ok, I think I will leave this open for the time being then, at least until another dev decides to close it or it is merged

**Comment by d0k3** [comment]
We will leave this open until @aspargas2 merged his changes. Thanks for the bug report, @enderghast13 and thanks a lot @aspargas2 for your help!

**Comment by d0k3** [comment]
@enderghast13 - can you retry with this build and tell us your results?
https://github.com/d0k3/GodMode9/files/4833936/GodMode9.zip

**Comment by enderghast13** [comment]
@d0k3 - I tested the build and it works fine. All the tickets that weren't there before are accessible now in the eshop directory. Thank you and @aspargas2!

**Comment by d0k3** [comment]
That's a known issue, @enderghast13 -we're working on it. Thanks a lot for testing!

Amazing work as always, @aspargas2 !
