### ISSUE TITLE
[BUG] ... failed game dump still takes up space on my SD card

### ISSUE THREAD

**Issue by ToxaGaming** [d0k3/GodMode9#598]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
I tried to dump my digital copy of Pokemon Ultra Moon as a CXI. When i selected "Dump as CXI" the 3DS just froze, so then I thought of restarting my 3DS and redoing the process. Unfortunately it just started dumping the game right as I turned the 3DS off and now that temporarily dumped data is stored somewhere, somehow on my SD card. I've already checked "gm9/out" and there was no data in that folder.

**Info about your system**
Include this info to make our work easier:
N3DS
* Bootloader: boot9strap
* Did you chainload GodMode9 via Luma? yes

**Have you actually read this?**
[yes] I have read the information above

**Comment by d0k3** [comment]
You shouldn't have turned your console off while it still worked, but I don't need to tell you. GM9 is not at fault here.

You'll be able to free that space again (and fix any other file system errors) with Windows chkdsk (command line tool, use Google).
