### ISSUE TITLE
Feature request - More verbose feedback like D9

### ISSUE THREAD

**Issue by 0xC0DEDEAD** [d0k3/GodMode9#60]
The progress bar is nice, but for opperations like decryption, the more detailed feedback of D9 is useful as is the log. That would be a wonderful addition along with a txt viewer to view the log

**Comment by d0k3** [comment]
I agree that there could be more specific error messages for typical user errors (such as no aeskeydb.bin provided), but other than that, GM9 is designed to "just work" and there should be no need for complicated console output. You will be hard pressed to find any cases that would contradict this.

**Comment by d0k3** [comment]
Okay, there are now helpful hints for when certain crypto operations fail, starting with https://github.com/d0k3/GodMode9/commit/9921c4d669d183231a4f5c3a38ddfb48a292dbff

If there is anything else you feel would need more detailed information, feel free to open another issue.
