### ISSUE TITLE
[FEATURE REQUEST] Please revert to the old button-based input for filenames.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#601]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.

**Describe the feature you'd like**
Add a clear and concise description of what you want to happen.

Revert to the old button-based input method, or at least provide a build of GM9 (or better, SaltMode9) without touchscreen features. I often found that the touchscreen calibration is incorrect and the calibrations do not persist across reboots.

**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.

I have mentioned in an issue before, I suggest using an "RPG name entry" style input screen, where you use the D-pad to select letters from a grid, A to input, B to erase one character, L/R to move the cursor and Start (or a dedicated place in the grid) to confirm. The 3DS is a game console and this method is the most familiar for gamers.

**Comment by d0k3** [comment]
I plan on adding button controls to the keyboard, so we'll keep this open for the time being. Won't make it into the next release, though.

**Comment by pthfdr-42** [comment]
I think that you can just make a compile option to disable the changes in commit 40b4e3f so it uses `ShowStringPrompt` instead of `ShowKeyboardOrPrompt`.

**Comment by d0k3** [comment]
Okay, here's something for you to have a look at:
https://f.secretalgorithm.com/14KemU/godmode9.firm

This one allows you to switch from the keyboard to the old input style by a press of the SELECT button. Won't work vice versa because of reasons (it's actually not that simple), and I'm thinking about leaving it that way. Thoughts? I can also add the touch disabling compile option if you still want it.

**Comment by pthfdr-42** [comment]
It works fine. Thanks.

**Comment by TurdPooCharger** [comment]
Anyone who may like to switch between touchscreen and button based typing, on GM9 v1.9.1 you can revert to the old method by removing this file.
- **[0:] SDCARD ()/gm9/support/**`gm9calib.bin`

**Comment by raisehero** [comment]
Showing how to switch to button based input would be nice inside the actual software itself without searching for this actual issue.

**Comment by d0k3** [comment]
Did you try the latest release (v1.9.3pre1)? The calibration data was always fetched directly. Calibration really only needs to be done if that fails. It could be a problem with your system.

Maybe try the newest release and create a bug if there are still problems?
