### ISSUE TITLE
GM9 fails to compile on latest devkitARM

### ISSUE THREAD

**Issue by autofire372** [d0k3/GodMode9#602]
Trying to build GodMode9 with the latest devkitARM installed leads to the following errors:

``c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_1MB_CTR'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_512KB_CTR'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_128KB_CTR'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_8MB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_1MB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_512KB_2'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_512KB_1'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_256KB_2'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_256KB_1'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_128KB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_64KB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_8KB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/gamecart/gamecart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_512B'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/utils/nandutil.o (symbol from plugin): in function `sig_nand_firm_retail_alt':
(.text+0x0): multiple definition of `sig_nand_ncsd_dev'; build/common/sighax.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/utils/nandutil.o (symbol from plugin): in function `sig_nand_firm_retail_alt':
(.text+0x0): multiple definition of `sig_nand_ncsd_retail'; build/common/sighax.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/utils/nandutil.o (symbol from plugin): in function `sig_nand_firm_retail_alt':
(.text+0x0): multiple definition of `sig_nand_firm_dev'; build/common/sighax.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/utils/nandutil.o (symbol from plugin): in function `sig_nand_firm_retail_alt':
(.text+0x0): multiple definition of `sig_nand_firm_retail'; build/common/sighax.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/utils/nandutil.o (symbol from plugin): in function `sig_nand_firm_retail_alt':
(.text+0x0): multiple definition of `sig_nand_firm_retail_alt'; build/common/sighax.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_1MB_CTR'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_512KB_CTR'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_128KB_CTR'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_8MB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_1MB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_512KB_2'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_512KB_1'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_256KB_2'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `FLASH_256KB_1'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_128KB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_64KB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_8KB'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
c:/msys64/opt/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld.exe: build/virtual/vcart.o (symbol from plugin): in function `EEPROM_512B':
(.text+0x0): multiple definition of `EEPROM_512B'; build/gamecart/card_spi.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make[1]: *** [../Makefile.build:18: arm9.elf] Error 1
make: *** [Makefile:83: arm9/arm9.elf] Error 2``

**Comment by Wolfvak** [comment]
We're aware of this - it just needs `extern` added at the start of some EEPROM and sighax buffer declarations, in their respective headers. The fix will be added as soon as dkA r54 is supported.

**Comment by NWPlayer123** [comment]
why'd you close this @Wolfvak the issue is unresolved, keep it open until r54 is supported and you can compile again :|

**Comment by Wolfvak** [comment]
fixed with https://github.com/d0k3/GodMode9/commit/244d24ee2ae0502c2566fca9fc18c013607322a4, please read the commit message for why I didn't care to fix it yet
