### ISSUE TITLE
[BUG] Attempting to run a search with a certain number of results triggers a data abort

### ISSUE THREAD

**Issue by aspargas2** [d0k3/GodMode9#605]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).

Using GodMode9 v1.9.1 (downloaded from the releases page), I pressed R+A on a directory with 4856 total files in all of its subdirectories, chose `Search for files...`, and pressed A with the search pattern remaining as `*`. The following prompt reported that only 2052 results were found. After I dismissed this prompt, I was greeted with a data abort. The crash dump is attached.
* Give us clear steps to reproduce (when/how did it happen?).

To reproduce, simply execute any search for files that should result in more than 4800 results. I don't know the exact number of expected results at which data aborts start occurring, but it's somewhere in between 3000 and 4800. It seems that for searches with 2048 or more expected results, the number of results stays at 2047 for all numbers of expected results until somewhere past 3000, after which it exceeds 2048 by a seemingly unpredictable amount and causes a data abort. Searches which falsely report 2047 results do not cause data aborts.

**Info about your system**
N2DSXL, GodMode9 loaded directly from boot9strap

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

My SD's integrity and my bootloader should be irrelevant here. This also happened when I searched a mounted ticket.db on ctrnand.

**Have you actually read this?**
[*I am too lazy to go find a unicode checkmark*] I have read the information above

[exception_dump_200612014813.txt](https://github.com/d0k3/GodMode9/files/4768972/exception_dump_200612014813.txt)

**Comment by aspargas2** [comment]
I think I found what causes this. On line 167 of fsdrive.c, there is a check for exceeding `MAX_DIR_ENTRIES` while searching. However, `GetDirContentsWorker` is recursive, so this check is ineffective and only breaks out of one call to this function. Previous calls still successfully process one more directory entry each before hitting that check. I'm not sure what the best solution to this would be; setting `ret` to false in this check just makes the whole search fail when `MAX_DIR_ENTRIES` is exceeded.

**Comment by d0k3** [comment]
This should be fixed by 2791b42f6e04ca5156af2836fae78dbabcf0e832 (still untested). Thanks @aspargas2 !

**Comment by aspargas2** [comment]
Yep, that fixed it.
