### ISSUE TITLE
problem with the key combination

### ISSUE THREAD

**Issue by jonaz8** [d0k3/GodMode9#606]
Greetings, I am Jonas and I am writing to discuss a problem I have with GODMODE9, and that is that I try to install FBI in H&S and when I get to the key combination it does not recognize them, just as when I want to uninstall HAX the same thing happens to me What could I do?.

PS: I use the google translator to write just in case they see a redaction error.

**Comment by d0k3** [comment]
Can you try to explain in a different way? May add some photos of your screen?

**Comment by jonaz8** [comment]
fixed, the problem was with a physical key that requires maintenance

**Comment by d0k3** [comment]
Alright, thank you!
