### ISSUE TITLE
[FEATURE REQUEST] Include .txt with dump info in GAMECART

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#607]
It'd be useful if a text file with dump info was included in the virtual gamecart folder.
Something like
```
Product Code: xxxx
Revision: xxxx
etc
```

Here the details of some useful ROM header fields for this file:

**DS**
| Field        	| Offset (hex) 	| Length (hex) 	| Note
|--------------	|--------------	|--------------	|-------------------------------------------
| Cart ID      	| _N/A_          	| _N/A_          	| Same as displayed in C: drive name in GM9
| Platform         | 12                  | 1                    | 00=DS, 02=DSi Enhanced, 03=DSi
| Product Code| C            	| 4            	| ASCII
| Revision     	| 1E           	| 1            	| Should be displayed as decimal

(source: https://problemkaputt.de/gbatek.htm#dscartridgeheader)

**3DS**
| Field        	| Section           |  Offset (hex) 	| Length (hex) 	| Note
|--------------	|--------------	|--------------	|----------------|---------------------------
| Cart ID      	| _N/A_            | _N/A_          	| _N/A_             | Same as displayed in C: drive name in GM9
| Platform         | main NCCH  |  18C                  | 1                    | 01 = 3DS, 02 = New 3DS
| Product Code| main NCCH   | 150                  | 10                    	| ASCII
| Revision     	| NCSD             | 312           	| 2            	| Should be displayed as decimal

(source: https://www.3dbrew.org/wiki/NCCH, https://www.3dbrew.org/wiki/NCSD, https://www.3dbrew.org/wiki/NCCH)

**Comment by InternalLoss** [comment]
This would be super useful, especially since users could then just paste the contents of said GAMEINFO into No-Intro/etc, and we wouldnt have to notate Cart ID etc

**Comment by aspargas2** [comment]
Personally I don't see a virtual file in the gamecart drive as the appropriate place for something like this. Couldn't a script be written relatively quickly to generate the info in a nice format and append it to a text file somewhere?

**Comment by mariomadproductions** [comment]
That'd be reasonable. Although I'm not sure how straightforward it'd be to retrieve the info, especially the Cart ID.

**Comment by d0k3** [comment]
I think we either need to provide the interface to generate such a file, or we need to provide the file itself. It's pretty useful for digital preservation.

**Comment by InternalLoss** [comment]
I think the GAMECART drive *would* be a good place to put this file, since the header etc is already here when dumping, so users could just mark the full NDS/3DS, gameinfo and header when applicable and copy to 0:/gm9/out - makes life a lot easier c:

**Comment by d0k3** [comment]
I had an idea. Just throwing that in, for now. Wouldn't it be a good idea to include all that stuff in the filename?

**Comment by mariomadproductions** [comment]
I think that'd be a good idea to put it in filename. That'd mean people would be getting this info with "normal use" of GM9 - they wouldn't have to go out of their way to get it by copying an additional file. Although you'd have to avoid the filename getting too long.

Also, some revisions to the my initial post:
- Instead of just looking for it in the ROM header, "Platform" should be calculated the same way it is for other purposes (which as I understand it will soon be combination of looking in the cart header + looking at the cart id). That might not account for if its a New 3DS or Old 3DS title, but that's not very important.
- I also recently learned that the "priv" file actually includes the Cart ID already as well as the private header (and some "made-up" padding?). I don't think its a good idea to bundle them together, because:
  - The cart ID isn't actually sensitive info (its just harmless hardware info, and multiple carts have the same ID), unlike the 3DS private header.
  - its not easy for users to parse the file to get the number (esp. to parse it in the same way GM9 does) - you need to know how to use a hex editor, or require them to use a script or bash/cmd command
  - we don't really want people to accidently submit this data (e.g. to No-Intro) alongside the wanted metadata

**Comment by d0k3** [comment]
I got something to test for you here:
https://f.secretalgorithm.com/aSHQu/godmode9.firm

Notes:
1. We got no relevant size limit for the dump name anymore.
2. There's no special calculation for platform yet.
3. I had to code blind. Don't have any carts here. I hope this build does not do anything super weird.
4. Name format is up for discussion.

As for the private header... I think you're not aware of it's purpose. It's used (was used) in the Gateway card, to allow online play without the risk of a ban. Each private header is unique, thus you could just grab a header from a cheap game (doesn't even need online capabilities) and use it for all your online gaming. Apparently Nintendo doesn't do any sanity checks here (check if the private header matches the actual game played).

**Comment by mariomadproductions** [comment]
I'll try that out.

Yeah I'm aware the private header is used for online stuff. But that just makes it more sensitive.

**Comment by mariomadproductions** [comment]
Here are the results:
<table>
<thead>
  <tr>
    <th><sub>v1.9.1: Drive name suffix</sub></th>
    <th><sub>v1.9.1: .3ds filename</sub></th>
    <th><sub>ROM image: Prod. Code</sub></th>
    <th><sub>Test build: Drive name suffix</sub></th>
    <th><sub>Test build: .3ds filename</sub></th>
    <th><sub>Notes</sub></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><sub>CTR9080FA45</sub></td>
    <td><sub>0004000000132800-v00.3ds</sub></td>
    <td><sub>CTR-P-AYNP</sub></td>
    <td><sub>KTR9080FA45</sub></td>
    <td><sub>0004000000132800_CTR-P-AYNP_00_1_9080FA45.3ds</sub></td>
    <td><sub>Seems good, except "KTR" should be "CTR", and I'm not sure what the "1" is after the revision is.</sub></td>
  </tr>
  <tr>
    <td><sub>NTR00001FC2</sub></td>
    <td><sub>NEW_MARIO_A2DP01_00.nds</sub></td>
    <td><sub>A2DP01</sub></td>
    <td><sub>NTR00001FC2</sub></td>
    <td><sub>NEW_MARIO_A2DP01_00_0_00001FC2.nds</sub></td>
    <td><sub>Seems good, except I'm not sure what the "0" is after the revision is.</sub></td>
  </tr>
  <tr>
    <td><sub>TWL40003FC2</sub></td>
    <td><sub>SONICCOLLECT_VSOV8P_00.nds</sub></td>
    <td><sub>VSOV8P</sub></td>
    <td><sub>TWL40003FC2</sub></td>
    <td><sub>SONICCOLLECT_VSOV8P_00_2_40003FC2</sub></td>
    <td><sub>Seems good, except I'm not sure what the "2" is after the revision is.</sub></td>
  </tr>
</tbody>
</table>

Btw, there are two other useful pieces of info that could be put in the filename:
* Date the dump was made (is there a way for GM9 to check that the date is correct?)
* GodMode9 version

**Comment by d0k3** [comment]
Okay, sorry bout the radio silence. "KTR" is the codename for the N3DS ("Kontrolle"). It is only shown for N3DS exclusive carts. "CTR" may be better because that's what Nintendo also uses internally.

The unknown numbers specify the platform (O3DS/N3DS/DS/DSi-enhanced/DSi-exclusive). Could be solved better, I guess.

As I got no way of testing this myself (no carts), I will need some help. Is the extension still visible for all dump names? Got any ideas on how to make the filename format better? Any issues (you can still copy the dumps, right?)?

**Comment by d0k3** [comment]
Okay, here's a new try:
https://f.secretalgorithm.com/l3AfB/godmode9.firm

This includes an .nfo file and reverts the file naming to what it was before. Any additional info (date / GM9 version) can be added later.

Can you try this and tell me what you think?

**Comment by d0k3** [comment]
Alright, I'm assuming this solved. If you're okay with it, you can close this, @mariomadproductions

**Comment by mariomadproductions** [comment]
Yeah, looks like we've ironed out all the bugs in our DMs.
