### ISSUE TITLE
Feature Request: Bootrom/OTP Dumping for People with broken Buttons

### ISSUE THREAD

**Issue by TopKek69420** [d0k3/GodMode9#61]
Pretty much what the title says. I'd like to request a "Dump Bootrom"/"Dump OTP" feature for people who have broken select/start/x buttons, since this seems to be quite a common thing from what I've heard

**Comment by james-d-elliott** [comment]
You can just copy them from mem virtual. boot9.bin, boot11.bin, otp.mem.

**Comment by d0k3** [comment]
Already solved I guess. Also, fix your buttons.
