### ISSUE TITLE
Godmode9 decrypt failure

### ISSUE THREAD

**Issue by thecampinpolice** [d0k3/GodMode9#615]
Hello, I am attempting to decrypt a game cartridge for Pokemon Alpha Sapphire, using GodMode9. 

When I go through the recommended steps to do this, 
(1. Navigate to [C:] GAMECART
2. 3DS Game Cartridge: Press (A) on [TitleID].trim.3ds to select it, then select “NCSD image options…”, then select “Build CIA from file”)

I get a warning immediately that the decryption has failed. 
Godmode9 then asks if I would like to verify the files, I choose yes. The verification completes successfully, but upon attempting to build cia from file again, i get a warning again indicating the decryption has failed.

**Info about your system**
Include this info to make our work easier:
* Console type: N3DS
* Anything special about your console?: No
* Bootloader: boot9strap
* Did you chainload GodMode9 via Luma: Yes
Other information: I am using a 32 Gb SD card that has about 2 Gb of content on it. It is formatted in FAT32.

**Have you actually read this?**
[x] I have read the information above

**Comment by d0k3** [comment]
That's pretty weird. Just to be safe - can you try with a different SD card? It may also be advisable to get that perfect key file (check the readme for a hint).

**Comment by thecampinpolice** [comment]
![image](https://user-images.githubusercontent.com/69011709/88966532-4df84b80-d261-11ea-992a-b0f60d47a6c0.png)

I can certainly try a different SD card. In the meantime, I see in the readme that these files have the file extension .bin, and mine appear to have an additional file extension on them (.here) for some reason. Do you think this would cause any issues?

**Comment by thecampinpolice** [comment]
Your suggestion of changing SD cards did in fact work. I'm not sure what is wrong with the 32 Gb SD, but perhaps it wasn't formatted correctly. In any case, thank you for your help, I appreciate it!

**Comment by d0k3** [comment]
The 3 files you showed me are just place holders. Zero bytes :).

Glad to read it works for you now! SD cards in combination with the 3DS SD hardware cause trouble often.
