### ISSUE TITLE
There needs to be some kind of hardware check in GodMode9!

### ISSUE THREAD

**Issue by derpmaster2** [d0k3/GodMode9#619]
Let me preface this by saying GM9 is one of the most helpful tools for a CFW'd 3DS out there. It was certainly helpful in the predicament I had this morning with my blackscreened old 3DS. But I wish I had been able to check my hardware. Here's why:

I had first thought I had bricked somehow. So I took my old NAND backup to restore it, only to find it was corrupted with the error:

"MBR MBR is corrupted" on "nand_minisize.bin".

I initially panicked, but after digging some more, I found a couple things to try. Reformat the SD card, try booting it with no SD card, try reseating the battery, nothing worked.

And so I tried reseating the WiFi card. Instantly came back to life.

What I am asking for is some kind of "hardware check" in which GodMode9 can check whether the 3DS is ready to boot and all hardware is good (e.g. camera, screens, and WiFi card, which are the only things required to boot other than the motherboard) so that you can rule out it being a hardware issue without taking it apart first.

**Comment by d0k3** [comment]
While I like the idea, this is out of the scope of GodMode9, and would take an immense effort to get to a somewhat working state. We got no baremetal drivers for camera and wifi, for example. Won't be implemented, maybe at a later point in time.
