### ISSUE TITLE
[FEATURE REQUEST] TWL Sound Access

### ISSUE THREAD

**Issue by HTV04** [d0k3/GodMode9#626]
**Got a great idea on how to improve GodMode9?**
I think adding access to the TWL Sound partition on the NAND would be a great addition for GodMode9. Currently, the partition can only be accessed with tools like FBI.

**Describe the feature you'd like**
I would like to be able to access the TWL Sound partition as one of the available drives. There doesn't seem to be a way to mount it manually.

**Describe alternatives you've considered**
I've tried to find a way to mount the TWL Sound partition manually, but there doesn't seem to be a way to do so.

**Comment by aspargas2** [comment]
"TWL Sound" isn't actually its own partition on nand. It's a FAT image in a file at `[2:] SYSNAND` -> `shared2` -> `0000`, and you can mount it in GodMode9 by navigating there and choosing the "Mount as FAT image" option.

**Comment by HTV04** [comment]
No wonder there wasn't any info for the TWL sound partition! I was so confused when I found NAND maps for the 3DS and DSi that only included the main TWL NAND and Photo partitions. Thank you so much!
