### ISSUE TITLE
[FEATURE REQUEST] CIA Editing

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#627]
It would be really nice if GodMode9 could edit CIA files and some other image files. If it can edit System Backups, then why couldn't it edit CIA's?

**Comment by ihaveamac** [comment]
CIA files are read-only and not designed to be modified. If you want to change the contents it has to be extracted and re-built.

**Comment by d0k3** [comment]
Not a possibility here. Imagine how long it would take 3DS hardware to extract and rebuild 1GB of data for every single edit. There are better tools for this out there.

**Comment by dwain12435** [comment]
Well, I know it would be difficult to implement, but it would be more
convenient for me, since I don't have a PC.

**Comment by ihaveamac** [comment]
It's way too difficult to implement for it to be worth it. If you intend to modify the contents of games then Luma3DS LayeredFS would likely work.
