### ISSUE TITLE
[BUG] Can't display properly when scrolling more than the length of the string

### ISSUE THREAD

**Issue by HIDE810** [d0k3/GodMode9#628]
**Description of the bug**
In touchscreen keyboard, scrolling more than the length of the string, the string will not display properly.  
[Video](https://youtu.be/oWv6myxI4JA)

**Info about your system**
* Console type N3DS
* Bootloader fastboot3ds
* GodMode9 v1.9.2pre1 via fastboot3ds

**Have you actually read this?**
[X] I have read the information above

**Comment by d0k3** [comment]
Thanks, great find!

Can you try this test build?
https://f.secretalgorithm.com/14QK4T/godmode9.firm

**Comment by d0k3** [comment]
Thanks a lot (and this quick, too)! And sorry bout the long radio silence.
