### ISSUE TITLE
[FEATURE REQUEST] Keyboard in hex editor

### ISSUE THREAD

**Issue by SirEnder125** [d0k3/GodMode9#629]
**Describe the feature you'd like**
Keyboard in hex editor, because the current value changing method is very difficult to use. please look into adding this.

**Comment by SirEnder125** [comment]
Has this request been acknowledged?

**Comment by d0k3** [comment]
Yup, we've seen it. Still considering it. Problem here: the keyboard only has a limited number of available chars. We can't input the whole range of ASCII symbols with it. Did you think about editing hex values directly? That only makes sense when you edit several values at once.

**Comment by SirEnder125** [comment]
I'm not sure what you mean by editing hex values directly, but I understand how the keyboard would be difficult to do.
Anyway, thanks for answering.

**Comment by d0k3** [comment]
I'll give you an example. The char 'A' has the hex value 0x41. If you edit it, you can either edit the char (problematic, keyboard would need 256 keys), or just edit the hex value.

**Comment by SirEnder125** [comment]
Oh, yeah, I understand now. Thank you.

**Comment by SirEnder125** [comment]
What about a keyboard that only edits the values?
keyboard with (1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F ,G) keys??
Suppose you know that the value needs to be 00 but it's 55
you have to decrease it and it takes time and that adds up when
editing multiple values. but a keyboard that only edits the values
other than the characters, I think would be much better

**Comment by SirEnder125** [comment]
I realize that my pas response may be hard to understand, and or implement.
Have you thought about adding the hex value editor keyboard? (123456789ABCDEF keys only)

**Comment by d0k3** [comment]
I have my doubts that would really be much faster than the current method. It would only be if we'd be able to edit multiple bytes at a time. Also keep in mind, GM9 is not intended for large scale hex editing - there would be several issues with that, starting with limited controls (buttons, touchscreen), limited screens, limited memory and slow read / write operations.

Can you name a use case that would profit from touchscreen controls here?

**Comment by SirEnder125** [comment]
Well, it would be helpful for editing saves faster, and making GM9 scripts without having to take out SD card.

**Comment by d0k3** [comment]
Okay, thought about it. Editing scripts in a hex editor is not a good idea - you'd need a text editor for this (which we don't have, and which is off the table for now). Closing this for now, as there's a lot of other stuff to do. Know that feature requests are always appreciated, even if this one didn't make it into GM9.
