### ISSUE TITLE
How do I dump the bootrom? Im using boot9strap, but dont see any option

### ISSUE THREAD

**Issue by thebeastgamer25** [d0k3/GodMode9#63]

**Comment by leo60228** [comment]
Go to the `M:` drive. You want `boot11.mem`, `boot9.mem`, and maybe `bootrom.mem`. I'm guessing `bootrom.mem` is shared data between the bootroms, but I'm not sure.

**Comment by thebeastgamer25** [comment]
Thanks! Also, why would someone dump it? Just wondering

**Comment by leo60228** [comment]
Dev I guess
