### ISSUE TITLE
[BUG] 1.9.2pre1 can't boot from file in fastboot3ds

### ISSUE THREAD

**Issue by Ammako** [d0k3/GodMode9#630]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
* Give us clear steps to reproduce (when/how did it happen?).
* Give us info about your system (where did it happen?).
* A photograph or even a short video of the bug happening is always helpful!

Booting into fastboot3ds and picking "Boot from file...", and trying to load gm9 1.9.2pre1 that way leads to a black screen. This worked fine with 1.9.1. It works fine if you set it as one of the boot slots.

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS)
* Anything special about your console? (defects, custom modifications,...)
* Bootloader (boot9strap/fastboot3ds)
* Did you chainload GodMode9 via Luma?
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

Original 2DS, fastboot3ds 1.2

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[X] I have read the information above

**Comment by aspargas2** [comment]
This is an issue with the latest fastboot3ds release and has been fixed in fastboot3ds master, but we may have a workaround on our end anyway. Could you try to boot this build with fastboot3ds release? https://cdn.discordapp.com/attachments/424654243199320066/754830433157644369/GodMode9.firm

**Comment by Ammako** [comment]
Yeah, that works

**Comment by aspargas2** [comment]
@Ammako could you try this build as well? https://cdn.discordapp.com/attachments/424654243199320066/758053787389919288/GodMode9.firm

**Comment by d0k3** [comment]
Will stay open until new fb3ds releases, and will be closed then.

**Comment by d0k3** [comment]
@Ammako - does this still happen in v1.9.3pre1?

**Comment by Ammako** [comment]
Seems good here

**Comment by d0k3** [comment]
Issue solved with @Wolfvak's mcuev branch.
