### ISSUE TITLE
[FEATURE REQUEST] Allow escaping of characters in strings in scripts

### ISSUE THREAD

**Issue by GingkathFox** [d0k3/GodMode9#632]
**Describe the feature you'd like**
It would be nice to be able to escape characters like `"` in strings. I thought you could do it, but when i tried i got a error.

**Describe alternatives you've considered**
none

**Comment by aspargas2** [comment]
I assume you mean in scripts. I thought this worked too, but let me test it myself real quick.

**Comment by GingkathFox** [comment]
yeah, apparently it doesnt, kinda sad about that

**Comment by aspargas2** [comment]
Yeah you're right, it doesn't work. Will look into making it work soon.

**Comment by GingkathFox** [comment]
cool :D

**Comment by d0k3** [comment]
@GingkathFox - here's a test build for you:
https://f.secretalgorithm.com/U7h5d/godmode9-v1.9.2pre1-29-g647d5722-20201230110808.zip

Do you think it makes sense to allow escaping of other chars but quotes `\"`)? Also, let me know if this works the way you'd expect it. There's a small sample script included in the VRAM drive.

**Comment by GingkathFox** [comment]
ill test it when i can, im really busy atm

**Comment by GingkathFox** [comment]
Awrighty, i like it :D
