### ISSUE TITLE
Question: What is the 3ds equivalent of std::cin?

### ISSUE THREAD

**Issue by SirEnder125** [d0k3/GodMode9#637]
Hello. I was wondering how to prompt user input with 3ds homebrew? Sorta like std::cin?

Like making the keyboard pop up with a message such as:
> Enter text here: 

--------------------------------
I've seen this in GM9, So I thought you might know.

**Comment by d0k3** [comment]
Not the right place to ask this, but I'll be nice. Look into `ui.c` `ShowPrompt`.

Don't open issues for stuff like this, better ask on Discord or on IRC.
