### ISSUE TITLE
[BUG] GM9 cannot mount my 64GB SDCard

### ISSUE THREAD

**Issue by Lyuu17** [d0k3/GodMode9#638]
**So you want to report a bug?**
* Give a clear description of the bug (what happened?). - I booted into gm9 to open the Scripts but GM9 can't mount my 64gb sdcard
* Give us clear steps to reproduce (when/how did it happen?). - Use a 64gb sdcard
* Give us info about your system (where did it happen?). 
* A photograph or even a short video of the bug happening is always helpful!
![image](https://user-images.githubusercontent.com/14199521/95650997-541f6980-0ae7-11eb-98d4-08e1f85f347b.png)

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS) - New 3DS XL
* Anything special about your console? (defects, custom modifications,...) - No
* Bootloader (boot9strap/fastboot3ds) - boot9strap
* Did you chainload GodMode9 via Luma? - Yes

**Have you actually read this?**
[] I have read the information above

**Comment by d0k3** [comment]
So, does that SD card even work for your console? That means, can you install stuff to it? Does the 3DS OS accept it?

**Comment by Lyuu17** [comment]
yeah, it does, no issues yet

only gm9 can't mount it

**Comment by GingkathFox** [comment]
whats your card manufacturer? i have a 64gb sandisk and it works perfectly

**Comment by Lyuu17** [comment]
i bought it from aliexpress

**Comment by luigoalma** [comment]
> i bought it from aliexpress

aliexpress is one of the places you can easily fall into a fake sdcard. Not saying you can't find real ones too but, chances are you'll hit fakes.
An sdcard can actually have a flash smaller than the size it reports itself to be to the OS or sdcard driver.
3DS's OS can mount these, most of the time, but data corruption is strong after a certain position of writing data, whatever the size of the real flash is.
You should backup all the contents of the card and use tools to test it.
[h2testw](https://3ds.hacks.guide/h2testw-(windows)) if you got windows, [f3](https://3ds.hacks.guide/f3-(linux)) if linux or [f3x](https://3ds.hacks.guide/f3x-(mac)) if you're on mac.
If test gives errors, there's a likelihood that a portion of the backed up contents of the sdcard will be corrupted, depending on how many things you had on the card. You should also be able to know the card's actual size.
If the test is OK then something's up here.
But if your test gives errors, your issue may be just your card.

**Comment by GingkathFox** [comment]
you can also use Disk Utility and test your card there. Its best to buy cards from places like Best Buy or Target, just because something is cheap doesnt mean its *good*.

**Comment by TurdPooCharger** [comment]
@Lyuu17, check if your SD card is fake, faulty, or dying.
1. Copy everything off the SD card to a computer.
2. [Quadruple reformat](https://gbatemp.net/threads/new-2ds-xl-microsd-card-error.534480/#post-8569741).
3. Full Write + Verify the _empty_ card with [H2testw](https://3ds.hacks.guide/h2testw-(windows).html). **Do not skip**.

**Comment by Lyuu17** [comment]
Yeh, it was a fake 64gb card. Only 29.2gb are real, so I made a new partition with parted manually and now I think it works and gm9 seems to mount it

**Comment by d0k3** [comment]
I'm glad you guys solved this. @Lyuu17 - while generally AliExpress is a good place to shop, this doesn't apply to storage memory. I got scammed once with a fake pendrive, too.
