### ISSUE TITLE
[BUG] Godmode9 not starting

### ISSUE THREAD

**Issue by Kjenium** [d0k3/GodMode9#639]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
If i hold start while turning on godmode9 doesn't start and the 3ds doesn't boot up or well sometimes does but it is kind of random
* Give us clear steps to reproduce (when/how did it happen?).
I actually don't know what's the problem.
* Give us info about your system (where did it happen?).
I'm on Luma 10.2
* A photograph or even a short video of the bug happening is always helpful!

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS)
N3DS
* Anything special about your console? (defects, custom modifications,...)
I just have luma 3ds
* Bootloader (boot9strap/fastboot3ds)
Boot9strap
* Did you chainload GodMode9 via Luma?
Yes
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[X] I have read the information above

**Comment by urherenow** [comment]
Add another payload to your luma/payloads folder. Any payload. Even if it's another copy of Godmode9 (with a different name, of course.

**Comment by d0k3** [comment]
Also try using the latest version of GodMode9:
https://github.com/d0k3/GodMode9/releases/tag/v1.9.2pre1

Let us know if anything works for you!

**Comment by d0k3** [comment]
@Kjenium - we need more info, otherwise I have to close this issue.

**Comment by Longestboi** [comment]
I'm having a similar problem to the op. 
When I boot GodMode9 v1.9.2pre1 from sdcard it works wonderfully. However, when I attempt to boot GodMode9 v1.9.2pre1from nand with fastboot3ds GodMode 9 doesn't boot. I've booted GodMode9 v1.9.1 from nand previously with no problems.

**Comment by Wolfvak** [comment]
@Longestboi try this version https://cdn.discordapp.com/attachments/424654243199320066/758053787389919288/GodMode9.firm (linked on issue #630)

**Comment by Longestboi** [comment]
@Wolfvak I actually fixed my problem by compiling a fastboot3ds and flashing that to firm0.

**Comment by d0k3** [comment]
Okay, lack of info from @Kjenium and apparently of #630. Closing this now.
