### ISSUE TITLE
ticket.db Issue

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#641]
The current ticket.db layout makes no sense. The "homebrew" folder contains all illegit CIAs, including pirated games, so it should be named "Illegit". The "eshop" folder should be renamed to "Legit" to match the last suggested change. The "unknown" folder should be deleted and its contents should be placed inside the "Illegit" folder because the contents of the "unknown" folder are never system apps or eShop downloaded apps. Also, the "system" folder should be renamed to "System" because the other ones are capitalized. BTW, the old boot logo looked better.

**Comment by d0k3** [comment]
This makes sense, we'll think about that. Know that this is not actually a new layout, it's the same it was before.

**Comment by d0k3** [comment]
Alright, I changed it. `homebrew` is now `illegit` and contains all tickets with bad signatures. `unknown` stays and contains all verified tickets of unknown category (this will be most likely empty for everyone).
