### ISSUE TITLE
Another ticket.db issue (or maybe a feature request)

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#642]
An option should be added to clean the ticket.db (remove unused tickets). I know that the new GodMode9 version doesn't show these tickets, but they are still there and should be removed. The only way I know of doing this involves using the new GodMode9 version to copy the tickets out of the ticket.db, deleting the ticket.db, wiping the free space on the CTRNAND, booting up the system normally, and then going back to GodMode9 and copying the tickets that were previously copied out of the ticket.db back into the new ticket.db. I really hope that you will add a simpler way to do this.

**Comment by d0k3** [comment]
Won't happen, as this is a 3DS OS thing and not a GM9 thing. When the system "deletes" a ticket it doesn't actually remove the data but instead removes the internal "shortcut" to that ticket. These unused tickets are now no more shown in GM9.

If you want a completely clean system, the NAND transfer may be your best option.

**Comment by aspargas2** [comment]
I think there may be some misunderstanding here. To me, "unused" tickets means tickets that are still in ticket.db like any other ticket (meaning gm9 can detect them just fine), but no title is installed that uses them. I'm not sure what the instructions described in the original post are meant to accomplish. Am I missing something here?
