### ISSUE TITLE
README Issue

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#643]
You really need to update the README. For example, it still says that the ticket.db is read-only, and you really need to be a bit more clear about the brick chance from memory edits. It says that editing the memory isn't very risky, but it can permanently brick your device. It should tell you what not to do to avoid this brick, and it should be more clear about what "permanently" means. Does it mean a brick that can be fixed by ntrboot, a brick that can be fixed by a hardmod, a Gateway-style brick, or a hard brick? There is also other outdated information in the README. Please find it and fix it.

**Comment by GlaZedBelmont** [comment]
>>> There is also other outdated infos
>> Please find them and fix them

How can you infos are outdated if you can't even point them yourself

**Comment by d0k3** [comment]
Ooof. Yes, you could be more specific. You could also fix that stuff yourself and propose a pull request.

As for the memory thing... you can do what you want with 99.99% of all places, without fearing any consequences. The remaining 0.01%? Nope, I don't know all of them. The write protection system protects you here. In short - if you don't have a reason to poke around in memory stuff, maybe just don't do it?
