### ISSUE TITLE
[FEATURE REQUEST]  Updating GM9 on your 3ds

### ISSUE THREAD

**Issue by linusrg1** [d0k3/GodMode9#647]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.
Ability to update GM( from within gm9
**Describe the feature you'd like**
Add a clear and concise description of what you want to happen.
A script that would allow the latest version of GM( to be grabbed from github and installed to your sd card. If it is impossible to get internet access with gm9 then a CIA program instead.
**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.
Grabbing the latest release from github, or using multi-updater.

**Comment by Wolfvak** [comment]
Refer to #240
