### ISSUE TITLE
[FEATURE REQUEST]  A feature that allowes you to compare the hex values of a fully functioning nand vs a corupt one to see what the differences 

### ISSUE THREAD

**Issue by linusrg1** [d0k3/GodMode9#648]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.
 
**Describe the feature you'd like**
Add a clear and concise description of what you want to happen.
A feature that allowes you to compare the hex values of a fully functioning nand vs a corrupt one to see what the differences are and then the files in the corrupt nand are replaced with the good ones. 
**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.
Lazarus, but while this fixed my NDS mode issue I'm faced with the issue of never being able to go stock again if I want to sell my 3ds.

**Comment by Wolfvak** [comment]
There would be many differences between a stock/modded-working NAND image and a broken one, too many to make sense of it. Broken images could arise from anything as simple as a missing file to a corrupted filesystem.

The best we could do is hash certain known regions of two NAND image (header, secret sector, filesystem headers, etc) to tell you which ones are different, but it's impossible to say which one _caused_ a certain issue. From there you'd have to look at the images yourself to notice the differences themselves. This could be done easily with a PC-side script, though.

**Comment by linusrg1** [comment]
Ok. And A side note would it be possible to do what you suggest  to see what prevents dsi mode from working?

**Comment by d0k3** [comment]
Sorry, but I'll have to close this. Comparing large files byte by byte (or region by region) is a job for a desktop PC, as mentioned by @Wolfvak. No one would want to wait for a 3DS to finish the job, and also setting it up with buttons and DPAD would be a nightmare.
