### ISSUE TITLE
[FEATURE REQUEST] Hexeditor Improvement

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#650]
The hexeditor should be able to insert and delete bytes.

**Comment by Wolfvak** [comment]
Can you give a realistic example of where this would be useful? Usually you only need to edit existing bytes, not add/remove them.

**Comment by dwain12435** [comment]
Ummm... Changing "No" to "Yes" in configuration file editing? Just one use
of many...

**Comment by Wolfvak** [comment]
But then what you want isn't a hexeditor but a text editor, and that's outside our (too wide at times) scope.

**Comment by d0k3** [comment]
As much as I'd like a text editor in there, it's simply too complex. A good text editor (even a "raw" one, without fonts and formats support) would very much be it's own software project. As for hexeditor insert/delete - that would require chaning the file size and moving data on the fly, and this would simply be much too slow on hardware like the 3DS. Sorry, but I'll have to close this.
