### ISSUE TITLE
[FEATURE REQUEST] CMAC Fix for Backups

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#653]
CMAC fixes should be an option for the CTRNAND of a mounted NAND backup.

**Comment by d0k3** [comment]
I'll look into that. I somewhat think there's a reason why this doesn't work, but I'm not sure.

**Comment by d0k3** [comment]
Please test the fix! Test build here:
https://f.secretalgorithm.com/ebMaN/godmode9.firm
