### ISSUE TITLE
Source files 

### ISSUE THREAD

**Issue by ash10121** [d0k3/GodMode9#654]
Hello all 
I have only just got into Doing the homebrew on the 2ds xl 

Ian having issues doing the 3ds to cia conversion 

I be live it's 2 files I need in gm9 sources but every were says don't ask go find them ..I have looked high and low could someone just please email them me 

I have 250 3ds games I can't convert 

Kind regards

**Comment by d0k3** [comment]
This is not the right place to ask for this. All the info you need is in the Guide, and for everything else why search machine can help. Sorry but I need to close this.

**Comment by ash10121** [comment]
That's not an issue Yes close it if you wish

But please can you inform me why we can't ask or they can't be shared ..I mean they are out there so why are people all secretive and act as if it's a drug deal



Sent from my Samsung Galaxy S8 - powered by Three



-------- Original message --------

**Comment by d0k3** [comment]
If you really really can't help yourself, try on Discord, GBAtemp, IRC or similar. You'll at least get a helpful hint. Support files like the ones you've searching for are not provided because they may contain copyrighted data.

Btw, if you followed the Guide, you should already have everything you need to start converting. So maybe check there?

**Comment by ash10121** [comment]
I have to say I followed a YouTube video
So yes this is were I could be going wrong

I have issues installing some cia files also sometimes and I beileive it is also to do with these source code

I really really do appreciate ypur replies and as I say am new to this so I was intrigued...and in all honesty is morless everything on here copyrighted ..I mean we not meant to put homebrew on but yet Its all over the next to download ..I was curious

Again thank you and I will do some more searching

My other issue is if I start again I already have c.f. firmware so it would baffle my head were to begin ha ha ha



Sent from my Samsung Galaxy S8 - powered by Three



-------- Original message --------
