### ISSUE TITLE
[FEATURE REQUEST] Separate write protection for MCU registers if this can cause an MCU brick

### ISSUE THREAD

**Issue by flarn2006** [d0k3/GodMode9#655]
**Describe the feature you'd like**
Currently, writing to memory regions has its own write-protect flag. Which makes sense; at the very least, it's possible that one might corrupt the memory of GodMode9 such that it will write to FIRM or something without the unlock sequence. This is something that could potentially happen by accident, so it makes sense to require an unlock sequence, but since it's very unlikely to happen by accident, it doesn't need to be a particularly scary one.

However, there's one, possibly two, files in there which might have the potential to do something even more dangerous, perhaps not unlikely by accident. These files are `M:/mcu_3ds_regs.mem` and possibly `M:/mcu_dsi_regs.mem`. From my understanding, writing bad values to certain MCU registers is what can cause an MCU brick, which not even ntrboot can fix.

I don't know the exact mechanism by which an MCU brick occurs, or what specific writes will cause an MCU brick, but I do know that there's two known causes, both involving code that was meant to do something innocuous. And one of them was written by Nintendo, who knows what all the MCU registers do. Of course, it didn't brick the hardware it was designed to run on, but it does go to show how easily it can probably happen if you don't know what you're doing.

So unless I'm mistaken, I think there should be a warning along these lines when attempting to write to one of the MCU register files:

    Writing to memory (lvl2) is locked!
    Unlock it now?
    
    (<A> yes, <B> no)

and then

    ! THIS IS YOUR ONLY WARNING !
    
    You want to enable memory
    lvl2 writing permissions.
    
    This enables you to write to
    MCU registers, potentially
    causing PERMANENT HARDWARE
    DAMAGE if you're not careful!

    To proceed, enter this:
    <...>

**Describe alternatives you've considered**
Another possibility would simply be to make the memory regions warning sufficiently clear about MCU bricks, but I'm not sure if any other memory regions are likely to cause any damage by accident.

**Comment by Wolfvak** [comment]
Another alternative would be to simply lock out write access and keep it a read-only "drive".

Is there any known use for MCU register writing for a GM9 user? We could make it an "advanced" feature and keep it behind an ifdef.

**Comment by flarn2006** [comment]
Isn't the purpose of GodMode9 supposed to be that it gives you access to everything? Even if there's no known use, someone might find one.

**Comment by Wolfvak** [comment]
That's a good argument but I'd still vouch for keeping it behind a compile time define. It's useless for a regular user, and an advanced user would already know not to do anything weird with it.

**Comment by d0k3** [comment]
I think I agree with @Wolfvak. MCU register writing is something else, guess we can do without that. And for everyone who really needs it, a compile option is more than enough.

**Comment by d0k3** [comment]
I just noticed, writing to MCU registers is not possible. They are write protected with no way of enabling write permissions (the code to write them is not even there)- for good reason as we know. It's understandable you haven't even tried it, though, @flarn2006 .

There was once a special build that allowed writing to these regions, but it's not in master.

So, I guess we can close this.
