### ISSUE TITLE
[FEATURE REQUEST] About the GM9 bootloader.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#656]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.

**Describe the feature you'd like**
I think that you should keep GM9's bootloader feature.

I have read the release notes, but do not have a Discord account, so I cannot post there.

1. It makes the SD card FS much cleaner. You can just keep the "Nintendo 3DS" folder on the SD card and remove everything else.
2. Once installed to FIRM0, it provides emergency access if the payload failed to function, for example, when Nintendo updated the firmware and breaks LUMA, you can still get a functional file manager.

**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.

**Comment by flarn2006** [comment]
About point 2, can't you do that already? Boot9Strap and Fastboot3DS both support configuring the system to boot a different .firm when you hold down a button, and that happens before the main firmware even loads. And even if you don't have that set up, couldn't you just put GodMode9 on the root of the SD card and rename it to boot.firm?

**Comment by urherenow** [comment]
@flarn2006 only with the bootloader version. If you pay attention to release notes and such, you'd see that there is a plan to stop offering the boot loader build.

**Comment by fox8091** [comment]
@urherenow GM9 still boots if you put it as boot.firm, they'd just be removing the ability to install GM9 directly to the FIRM partitions to use as a bootloader afaict.

**Comment by urherenow** [comment]
You still aren't getting it. READ. THE. RELEASE. NOTES.

"For this reason, the GodMode9 bootloader will be removed starting with the next major release. If you feel that decision is not right, you're free to discuss with us."

**Comment by pthfdr-42** [comment]
@flarn2006 Sometimes you cannot easily take the SD card out (New 3DS) or access it (when you are outside and do not have access to a PC or OTG cable).
In these cases, you can still restore to an older system version in GM9 or load an alternative firm file.

**Comment by d0k3** [comment]
"Removing the bootloader" actually only means removing the ability to directly boot into another firm and accessing the boot menu (when installed to FIRM0). You will still be able to install GM9 to FIRM0 and it will run like it booted from anywhere else. For everything else, fb3ds is the far better option. Does that solve it? If so you can close this issue.

**Comment by pthfdr-42** [comment]
>"Removing the bootloader" actually only means removing the ability to directly boot into another firm and accessing the boot menu (when installed to FIRM0).
This is exactly what is needed, and is exactly why I am submitting this issue.

>fb3ds is the far better option
Then you have to load another FIRM and put configs on the SD.

Can you just keep the bootloader as is? (It is already a "pro" feature)

**Comment by fox8091** [comment]
@pthfdr-42 fb3ds can load FIRM files from CTRNAND as well. And the config is made through fb3ds on console? Additionally, anything you chainload from GM9 has to be stored *somewhere*, whether that be SD or CTRNAND, so it's not much different to have GM9 there as well for fb3ds.

**Comment by pthfdr-42** [comment]
@fox8091 Stop recommending fb3ds like you are Lennart Poettering.
fb3ds saves the config on the SD card.
I mean, why you need TWO pieces of software when you could just use ONE? (Especially when the other one adds no actual feature just like PulseAudio)

(Is there any technical issue that marks the bootloader for removal? If not, you can just keep it as is.)

**Comment by d0k3** [comment]
@ptfhdr-42 - I understand the thing about just using one software instead of two.

However, fb3ds is designed as bootloader, not as universal tool. fb3ds update after far less frequent and fb3ds is specifically tested as a bootloader before every release. It contains failsafe and tons of code just for making sure nothing can ever go wrong.

Of course we also test GM9 before every release, and of course we don't know of any issues with the bootloader. No known bricks so far, too. But, keep in mind, GM9 does a lot more, and the focus of testing is never the bootloader.

Also, fb3ds adds stuff and features. It boots faster, it doesn't turn on the screen when it doesn't have to. It allows to set a splash screen and splash duration. It allows you to set custom key combos for FIRMs. And more of course.

The actual reason for us wanting to remove the bootloader stuff is to simplify the code and make messups less likely to happen. It is still up for discussion, of course.

**Comment by pthfdr-42** [comment]
Well, (I hope that) you can just leave the code there.
It works, and some people depends on it (see Pango's removal of bitmap fonts support).
Or at the very least, you can add a compile option.

**Comment by d0k3** [comment]
We'll think about it, alright? Can you describe how Pango's removal method works or give us a link?

**Comment by pthfdr-42** [comment]
[Here is the issue.](https://gitlab.gnome.org/GNOME/pango/-/issues/386)
Basically, Pango removed the support of X11 bitmap fonts, so you can only use TTF/OTF on GTK applications, and some versions later it also makes the system to ignore bitmap fonts completely.

**Comment by d0k3** [comment]
Oh, okay. That was comparison. Got it wrong earlier, thought Pango relied on the GM9 bootloader :^)

**Comment by Wolfvak** [comment]
Continued on https://github.com/d0k3/GodMode9/discussions/660
