### ISSUE TITLE
Feature Request - Fill unused sectors by zero on NAND backup.

### ISSUE THREAD

**Issue by nuimk** [d0k3/GodMode9#66]
As a person who regulary backup the NAND image, I see the size of compressed NAND increase every time the system firmware get updated.

If GodMod9 can detect the unused sectors and replace it with some data that encrypted to all zeroes in NAND. The compressed NAND should be the smallest one.

This should help people who did CTRNAND transfer in the past to get better compression ratio.

**Comment by d0k3** [comment]
Has been thought about, but not possible. Parsing the FAT tables and zeroing out stuff is too dangerous and may lead to data loss (if I do something wrong). Maybe there's a PC tool that can do this on the individual FAT partitions?

Btw, never used, "encrypted" sectors are also all zeroes in NAND. See sectors between 0x00 and 0x96.

**Comment by nuimk** [comment]
As you said, Parsing the FAT tables is too dangerous. After a couple days of thinking, I found another method that work very well and want to share this with you.

Instead of parsing the FAT table. I generate a random 512 bytes file. Then create a new junk file in ctrnand partition, repeatedly fill that junk file with a random 512 bytes until out of space. And remove that junk file.
If we read ctrnand sector by sector, the one that contains random bytes is unused sector. After overwrite that sector by corresponding xorpad, the final encrypted sector will be all zeroes.

So I can do this offline in PC with `3DSFAT16tool` and the final compressed NAND size reduce from 522 MB to 388 MB.

**Comment by d0k3** [comment]
I still don't like putting something like that into GM9 for  what I feel is just a minimal gain. Doing a script that would do this on PC would be nice, tho, I guess.
