### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by cooolgamer** [d0k3/GodMode9#663]
hello, I trying to compile godmode9 and I have this problem:
![image](https://user-images.githubusercontent.com/64099608/102711224-44c35600-42b8-11eb-9585-2cf40ad43092.png)
note that I run cmd on administrator, idk why it say "permission denied"

it's possible to help me?
Thanks.

**Comment by urherenow** [comment]
Move the entire directory to a different drive or at least into its own folder (outside of /Users). You shouldn't be doing things like this in system default paths. Everything from anti-virus to anti-malware, to Windows itself, doesn't like getting spammed with a load of file manipulation in those folders...

**Comment by cooolgamer** [comment]
![image](https://user-images.githubusercontent.com/64099608/102895747-8cd3ab80-4465-11eb-8c81-6b869d706ff4.png)
same error

**Comment by urherenow** [comment]
Does python actually run if you type python3 at the command prompt? (If not, it's not in your path).

What happens if you type "make clean"?

**Comment by cooolgamer** [comment]
run python3 launch the microsoft store IDK why, it's installed and it's on my path and make clean do nothing.

**Comment by cooolgamer** [comment]
OH  I uninstalled python 8 and it work!
