### ISSUE TITLE
compilation error 2

### ISSUE THREAD

**Issue by cooolgamer** [d0k3/GodMode9#664]
hmmm... After compiling, it say me the same thing...
![image](https://user-images.githubusercontent.com/64099608/102899306-00c48280-446b-11eb-8224-4ade5908733a.png)
It don't work...

**Comment by cooolgamer** [comment]
it's when it create a .tar

**Comment by Wolfvak** [comment]
I'm sorry, but your python installation is somehow broken - I've never seen an error like this before. Try reinstalling whatever build system you're using.
Also, please try to merge all your comments into one message, otherwise you're spamming the mailboxes of everyone who watches this repo.

**Comment by cooolgamer** [comment]
![image](https://user-images.githubusercontent.com/64099608/102899491-441ef100-446b-11eb-8e33-19999e23ad86.png)
and this happen when I type python3
