### ISSUE TITLE
GodMode9 ntrboot Issue

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#666]
When GodMode9 is flashed directly to a flashcard and launched via ntrboot, it fails to decrypt the NAND.

**Comment by aspargas2** [comment]
Do you mean it just fails to show CTRNAND, and only on New3DS systems? That's a known issue, and happens because we don't embed the key(Y I think) for New3DS CTRNAND, and it's impossible to get it from somewhere else because it's in process9, which is part of native firm. We've considered embedding this and other keys in the past, but I'm not sure where everyone stands on it right now.

**Comment by urherenow** [comment]
If that's the case, I believe the readme mentions an MD5 for aeskeys.db, which isn't too hard to find anyway. Tells you where to put it as well.

**Comment by Wolfvak** [comment]
This issue really needs more info. What kind of system was this flashed on? Which version of GM9 did you flash, and was it a release build or self compiled? How does it "fail to decrypt the NAND"? Does it just not show the sysnand partitions or does it display an error message?

**Comment by d0k3** [comment]
I think @aspargas2 is right

**Comment by dwain12435** [comment]
This issue was encountered on a New 3DS. I used the GodMode9 v1.9.2
prerelease (precompiled release). I'm pretty sure it coukdn't decrypt
the FIRM partitions either.

**Comment by aspargas2** [comment]
Could you make sure of that please, and be more specific about what the symptoms exactly are of these things you are claiming? If `firm0.bin` and `firm1.bin` are present in `[S:] SYSNAND VIRTUAL` and are recognized as FIRM files, it has decrypted the FIRM partitions. If you're talking about the decrypt option on a New3DS NATIVE_FIRM file, that's a different layer of encryption that may also be broken from this context.

**Comment by dwain12435** [comment]
Never mind, it was just the CTRNAND that failed to encrypt.
