### ISSUE TITLE
(Maybe) Bug in Build CIA (legit) option

### ISSUE THREAD

**Issue by Real96** [d0k3/GodMode9#667]
Don't know if this is wanted but in Title Manager, once you select Build CIA (legit) and choose between legit or not legit option, it will always use the same option if you want to build cia for another game or for the same game, without letting you choosing again. You have to restart Godmode to change your choise.

I'm using build g647d5722

**Comment by d0k3** [comment]
@Real96 - that's the expected behaviour. When you're processing a large list of content to build CIAs, you don't want to be asked every time. You want to leave GodMode9 unattended. So, that was our solution. The wording of the prompt hints at that ('default behaviour')
