### ISSUE TITLE
Cartridge showing issue

### ISSUE THREAD

**Issue by clauz07** [d0k3/GodMode9#668]
I have an european old3ds xl
When i boot up godomode9 it doesn't show the properties of the insterted cartirdge, i need to enter the cartridge partition to see the cartridge's properties

**Comment by Wolfvak** [comment]
Cartridge initialization can take some time and it's annoying to have it happen when the user might not want to waste their time.
You can check this comment for a bit more info https://github.com/d0k3/GodMode9/issues/492#issuecomment-507070479
