### ISSUE TITLE
[FEATURE REQUEST] FTP server in GodMode9

### ISSUE THREAD

**Issue by hifinerd** [d0k3/GodMode9#671]
**Got a great idea on how to improve GodMode9?**
An FTP server that can be run inside GM9 so users don't have to eject and reinsert an SD, which is a pain on New 3ds systems.

**Describe the feature you'd like**
An option in the GM9 Home menu to start and stop an FTP server, and connect to WiFi if necessary.

**Describe alternatives you've considered**
I have considered using apps like FTPD, but it's far too clunky to reboot into Luma3ds, then launch FTPD.

**Comment by fox8091** [comment]
I'm not sure how feasible this is to implement at the moment, as it requires a full bare-metal WiFi stack, something we really don't have at the moment.

**Comment by d0k3** [comment]
As much as I'd like this myself, we will most likely never have a thing such as a reliable wifi driver in baremetal. Wireless file transfer will require the OS.
