### ISSUE TITLE
[help] firm booting code in my own application

### ISSUE THREAD

**Issue by splapoon** [d0k3/GodMode9#673]
do you know any way of booting a firm in c? i've got the BootFirm(()) command sown, it could be helpful if you could help me thanks

**Comment by urherenow** [comment]
GitHub isn't a forum. I would normally tell people to go to gbatemp, but this particular subject is probably better for discord.

**Comment by splapoon** [comment]
oh ok i'll try asking on the Nintendo Homebre Discord. Thanks.
