### ISSUE TITLE
[FEATURE REQUEST] Auto 'yes' on batch .3ds verification

### ISSUE THREAD

**Issue by eyeonus** [d0k3/GodMode9#675]
Please make it possible to automatically attempt fixing 'bad crypto flags' and automatically continue on failed file verification when performing verification on multiple .3ds files.

I just spent I think 6 hours staring at the screen waiting for it to get to the next file so I could push 'a' while doing a verification on 40 titles. Oog.

**Comment by d0k3** [comment]
Doing this is already possible, but you need to select the auto-fix option on the first borked file. I won't remove the prompt, cause actually altering the file may not be what the user wants when all they asked for is a verification.

Try this test build:
https://f.secretalgorithm.com/uIKvN/godmode9.firm

**Comment by eyeonus** [comment]
There's an auto-fix option?

**Comment by d0k3** [comment]
In the test build, yes. That will go into the new release. Could you try it?

**Comment by eyeonus** [comment]
Sure. Give me a sec.

**Comment by eyeonus** [comment]
Well, it seems to work, but could maybe make it 'a' -> this one 'b' -> cancel like previously, and add either 'r'+'a' or 'x' for the yes to all option, rather than the menu?

And maybe add a message like "decrypt flag fix success' on the ETA progress bar hold b to cancel screen if yes to all is chosen, maybe left aligned above the bar if it would fit there? (Just because I don't want to be asked every time doesn't mean I don't want to know. ;) )

I know I'm being nitpicky.

**Comment by eyeonus** [comment]
Unrelated note, the test build also fixed the problem where at startup I'd get just a black screen and I would have to close and reopen the clamshell for the screens to show anything, so props to you.

**Comment by d0k3** [comment]
Well, you know this was basically hacked in after long discussions (cause it's actually a certain emulators' fault these files could become as widespread as they are)? I won't do any big changes to it, but I may think about adding some kind of info to it. Keeping this open for now.

**Comment by eyeonus** [comment]
I was not aware, but I'm glad those discussions resulted in this being a thing that exists.

My nitpicks are for two reasons: adding a new button prompt rather than a menu system is a smaller change from a user standpoint, and for three options, a menu is needlessly time consuming (one button press vs. up to four for the same task).

I'm just happy that you included it *at all*, so don't think I'm going to be all incensed or what-have-you if you don't implement my nitpicks. It's all good, either way.

**Comment by d0k3** [comment]
Alright, thought about it. While this is a valid request, it would take too much work and would be of pretty limited use. GM9 already offers to batch that stuff, it's just _a very little_ inconvenient. Add to that the fact that these fix-needing dumps only exist because someone in the past didn't properly decrypt them and they shouldn't even be floating around.

Closing this now.
