### ISSUE TITLE
[BUG] ntrboot still warns about missing aeskeydb.bin

### ISSUE THREAD

**Issue by gholms** [d0k3/GodMode9#676]
**So you want to report a bug?**
Booting v1.9.3pre1 from a NTR flash cart using still results in the "Not running from a boot9strap compatible entrypoint" warning that recommends providing `aeskeydb.bin` despite that file now being included in the stock build.  After dismissing this warning CTRNAND is readable as expected in this version.

**Info about your system**
Include this info to make our work easier:
* Console type:  N3DS
* Anything special about your console?  Stock, cfw never installed
* Bootloader:  ntr
* Did you chainload GodMode9 via Luma?  No

**Have you actually read this?**
[x] I have read the information above

**Comment by d0k3** [comment]
Good catch, thank you!
