### ISSUE TITLE
[BUG] Any arbitrary script executed from HOME -> Scripts… don't get the same warning as manually executing the .gm9 from the file browser

### ISSUE THREAD

**Issue by raisehero** [d0k3/GodMode9#677]
* Give a clear description of the bug (what happened?). :
Any arbitrary scripts located on /gm9/scripts when executed from HOME -> Scripts… don't get the same warning as manually executing the .gm9 from the file browser, even if said script is on /gm9 scripts. ExecuteGM9Script(loadpath); is called without executing ShowPrompt();
Compare [this](https://github.com/d0k3/GodMode9/blob/ee43fe328f9ed66b68b266a361725f2036a24faf/arm9/source/godmode.c#L2766) with [that](https://github.com/d0k3/GodMode9/blob/ee43fe328f9ed66b68b266a361725f2036a24faf/arm9/source/godmode.c#L2000).
* Give us clear steps to reproduce (when/how did it happen?).
** Execute script from the file browser, warning doesn't appear.
** Execute script from /gm9/scripts, warning appears.
* Give us info about your system (where did it happen?).
GodMode9's HOME menu -> Scripts…
* A photograph or even a short video of the bug happening is always helpful!
Issue/Bug should explain itself, please let me know it isn't clear.

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS)
N3DS
* Anything special about your console? (defects, custom modifications,...)
PSP-1000 C-stick modification
* Bootloader (boot9strap/fastboot3ds)
boot9strap
* Did you chainload GodMode9 via Luma?
Yes
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

Please let me know if it isn't reproduceable under the current conditions. I will try, though it's time intensive.

**Have you actually read this?**
[ x ] I have read the information above

**Comment by d0k3** [comment]
That's correct, cause we assume you are responsible enough to only put trusted scripts there. A warning here would become annoying fast. Also, you still got the file permissions system to protect you.
