### ISSUE TITLE
missing end in clear friendlist script causes lazurus script to run

### ISSUE THREAD

**Issue by MechanicalDragon0687** [d0k3/GodMode9#681]
https://github.com/d0k3/GodMode9/blob/c70a7db0f3a8cfe46aba6674d6a3dc2d414e7a0e/resources/gm9/scripts/GM9Megascript.gm9#L1676

Missing an end statement here, which will cause the script to continue running at line 1712, which is part of the lazurus prep script

**Comment by d0k3** [comment]
Thanks, good catch! Want to do a pull request?

**Comment by d0k3** [comment]
Fixed by yourself in #682, thanks!
