### ISSUE TITLE
[BUG] Unable to install the CIA version of FBI

### ISSUE THREAD

**Issue by TimmSkiller** [d0k3/GodMode9#685]
* What happened?
Trying to install the CIA version of FBI results in an error: "Install failed."

* When/How did it happen?
When selecting the CIA, chosing `Install Game Image...` and confirming the prompts. It loads until 98%, where I assume it's installing the ticket, then proceeds to throw the error.
* Give us info about your system.
Old Nintendo 3DS, running the latest firmware version, using the latest GodMode9 prerelease build.
* Anything special about your console? (defects, custom modifications,...)
No.
* Bootloader (boot9strap/fastboot3ds)
boot9strap v1.3
* Did you chainload GodMode9 via Luma?
No.

* Additional Information
I was able to install the same exact CIA using the homebrew version of FBI without any issues.

**Comment by d0k3** [comment]
Thanks for this one @TimmSkiller ! It will work now in all cases.
