### ISSUE TITLE
[FEATURE REQUEST] Support for decrypting dev CIA files

### ISSUE THREAD

**Issue by ccdffddfddfdsfedeee** [d0k3/GodMode9#688]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.

**Describe the feature you'd like**
Is it possible to decrypt dev CIA files? It says failed every time, and it still does not work with aeskeydb.bin.

**Describe alternatives you've considered**
A computer works, but it takes a long time.

**Comment by d0k3** [comment]
That should already work, even without an aeskeydb.bin file. Can you add some info? What exactly did you try to decrypt and what was the output?

**Comment by ccdffddfddfdsfedeee** [comment]
Screenshots of the errors:
![snap_210327151334](https://user-images.githubusercontent.com/61155247/112732906-2ef6aa00-8f13-11eb-9512-5617069fc1be.png)
![snap_210327151026](https://user-images.githubusercontent.com/61155247/112732918-36b64e80-8f13-11eb-8282-3aec4c239ca6.png)

**Comment by d0k3** [comment]
Alright thanks. First of all, this doesn't look like a dev CIA, but rather like a system CIA. Is that what you meant?

**Comment by d0k3** [comment]
The second screenshot - that didn't happen right after the failed decryption, right? I'd assume it could happen after mounting an incorrectly decrypted CIA.

**Comment by ccdffddfddfdsfedeee** [comment]
The CIA is a dev encrypted system CIA, and the second screenshot is the same CIA as the first one

**Comment by d0k3** [comment]
Alright, can you contact me via some other means? Maybe via the official GM9 Discord or via Telegram (@d0k3_homebrew_legend). I may need some additional data from you.

**Comment by ccdffddfddfdsfedeee** [comment]
I do not have accounts for those

**Comment by d0k3** [comment]
Okay, I guess I know what's going wrong there. Decrypting this will work on a dev 3DS, but I'm strongly assuming you got none. One issue here is, there's no way to tell apart retail NCCHs from dev NCCHs, apart from trying to decrypt (and failing). The other issue is that a retail 3DS simply does not have dev keys.

There is a workaround, though. You could create an `aeskeydb.bin` file that replaces your retail NCCH keys with dev ones. As far as I know, someone already did this in the past. If you need help with this, you can ask on the IRC channel GodMode9 on Freenode.

**Comment by d0k3** [comment]
Alright, closing this now, because adding this feature wouldn't benefit most users, while it would be a lot of work to implement (and still wouldn't be convenient for the users).

Apart from the workaround I mentioned, GodMode9 will only handle the data belonging to the systems type (retail/dev). It's better to decrypt dev data on a PC.
