### ISSUE TITLE
[FEATURE REQUEST] Use .cci extension instead of .3ds for cart dumps

### ISSUE THREAD

**Issue by flarn2006** [d0k3/GodMode9#689]
This is a very minor detail, but when you open a gamecart and have the virtual file with the cart image, I think it would make more sense for its extension to be CCI, not 3DS. CCI (CTR Cartridge Image) is the "official" extension for cartridge ROM's. To my knowledge, about the only thing anyone uses cartridge files for these days is Citra, which registers the CCI extension as well as 3DS. Gateway might not support it (maybe it does) but I'd be surprised if anyone still uses that, unless they simply never bothered to update anything, in which case they wouldn't be using Godmode9, and if someone really is they can just rename it. The 3DS extension also has a practical disadvantage in that it's already taken by Autodesk 3DS Max.

**Comment by d0k3** [comment]
I actually agree, but .3DS is a common and recognized extension by now and changing it now may confuse users. I'd like more opinions on that.

**Comment by KookiesGH** [comment]
I already gave a thumbs up for this, but I think it could be beneficial for uniformity; CXI is the executable format of choice for dumped titles, and CCI for dumped cartridges. True, .3ds is already the widely known extension for cartridges, but it doesn't really represent the data you're working with: a file with a .cxi extension is definitely executable image from a Nintendo 3DS, and a .3ds file could be more generic. This is, however, a minor nitpick, so take it with a grain of salt.

**Comment by malvarenga123** [comment]
I think it's too late to change it now. Most users will expect a .3DS file.

**Comment by d0k3** [comment]
Alright, while I generally agree with this, there doesn't seem to be too much interest in this topic. As changing this now will most likely lead to a lot of confused users, while having little benefit, I'll be closing this now.

**Comment by flarn2006** [comment]
Fair enough.
