### ISSUE TITLE
Feature Request: Make Godmode9 have EmuNAND9 Capabilities

### ISSUE THREAD

**Issue by kamenrider-darkglass** [d0k3/GodMode9#69]
I'm unsure of where to post feature requests so I decided to post it here in the issues section. Hope you don't mind. 

Anyway, ever since boot9strap replaced a9lh, all previous .bin payloads became obsolete; including the beloved EmuNAND9. What makes it special over Godmode9 is that it can format SD cards to have GW compatible EmuNAND in addition to RedNAND, which became mainstream because of how much space it saves over the former. The ability to format SD cards to either GW compatible NANDs or RedNANDS as well as being able to convert one into the other made EmuNAND9 very versatile in making EmuNANDs over Godmode9. 

Godmode9 is unfortunately very lacking when it comes to formatting emuNANDS, especially when it comes to userfriendliness as well as attempting to make GW compatible EmuNANDs. EmuNAND9 is unfortunately discontinued, which is why I am making this request.

I want the ability to use a Gateway Card in ADDITION to playing games on Luma CFW. Advantages of a Gateway + Luma combo include:

-Extra Games to play without sacrificing space on the micro SD card for Luma (This includes the 300 titles limit)
-Ease of removing it to add games VS struggling to remove micro SD from console for Luma by removing the back-plate.
-Gateway-exclusive features such as cheats 

Please consider adding the ability to make GW-Compatible NANDs to Godmode9's next update. Also, if making a GW-compatible NAND already exists, please tell me how to make an optimal one. I don't know what the legacy option does for Godmode9.

**Comment by james-d-elliott** [comment]
Couldn't you just build the firm version of emunand9 with firmtool?

**Comment by mariogamer2** [comment]
@james-d-elliott It could be as simple as this... But I don't know if yoyu must modify something in the code and/or command.

**Comment by d0k3** [comment]
Building the firm version works. Also, as much as I dislike adding in anymore GW compatibility fixes to my tools, @kamenrider-darkglass, you got a point here. I'll look into it.

**Comment by d0k3** [comment]
@kamenrider-darkglass - please test these new changes and give me feedback.
