### ISSUE TITLE
[BUG] GodMode9 crashes upon accessing 512 byte EEPROM saves from NTR/TWL carts from the gamecart drive

### ISSUE THREAD

**Issue by enderghast13** [d0k3/GodMode9#690]
GodMode9 2.0.0 will crash immediately upon pressing the A button while selecting the save file of a DS/i gamecart if the cartridge uses a 512 byte EEPROM chip for saving. This happens before the menu pops up with options for viewing the file in the hex editor, etc. It is still possible to copy the file to another directory, and viewing it shows no visible errors in dumping and does not crash GodMode9. These save types still work fine in GodMode9 1.9.1, and I have not tried any versions between these two. I don't have any 3DS cartridges with 512 byte EEPROM chips to test (if any were made). I am using an O3DS and booting with fastboot3ds 1.2.

Garfield's Fun Fest (USA) (the game hasn't been played and the save has not been written):
```
Exception: Prefetch Abort (3)
GodMode9 v2.0.0
2021-03-25 22:41:03
 
R00: 00000001 | R01: 20129378
R02: 00020000 | R03: 00000000
R04: FFFFFFFF | R05: FFFFFFFF
R06: FFFFFFFF | R07: FFFFFFFF
R08: 00000001 | R09: 01FFF470
R10: 0003BEEF | R11: 0000DC00
R12: 00000000 | R13: 227EFA28
R14: 0803AD15 | R15: 00000000
CPSR: 200000FF

Stack:
227EFA20: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
227EFA30: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
227EFA40: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
227EFA50: 64 C6 04 08 0F 0F 0F 0F 08 10 00 20 00 00 00 00 
227EFA60: 01 00 00 00 02 10 00 00 50 13 00 20 03 00 00 00 
227EFA70: FF FF FF FF 48 03 00 00 01 00 00 00 00 00 00 00 
227EFA80: 00 02 00 00 2F 00 00 00 3A 00 00 00 C8 FA 7E 22 
227EFA90: 1F 00 00 00 0F 0F 0F 0F 00 00 00 00 0F 0F 0F 0F
```

de Blob 2 (USA) (DSi Enhanced):
```
Exception: Prefetch Abort (3)
GodMode9 v2.0.0
2021-03-25 22:36:09
 
R00: 00000001 | R01: 20129378
R02: 00020000 | R03: 00000000
R04: 00000000 | R05: 00000000
R06: 00000060 | R07: 00000401
R08: 00000001 | R09: 01FFF470
R10: 0003BEEF | R11: 0000DC00
R12: 00000000 | R13: 227EFA28
R14: 0803AD15 | R15: 000003A0
CPSR: 200000FF

Stack:
227EFA20: 01 04 00 00 A1 03 00 00 00 00 00 00 00 00 00 00 
227EFA30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
227EFA40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
227EFA50: 64 C6 04 08 0F 0F 0F 0F 08 10 00 20 00 00 00 00 
227EFA60: 01 00 00 00 02 10 00 00 50 13 00 20 03 00 00 00 
227EFA70: FF FF FF FF 48 03 00 00 01 00 00 00 00 00 00 00 
227EFA80: 00 02 00 00 2F 00 00 00 3A 00 00 00 C8 FA 7E 22 
227EFA90: 1F 00 00 00 0F 0F 0F 0F 00 00 00 00 0F 0F 0F 0F 
```

Foto Showdown (USA) (DSi Exclusive):
```
Exception: Prefetch Abort (3)
GodMode9 v2.0.0
2021-03-25 22:26:48
 
R00: 00000001 | R01: 20129378
R02: 00020000 | R03: 00000000
R04: 4F713A2F | R05: 2613E95F
R06: 7569C709 | R07: 0B7CDCAE
R08: 00000001 | R09: 01FFF470
R10: 0003BEEF | R11: 0000DC00
R12: 00000000 | R13: 227EFA28
R14: 0803AD15 | R15: EBBC99E0
CPSR: 200000DF

Stack:
227EFA20: AE DC 7C 0B E2 99 BC EB B4 2B 9B FB 66 CF F1 6D 
227EFA30: BA 4E A8 3E 58 BD 44 6C F8 4C 41 BB 8F 6E 1A B0 
227EFA40: 2E E0 B6 1D C8 E7 EA D4 D6 A5 28 54 38 47 4D 90 
227EFA50: 64 C6 04 08 0F 0F 0F 0F 08 10 00 20 00 00 00 00 
227EFA60: 01 00 00 00 02 10 00 00 50 13 00 20 03 00 00 00 
227EFA70: FF FF FF FF 48 03 00 00 01 00 00 00 00 00 00 00 
227EFA80: 00 02 00 00 2F 00 00 00 3A 00 00 00 C8 FA 7E 22 
227EFA90: 1F 00 00 00 0F 0F 0F 0F 00 00 00 00 0F 0F 0F 0F 
```

[X] I have read the information above

**Comment by d0k3** [comment]
That shouldn't happen. Thanks for posting the crash report! @dratini0 - got any idea what happens here?

**Comment by dratini0** [comment]
Well, this was fun - turns out there was a bug in the function reading the 512B flash chips, and some changes around the title display exposed it. Thank you for the detailed bug report!

**Comment by enderghast13** [comment]
> 
> 
> Well, this was fun - turns out there was a bug in the function reading the 512B flash chips, and some changes around the title display exposed it. Thank you for the detailed bug report!

I just tried out the commit and it seems to work fine now. Thank you!

**Comment by dratini0** [comment]
That's good to hear! On a second thought, I should probably have asked you to try it out before confidently asserting that is was fixed, but at least I was right!
