### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by ryuto2** [d0k3/GodMode9#693]
When I converted it to CIA and gave it to another person, the person who installed CIA got an error and the data disappeared. Fix Please(Japanese)

**Comment by urherenow** [comment]
Converted what? If you made a legit .cia from something you bought in the eshop, it would have a ticket with your console's information and would not install on another one.

It depends what you made into a .cia, and which options you used when you created it.

**Comment by Wolfvak** [comment]
Hi, would you mind editing your title to be a bit more descriptive? Also, please know we don't support nor encourage piracy, so we can't really help you share your personal backups with other people. However, it'd be interesting to know _exactly_ how this was dumped and what error the other person is getting.

Overall, it needs more info to be fixable.

**Comment by d0k3** [comment]
@ryuto2 - there's no way we could help you or fix anything with the current info provided. You need to tell us, how you created the CIA and from what, and the exact error the other 3DS got.

**Comment by d0k3** [comment]
Alright, a week has gone by, and this bug report does not contain anywhere near enough info to do anything about it. @ryuto2 - if you can add any more info, feel free to continue writing here, we will get notified. For now, I'll close this bug report for lack of info.
