### ISSUE TITLE
[BUG] ...This system is missing one or more.db files .

### ISSUE THREAD

**Issue by sthetix** [d0k3/GodMode9#694]
So I tried to replace the 3ds.hacks.guide finalizing setup just by using Godmode9 to install all the cia files. But Godmode9 won't let me do it unless we have installed any title with FBI. 

When I tried to install any of the essential apps (FBI / anemone/ dsp1, etc), Godmode9 will show you an error notification 

Install error : 
This system is missing one or more .db files
Maybe the SD card is missing or Unintialized ?

![image](https://user-images.githubusercontent.com/22261135/112969272-4a61ef00-9177-11eb-988b-083bedc4f5cc.png)

This happens on my 2DSXL with Luma3DS 10.2.1

Is this a bug or it is intended to be like that? Thanks

**Comment by TimmSkiller** [comment]
There is no title database (which is required to install anything). If `sd:/Nintendo 3DS/{ID0}/{ID1}/db/title.db` doesn't exist, you will get this error. The reason that running FBI fixed this issue is because if FBI detects that this is missing, it will create it.

**Comment by TimmSkiller** [comment]
https://www.3dbrew.org/wiki/Title_Database

**Comment by sthetix** [comment]
Thanks!

**Comment by sthetix** [comment]
I tried to copy - paste the dbs folder from the ctrnand to the sd card and it worked.

**Comment by TimmSkiller** [comment]
That may work, however, that does not mean that you should do it.

**Comment by sthetix** [comment]
My bad, it didn't work. I couldnt install it. So i guess, we do need FBI. Thanks for the help.

**Comment by d0k3** [comment]
Am I assuming right this was on a new, never before run 3DS system? There's a pretty easy solution for that: Copy the missing .db files from a system that has them. Preferably a system that's also freshly installed. You can also reuse these files over multiple systems.

**Comment by sthetix** [comment]
Yes, I assume it is new. I copied the title.db and import.db from other system, but it didn't work. 

So what I did is open the system settings, go to Data Management, and then the console  rebuilt the database. And after that, we can install all the cia files from godmode9.

But, from what you said, it seems that there is a way to get a "universal" database file?

**Comment by aspargas2** [comment]
As d0k3 said, copying blank .db files from another system does work, you just need to make sure you copy them such that the SD encryption is accounted for (copying them to and from the A: virtual drive in gm9 will do this), and fix their CMACs after you place them on the new system. Also, I should mention that it would be possible to just implement code in gm9 to generate these .db files from scratch, and it is something I plan on eventually trying to do.

**Comment by sthetix** [comment]
Thanks a bunch!. It worked!. .Yes, I hope there will be a script to do get the task easier.

**Comment by cooolgamer** [comment]
To solve the issue: just install any cia file using fbi or other cia installer.
That's all

**Comment by MAK-THIRTHEEN** [comment]
Hello, can you send me the file title.db
