### ISSUE TITLE
Dumping ctrnand_full.bin produces garbage on n3DS....

### ISSUE THREAD

**Issue by ApacheThunder** [d0k3/GodMode9#70]
I have tried dumping/decrypting my CTR_NAND partition using the ctrnand_full option. (as I need the decrypted MBR table too for something I'm testing)

However it is currently only producing garbage data as I can plainly see in my hex editor:

![image](https://cloud.githubusercontent.com/assets/11767416/26430469/fc1de1f0-40b2-11e7-8a0b-754c380f07b3.png)

Not tested this with o3DS since I do not own one, but this looks to be broken on n3DS right now....

I will be trying the xorpad generator instead until this is resolved. :P

**Comment by ApacheThunder** [comment]
After further investigation it seems to produce valid nand dumps but the unused regions at the start is filled with garbage so while ugly it doesn't break anything....Still though this should be something to look into?

**Comment by d0k3** [comment]
As I already said, this is the proper way of decrypting this area, and that garbage is exactly what is in that sector.
