### ISSUE TITLE
[BUG] GodMode9 (v2.0.0) doesn't boot in O3DS

### ISSUE THREAD

**Issue by leoisnothere** [d0k3/GodMode9#701]
* Give a clear description of the bug (what happened?): My O3DS doesn't boot GodMode9 (v2.0.0)
* Give us clear steps to reproduce (when/how did it happen?): I only pressed the start button and then I pressed power, the screen shows GodMode9 but it doesn't boot

**Info about your system**
Include this info to make our work easier:
* Console type: O3DS
* Anything special about your console?: Nothing, is 100% original
* Bootloader: boot9strap
* Did you chainload GodMode9 via Luma?: Yes, and it doesn't boot
* I followed the guide and I use luna and boot9strap

My SD card is alright, I tested it

**Have you actually read this?**
[√] I have read the information above
 
Here's a photo of the issue.
![16183143080231181026415655978652](https://user-images.githubusercontent.com/82447759/114547260-3795f280-9c2c-11eb-900e-44906fe7b864.jpg)

**Comment by d0k3** [comment]
@leoisnothere - here's a test build for you:
https://f.secretalgorithm.com/lVxxY/godmode9.firm

Just continue using the A button, until you get no new messages. Tell us what's the last message you've seen.

**Comment by d0k3** [comment]
Alright, I'll assume @leoisnothere got this sorted out. As this is the only bug report of that sort, I'll close this. Feel free to reopen or continue commenting if the issue persists.
