### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Walvire** [d0k3/GodMode9#71]
I only have access to Homebrew trying to get CFW thu A9LH. I would also like to create a NAND.bin backup before I do it. I downloaded the GodMode9.3dsx and GodMode9.smdh files and extracted them into the 3ds folder. I've tried this several times and have not been able to get GodMode9 to work though Homebrew. Any suggestions?

**Comment by FenrirWolf** [comment]
Use the .bin version and boot it with safehax.

Also, don't get a9lh since that's outdated now.

**Comment by d0k3** [comment]
This is Github issues, not a place for support. Issue titles like "Question" help no one. Also, do what @FenrirWolf said.
