### ISSUE TITLE
Add support for 128 GB micro SD Cards?

### ISSUE THREAD

**Issue by Awesome-neos145** [d0k3/GodMode9#711]
Launching GodMode9 on my New 2DS XL, The card doesn't appear. (Though it works on 3DS Homebrew, Games, And even the home menu). I tried reloading it, but it said: "Initialising SD card failed! Retry?". Maybe add support for 128 gigabyte cards?

**Comment by TimmSkiller** [comment]
I'm using a 128GB card and have not come across this issue

**Comment by Awesome-neos145** [comment]
> 
> 
> I'm using a 128GB card and have not come across this issue

Could it be a System Specific thing?

**Comment by d0k3** [comment]
It could be an SD card specific thing. Or, the card reader in your 3DS is acting up. Do other SD cards work in GM9, on this 3DS console?

**Comment by Awesome-neos145** [comment]
> It could be an SD card specific thing. Or, the card reader in your 3DS is acting up. Do other SD cards work in GM9, on this 3DS console?

It could be due to the fact that's it is an XC instead of a HC. And yes. My 16 GB card does work with it. My 16 GB card is an HC, and my 128 GB Card is an XC.

**Comment by d0k3** [comment]
I'm pretty sure, all SD cards 128Gb and up are XC cards. Can you give use mroe info? What did you use to format it, what brand is it?

**Comment by Awesome-neos145** [comment]
I used the HP USB Disk format tool to format it to FAT32, and the brand is Sandisk.
