### ISSUE TITLE
[BUG] CIA build failed

### ISSUE THREAD

**Issue by yxzsya** [d0k3/GodMode9#712]
* Give a clear description of the bug (what happened?). 
CIA build failed when I tried to build a CIA from my Pokemon Ultra Moon cartridge
* Give us clear steps to reproduce (when/how did it happen?).
I selected "Build CIA from file" in the NCSD image options 

* Console type (O3DS/N3DS)
N3DS
* Anything special about your console? (defects, custom modifications,...)
No
* Bootloader (boot9strap/fastboot3ds)
boot9strap
* Did you chainload GodMode9 via Luma?
yes

**Comment by d0k3** [comment]
Maybe SD card full or SD failure? Try with a different SD card and make sure there's enough space.

**Comment by d0k3** [comment]
We need more info to be able to solve this. In general, building CIAs from carts, even large ones like Pokemon Ultra, works. Closing this for now, feel free to add some more info if you can!
