### ISSUE TITLE
Godmode9 thinks down on dpad is constantly pressed

### ISSUE THREAD

**Issue by uzitalo** [d0k3/GodMode9#713]
Whenever i open godmode9 i cannot choose any options because the down on the dpad seems to be pressed causing the choices to move down all the time. It seems this issue is only in godmode9 because in Luma3DS chainloader i can freely press up or down to choose between differnet versions of godmode9 (i tried a few older versions to see if they worked, sadly no :( )

I have an O3DS, all buttons works fine in different games and so on.

I know that you could remap the downbutton to lets say the 'y' button instead but i dont understand how to recompile the firmware with this change :(

**Comment by d0k3** [comment]
I may be able to help you later with a custom build. Just so you know, if the button does not work in GM9, there's trouble with it. It may still work for games, but later failure is likely, and there may be some issues you're not noticing yet.

**Comment by uzitalo** [comment]
Well, so today i finally took my time and completely disassembled the O3DS, cleaned everything that has to do with dpad and thumbstick... and now it works perfectly with godmode9... so i guess the issue after all my troubleshooting still was some rubbish in the dpad or thumbstick... thanx for the reply and the option of a custom build but like you said @d0k3 a later failure will probably happen... so either clean your dpads or hand it over to someone that can do it for you... i used this guide... https://www.ifixit.com/Guide/Nintendo+3DS+Circle+Pad+Replacement/6064

**Comment by d0k3** [comment]
Good to know! And, well, 3DS consoles break, they're nto built as well as an original DMG Gameboy. So far I had a shoulder button and the volume slider break on mine.
