### ISSUE TITLE
Quick question...

### ISSUE THREAD

**Issue by AbnormalPoof** [d0k3/GodMode9#714]
Which file in the source code houses the button mapping? I wanna compile my own build because my R button is broken.

**Comment by d0k3** [comment]
Wrong place to ask this. Try the GitHub search, ask here on Discussions or ask on the GM9 Discord next time.

What you're searching for is here:
https://github.com/d0k3/GodMode9/blob/master/common/hid_map.h

**Comment by AbnormalPoof** [comment]
Ah, my bad.
Thanks
