### ISSUE TITLE
[BUG] Crash when showing actions for 512-byte DS saves

### ISSUE THREAD

**Issue by SNBeast** [d0k3/GodMode9#715]
[deleted for brevity]

**Have you actually read this?**
[x] I have read the information above

The issue:
Upon the selection of the save for a DS game wiith a 512-byte save, an exception will occur.
[This](https://github.com/d0k3/GodMode9/files/6745189/exception_dump_210630194835.txt) is a dump of one such exception, and [this](https://github.com/d0k3/GodMode9/files/6745212/LEGOHP2_B83EWR_00.txt) is the info GM9 generates about one of the afflicted games.

Console Type: n3DS
Special Things About Console: none
Bootloader: boot9strap
Chainloader: Luma3DS

Steps to reproduce:
Step 1: Insert a DS game that has the same 512-byte save type. (A few of these games include Spanish for Everyone! and both Lego Harry Potter)
Step 2: Navigate to the DS game's virtual path.
Step 3: Press A.

Additional Note: GodMode9i dumps these saves correctly as far as I can tell.

**Comment by lifehackerhansol** [comment]
Duplicate of https://github.com/d0k3/GodMode9/issues/690?

It was fixed in the nightly on said issue.

**Comment by SNBeast** [comment]
Oh. Whoops. I didn't remove the is:open search filter so I didn't see that.
