### ISSUE TITLE
[FEATURE REQUEST] Give the option to dump NDS files for DSiWare titles in title manager

### ISSUE THREAD

**Issue by kyoforkshomebrews** [d0k3/GodMode9#720]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.

When selecting a .tmd file on TWLN it lets you dump it as nds, but in title manager it only shows the option to dump as .CIA

**Describe the feature you'd like**
Add a clear and concise description of what you want to happen.

Basically I want that same option available on .tmd DSiWare files also be available on them in the title manager.

**Describe alternatives you've considered**
Add a clear and concise description of any solutions or features you've considered.

Well, alternatively you can search the TWLN for .tmd files and select to dump .nds there.

**Comment by d0k3** [comment]
Can you try with this test build?

[GodMode9.zip](https://github.com/d0k3/GodMode9/files/6835961/GodMode9.zip)

**Comment by kyoforkshomebrews** [comment]
I tried it, it gives the option but it says "CXI build failed" when I select it.

**Comment by d0k3** [comment]
Sorry, I didn't pay attention. And you were much too quick in testing this :) (thanks for that!).

This one should work:
[GodMode9.zip](https://github.com/d0k3/GodMode9/files/6835983/GodMode9.zip)

**Comment by kyoforkshomebrews** [comment]
Yep, this works! Thanks for the awesome work :+1:
