### ISSUE TITLE
Dsi binaries are missing

### ISSUE THREAD

**Issue by jorshock** [d0k3/GodMode9#730]
Hi, lately I am having a crash when launching pokémon white, black, white 2 and black 2.
When executing it either by twilight menu ++ or by forwarders it tells me that the dsi binaries are missing, if I run it in ds mode the game takes too long to load and then it is unplayable, this did not happen to me for a long time but suddenly from one day to the next I happens, if I patch the rom, I don't get the error but it is still very slow. Maybe it's a gm9 or nds-bootstrap bug? I have no idea but I hope they fix it soon.
Thanks.

**Comment by lifehackerhansol** [comment]
If dumping your cartridge does not produce DSi binaries, then that would imply your cartridge is either breaking down or you don't have a legitimate cart. Also, nds-bootstrap does not check this, TWiLight Menu++ does.

If you can, you should plug in your game cart, select the _full_ dump (not the trim one!), calculate the SHA256, and share, so we can compare the hashes and send the hash data here.

**Comment by jorshock** [comment]
Yes but if I try to play it in forwarders and not twilight menu ++ it happens more of the same

**Comment by lifehackerhansol** [comment]
Not sure if you understood what I said earlier. I am trying to rule out the cartridge itself as the issue. Hence I asked for a hash check of your Slot-1 game cartridge that you dumped the ROM from.

**Comment by jorshock** [comment]
And how do I do that?😅

**Comment by lifehackerhansol** [comment]
I already explained in my first message.

**Comment by d0k3** [comment]
I suspect this is not a GM9 issue. @jorshock - could you try to copy the .nds file (the full one, not the trimmed one) from the cart? It's in the C: drive in GM9. After you've done so, calculate the SHA256 (press A on the file, it's in the menu).

**Comment by DeadSkullzJr** [comment]
Just throwing this clarification out there given I actually own these titles and dumped them personally. The DSi binary data is stored in the ROM image itself, it has to have that data in order to even have a functional DSi Enhanced mode. I have dumped these titles using GodMode9 in the past and of course they turned out to be matching with verified checksum data online.

The only way this can occur is if the following is happening:
1. You are using a bad dump, which this can only occur one of two ways, you either used a very old build of GodMode9**i** (not to be confused with GodMode9) to dump your copy of the game, which at the time did produce bad dumps of these titles, or you straight up went on the internet and downloaded a dump (which support can't really be provided for that given well, it's a bad dump from the internet, it's not exactly the fault of either side of developers for this via their software).
2. The dump is modified in some way, reason being I say this is because nearly all existing ROM editing related tools online literally destroy DSi related data given the tools were not geared for DSi related data in general, only NDS related data.
3. You may be using an old version of TWiLightMenu, some versions did have similar quirks like this in the past, double check to make sure you are running the latest.

**Comment by atomic410** [comment]
> Just throwing this clarification out there given I actually own these titles and dumped them personally. The DSi binary data is stored in the ROM image itself, it has to have that data in order to even have a functional DSi Enhanced mode. I have dumped these titles using GodMode9 in the past and of course they turned out to be matching with verified checksum data online.
> 
> The only way this can occur is if the following is happening:
> 
> 1. You are using a bad dump, which this can only occur one of two ways, you either used a very old build of GodMode9**i** (not to be confused with GodMode9) to dump your copy of the game, which at the time did produce bad dumps of these titles, or you straight up went on the internet and downloaded a dump (which support can't really be provided for that given well, it's a bad dump from the internet, it's not exactly the fault of either side of developers for this via their software).
> 2. The dump is modified in some way, reason being I say this is because nearly all existing ROM editing related tools online literally destroy DSi related data given the tools were not geared for DSi related data in general, only NDS related data.
> 3. You may be using an old version of TWiLightMenu, some versions did have similar quirks like this in the past, double check to make sure you are running the latest.

Hello, i wanted to know, where do you think a clean rom vould be found for those who cant dump the cartridge, i have also been having this problem and they are hard to find if you didnt originaly own them. Or would it be possible for you to upload your dumped copy of pokemon black/white. Since i believe it may be what you said but i have not found a rom with dsi binaries i could use. Thank you in advance and please try seeing if you can upload your roms. Have a good day

**Comment by DeadSkullzJr** [comment]
> > Just throwing this clarification out there given I actually own these titles and dumped them personally. The DSi binary data is stored in the ROM image itself, it has to have that data in order to even have a functional DSi Enhanced mode. I have dumped these titles using GodMode9 in the past and of course they turned out to be matching with verified checksum data online.
> > The only way this can occur is if the following is happening:
> > 
> > 1. You are using a bad dump, which this can only occur one of two ways, you either used a very old build of GodMode9**i** (not to be confused with GodMode9) to dump your copy of the game, which at the time did produce bad dumps of these titles, or you straight up went on the internet and downloaded a dump (which support can't really be provided for that given well, it's a bad dump from the internet, it's not exactly the fault of either side of developers for this via their software).
> > 2. The dump is modified in some way, reason being I say this is because nearly all existing ROM editing related tools online literally destroy DSi related data given the tools were not geared for DSi related data in general, only NDS related data.
> > 3. You may be using an old version of TWiLightMenu, some versions did have similar quirks like this in the past, double check to make sure you are running the latest.
> 
> Hello, i wanted to know, where do you think a clean rom vould be found for those who cant dump the cartridge, i have also been having this problem and they are hard to find if you didnt originaly own them. Or would it be possible for you to upload your dumped copy of pokemon black/white. Since i believe it may be what you said but i have not found a rom with dsi binaries i could use. Thank you in advance and please try seeing if you can upload your roms. Have a good day

Uh, not supposed to ask or host ROMs on this platform, it's illegal.

**Comment by atomic410** [comment]
> > > Just throwing this clarification out there given I actually own these titles and dumped them personally. The DSi binary data is stored in the ROM image itself, it has to have that data in order to even have a functional DSi Enhanced mode. I have dumped these titles using GodMode9 in the past and of course they turned out to be matching with verified checksum data online.
> > > The only way this can occur is if the following is happening:
> > > 
> > > 1. You are using a bad dump, which this can only occur one of two ways, you either used a very old build of GodMode9**i** (not to be confused with GodMode9) to dump your copy of the game, which at the time did produce bad dumps of these titles, or you straight up went on the internet and downloaded a dump (which support can't really be provided for that given well, it's a bad dump from the internet, it's not exactly the fault of either side of developers for this via their software).
> > > 2. The dump is modified in some way, reason being I say this is because nearly all existing ROM editing related tools online literally destroy DSi related data given the tools were not geared for DSi related data in general, only NDS related data.
> > > 3. You may be using an old version of TWiLightMenu, some versions did have similar quirks like this in the past, double check to make sure you are running the latest.
> > 
> > Hello, i wanted to know, where do you think a clean rom vould be found for those who cant dump the cartridge, i have also been having this problem and they are hard to find if you didnt originaly own them. Or would it be possible for you to upload your dumped copy of pokemon black/white. Since i believe it may be what you said but i have not found a rom with dsi binaries i could use. Thank you in advance and please try seeing if you can upload your roms. Have a good day
> 
> Uh, not supposed to ask or host ROMs on this platform, it's illegal.

Ok, dont worry i understand, ive lost access to my cartridge and dont know how i can get this fixed so i searched online, thanks for replying quickly and explaining

**Comment by d0k3** [comment]
Alright, closing this. Apparently not a GodMode9 issue.
