### ISSUE TITLE
{For D0k3}

### ISSUE THREAD

**Issue by ErgFox9** [d0k3/GodMode9#732]
sorry if I write to you here but I can not contact you elsewhere, my friend Ergastolator1 and I did gm9 megascript in Italian, and we are asking you if you could advertise it because nobody pays attention to it and we would like to become famous (because we will do other things our aim is to translate apps and more for 3ds into other languages ​​to facilitate cfw and the experience) and maybe earn some money because my friend would like a 3ds but he has no money :( if you accept or not do nothing I will thank you anyway

link: https://github.com/ErgFox9/gm9italy

**Comment by GlaZedBelmont** [comment]
If I may interject, you removed several people from the credits instead of placing your names at the bottom of the list. There are also several untranslated sections.

I don't think @d0k3 is even accepting donations (please correct me if I'm wrong).

**Comment by Wolfvak** [comment]
There are chatrooms listed in the readme (both IRC and Discord), you can contact us through there.

**Comment by Nemris** [comment]
I'll add my five cents here - as a native Italian, I can see quite some typos that generally hint at a literal translation instead of one that preserves the original's meaning.

Moreover, I also see inconsistencies with casing, punctuation and suchlike.
