### ISSUE TITLE
[FEATURE REQUEST] Add a way to override cart dump size

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#742]
Some dev carts report their dump size incorrectly (above or below the capacity of the cart), which means that allowing GM9 to try and dump the cart based on that value will result in a too-small dump, or an error if it tries to dump past the boundary. I think providing an option to dump the cart with a specific size would be useful. I think this could be implemented without a significant interface change by adding some more "virtual ROM files" to the GAMECART drive. E.g. XXXX-64MiB.nds/.enc/.3ds, XXXX-512MiB.nds/.enc/.3ds etc - with all the possible cart sizes listed. Maybe to keep the directory listing clear, they could be in a subfolder (although maybe that is harder to implement).

**Comment by mariomadproductions** [comment]
I mean as long as the files are in a subfolder or labelled correctly (like "XXX-Size forced to X MiB.nds"), I don't think it will be confusing.

I've asked the dumper to confirm if this issue still occours in GM9 v2.0.0.

Not sure what you are asking about an overdump. Either an error would occour, or it would just read out invalid data. But that doesn't really matter - if the user is forcing the dump size, they should expect that. Not sure what you mean about distinguishing dev carts from retail carts.

**Comment by mariomadproductions** [comment]
> What happens in GodMode9 if it tries to read more than what's there? Is there an error message, does it simply crash, ...? If GodMode9 can detect an error here, and if GodMode9 can also recognize dev carts, then it could detect the actual size by just trying (ie. doing what a human would do anyways in that subfolder).

I'll ask.

> I've got another idea. What about providing a script command for dumping carts with a specified size? Would that help?

Yeah that could work.

**Comment by d0k3** [comment]
Well, looks like I didn't pay attention. Try this one:
[GodMode9-v2.0.0-39-g0f7eb65b-20211108171217.zip](https://github.com/d0k3/GodMode9/files/7498427/GodMode9-v2.0.0-39-g0f7eb65b-20211108171217.zip)

As for the filename based on the ROM header, I wonder what you'd need it for. As I understood, this is special functionality, for some special dev carts, most not even having the usual format (NCSD/NDS). Do you really need the standard output path for that and what for?

**Comment by d0k3** [comment]
I figured we may as well do it proper. This test build has cart dumping via script *and* a cart dump option in the context menu [R+A] of the cart drive:
[GodMode9-v2.0.0-39-g0f7eb65b-20211108185829.zip](https://github.com/d0k3/GodMode9/files/7499107/GodMode9-v2.0.0-39-g0f7eb65b-20211108185829.zip)

If you give it a try and it works for you, could you please provide me with screenshots of the unput dialogues? As I said, I can't test it myself, but I still want it to look proper.

**Comment by mariomadproductions** [comment]
I'll try it out now.

> As for the filename based on the ROM header, I wonder what you'd need it for. As I understood, this is special functionality, for some special dev carts, most not even having the usual format (NCSD/NDS). Do you really need the standard output path for that and what for?

Just so the user can dump multiple ROMs in one go without worrying about the previous dumps being "clobbered", and for easy identification by the user which ROM dump goes with which cart.

**Comment by mariomadproductions** [comment]
Okay, tried it. With the script I get a partial ROM dump again (dump takes a short amount of time). With R+B it takes longer, but then it crashes at 96%.

**Comment by mariomadproductions** [comment]
Yeah it does, and choosing to leave the secure area encrypted work. I'll test "no" to leaving it encrypted now. I'll take screenshots (or photos).

**Comment by mariomadproductions** [comment]
Okay, initial test results: it says "Failed dumping cart" if I select "no" to leaving it encrypted. Screen clears properly. Couldn't take screenshots (some of my 3DS buttons are not very responsive so it may be that), but here are some photos of my dirty 3DS screen
![1](https://user-images.githubusercontent.com/9919020/141123310-69cc46c1-5028-4a1c-8522-78d834a33638.jpg)
![2](https://user-images.githubusercontent.com/9919020/141123323-3146e8ca-aae1-4284-85be-046d5449ec9e.jpg)
![3](https://user-images.githubusercontent.com/9919020/141123332-6db153a1-ae97-43c5-bc10-20c9d6a57b7e.jpg)
![4](https://user-images.githubusercontent.com/9919020/141123340-fe09b0e7-9f00-47d9-98bb-3f26e4378276.jpg)
![5](https://user-images.githubusercontent.com/9919020/141123351-3a8a03a2-b6d7-49d0-836b-987dbaba1e2f.jpg)

**Comment by d0k3** [comment]
All fixed and merged to master. Feature will be in the next release.
