### ISSUE TITLE
[BUG] Continuous upwards scroll

### ISSUE THREAD

**Issue by ximmo** [d0k3/GodMode9#746]
So. after updating to 2.0, essentially the "cursor" continually scrolls upwards, the instant I enter Godmode9, and not an instant before. When I press Power on+start, the luma chainloader pops up first and it doesnt have the upwards scroll, just when I then confirm my choice.

**Info about your system**
O3DSXL
don't actually remember what bootloader i have
GodMode9 via Luma

**Comment by ximmo** [comment]
Of course it stopped the instant I posted this...

**Comment by TimmSkiller** [comment]
Just for clarity this is called stick drift and is caused by the control pad.
