### ISSUE TITLE
[FEATURE REQUEST] Merge Updates into base game when dumping

### ISSUE THREAD

**Issue by RinMaru** [d0k3/GodMode9#747]
would it be possible to merge update data and dlc into one cia when dumping titles? ive looked up guides and no tools really seem to work or are outdated.

**Comment by GlaZedBelmont** [comment]
@urherenow mate, GodMode9 is for 3DS, not Switch lmao

**Comment by d0k3** [comment]
Not possible rigth now, and really, you wouldn't want that on 3DS hardware. We'd need a RomFS (re-)writer, which would be slow as hell. If something like that is possible, it's better to do it on a computer. Maybe @ihaveamac's tools can help here, thinking about ninfs, which has part of the functionality required.
