### ISSUE TITLE
[BUG] Save data not detected for Pokemon Black (Korea) [IRBK]

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#748]
**Description**
Sava data is not detected in Pokemon Black (Korea) [IRBK], even though the game of course does use save data.

**Steps to reproduce**
- Boot
- Insert cart
- Go to "GAMECART" - notice lack of .sav file
- View the .txt file - notice that save type is set to "NONE"

**System info**
Console type: N3DS
Anything special about your console: No
Bootloader: boot9strap
Did you chainload GodMode9 via Luma: Yes

**Screenshot**
![snap_211022023722](https://user-images.githubusercontent.com/9919020/138337466-467208e3-287b-47fe-89dd-0230ce55a665.png)

**Comment by mariomadproductions** [comment]
Good point, there have been commits since v2.0.0 in regard to saves. I'll ask the cart owner to try it.

**Comment by mariomadproductions** [comment]
That build seems to be working. The save appears and can be dumped:
[POKEMON_B_IRBK01_00.zip](https://github.com/d0k3/GodMode9/files/7392981/POKEMON_B_IRBK01_00.zip)

The txt file:
```
Title String : POKEMON B
Product Code : IRBK01
Revision     : 0
Cart ID      : E080FF80
Platform     : DSi Enhanced
Save Type    : SPI
Save chip ID : 204013
Timestamp    : 2021-10-22 06:14:49
GM9 Version  : v2.0.0-32-gc966acc8
```

**Comment by Ammako** [comment]
It's c966acc851adeb2ca863f5de1f6e285d3c9e4b30
