### ISSUE TITLE
Invisible SD Card?

### ISSUE THREAD

**Issue by SerraraFluttershy** [d0k3/GodMode9#75]
The latest .FIRM release of GM9 has a very strange bug: upon viewing an SD card with a capacity at or over 16 GB, it shows absolutely nothing inside, except for files you copy to it inside of that session.

Otherwise, GM9 operates perfectly fine.

**Comment by james-d-elliott** [comment]
Mine seems fine, have you tested the cards you're using with h2testw?

**Comment by deadair3210** [comment]
Works fine on my 128 GB SD card, sounds like a filesystem issue. Possibly move files off and reformat it?

⁣Sent from BlueMail ​

**Comment by SerraraFluttershy** [comment]
The SD card was formatted multiple times, and has no integrity issues. It's 32 GB.

**Comment by d0k3** [comment]
I've got a 64GB SD card, and I've never encountered that issue, also never heard about it. Did you take a look at your SD cards contents on PC? Do they differ from what GM9 displays? Also, did you use GM9 to format that SD card?

**Comment by SerraraFluttershy** [comment]
Yes, they show up normally within homebrew on the 3DS, on my phone, and on my computer as well.
However, I didn't use GodMode9 to format the card itself.

**Comment by SerraraFluttershy** [comment]
![default](https://cloud.githubusercontent.com/assets/23690950/26526270/bdc8af5e-433a-11e7-920c-103d50dc6e03.PNG)
Never mind, I think this SD card my mother got was a fake.
Sorry for bothering you with this fake issue,
