### ISSUE TITLE
Write Permissions on SD Card

### ISSUE THREAD

**Issue by AdrianXL1** [d0k3/GodMode9#755]
Whenever I try to copy a file from my downloads to my cias folder on the sd card, it says write protection is enabled. How can I remove this write protection? Just for clarification, I'm just copying files to the cias folder, nothing else. I can't find anything on the internet to help me

**Comment by urherenow** [comment]
Github is not a support forum. Either your sd adapter's physical lock is in the wrong position, or you have a fake card that doesn't *actually* have the free space it's telling you that it has.

**Comment by d0k3** [comment]
You need to be more specific. What's the exact folder and drive your copying from and where are you copying to? If it's in the "Nintendo 3DS" folder, yes there is a write protection. You can unlock it, but writing there directly is not recommended. Is what you really want "install"? That's in the A button menu and it also works in batch for multiple files.

**Comment by AdrianXL1** [comment]
I'm copying a .cia file from my PC downloads directly into the folder on the root of the sd card named "cias"

**Comment by d0k3** [comment]
And you're trying to copy files from your PC to the SD card, using a card reader? Well, then it obviously does not belong here, cause this is not a GM9 issue. @urherenow 's reply may help you though.

**Comment by AdrianXL1** [comment]
The SD card is just fine, and it's not locked

**Comment by AdrianXL1** [comment]
what do you mean a "card reader" (just to clarify I'm plugging the SD card straight into the PC if that's what you mean)

**Comment by AdrianXL1** [comment]
To make things short, how can I remove write permissions (aka make it red) so I can copy these files into my SD card

**Comment by d0k3** [comment]
Not a GM9 bug, so I'm closing this. You may ask elsewhere or just try a search engine (there are multiple reasons why it may not work, it may also be broken).

**Comment by aspargas2** [comment]
To be clear, the gm9 system of write permission levels is only a gm9 thing, and cannot effect anything that happens outside of gm9.

**Comment by AdrianXL1** [comment]
thanks, I realized that it was an issue with my PC's SD card reader. so sorry for the trouble
