### ISSUE TITLE
[FEATURE REQUEST] Dump to/Build CIA from folder

### ISSUE THREAD

**Issue by ChaoticPumpkin** [d0k3/GodMode9#756]
**Describe the feature you'd like**

You can mount a title to a virtual drive, then copy everything to `gm9/out/`. I'd like if there was an option to directly copy the output to a folder, and to be able do the opposite, building a CIA from a folder, which would be mainly useful for doing mods to the homemenu or other system apps.

**Comment by d0k3** [comment]
We'd need a ROMFS builder, which would take a lot of work, and even then, the 3DS would be awfully slow in building a CIA in that way. The time used for implementing a feature rarely anyone would use is better invested in other areas.
