### ISSUE TITLE
[FEATURE REQUEST] Ability to convert .nds files to .cia files

### ISSUE THREAD

**Issue by JoshuaFurman** [d0k3/GodMode9#757]
I'm requesting a feature to convert .nds files to .cia files so that they can be installed on the homepage of the 3ds. 

Thanks!

**Comment by d0k3** [comment]
Has been asked before, and it's not possible. The 3DS can't install NDS cart dumps. Even though DSiWare dumps usually have the same extension (and can be installed), it's not the same thing.
