### ISSUE TITLE
Updated to 2.1.0, but loads 1.9.2pre

### ISSUE THREAD

**Issue by troywweber7** [d0k3/GodMode9#760]
I followed the update instructions for 2.1.0. The first time I loaded gm9, it worked and I had access to the title manager. But since then, no matter what I try, it now only boots into the older version of gm9 without the title manager.

I have tried deleting the .firm fully and gm9 folder and then reinstalling. I've tried reinstalling using the Universal Updater. Now it just always boots into 1.9.2pre.

I'm hoping someone can help me debug what is going on here so I can use the latest gm9. I will gladly share more relevant info or try to find any logs if I can. I would also just be curious to know if anyone has experienced this before.

**Comment by urherenow** [comment]
Github is not a help forum. Ask on gbatemp or discord.

Problem is you've probably installed gm9 to nand, and you're booting it from there.

**Comment by d0k3** [comment]
What @urherenow said. If an older version is loaded, that's because you tell your bootloader to do so. Maybe start by searching your SD card for other GodMode9.firm files? If that doesn't lead to success, ask in some help forum.
