### ISSUE TITLE
[BUG] Error when trying to restore NAND

### ISSUE THREAD

**Issue by aarongeorge** [d0k3/GodMode9#762]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).

Ran into an issue trying to restore the original NAND backup of a New 2DS XL with GM9.

When trying to run the restore, after selecting the .bin file to restore it throws the following error:

```
0:gm9/scripts/GM9Megascript.gm9
line 132: find fail
find I:twln.bin NULL

(<A> to continue)
```

**Info about your system**
Include this info to make our work easier:
* Console type
New 2DS XL
* Anything special about your console?
Nothing custom aside from installing Luma using the guide
* Bootloader
Bootstrap9
* Did you chainload GodMode9 via Luma?
GodMode9 loads holding Start on boot

**Have you actually read this?**
[x] I have read the information above

**Comment by d0k3** [comment]
This simply means there is something wrong with your backup. I suggest you do a fresh backup now, then try to verify and restore the one that caused this error via the GM9 A button menu. If you need help, ask on GBATemp or support channels.
