### ISSUE TITLE
"SYSNAND TWLN" and "SYSNAND TWLP" missing on dev units

### ISSUE THREAD

**Issue by Myriachan** [d0k3/GodMode9#77]
I ran the same build of GodMode9 on a Snake and on a retail system, and the "SYSNAND TWLN" and "SYSNAND TWLP" directories are missing.

**Comment by d0k3** [comment]
Key 0x03, which is required for accessing TWLN / TWLP is set up here (for A9LH and B9S):
https://github.com/d0k3/GodMode9/blob/master/source/nand/nand.c#L170-L192

As I don't own a dev unit, I can only test on retail, where this routine works fine. @SciresM - got any ideas what goes wrong there? That key would normally be set by NATIVE_FIRM (I think).

Also, you can't access EmuNAND TWLN and EmuNAND TWLP either, right? Can you build from the `freencsd` branch and try again?

**Comment by fox8091** [comment]
Panda O3DS, can also confirm. TWL is not showing up in GM9.

**Comment by fox8091** [comment]
It worked fine under A9LH though, so that routine (should) be fine.

**Comment by d0k3** [comment]
Should be fixed in the next ersion of boot9strap.

**Comment by d0k3** [comment]
As i said, boot9strap issue, and fixed on the next version. Closing this now...
