### ISSUE TITLE
Legit/standard cia building question

### ISSUE THREAD

**Issue by RECKZ-RZ** [d0k3/GodMode9#770]
“Building CIAs (legit type): Installed content can be built as legit or standard CIA. Legit CIAs preserve more of the original data and are thus recommended for preservation purposes.” 

What does more original data mean? Also which one should I use if I’m sending a game to a friend

**Comment by urherenow** [comment]
Piracy is not supported. You'll just have to read the docs and try to understand them.

**Comment by d0k3** [comment]
This also isn't an issue but rather a support request. @RECKZ-RZ - the answer to your question is in the readme file.
