### ISSUE TITLE
[BUG] Graphical Bug

### ISSUE THREAD

**Issue by Pokemiah** [d0k3/GodMode9#771]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Bug: Screen flickers when booting GodMode9. It only seems to appear on this device and it started appearing after updating from 1.9.1.
* Steps to reproduce: 
* 1. Boot up any version of GM9 past 1.9.1.
* 2. That’s it.

https://user-images.githubusercontent.com/35645879/162596913-7d2c5fa7-46e5-4251-b3ca-2ede46e48390.MOV

**System Info**
Include this info to make our work easier:
* Console type: N3DSXL
* Anything special about your console?: The screen does have slight issues where it appears brighter and washed out on initial boot, so that may be a cause.
* Bootloader: boot9strap
* Did you chainload GodMode9 via Luma?: Yes.

**Have you actually read this?**
[yes] I have read the information above

**Comment by profi200** [comment]
This looks almost certainly like hardware failure to me. Follow these steps and see if the problem persists:

1. Open the battery cover on the back side (where the microSD is located).
2. Remove the battery and hold the power button for 30 seconds.
3. Leave the system unpowered for 10 minutes.
4. Insert battery and boot to HOME menu normally before you enter GodMode9 or any other homebrew.
5. Power off and boot GodMode9 again.

**Comment by Pokemiah** [comment]
Ok, I tried your suggestion but it didn’t work. I think it reduced the stutter slightly, but that’s it. I do agree it might be a hardware issue, possibly the screen itself. That’s my guess anyway.

**Comment by urherenow** [comment]
I assume it doesn’t do that outside of gm9, because you didn’t mention that. If it doesn’t do that when looking at your home menu or while playing a game, how do you come to the conclusion that it’s a hardware issue?

**Comment by Pokemiah** [comment]
First of all, yes it does only do it with GM9. As to why I agree that it might be a hardware issue is because of the weird saturation my screen has when booting up my 3DS outside of GM9 and my brother’s 3DS does not have this flickering issue. I’m not 100% sure of it being a hardware issue, I just think it’s highly probable.

**Comment by profi200** [comment]
The reason why i think this is hardware failure is look at the corners of the top screen in this video. Bottom left is the most obvious. It looks like this LCD is damaged either from a drop or other force.

Anyway, since the battery pull didn't fix it i would lean towards hardware issue. You mentioned washed out colors which can be a result of wrong calibration. Was the LCD ever replaced?

**Comment by Pokemiah** [comment]
No. It’s the same screen that came with the 3DS.

**Comment by urherenow** [comment]
Was it ever opened for any reason? Those ribbon cables can be very temperamental.

It's still throwing me off that you say it's fin playing a game. Would you consider installing fastboot3ds to see if the behavior is the same?

**Comment by d0k3** [comment]
@Pokemiah - did you try fastboot3DS? We did, in fact, have some weird issues with Luma 3DS bootloader and GodMode9 in the past, but I doubt it's the same thing. Could be some kind of limited hardware failure. The 3DS was not built for eternity as we all know.

**Comment by Pokemiah** [comment]
@d0k3 I have not. I’ve been busy with my college finals this past month. However, I should be able to get to it later today as I have time.

**Comment by Pokemiah** [comment]
Ok, so I finally got around to switching to FastBoot3DS and that solved the issue. My screen no longer flickers with the latest version. I don’t know if it was my hardware, the chain loader, or a combination of both, but the issue has been resolved and I booted it three times just to make sure. Thanks for the help.
