### ISSUE TITLE
[Help wanted] Install CIA with gm9 script?

### ISSUE THREAD

**Issue by TheGhostboi64** [d0k3/GodMode9#775]
Is there a possible way to install cias with a gm9 script? I’m trying to experiment with gm9 scripts. Any help is appreciated.

**Comment by d0k3** [comment]
Wrong place. The issues section is not for support requests. Try the "install" command. You may also ask for help on Discord or GBAtemp. And, looking into these sample scripts may help, too.

**Comment by TheGhostboi64** [comment]
Thank you!
