### ISSUE TITLE
GM9 formatted 4GB SD in 64K cluster unreadable, fixed by re-formatting with Windows

### ISSUE THREAD

**Issue by MelonGx** [d0k3/GodMode9#78]
It happened on GM9 1.1.8 (20170525 nightly).
32K or less cluster on 4GB SD didn't have this issue.

**Comment by d0k3** [comment]
There was nothing changed in the way the format routines work, so I'd assume a strange quirk in the 3DS card reader hardware. Can you reproduce this? Ie. try again, see if it happens again.

**Comment by MelonGx** [comment]
It happened again on another 4GB MicroSD.
Maybe it's an incompatible issue of 64K cluster with 4GB SD?
I'll try to check 8/16/32GB for this.

**Comment by d0k3** [comment]
Was the other 4GB MicroSD of the same kind? There were never any issues formatting 4GB SDs any way you want, I can't reproduce it, and no other user has come forward with any similar issue. Looks like it's just you for now.

**Comment by MelonGx** [comment]
4GB SD - Transcend 4GB (on New Love Plus exclusive O3DS JPN, B9S GM9 1.1.8)
4GB MicroSD - Toshiba 4GB bundled (on N3DS JPN, B9S GM9 1.1.8)

**Comment by d0k3** [comment]
You are correct, 64kB cluster sizes don't work on SD cards that small. A new workaround will revert to auto cluster size if this is attempted again.
