### ISSUE TITLE
any help is appreciated

### ISSUE THREAD

**Issue by C411y** [d0k3/GodMode9#781]
hi, sorry, I'm really new to all of this and could do with some help. I need to be able to "copy" "GodMode9.firm" and the ("gm9" Folder) but am unable to do this as I can not find them. sorry if this is written in the wrong area or if I should already know how to solve my issue but any help would be greatly appreciated :)

**Comment by d0k3** [comment]
You may want to get someone to help you with this. The release ZIP file is easily found here. That being said, GitHub issues is really not the right place to ask for the basics. Look around on GBAtemp or ask on Discord.
