### ISSUE TITLE
GodMode9 can't find "scripts" folder, despite it being in my SD card

### ISSUE THREAD

**Issue by bbpink217** [d0k3/GodMode9#782]
Just the title. For whatever reason now it suddenly can't find the scripts folder that's clearly in my SD card :/ I'm trying to run a script as to make sure my system won't brick when uninstalling my cfw, but now I'm unable to do so. I've already tried switching out my luma and gmd folders to the latest versions, but no luck. Any help?

**Comment by TheGhostboi64** [comment]
the gm9 scripts are on SD:/gm9/scripts

**Comment by d0k3** [comment]
Assuming @bbpink217 just got the location wrong, so I'll close this. If there are still issues left, just comment here!
