### ISSUE TITLE
Gm9 error data abort [BUG] ...

### ISSUE THREAD

**Issue by userbamb** [d0k3/GodMode9#783]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
* Give us clear steps to reproduce (when/how did it happen?).
* Give us info about your system (where did it happen?).
* A photograph or even a short video of the bug happening is always helpful!

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS)
* Anything special about your console? (defects, custom modifications,...)
* Bootloader (boot9strap/fastboot3ds)
* Did you chainload GodMode9 via Luma?
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader
![20220727_165612](https://user-images.githubusercontent.com/110114819/181281197-854e4e24-747e-4049-a168-17aaf3eeb298.jpg)
 This happens

**Comment by Wolfvak** [comment]
Can you explain what you did to trigger the bug? Also, please scan the QR code and post the output here (preferably `quoted`).

**Comment by userbamb** [comment]
I think I accidentally updated a game, the console did the arm11 error so I
said well I want to restore my nand from the backup and this error happened.
Exception: Data Abort (4) GodMode  v2.1.1 2001-01 01 00:02:07 0: 2011 D90 |
R01: 20118D90  000000 0 | R03: 00000000 R04:  0000001 | R05: 0805FB90 R06:
08 5E534 | R07: 00000000 R08: 0000 000 | R 9: 00000000 R10: 000000 0 | R11
00000001 R12: 00000000

Il mer 27 lug 2022, 17:11 Wolfvak ***@***.***> ha scritto:

**Comment by userbamb** [comment]
But now on some groups they telling me could be hardware problem but idk where to start, it's a console o bought used so never had it idk

**Comment by userbamb** [comment]
Then also does this
![1658935025699618239477810988162](https://user-images.githubusercontent.com/110114819/181284740-e01991d5-bd4c-4f67-bb58-72f0510e32af.jpg)

**Comment by userbamb** [comment]
ã  -	
    
 	  
 
        O           O
 -

è     
  N á   /
     
-  
	 
   
 O         é        	
á    è
               O

**Comment by userbamb** [comment]
This the last qr scanned lol

**Comment by userbamb** [comment]
䕘捥灴楯渺⁄慴愠䅢潲琠⠴⤊䝯摍潤攙⁶㈮ㄮㄊ㈰〱ⴰㄍ〱‰〺〱㨴㠊 刐〺′㈷䕅㝅䌠簠刐ㄺ‰䘰䘰䘰䘊到㈚‰〰〰〘㜠簠到㌺‰〰〰〰《到㐺‐䘰䘰䘰䘀簠到㔺′㈷䕅㝅䌊到㘺‰【〰〸㘠簀到㜺‰〰〰〰㌊到㠺′㈷䕅㐶〠簠刐㤺‰㠰㕆䈹《刱〚‰㠰㕆䈙〠簠刱ㄚ′㈷䕃㐷㐊刱㈺‰〰〰〰

**Comment by userbamb** [comment]
And that's anotherone

**Comment by userbamb** [comment]
Now it works... I succeded to reinstall the nand... What do I do?

**Comment by userbamb** [comment]
I mean is it resolved?

**Comment by al3x10m** [comment]
test your ram with the above firm file..nand might be fine..but ram seems to be shot from what i see. post your results

**Comment by userbamb** [comment]
![Uploading Screenshot_20220727-174530.png…]()

**Comment by userbamb** [comment]
That was when I run it before i resolved the nand thing

**Comment by Wolfvak** [comment]
First, stop sending single line messages. Try to explain what you did, what you're trying to do and what's actually happening.
Try to include as many details as possible.

Also, post the results of the RAM tester, it will take almost an hour to run, so just let it be. At the end it should create a file in the SD card, upload that here.

If you can't do that, we can't help you.

**Comment by userbamb** [comment]
ok sorry for the messy thread, I dont know how to run the test actually if it takes like an hour I didn't do that, could someone tell me how to run the test so I can help you helping me. TYsm and sorry but im actually panicking

**Comment by al3x10m** [comment]
download that firm file from wolfvak's post...rename it to boot.firm on your pc...plug in your sdcard...rename the existing boot.firm to something like boot2.firm...then copy the firm you downloaded to the sdcard then plug it back to your 3ds..when you boot your 3ds it should start it

**Comment by d0k3** [comment]
No additional info on this one for two months straight, so I'm closing this, and I'm suspecting hardware failer. @userbamb - if you can still add something or this is not resolved, feel free to add further comments to this post. Thanks everyone for helping out!

**Comment by userbamb** [comment]
I just put the file as it is on the SD card and shows this

Il mer 27 lug 2022, 17:32 Wolfvak ***@***.***> ha scritto:

**Comment by d0k3** [comment]
@userbamb - what exactly does it show?

**Comment by Akiran495** [comment]
I have similar problem on my new nintendo 3ds like userbamb .what is the solution of the problem

**Comment by vaki189** [comment]
![17283042006161728917600914588305](https://github.com/user-attachments/assets/8f7a2720-2f8e-4fb6-89e6-5fefb92c9a6e)
