### ISSUE TITLE
[FEATURE REQUEST] ... Support for Modified SDXC cards

### ISSUE THREAD

**Issue by JawG-PawG** [d0k3/GodMode9#784]
Little known fact: 3rd party SD card managers can format 64, 128 and 256 GB SDXC cards from exFAT to FAT32, making them perfectly usable with 3DS consoles. (I'm running a 64GB)
Problem: while GodMode9 will launch, it can't mount the SD card.

Could GodMode9 have support for these modified cards? I had to do quite a bit of mucking around with smaller cards to extract the Gen7 Pokemon binaries for the GTS Anti-freeze fix.

**Comment by Epicpkmn11** [comment]
I've had no issues with my 64 and 128 GB cards in GodMode9... Perhaps you've got it formatted weirdly, reformatting with [SD Formatter](https://www.sdcard.org/downloads/formatter/), then [GUIFormat](http://ridgecrop.co.uk/index.htm?guiformat.htm) if you're on Windows or the default on anything else might help? Yes, double formatting can make a difference.

See [3ds.hacks.guide's formatting page](https://3ds.hacks.guide/formatting-sd-(windows)) ([macOS](https://3ds.hacks.guide/formatting-sd-(mac))/[Linux](https://3ds.hacks.guide/formatting-sd-(linux))) for more details.

**Comment by JawG-PawG** [comment]
Thanks! Will try now. Doing full format instead of quick. Will let you know how I go.

**Comment by d0k3** [comment]
If you mean *converting* these cards from exFAT to FAT32, that was something that was considered for GM9. We didn't do it cause (a) it would have been a lot of work for us and (b) it would be awfully slow on 3DS hardware. You really want to do the conversion on a PC. Just formatting any card with FAT32 should not be a problem at all. You may want to look into the HOME menu.

**Comment by JawG-PawG** [comment]
guiformat.exe did the trick. thank you guys so much!
