### ISSUE TITLE
how do i download this..?

### ISSUE THREAD

**Issue by pastel-n0va** [d0k3/GodMode9#787]
i dont have a sd card reader, the sd slot on my pc is too big, so am i out of luck? or is there another way?

**Comment by pastel-n0va** [comment]
*confused screaming*

**Comment by Epicpkmn11** [comment]
What part are you confused on?

**Comment by urherenow** [comment]
Take it to discord or gbatemp. Github is not a help forum, and this isn't a GM9 issue.

**Comment by pastel-n0va** [comment]
i dont have a Discord.

end of issue, goodbye now.
