### ISSUE TITLE
latest update

### ISSUE THREAD

**Issue by isasquatch** [d0k3/GodMode9#788]
Can I update my 3ds if i have this version installed?

**Comment by Epicpkmn11** [comment]
Yes, 3DS updates don't affect GodMode9 at all. What you actually need to make sure is up to date is Luma3DS, see the [Restoring/Updating CFW](https://3ds.hacks.guide/restoring-updating-cfw) page of the guide for how to update.

PS. GitHub issues are not for support, it'd be better to ask in a discussion or join the Discord/IRC

**Comment by isasquatch** [comment]
Oh, I understand. I should have looked more on where to ask. Anyways, thanks for your answer. I'll do that as soon as i can
