### ISSUE TITLE
[BUG] Pokemon Sapphire save file failed to inject due to incorrect size

### ISSUE THREAD

**Issue by ohyocbz** [d0k3/GodMode9#794]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
An error "Savegame inject failed!" occured when trying to inject a GBA save file from my microSD card, only to find out that my save file size was **~_129 KB_** (131,088 bytes size mentioned on File Explorer; 135,168 bytes size on disk) instead of exactly 128 KB (131,072 bytes)

* Give us clear steps to reproduce (when/how did it happen?).
Copied the GBA raw format save file from my Windows computer --> Pasted it to the root of my 128 GB microSD card --> Booted my 3DS via GodMode9 --> Pressed L to mark it and Y to copy the save file to the clipboard --> Went to S: SysNAND Virtual and select "agbsave.bin" --> AGBSAVE options --> Inject GBA VC save

* Give us info about your system (where did it happen?).
In SysNAND Virtual agbsave.bin injecting GBA VC save

* A photograph or even a short video of the bug happening is always helpful!
![20221106_211439](https://user-images.githubusercontent.com/117028047/200174741-aaa3afb7-28fe-482f-a419-e819de6b723b.jpg)
Some additional attachments including the save file:
[20221106_BugReport.zip](https://github.com/d0k3/GodMode9/files/9945977/20221106_BugReport.zip)

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS)
N3DS

* Anything special about your console? (defects, custom modifications,...)
None

* Bootloader (boot9strap/fastboot3ds)
boot9strap

* Did you chainload GodMode9 via Luma?
Yes

* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[X] I have read the information above

**Comment by d0k3** [comment]
@ohyocbz - thanks for the bg report! Can you try this test build?
[GodMode9_794.zip](https://github.com/d0k3/GodMode9/files/10076785/GodMode9_794.zip)

**Comment by ohyocbz** [comment]
> @ohyocbz - thanks for the bg report! Can you try this test build? [GodMode9_794.zip](https://github.com/d0k3/GodMode9/files/10076785/GodMode9_794.zip)

Hello! Sorry for the long wait and reply. I was also busy irl so it took me quite some time to check this out on my own at night. Here's what happened so far:

1. The 129kb save file inject that I uploaded here before was finally working and could play perfectly 😄
![20221124_001246](https://user-images.githubusercontent.com/117028047/203603393-1ef046cc-62ae-474e-8081-079fa018c2e6.jpg)
![20221124_001325](https://user-images.githubusercontent.com/117028047/203603432-144d628f-a9a2-44bc-a189-d2dfac191339.jpg)
![20221124_001451](https://user-images.githubusercontent.com/117028047/203603441-7ed31e42-3757-4bee-8bee-8cba9b79a606.jpg)
![20221124_001540](https://user-images.githubusercontent.com/117028047/203603448-5e660a89-a368-480a-ad5d-4ed90ca4e042.jpg)

3. I also did backup the new save to the gm9/out folder and I was surprised that the file size went back to 128kb or the usual bytes
![20221124_001655](https://user-images.githubusercontent.com/117028047/203603935-8c79fa99-d5cf-4571-abc9-b608d3ee03c1.jpg)

4. I tried to play it on my computer using mGBA emu to  continue and save once again and I find it very odd on why the save file size went back to 129kb

5. So I use this new 129kb save file, put it on my sd card and boot the payload until this message appeared out of the blue:
![20221124_003756](https://user-images.githubusercontent.com/117028047/203604708-eedb9a7a-a24c-4c68-9bde-a8588f1bd04a.jpg)

6. i got nervous and thought my sd card got corrupted but im glad my OS repaired it and found no errors. Before I was about to replace the GodMode9.firm from winrar, is it normal for a debug payload firm's file size to be larger after a single use?
![20221124_004707](https://user-images.githubusercontent.com/117028047/203604896-d6b9378e-4157-4507-9d49-6aec965fac15.jpg)

7. I replaced it and boot up godmode9 and inject the new incorrect file size and it works like a charm and was indeed playable
![20221124_004631](https://user-images.githubusercontent.com/117028047/203605077-a939b116-826d-4ed5-ac78-027a28bc424f.jpg)

Thank you so much for your time and effort on fixing this that I almost forgot about this

**Comment by d0k3** [comment]
Thanks a lot to you for testing this as thorough as you did. You're right, the additional 1kb is some emulator specific RTC data. I've got no way of keeping this data or even restore / use it. Also, no need to worry about it, as you see, mGBA just rebuilds the data when you import the save back.

As for the error and the `GodMode9.firm` size - I'm at a loss here. Something weird happened to cause this. Maybe you did mix up GodMode9 firms? The file itself should not change size when running.

**Comment by ohyocbz** [comment]
> Thanks a lot to you for testing this as thorough as you did. You're right, the additional 1kb is some emulator specific RTC data. I've got no way of keeping this data or even restore / use it. Also, no need to worry about it, as you see, mGBA just rebuilds the data when you import the save back.

So I'll have to use this test build payload you gave me for the mean time when injecting or dumping my saves with RTC

> As for the error and the `GodMode9.firm` size - I'm at a loss here. Something weird happened to cause this. Maybe you did mix up GodMode9 firms? The file itself should not change size when running.

I think I did mixed up without noticing while transferring, I'll just have to be careful from now on
