### ISSUE TITLE
[BUG] ... I can't convert my .3ds to .cia

### ISSUE THREAD

**Issue by Noadecajou** [d0k3/GodMode9#795]
**Have you actually read this?**
[X] I have read the information above

When i want convert my .3ds game to .cia gm9 shows me "operation failed"
I have tested with many roms and it never worked
I have 2ds and Luma, my godmode9 is in v2.0.0

(Sorry for my bad English)

**Comment by d0k3** [comment]
Have you also tried a different SD card? If you got none, you could also check the one you got via chkdsk. Also make sure you got enough space free.

**Comment by Noadecajou** [comment]
I don't have an other SD card, this is the original card of the 2ds. But 
I'm sure I have enough free space

**Comment by d0k3** [comment]
You will need to check this SD card via a computer then. Does installing the .3DS to your system work?

**Comment by Noadecajou** [comment]
Yes I tested them with Citra and they work

**Comment by Noadecajou** [comment]
my .3DS files work when I use Citra with my computer but I can't convert them to .cia with Godmode9, it shows me "operation failed"

**Comment by Noadecajou** [comment]
sorry

**Comment by Noadecajou** [comment]
I suggest you to send me a means of communication and I will send you a video detailing everything I do to convert my files so you can tell me what is wrong

**Comment by d0k3** [comment]
Well, just upload it on Youtube. Or upload the video file to some hoster.

**Comment by Noadecajou** [comment]
ok i will do that tomorrow

**Comment by AlexSteiner30** [comment]
can u send me the 3ds file so that I can see what the problem is?

**Comment by Noadecajou** [comment]
https://www.mylink1.biz/aeRc
the password is ByAlvRo

**Comment by AlexSteiner30** [comment]
let me convert it for you

**Comment by Noadecajou** [comment]
it's work for you ?

**Comment by AlexSteiner30** [comment]
i am doing it right now

**Comment by Noadecajou** [comment]
thanks really

**Comment by Noadecajou** [comment]
in fact I would especially like to convert a specific file but it cannot be found on the internet, how can I send it to you?

**Comment by AlexSteiner30** [comment]
no problem at all 5 minutes

**Comment by AlexSteiner30** [comment]
> in fact I would especially like to convert a specific file but it cannot be found on the internet, how can I send it to you?

discord

**Comment by AlexSteiner30** [comment]
finished i am testing it now

**Comment by Noadecajou** [comment]
Noadecajou#9578
