### ISSUE TITLE
[FEATURE REQUEST] Translation system (Crowdin for example)

### ISSUE THREAD

**Issue by Minionguyjpro** [d0k3/GodMode9#796]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.

**Describe the feature you'd like**
I would like to see a translation system on Crowdin or somewhere else, so everyone can use GodMode9 in their own language.

**Describe alternatives you've considered**
X

**Comment by Epicpkmn11** [comment]
This is a duplicate of #766, already being implemented by #768

**Comment by Minionguyjpro** [comment]
I saw that, forgot to close. Closing
