### ISSUE TITLE
[BUG] DSiWare tmd's matching the NoIntro 3DS CDN dat fail to verify and install

### ISSUE THREAD

**Issue by Daeymon** [d0k3/GodMode9#799]
So essentially, DSiWare games from the 3DS CDN (checked against the NoIntro "Nintendo - Nintendo 3DS (Digital) (CDN)" dat) will not verify or install with GodMode. I have got both a encTitleKeys.bin and decTitleKeys.bin that contains the keys for these games.

3DS games from the 3DS CDN, checked against the same dat, verify and install fine.

**Comment by ZeroSkill1** [comment]
Where are you placing enc/decTitleKeys.bin? They are supposed to go in `sd:/gm9/support`.

**Comment by ZeroSkill1** [comment]
I am unable to reproduce this. It is likely that your key files contain incorrect keys.

**Comment by Daeymon** [comment]
Could I ask, what title from the "Nintendo - Nintendo 3DS (Digital) (CDN)" set did you successfully verify with GodMode? I've been unable to verify "Mario vs. Donkey Kong - Minis March Again! (Europe) (DSiWare)" or "Zelda Four Swords - Anniversary Edition (Europe) (DSiWare)". I've been able to use CDN-FX to look inside my bin files, and can confirm the keys for those games are present.

**Comment by ZeroSkill1** [comment]
Both of the titles you mentioned verify just fine with the correct key files.

**Comment by ZeroSkill1** [comment]
Yes, that is correct.

**Comment by d0k3** [comment]
Looks like this is an issue on your end @Daeymon

**Comment by Daeymon** [comment]
Turns out the issue wasn't my key bin files but the tickets on the device itself. I got FBI to remove all unused tickets and it started verifying and installing fine.
