### ISSUE TITLE
Regarding GBA VC injection

### ISSUE THREAD

**Issue by ozesnoloco** [d0k3/GodMode9#80]
Since you closed the thread on boot9strap where we were talking about the failing injection (https://github.com/SciresM/boot9strap/issues/5), I have opened a new thread here. Answering at your last question, when I edit a VBA save, it result on a 64kb file, but if I try to paste that on S:/, GM9 says "the file is larger than space available" and it does not let me paste my gbavc.sav. So, I need to trimm it in order to have a 32kb file and GM9 let me paste it on S:/.
As for your suggestion on running luma chainloader... how I do it?

**Comment by d0k3** [comment]
Well, that's actually normal. The file that emulator creates is too big, so you have to truncate it.

Read about payload chainloading [here](https://github.com/AuroraWright/Luma3DS/wiki/Other-features-and-notes).

So far this is a non issue :). Is there anything that doesn't work except that.

**Comment by ozesnoloco** [comment]
Well... I will try dumping/injecting more GBA VC save with different games to see if problem persist. If you want, closet this and I'll report future issues on a new thread

**Comment by d0k3** [comment]
Alright, closing this now and you reopen if something turns up. To be clear - the 64kB file is a VBA issue, not a GM9 one. VBA just uses all the available space when GM9 can only provide what AGBSAVE provides.
