### ISSUE TITLE
[FEATURE REQUEST] EDITING FILES

### ISSUE THREAD

**Issue by EpicDoodleboy2** [d0k3/GodMode9#805]
**Got a great idea on how to improve GodMode9?**
No

**Describe the feature you'd like**
Having to edit files without taking out the sd card and ruining/breaking the screw covers and possibly damaging the sd card.
![20230408_125157](https://user-images.githubusercontent.com/111697934/230719650-d99e714d-3835-4067-bf9a-d73b059c6839.jpg)

**Comment by Epicpkmn11** [comment]
GodMode9 already has a hex editor which can be used to edit files, though somewhat limited as I don't think it can insert/delete bytes

**Comment by EpicDoodleboy2** [comment]
> GodMode9 already has a hex editor which can be used to edit files, though somewhat limited as I don't think it can insert/delete bytes

I mean like text like turning true into false

**Comment by Wolfvak** [comment]
Full text editing has been considered before and was rejected as an idea - and nothing has changed since then.
