### ISSUE TITLE
Gateway unbricking with magnethax/ntrboothax/etc

### ISSUE THREAD

**Issue by GerbilSoft** [d0k3/GodMode9#81]
It's not released yet, but it might be worth investigating this for a future update.

Gateway's brick code uses the eMMC secure command set to set a password. Earlier versions I believe used a predictable password, so it could be unlocked; later versions are more random, so the only option is a secure erase.

References:
* http://gbatemp.net/threads/3ds-unbricking-possible.361226/
* http://gbatemp.net/threads/3ds-unbricking-progress.361171/
* https://github.com/krisztian1997/3dsunbricker
* https://github.com/bkifft/RPU

**Comment by d0k3** [comment]
There is already something in the works, and this is too specific to include in GM9. Also, can't have all the glory to myself :^). Closing this now.
