### ISSUE TITLE
Godmode9 booting error

### ISSUE THREAD

**Issue by Josahi71** [d0k3/GodMode9#810]
---
name: Godmode9 reboots whenever I press a button
title: "[Godmode9 booting error]"
labels: bug, possible user error
---

After installing Luma and placing godmode9 in the payloads folder, my N3ds will only boot to godmode9 (without even holding start) and once it boots, every time I press a button to try and navigate the godmode9 menu, godmode9 reboots and I cant navigate any further. 

* I'm using a new Nintendo 3ds (not xl) using Luma as my chain loader and using boot9strap as my boot loader.

* What might be important to know is that my top screen is broken and the ribbon cable has a small tear, but games play fine. I'm working on getting a new one, but trying to figure out modding in the meantime.

**Comment by Wolfvak** [comment]
Only reason GM9 would reboot this way is if it detects the START button is being held.
Maybe there's something else broken with your system that makes it think it is?

**Comment by d0k3** [comment]
Every now and then, we got some issue here that obviously has to do with broken hardware like yours, @Josahi71 . There are way to map the START button to something else in `godmode.c`, or to just disable it entirely. Just waiting for that new device of yours may be an option, too.

As this is specific to your hardware malfunction, it's not an actual bug. I suggest you discuss this either here, in the discussions, or on the GM9 Discord.
