### ISSUE TITLE
[FEATURE REQUEST] Zip/Rar/7Z Unpacking

### ISSUE THREAD

**Issue by TwystedXYZ** [d0k3/GodMode9#817]
**Got a great idea on how to improve GodMode9?**
That's always appreciated. Please make sure you add all the required info here.
I want a ZIP/RAR/7Z extraction tool added to GM9.
**Describe the feature you'd like**
Add a clear and concise description of what you want to happen.
There's no stable way of extracting RAR/7Z on a 3DS, so my solution would be to add it to GodMode9 using 7-Zip's source code. https://github.com/mcmilk/7-Zip
**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.
Maybe a port of 7-zip itself to the 3DS, but that's a bit too far.

**Comment by ihaveamac** [comment]
What use case is there for this? Decompression would likely be way slower than doing it on a PC.

**Comment by d0k3** [comment]
@TwystedXYZ - it's not like that's not possible (see this other repo of mine [here](https://github.com/d0k3/ZIP3DSFX)), but it's simply not worth it. As @ihaveamac said, it would be a lot slower than just doing it on PC, and the additional libraries would increase the size of the GM9 firm a lot.

**Comment by Gruetzig** [comment]
It is not possible to create a GodMode9 script that does that.
