### ISSUE TITLE
[BUG] Buttons act weird on GodMode9, but work perfectly everywhere else.

### ISSUE THREAD

**Issue by EstevaoU** [d0k3/GodMode9#823]
I was following the 3DS hacking guide and got stuck at the final step, where one would have to use GodMode9 to installs scripts, do backups and stuff. Issue is: i am not able to use it since it has it's own will
I am on an old 3DS and followed the guide strictly, from formatting the SD Card to updating the system and all. All buttons work perfectly everywhere else except on GodMode9.

https://github.com/d0k3/GodMode9/assets/71881046/14ee2fd6-afc7-4ae1-83d4-fd08369a3321

**Info about your system**
Include this info to make our work easier:
* Console type: Old 3DS
* Anything special about your console: It was secondhand and already had luma CFW, but it seemed like a very clean install and it didn't even had extra folders or files on it's SD Card when i first started to update the CFW. Could it be something that the previous owner did?
* Bootloader: boot9strap
* Did you chainload GodMode9 via Luma? Yes

Yes, I have read the text blaming it on my SD Card being wonky. No, i don't think it's the case

**Comment by EstevaoU** [comment]
If i hold left when the selection gets where i want, i can hold it on place and press A to do what i want. But i'm still getting issues with buttons being recognized: the unlock sequence needed to install the basic tools (which, very respectfully, sounds a bit silly to say the least) gets the arrows all lit up (only when using the circle-pad though, d-pad doesn't work here) but doesn't recognize the A button when i get to it right at the end. I press it, but it just plays dead.
This is the only thing that's stopping me from completing the guide and it's so, so frustrating and the discord server offers absolute no help every time i ask there. Is it just not possible to change this sequence just to not include the A at the end? It must be one line of code, is it impossible to just make a custom patch of GM9 just for my specific situation? Please? I'm almost begging for this, this console was a present from the effort of multiple friends, it can't just be fated to sit useless because of something so tiny

**Comment by EstevaoU** [comment]
https://github.com/d0k3/GodMode9/assets/71881046/06c5a291-e4d4-4169-acf9-8608d72d9386

Here's a video example of what's happening. Please, someone help me

**Comment by EstevaoU** [comment]
Please.

**Comment by fyredragon69** [comment]
saying "please" won't get you an answer faster, have patience
that looks like a faulty circle pad, i had the same issue happen to me
try replacing it or have someone do it for you

**Comment by Wolfvak** [comment]
GM9 has lower tolerances that the main operating system, if it feels the CPad is even slightly tilted in any direction it'll report that (and move the menu selector in a certain way, for example).

As @fyredragon69 said, this is probably it. You can also try [this](https://cdn.discordapp.com/attachments/894237155931602974/1113552084000841738/gm9nocpad.firm) build, it has CPad controls disabled. Either way please report what happens so we can move further on this.
