### ISSUE TITLE
Request to add support for Installing NDS files as well instead of just CIA and 3DS files.

### ISSUE THREAD

**Issue by Kssonety** [d0k3/GodMode9#834]
*Got a great idea on how to improve GodMode9!

Basically I would like godmode9 for 3ds to support installing NDS files.
By NDS files the file I uploaded is an example NDS file
[flappybird.zip](https://github.com/d0k3/GodMode9/files/13875950/flappybird.zip)

Tried Twighlight Menu++, It does work but it is annoying to go into 2 apps.

**Comment by kaktusmisapolak** [comment]
NDS files can't be installed, they work differently

**Comment by d0k3** [comment]
As @kaktusmisapolak said.

**Comment by Kssonety** [comment]
Ah, ok. I thought it would work like NDS bootstrapper or something.
