### ISSUE TITLE
[FEATURE REQUEST] jpg & bmp support

### ISSUE THREAD

**Issue by giiutfff** [d0k3/GodMode9#835]
**Got a great idea on how to improve GodMode9?**
Currently png pictures can be displayed, jpg and bmp are not supported. 

**Describe the feature you'd like**
It'd be nice to have the ability to view photos taken in 3ds camera and screenshots made by luma.

**Describe alternatives you've considered**
I don't know if there is anyway to see bmp files on 3ds. However being able to see jpg gives more control over files compare to 3ds camera app.(eg. organise them in a custom folder)

**Comment by d0k3** [comment]
Won't be coming, because adding libs for that will bloat the .firm file. Add to that the fact that the .3ds screen is rather low pixel. I guess I'd take a pull request with some lightweight code to add the functionality, but I don't think that will happen.
