### ISSUE TITLE
No support for boot9strap v1.1

### ISSUE THREAD

**Issue by qwertyatom100** [d0k3/GodMode9#84]
In boot9strap v1.1, payload handling was changed. This breaks loading this from Luma as well as direct loading.

Since the majority of the community is running B9S now, updating to support new B9S is important.

Thanks for making such a great tool d0k3!

**Comment by d0k3** [comment]
Try again with the most recent 1.2.1 release, then tell me if it works now.

**Comment by MelonGx** [comment]
20170601+ have no proper .firm so use 20170531-232521 one.

**Comment by d0k3** [comment]
Okay, what @MelonGx just wrote is a problem with the latest hourlies, not GM9. And 1.2.1 works (confirmed). Closing this, feel free to reopen if you feel it's unsolved.
