### ISSUE TITLE
[FEATURE REQUEST] Add "Check for Save Data Corruption" option when managing CIAs or when dumping cartridges 

### ISSUE THREAD

**Issue by KenoAkita** [d0k3/GodMode9#849]
So, sometimes there is a possibility of save data corrupting when sudden power loss when saving a game. Examples are the battery disconnecting. or the battery dying. I think there should be a feature where you can repair corrupted save files if corruption occurred.

**Comment by fyredragon69** [comment]
how exactly would you check for save data corruption and fix it? not every game has the same save data structuring, adding every single game would make it quite bloated

**Comment by luigoalma** [comment]
Not only that, at the point data got corrupted we can't guess what's the expected data contents of a broken save.
Most GodMode9 can do is fix CMACs of the .sav that contains the actual save data if by chance it was the only thing that was left incorrect in a very timely shutdown, but that you can do already when do you calculate CMAC of a .sav file.
But you got to be rather lucky to be *just* a broken CMAC.

**Comment by d0k3** [comment]
Agreed to everything that was written earlier. We may be able to check CMACs, but there is no way we could repair anything.
