### ISSUE TITLE
Feature Request - Expand the title injection feature

### ISSUE THREAD

**Issue by capito27** [d0k3/GodMode9#85]
currently, one may only inject titles into H&S, could it be reasonable to hope the system be revamped to work with any title, i could see such a thing work by placing a .cia/.cxi/.app (or a combination of those formats) in the clipboard and when selecting an installed NCCH image from CTR/EMUNand or CTR/EMUNand SD, have an option on the NCCH image options menu to inject the selected .cia/.cxi/.app in the selected title.

if such a thing is not feasible or there is no need for it, feel free to close the issue.

**Comment by d0k3** [comment]
H&S injection always was a hacky helper construct, and the only thing that makes sense to inject is a CIA installer, so following titles can be properly installed.

So, no, this doesn't really​ make sense.
