### ISSUE TITLE
BUG ABOUT CIA

### ISSUE THREAD

**Issue by Tarinosius** [d0k3/GodMode9#852]
ok , I have a 3ds with Boot9trap and Luma 
When i try to build a CIA with the Yokai watch 3 gamecard it says : "build CIA failed"
I Have the latest version of gm9 and the gamcard is not in "reading only" mode 
I tried with .3ds file but it is not working either
I don't Have " trim.nds "
Please can someone help me ?

**Comment by urherenow** [comment]
Github is not a help forum. Please seek assistance on Discord or gbatemp.

**Comment by Tarinosius** [comment]
ok but noody answer on discord and gbatemp so what can i do ?
