### ISSUE TITLE
agbsave.bin options not showing up.

### ISSUE THREAD

**Issue by Cyijj1** [d0k3/GodMode9#853]
Hi!
I have been recently trying to move a Pokemon yellow .sav file so I can transfer a save from my computer to my 3ds LL. But similar to this post (https://github.com/d0k3/GodMode9/issues/412) I do not see the options for the agbsave.bin in Godmode 9. But the reason I have not just downloaded the test build is because this is a GB game and not a GBA one. And yes I have just now updated GodMode 9 to 2.1.1. Any help would be really appreciated!

**Comment by Gruetzig** [comment]
That feature is only for GBA virtual console, To manage saves of GB/GBC VC, use a regular save manager like JKSM or Checkpoint.
