### ISSUE TITLE
[FEATURE REQUEST] add dumpkeys 

### ISSUE THREAD

**Issue by Riot20058** [d0k3/GodMode9#855]
**Got a great idea on how to improve GodMode9?**
script very easy does dump 3ds keys Add into Favorite emulator and cut step Add file into it yourself 

**Describe the feature you'd like**
Have 
[DumpKeys.zip](https://github.com/d0k3/GodMode9/files/15214429/DumpKeys.zip)

**Describe alternatives you've considered**
Thier are non easy throw the file into the script folder so people have it cash used it for citra emulator quite quick and easy

**Comment by Riot20058** [comment]
![Uploading 17149408038126139000195388104755.jpg…]()
See should look once done why not place into GodMode9 by default very easy script used press A files magical end on SD card

**Comment by Riot20058** [comment]
![Screenshot (1)](https://github.com/d0k3/GodMode9/assets/128275823/d5669065-d955-4980-80f3-7ef3b951faf5)
see for screenshot look once have in files app itself

**Comment by d0k3** [comment]
If there's a script you'd like to have included in GM9, you need to create a proper pull request, not a bug.
