### ISSUE TITLE
[FEATURE REQUEST] GodMode9U?

### ISSUE THREAD

**Issue by RobokingsCosmos** [d0k3/GodMode9#856]
I know this is built only for 3DS, DSi, and DS but intriguingly enough would anyone be able to port GodMode9 to the Wii U for the Aroma environment? Feel free to close this though if not interested but I strongly support this idea. You can load GodMode9U by holding X while turning on the Wii U and I imagine it will show SLC and SLCMPT partitions while showing your SD card and the disc you have in your console. It lets you dump Wii U and Wii discs, and becomes a greater alternative to WUP installer where you can either digitize or dump your games while using some sources like dumpling, Wii U disc dumper, and some other one for the standard Wii discs
While letting you hit the home button you got power off system, reboot system, Title manager and in scripts to decide if you want to either or delete your NNID in the GM9Megascript, Backup Cemu files, Dump NAND, and inject Payloader to H&S. in the section after hitting home More... SD Format menu, Set RTC date&time, configure brightness, Calibrate touchscreen. System info, and Show Readme

**Comment by ihaveamac** [comment]
> I know this is built only for 3DS, DSi, and DS

No, this is only for 3DS. If you've heard of "GodMode9i", it's an entirely separate project for DSi.

Anything resembling a "GM9" for Wii U would also be a completely separate project. It is a very different platform on every level.
