### ISSUE TITLE
GodMode9 compiled with gcc 14.1.0 hangs at boot

### ISSUE THREAD

**Issue by profi200** [d0k3/GodMode9#859]
As discussed on the server here is the issue.

How to reproduce:
Compile GodMode9 with devkitARM r64 (gcc 14.1.0) and try to boot it from Luma3DS or fastboot3DS. It will hang on blackscreens (no backlight).
Have not tried to compile under Windows so can't say for sure if the behavior differs but i doubt it. It's likely undefined behavior somewhere that gets detected and optimized in a way that breaks the code.

Probably unrelated to the actual issue this new warning popped up:
```
lto-wrapper: warning: using serial compilation of 8 LTRANS jobs
lto-wrapper: note: see the '-flto' option documentation for more information
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/14.1.0/../../../../arm-none-eabi/bin/ld: warning: arm9.elf has a LOAD segment with RWX permissions
```

**Comment by urherenow** [comment]
in the last few (I think) versions of dkp toolsets, that warning pops up for most large Switch projects as well. It doesn't seeem to be an issue with any of them, though.

**Comment by astronautlevel2** [comment]
+1 to this being optimization related - compiling at the `-O1` level rather than `-Os` lets it behave as expected, so there's probably some optimization in the O2 set that breaks it.

**Comment by astronautlevel2** [comment]
After further investigation, it seems to be the ipa-vpr (interprocedural propagation of value ranges) optimization that breaks things - compiling with `-fno-ipa-vrp` results in a binary that works fine.

**Comment by DarkRTA** [comment]
opt flags breaking code reeks of UB

**Comment by profi200** [comment]
If no one has time i guess i will try and narrow down the buggy code later. But it's annoying that i don't even have output to the LCD. I will have to see what else i can use.

**Comment by profi200** [comment]
Found the bug. When compiling with LTO size 0 is passed to mmuMapArea() here because the data section size becomes 0:
https://github.com/d0k3/GodMode9/blob/master/arm11/source/system/sys.c#L83

The decompilation shows the loop has been optimized to a do while() loop:
https://gist.github.com/profi200/548e96a12a6aecaa7a6b39659da0b49e
