### ISSUE TITLE
Feature Request - Inject System Files

### ISSUE THREAD

**Issue by nwhiteman42** [d0k3/GodMode9#87]
In Decrypt9 there is an option to inject system files like LocalFriendCodeSeed_B.  If you click A on this file on GodMode9 there is no option to inject it.  Would this be possible to add?

**Comment by mariogamer2** [comment]
Replacing hem work well, I don't see why you would want this.

**Comment by nwhiteman42** [comment]
Because GodMode9 sort of replaced Decrypt9 and it has all the other features so why no add this one

**Comment by AnalogMan151** [comment]
It already has this. Just copy and paste it and overwrite.

**Comment by nwhiteman42** [comment]
What part of sysnand to I copy to?

**Comment by sora10pls** [comment]
Depends what the system file is. If, for example, you wish to inject LocalFriendCodeSeed_B, you'd do the following:

- Have `LocalFriendCodeSeed_B` on your SD Card
- Run GodMode9
- Navigate to `[0:] SDCARD`
- Press `(Y)` on `LocalFriendCodeSeed_B` to copy it
- Exit back to main menu
- Navigate to `[1:] SYSNAND CTRNAND`
- Navigate to `/rw/sys/`
- Press `(Y)` to paste `LocalFriendCodeSeed_B`
- Select `Copy path(s)`
- Unlock SysNAND writing (LV1)
- Enter keycombo
- Choose `Overwrite file(s)`
- Unlock SysNAND writing (LV2)
- Enter keycombo
- ???
- Profit

**Comment by nwhiteman42** [comment]
Okay.  Thanks
