### ISSUE TITLE
Keybind location file/s

### ISSUE THREAD

**Issue by StonyBaboon** [d0k3/GodMode9#874]
I'm with a very specific problem that I need to rebind some keys on the godmod, as such I would like to know in wich file of the source code can I do that? Would apreciate if anyone knows by head and share =)

**Comment by Wolfvak** [comment]
https://github.com/d0k3/GodMode9/blob/master/common/hid_map.h

You can cross check these bits against 
https://3dbrew.org/wiki/HID_Registers#HID_PAD
