### ISSUE TITLE
Feature Request - Add new menu to copy to 0:/gm9out and create hash

### ISSUE THREAD

**Issue by nuimk** [d0k3/GodMode9#88]
I think this functionality is missing from Decrypt9Wip. When I backup NAND using gm9, it doesn't create `.sha` file.

**Comment by WubTheGame** [comment]
i like this idea and think that GM9 should also have a verification feature. i also think that in the Misc menu, there should be an option called "NAND Options" with "Backup NAND" and "Restore NAND" being separate options, as well as "Verify Backup" that way you can have multiple backups without having to put them onto your computer or move them.

**Comment by d0k3** [comment]
GM9 is _file based_. That means, to safe restore or verify a NAND dump, you select that NAND dump, then select safe restore / verify or whatever else you want to do. Similariy, if you want to backup, you coyp the nand.bin / nand_min.bin file out of S:/.

That backup thingy in 'Misc...' is really only a helper construct to make stuff easier for those coming from D9. I may have you covered with that idea you had, though. Soon ;).

@nuimk - do you really think .sha files are useful for other copy operations, too, or just for NAND stuff? If so, can you specify?

**Comment by nuimk** [comment]
@d0k3 I think .sha files are useful for dumping things from 3ds to SD, but it will add complexity to generic copy operations, hard to implement and confuse users. I'm asking for this feature because I couldn't do it from DecryptWip9 before you release the latest version which work with boot9strap v1.2.

My suggestion is to generate `.sha` when using that backup menu in 'Misc..'. In my use case. I just need that file to verify NAND dump on PC.

**Comment by d0k3** [comment]
Implemented via a [.gm9 script](https://transfer.sh/JPik5/sysnand_backup.gm9). Scripting will be in the next stable release, you can also get it via the latest hourly.
