### ISSUE TITLE
Feature Request - Gateway Card as a Filesystem

### ISSUE THREAD

**Issue by fox8091** [d0k3/GodMode9#89]
Using [this](https://github.com/shinyquagsire23/gwcard), it should be possible to use a Gateway red card's mSD as another filesystem, allowing one to easily convert 3ds cartridge backups to CIAs.

**Comment by d0k3** [comment]
I'll actually think about this, but won't receive high priority for now.

**Comment by fox8091** [comment]
Totally understand it not being high priority. 😄 Just putting this here for future reference.

**Comment by WubTheGame** [comment]
i really want to be able to use godmode9 to convert .3ds roms to Cias. that way i have even more reason to use Godmode9 (i haven't quite dropped D9 nor HG9 yet) as i won't need HG9 or D9 to convert cartridges to CIA's. i could just copy paste it from Cart to SD, then Convert to CIA.

**Comment by ihaveamac** [comment]
it already does that, select the file and build cia.

**Comment by WubTheGame** [comment]
oh? i never realized that. thanks.

**Comment by d0k3** [comment]
Okay, seeing that this is specific to the GW card (and a few clones), I won't do it. If someone else is interested, I might take the pull request, but it has to be as versatile as possible (= supporting a few flashcards is not enough). Closing this now...

**Comment by fox8091** [comment]
No offense, but not all cards expose raw filesystems via CTRCARD commands, and some don't even expose it at all (Sky3DS being an example). There aren't even that many 3DS flashcarts to begin with. By supporting Gateway's method, you include all [clones](http://wiki.gbatemp.net/wiki/3DS_Flashcart_Comparison) of it. It's better to support as many as possible rather than none at all.

**Comment by d0k3** [comment]
Although I see the use of this, it's still a rather niché feature. Seeing that there are more clones than I thought, I wouldn't be too adversed against taking a pull request, though.

**Comment by fox8091** [comment]
I may hack something together in the next few days then. All it should require is swapping out sdmmc libs for gwcard libs for fatfs. (Only for those functions though.)
