### ISSUE TITLE
[Suggestion] injection into other system applications

### ISSUE THREAD

**Issue by Jan200101** [d0k3/GodMode9#90]
Right now there is a unoffical fork that allows you to inject into AR https://github.com/CrimsonMaple/GodMode9
It would be nice to see this being expanded on

**Comment by d0k3** [comment]
In short: nope. Injection is a hacky helper construct, which only makes sense __once___, to inject a CIA installer. Even that is no more required starting from Luma 3DS v8.0 (cause you can run FBI without installation).

Why you guys would want to abuse your system titles for whatever is beyound me. I can guarantee this is not really useful for anything besides injecting homebrew.
