### ISSUE TITLE
Feature request - nand.bin.sha written as sha256sum

### ISSUE THREAD

**Issue by NeroReflex** [d0k3/GodMode9#91]
I would like to have sha256 files of nand backups generated as "sha256sum nand.bin > nand.bin.sha"
If you want to implement this change I have done this for you in my fork of decrypt9wip: https://github.com/NeroReflex/D9Hack

**Comment by d0k3** [comment]
This is just so that you can view the hash in a text editor and don't have to use a hex editor? Doesn't really make sense, and would be a pretty big change right now (has to work across tools). Won't be implemented.

**Comment by DMSalesman** [comment]
So, is the fact that the sha256sum not be dumped in a plaintext file intended?
