### ISSUE TITLE
Godmode9 not launching

### ISSUE THREAD

**Issue by tonydaexpert** [d0k3/GodMode9#92]
I had Luma for about 6 months now. I updated to sighax and everything was fine but today I decided to update to Bootstrap 1.2 I was following the steps on https://3ds.guide/updating-b9s.html and everything was going well till it told me to launch godmode9 (just got the newest version 1.2.1 on my sd) to update the bootstrap but when I turned on my 3ds and holding start it just launches the home menu. It worked fine before.
New 3ds Xl version 11.4.0-37U
Luma version: 7.1

**Comment by Ordim3n** [comment]
Did you update GM9 to the latest update

**Comment by tonydaexpert** [comment]
Yes I updated to Version 1.2.1 right before this happened

**Comment by Ordim3n** [comment]
Did you took the .firm or the .bin?

**Comment by tonydaexpert** [comment]
.firm

**Comment by d0k3** [comment]
You did something wrong. If you hold start and go right into home menu, launching GM9 is not even attempted. Check your folders.

**Comment by tonydaexpert** [comment]
It was a problem with Luma. Attempting to use the cia updater on Bootstrap 1.0 will mess things up.  Everything is fine now

**Comment by james-d-elliott** [comment]
Bootstrap 1.0 doesn't support the latest Luma is all that is. You need to upgrade.

**Comment by h4rv1n** [comment]
I have the same problem, how did you proceed?

**Comment by tanganyang** [comment]
I got the same problem, just double checked all the required files are the newest version. Althrough I can't launch godmode9, I can still use the FBI to install the .cia files.

**Comment by d0k3** [comment]
Try loading GodMode9 as boot.firm (replace Luma). Does it work? If so, this is a Luma issue. Also have the latest boot9strap installed.

**Comment by d0k3** [comment]
@h4rv1n @tanganyang did you read my last comment?

**Comment by tanganyang** [comment]
yes, I didn't get a chance to try it yet. I will post the result later. Thanks.

**Comment by d0k3** [comment]
@h4rv1n @tanganyang - I'll interpret the radio silence as solved problem. Feel free to keep writing in here if it is not solved yet.

**Comment by Pojapoeg99** [comment]
Hi dok3. Can you help me? I cant lauch the godmod9 and i cant understand what i should do. Thanks dude
