### ISSUE TITLE
Feature Request - .FIRM Payload loading

### ISSUE THREAD

**Issue by Lordkurzschluss** [d0k3/GodMode9#96]
I guess that adding a ".FIRM ARM9 Payload" like it is in the a9lh release
Some people (Like me) would love this feature.

**Comment by mariogamer2** [comment]
Why not using luma?

**Comment by d0k3** [comment]
This is already planned. Will be coming later.

**Comment by Lordkurzschluss** [comment]
@mariogamer2 Because i dont wanna reboot anytime when i switch the payloads.

**Comment by d0k3** [comment]
Okay, here:
https://github.com/d0k3/GodMode9/commit/b9eea8e92b5f5a3bf3da0264662d723900fb5305

Big downside: works only with most recent boot9strap nightly.

**Comment by Lordkurzschluss** [comment]
Thanks!

**Comment by qwertyatom100** [comment]
This feature has been removed

**Comment by d0k3** [comment]
Oh well, seems like I really have no choice but to keep my own fork of boot9strap. Does one of you guys have a hardmod?

If so, you can try this:
https://transfer.sh/JY4K3/boot9strap-1.2-build170724-bootonce.zip
(actually nothing bad should happen cause there are not critical changes in it)

Source code is here:
https://github.com/d0k3/boot9strap

**Comment by CuriousTommy** [comment]
For anyone that is curious, here is the commit that remove the feature GM9 relied on, https://github.com/SciresM/boot9strap/commit/ff16d59ff8fba431f5c5c934eea7db4d122eef1c.

In that commit, TuxSH wrote why this was removed:

> This experimental feature was supposed to be conditionally enabled to take end-users with slow SD cards into account, and was supposed to be used with A9NC (which, anyways, is extremely niche).
>
> It was certainly **NOT** designed to be used merely as an inappropriate and lazy way to chainload a payload from SD card or NAND (doing so is also extremely inefficient due to the need to write a file and reboot).
>
> People concerned should see b9s's own source code to have see a proper example to load FIRM payloads correctly (I could help anyone who would have trouble integrating that code into their projects) instead.

**Comment by d0k3** [comment]
Okay, here you go (tested):
https://github.com/d0k3/boot9strap/releases/tag/1.2%2Bbootonce

GM9 may receive a proper FIRM loader later, for now this will have to do.
