### ISSUE TITLE
Feature Request - Reverse-LZSS Decompress exefs/.code to code.bin

### ISSUE THREAD

**Issue by Kenshii** [d0k3/GodMode9#98]
Adding this as an option to the context menu would be nice, as it'd mean not having to run
```
ctrtool -t lzss --lzssout=code.bin .code
```
in ctrtool afterwards.

**Comment by d0k3** [comment]
Agreed, this would be a good addition.

**Comment by phijor** [comment]
Maybe this could be added in the form of a virtual file when mounting a `NCCH`-container? Code compression isn't a property of the `.code` contained in the `exefs`, rather it's enabled by a flag in the `exheader` of a `NCCH`. So instead of

```
romfs/
...
exefs/
|- .code
|- banner
`- icon
```

wouldn't it be possible to have something along the lines of

```
romfs/
...
exefs/
|- .code      (<- this is the uncompressed arm11 code)
|- .code.lzss
|- banner
`- icon
```
?

**Comment by AnalogMan151** [comment]
I'd like to contribute my interest into this as well. It would be useful for extracting DSP1 firmware via script without the need for special homebrew.

**Comment by d0k3** [comment]
Just as a note - good sample code for decrypting the code is found here:
https://github.com/zoogie/DSP1/blob/master/source/main.c

Thanks, @AnalogMan151

**Comment by TheCyberQuake** [comment]
With that I would love if we had a way to simply dump dspfirm.cdc from one of the drives that already exist rather than manually using other script commands to find and pull dspfirm from home menu or mset.

**Comment by d0k3** [comment]
Added in https://github.com/d0k3/GodMode9/commit/a6a15eb70d66e3c96bbc164598f9482bb545b3f9
