### ISSUE TITLE
Feature Parity Request: Manufacturing Date

### ISSUE THREAD

**Issue by zoogie** [d0k3/GodMode9#99]
Show Manufacturing Date just like the awesome, legendary, often imitated never duplicated, Decrypt9WIP :-p

**Comment by WubTheGame** [comment]
other than "bragging rights about when your system was made" how would this be useful?

**Comment by d0k3** [comment]
You've got a point in that GM9 so far has no pendant to D9's "System Info". However, a superior alternative is already in the works and will be merged into master when it's done (most likely before the next release).

See here: https://github.com/Myriachan/GodMode9/commit/ccc688919c1d3835c7d53c9363fd3dc15453c878

**Comment by zoogie** [comment]
"MeowPrintf()" I can't wait for this. Serious!

...Thanks for the response. Just joking about d9, I'm starting to get used to gm9 now.
